dream-num/univer

.github/contributing-zh.md
.vscode/extensions.json

使用vscode开发时，启动项目时提示项目推荐插件安装，保持一致性

chore: 添加vscode项目推荐插件配置文件

---

packages/base-render/src/Basics/IEvents.ts
packages/base-render/src/Component/Sheets/Spreadsheet.ts
packages/base-render/src/Engine.ts
packages/base-sheets/src/Controller/Selection/SelectionManager.ts

* Removed some duplicated (unnecessary) type declarations
* Fix zooming issues
* Fix some types

fix(selection): moving event should be effected by scale

---

packages/base-render/src/Component/Sheets/Spreadsheet.ts
packages/base-render/src/Viewport.ts
packages/core/src/Sheets/Domain/Worksheet.ts
packages/sheets-plugin-operation/src/Domain/Paste.ts

Fix rendering when scaling ratio is not 1.0.

fix(rendering): fix sheet rendering scaling

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/bug_report.zh-CN.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/feature_request.zh-CN.yml

chore: add issue template

---

packages/sheets-plugin-find/src/Controller/FindController.ts
packages/sheets-plugin-find/src/Controller/FindModalController.ts
packages/sheets-plugin-find/src/Controller/menu.ts
packages/sheets-plugin-find/src/FindPlugin.ts
packages/sheets-plugin-find/src/commands/show-modal.command.ts
packages/sheets-plugin-find/src/services/find.service.ts
packages/sheets-plugin-image/src/Controller/OverGridImageController.ts
packages/sheets-plugin-image/src/Controller/menu.ts
packages/sheets-plugin-image/src/ImagePlugin.tsx
packages/sheets-plugin-image/src/commands/upload.command.ts
packages/sheets-plugin-image/src/services/upload.service.ts
packages/sheets-plugin-import-xlsx/src/Controller/ImportXlsxController.ts
packages/sheets-plugin-import-xlsx/src/Controller/menu.ts
packages/sheets-plugin-import-xlsx/src/ImportXlsxPlugin.tsx
packages/sheets-plugin-import-xlsx/src/commands/upload.command.ts
packages/sheets-plugin-import-xlsx/src/services/upload.service.ts
packages/sheets-plugin-numfmt/src/Basics/Const/DEFAULT_DATA.ts
packages/sheets-plugin-numfmt/src/Controller/NumfmtController.ts
packages/sheets-plugin-numfmt/src/Controller/NumfmtModalController.ts
packages/sheets-plugin-numfmt/src/Controller/menu.ts
packages/sheets-plugin-numfmt/src/NumfmtPlugin.ts
packages/sheets-plugin-numfmt/src/View/UI/FormatItem.tsx
packages/sheets-plugin-numfmt/src/commands/set-numfmt-range-data.command.ts
packages/sheets-plugin-numfmt/src/commands/show-modal.command.ts
packages/sheets-plugin-numfmt/src/services/numfmt.service.ts

command triggers a specific operation DOM service

refactor(ui): plugin operation service

---

packages/base-sheets/src/Commands/Commands/copy-worksheet.command.ts
packages/base-sheets/src/Commands/Commands/insert-sheet.command.ts
packages/base-sheets/src/Commands/Commands/remove-sheet.command.ts
packages/base-sheets/src/Commands/Commands/set-tab-color.command.ts
packages/base-sheets/src/Commands/Commands/set-worksheet-hide.command.ts
packages/base-sheets/src/Commands/Commands/set-worksheet-show.command.ts
packages/base-sheets/src/Commands/Mutations/insert-sheet.mutation.ts
packages/base-sheets/src/Commands/Mutations/remove-sheet.mutation.ts
packages/base-sheets/src/Commands/Mutations/set-tab-color.mutation.ts
packages/base-sheets/src/Commands/Mutations/set-worksheet-activate.mutation.ts
packages/base-sheets/src/Commands/Mutations/set-worksheet-hide.mutation.ts
packages/base-sheets/src/Controller/BasicWorkbook.controller.ts
packages/base-sheets/src/Controller/BasicWorksheet.controller.ts
packages/base-sheets/src/index.ts
packages/ui-plugin-sheets/src/Controller/ToolbarUIController.ts
packages/ui-plugin-sheets/src/Controller/menu.ts
packages/ui-plugin-sheets/src/View/SheetBar/SheetBar.tsx

chore(base-sheets): refactor command

---

.husky/pre-commit

chore: lint changed files before committing

---

.github/workflows/ci-test.yml
examples/univer-doc-ts/tsconfig.json
examples/univer-sheet-ts/tsconfig.json
examples/univer-slide-ts/tsconfig.json
examples/univer-vanilla-ts/tsconfig.json
packages/base-docs/tsconfig.json
packages/base-formula-engine/tsconfig.json
packages/base-numfmt-engine/tsconfig.json
packages/base-render/tsconfig.json
packages/base-sheets/tsconfig.json
packages/base-slides/tsconfig.json
packages/base-ui/tsconfig.json
packages/common-plugin-data/tsconfig.json
packages/core/tsconfig.json
packages/sheets-plugin-filter/tsconfig.json
packages/sheets-plugin-find/tsconfig.json
packages/sheets-plugin-formula/tsconfig.json
packages/sheets-plugin-image/tsconfig.json
packages/sheets-plugin-import-xlsx/tsconfig.json
packages/sheets-plugin-numfmt/tsconfig.json
packages/sheets-plugin-operation/tsconfig.json
packages/ui-plugin-docs/tsconfig.json
packages/ui-plugin-sheets/tsconfig.json
packages/ui-plugin-slides/tsconfig.json
tsconfig.json

ci: support eslint & type checking

---

packages/core/src/services/undoredo/undoredo.service.ts

fix(core): undoredo service

---

packages/base-sheets/src/Commands/Commands/insert-range-move-down.command.ts
packages/base-sheets/src/Commands/Commands/move-range-to.command.ts
packages/base-ui/src/Components/ColorPicker/ColorPicker.tsx
packages/base-ui/src/Components/Slider/Slider.tsx
packages/base-ui/src/Components/Slider/test/index.test.tsx
packages/base-ui/src/Components/Tabs/Tabs.stories.tsx
packages/base-ui/src/Components/Tabs/Tabs.tsx
packages/base-ui/src/Components/Tabs/index.module.less
packages/base-ui/src/Components/Tabs/test/index.test.tsx
packages/ui-plugin-sheets/src/View/SheetBar/SheetBar.tsx
packages/ui-plugin-sheets/src/View/SheetBar/index.module.less

refactor(base-ui): add drag to tabs component

refactor(base-ui): tabs component

---

examples/univer-sheet-ts/src/main.tsx
packages/base-ui/src/Basics/CSS/Skin/base.module.less
packages/base-ui/src/Basics/CSS/Skin/default.module.less
packages/base-ui/src/Basics/CSS/index.ts
packages/base-ui/src/Common/AppContext.tsx
packages/base-ui/src/views/app.tsx
packages/core/src/Basics/Univer.ts
packages/core/src/Types/Interfaces/IUniverData.ts
packages/core/src/index.ts
packages/core/src/services/theme/Theme.ts
packages/core/src/services/theme/theme.service.ts
scripts/clean.mjs

[#117](https://github.com/dream-num/univer/issues/117)

feat: add theme service

---

packages/base-render/src/Component/Sheets/SheetSkeleton.ts
packages/base-render/src/Engine.ts
packages/base-render/src/Shape/Circle.ts
packages/base-sheets/src/Basics/Const/DEFAULT_SPREADSHEET_VIEW.ts
packages/base-sheets/src/Basics/component-tools.ts
packages/base-sheets/src/Controller/Selection.controller.ts
packages/base-sheets/src/Controller/header-freeze.controller.ts
packages/base-sheets/src/Controller/header-menu.controller.ts
packages/base-sheets/src/Controller/header-move.controller.ts
packages/base-sheets/src/Controller/header-resize.controller.ts
packages/base-sheets/src/SheetPlugin.ts
packages/base-sheets/src/View/CanvasView.ts
packages/base-sheets/src/View/HeaderMenuShape.ts
packages/base-sheets/src/View/HeaderResizeShape.ts
packages/base-sheets/src/View/headerMenuShape.ts
packages/base-sheets/src/View/headerResizeShape.ts
packages/core/src/Basics/Univer.ts

develop header resize and menu

feat(sheet): develop header resize and menu

---

packages/base-slides/src/SlidePlugin.ts
packages/base-slides/src/View/Render/Adaptor.ts
packages/base-slides/src/View/Render/Adaptors/SlideAdaptor.ts
packages/base-slides/src/View/Render/CanvasView.ts
packages/sheets-plugin-find/src/Controller/FindModalController.ts
packages/sheets-plugin-find/src/Domain/TextFind.ts
packages/sheets-plugin-find/src/FindPlugin.ts
packages/sheets-plugin-image/src/ImagePlugin.tsx
packages/sheets-plugin-image/src/Model/Apply/index.ts
packages/sheets-plugin-image/src/View/UI/ImagePanel/ImagePanelUI.tsx

fix(*): fix ts errors

---

packages/base-ui/src/Basics/CSS/Skin/base.less
packages/base-ui/src/Basics/CSS/Skin/default.module.less
packages/base-ui/src/Basics/CSS/Skin/green.module.less
packages/base-ui/src/Components/Avatar/Style/index.module.less
packages/base-ui/src/Components/Button/Style/index.module.less
packages/base-ui/src/Components/Button/Style/mixin.less
packages/base-ui/src/Components/ColorPicker/index.module.less
packages/base-ui/src/Components/DesignToken/Palette.tsx
packages/base-ui/src/Components/Input/Style/mixin.less
packages/base-ui/src/Components/InputNumber/Style/mixin.less
packages/base-ui/src/Components/Menu/index.module.less
packages/base-ui/src/Components/Select/index.module.less
packages/base-ui/src/Components/SiderModal/index.module.less
packages/base-ui/src/Components/Tabs/index.module.less
packages/base-ui/src/Components/Tooltip/index.module.less
packages/base-ui/src/views/app.module.less
packages/base-ui/src/views/components/contextmenu/contextmenu.module.less
packages/base-ui/src/views/components/toolbar/index.less
packages/base-ui/src/views/components/toolbar/index.module.less
packages/core/src/services/theme/theme.ts

[#117](https://github.com/dream-num/univer/issues/117)
https://univer-design.vercel.app/

feat(ui): new palette

---

packages/base-sheets/src/commands/commands/__tests__/create-command-test-bed.ts
packages/base-sheets/src/commands/commands/__tests__/create-selection-command-test-bed.ts
packages/base-sheets/src/commands/commands/__tests__/set-selections.command.spec.ts
packages/base-sheets/src/commands/commands/set-selections.command.ts
packages/base-sheets/src/commands/commands/utils/selection-util.ts
packages/base-sheets/src/index.ts
packages/core/src/Types/Interfaces/IRange.ts
packages/ui-plugin-sheets/src/controller/sheet-ui.controller.ts
packages/ui-plugin-sheets/src/controller/shortcuts/selection.shortcut.ts

test(sheet:selection): finish selection test

---

packages/base-render/src/Scene.ts
packages/base-sheets/src/Basics/component-tools.ts
packages/base-sheets/src/Controller/header-menu.controller.ts
packages/base-sheets/src/Controller/header-resize.controller.ts

Some improvements on the controller

refactor(sheet): header resize controller

---

.github/workflows/ci-preview.yml

ci: adding a comment with the deployment URL for the PR

---

.vscode/settings.json
packages/base-ui/package.json
packages/base-ui/src/base-ui-plugin.ts
packages/base-ui/src/services/local-storage/local-storage.service.ts
packages/core/src/index.ts
packages/core/src/services/local-storage/local-storage.service.ts
packages/core/tsconfig.json
pnpm-lock.yaml

feat: add ilocalstorageservice

---

packages/base-render/src/Component/Docs/DocSkeleton.ts
packages/base-render/src/Component/Docs/text-selection-render-manager.ts
packages/base-render/src/Component/Sheets/Extensions/Font.ts
packages/base-render/src/Shape/BaseScrollBar.ts
packages/base-render/src/Shape/ScrollBar.ts
packages/base-sheets/src/Basics/Const/COMMAND_LISTENER_CONST.ts
packages/base-sheets/src/Basics/Const/index.ts
packages/base-sheets/src/Controller/Selection.controller.ts
packages/base-sheets/src/Controller/header-resize.controller.ts
packages/base-sheets/src/Controller/sheet-render.controller.ts
packages/base-sheets/src/index.ts
packages/base-sheets/src/services/selection-manager.service.ts
packages/core/src/Docs/Domain/DocumentBodyModel.ts
packages/ui-plugin-sheets/src/View/SheetContainer/index.module.less
packages/ui-plugin-sheets/src/controller/editor-bridge.controller.ts
packages/ui-plugin-sheets/src/controller/editor/editing.controller.ts
packages/ui-plugin-sheets/src/controller/editor/start-edit.controller.ts
packages/ui-plugin-sheets/src/services/editor-bridge.service.ts
packages/ui-plugin-sheets/src/sheet-ui-plugin.ts

- support scroll bar in editor
- fix pointerdown save

feat(sheet): editor scroll bar

---

packages/base-sheets/src/commands/commands/set-worksheet-row-height.command.ts
packages/base-sheets/src/commands/mutations/set-worksheet-row-height.mutation.ts

bug in undo row height mutaion

fix: bug in undo row height mutaion

---

packages/base-sheets/src/Controller/auto-height.controller.ts
packages/base-sheets/src/commands/commands/set-range-values.command.ts
packages/ui-plugin-sheets/src/controller/editor-bridge.controller.ts
packages/ui-plugin-sheets/src/controller/format-painter/format-painter.controller.ts

feat(sheet): trigger auto height after set range value

---

.eslintrc.cjs

chore: support type overload

---

packages/base-docs/src/Controller/move-cursor.controller.ts
packages/base-docs/src/Controller/text-selection.controller.ts
packages/base-render/src/Basics/Position.ts
packages/base-render/src/Basics/Tools.ts
packages/base-render/src/Component/Docs/Common/TextSelection.ts
packages/base-render/src/Component/Docs/text-selection-render-manager.ts
packages/base-render/src/Component/Sheets/Extensions/BorderAuxiliary.ts
packages/base-render/src/ScrollTimer.ts
packages/common-plugin-data/src/Docs/DEFAULT_DOCUMENT_DATA_SIMPLE.ts
packages/common-plugin-data/src/Docs/index.ts
packages/core/src/Docs/Domain/DocumentBodyModel.ts
packages/ui-plugin-sheets/src/controllers/editor/start-edit.controller.ts

fix(doc): arrow key in doc

---

packages/ui-plugin-sheets/src/views/SheetBar/SheetBarTabs/SheetBarItem.tsx
packages/ui-plugin-sheets/src/views/SheetBar/SheetBarTabs/index.module.less
packages/ui-plugin-sheets/src/views/SheetBar/SheetBarTabs/utils/slide-tab-bar.ts
packages/ui-plugin-sheets/src/views/SheetBar/index.module.less

fix(sheet): sheet bar scroll style,left line right line

---

packages/base-docs/src/commands/mutations/functions/common.ts

fix: style error when input at the begining of paragraph

---

packages/base-docs/src/Controller/delete-left-input.controller.ts
packages/base-docs/src/Controller/ime-input.controller.ts
packages/base-docs/src/Controller/line-break-input.controller.ts
packages/base-docs/src/Controller/move-cursor.controller.ts
packages/base-docs/src/Controller/normal-input.controller.ts
packages/base-docs/src/commands/commands/__tests__/inline-format.command.spec.ts
packages/base-docs/src/commands/commands/core-editing.command.ts
packages/base-docs/src/commands/commands/inline-format.command.ts
packages/base-docs/src/commands/mutations/core-editing.mutation.ts
packages/base-docs/src/commands/mutations/functions/common.ts
packages/base-docs/src/commands/mutations/functions/delete-apply.ts
packages/base-docs/src/commands/mutations/functions/insert-apply.ts
packages/base-render/src/Component/Docs/Block/Paragraph/Layout.Ruler.ts
packages/base-render/src/Component/Docs/Common/Span.ts
packages/base-render/src/Component/Docs/Common/TextSelection.ts
packages/base-render/src/Component/Docs/Common/Tools.ts
packages/base-render/src/Component/Docs/Common/convert-cursor.ts
packages/base-render/src/Component/Docs/DocSkeleton.ts
packages/base-render/src/Component/Docs/text-selection-render-manager.ts
packages/base-render/src/Scene.Transformer.ts
packages/core/src/Docs/Domain/DataStreamTreeNode.ts
packages/core/src/Docs/Domain/DocumentBodyModel.ts
packages/core/src/Shared/Common.ts
packages/core/src/Shared/SortRules.ts
packages/core/src/Types/Interfaces/ISelectionData.ts
packages/ui-plugin-sheets/src/controllers/editor/start-edit.controller.ts

fix(doc): remove isStartBack and isEndBack and fix issue #352

---

packages/design/package.json
packages/design/src/components/select-list/SelectList.stories.tsx
packages/design/src/components/select-list/SelectList.tsx
packages/design/src/components/select-list/index.module.less
packages/design/src/components/select-list/index.ts
packages/design/src/components/select/Select.stories.tsx
packages/design/src/components/select/Select.tsx
packages/design/src/components/select/index.module.less
packages/design/src/components/select/index.ts
packages/design/src/index.ts
pnpm-lock.yaml

feat(design): add `Select` component

---

packages/base-sheets/src/commands/commands/__tests__/copy-worksheet.command.spec.ts
packages/base-sheets/src/commands/commands/__tests__/remove-sheet.command.spec.ts
packages/base-sheets/src/commands/commands/__tests__/set-frozen.command.spec.ts
packages/base-sheets/src/commands/commands/__tests__/set-worksheet-hide.command.spec.ts
packages/base-sheets/src/commands/commands/__tests__/set-worksheet-name.command.spec.ts
packages/base-sheets/src/commands/commands/__tests__/set-worksheet-order.command.spec.ts
packages/base-sheets/src/commands/commands/__tests__/set-worksheet-show.command.spec.ts
packages/base-sheets/src/commands/commands/remove-sheet.command.ts
packages/base-sheets/src/commands/commands/set-frozen.command.ts
packages/ui-plugin-sheets/src/commands/commands/set-selection-frozen.command.ts

- add some worksheet test
- rename set-selection-frozen.command.ts file

test(sheet): add worksheet test

---

packages/ui-plugin-sheets/src/controllers/shortcuts/editor.shortcut.ts

feat: support create paragraph  in sheet cell

---

packages/base-render/src/components/sheets/sheet-skeleton.ts
packages/core/src/index.ts
packages/core/src/services/sheet-interceptor/__tests__/sheet-interceptor.service.spec.ts
packages/core/src/services/sheet-interceptor/sheet-interceptor.service.ts

feat: general sheet interceptor

---

packages/base-docs/src/commands/mutations/__tests__/apply-utils.spec.ts
packages/base-docs/src/commands/mutations/functions/common.ts
packages/base-docs/src/commands/mutations/functions/update-apply.ts

fix: insert textRuns

---

packages/base-docs/src/commands/mutations/__tests__/apply-utils.spec.ts
packages/base-docs/src/commands/mutations/functions/common.ts

fix: issues when insertTextRuns is empty

fix: issues when insertTextRuns is empty

---

packages/ui-plugin-sheets/src/controllers/contextmenu/contextmenu.controller.ts

fix: sheet menu item

---

packages/base-docs/src/index.ts
packages/base-formula-engine/src/analysis/lexer.ts
packages/base-formula-engine/src/basics/regex.ts
packages/base-formula-engine/src/basics/sequence.ts
packages/base-formula-engine/src/dependency/formula-dependency.ts
packages/base-formula-engine/src/index.ts
packages/base-formula-engine/src/services/formula-engine.service.ts
packages/base-render/src/basics/cell-data.ts
packages/base-render/src/basics/index.ts
packages/base-render/src/components/sheets/sheet-skeleton.ts
packages/base-render/src/shape/scroll-bar.ts
packages/core/src/shared/reference.ts
packages/core/src/types/interfaces/i-cell-data.ts
packages/core/src/types/interfaces/i-style-data.ts
packages/sheets-plugin-formula-ui/package.json
packages/sheets-plugin-formula-ui/src/common/selection.ts
packages/sheets-plugin-formula-ui/src/controllers/prompt.controller.ts
packages/ui-plugin-sheets/src/controllers/editor/editing.controller.ts
packages/ui-plugin-sheets/src/controllers/move-range.controller.ts
packages/ui-plugin-sheets/src/index.ts
pnpm-lock.yaml

feat(formula): input hightlight

---

packages/base-docs/src/commands/commands/inline-format.command.ts
packages/base-docs/src/commands/operations/text-selection.operation.ts
packages/base-docs/src/controllers/delete-left-input.controller.ts
packages/base-docs/src/controllers/ime-input.controller.ts
packages/base-docs/src/controllers/line-break-input.controller.ts
packages/base-docs/src/controllers/move-cursor.controller.ts
packages/base-docs/src/controllers/normal-input.controller.ts
packages/base-docs/src/controllers/text-selection.controller.ts
packages/base-docs/src/services/text-selection-manager.service.ts
packages/base-render/src/components/docs/common/range.ts
packages/base-render/src/components/docs/text-selection-render-manager.ts
packages/ui-plugin-docs/src/controllers/clipboard.controller.ts
packages/ui-plugin-sheets/src/controllers/editor/start-edit.controller.ts
packages/ui-plugin-sheets/src/controllers/selection.controller.ts

refactor(doc): optimization of text selections

---

packages/base-docs/src/doc-plugin.ts
packages/base-docs/src/services/clipboard/__test__/html-and-udm-convert.spec.ts
packages/base-sheets/src/commands/operations/selection.operation.ts
packages/sheets-plugin-formula-ui/src/controllers/prompt.controller.ts
packages/ui-plugin-sheets/src/commands/operations/cell-edit.operation.ts
packages/ui-plugin-sheets/src/controllers/editor-bridge.controller.ts
packages/ui-plugin-sheets/src/controllers/editor/start-edit.controller.ts

fix: tab should not empty cell content

---

packages/design/src/components/design-token/Palette.tsx
packages/design/src/components/scrollbar/Scrollbar.stories.tsx
packages/design/src/components/scrollbar/Scrollbar.tsx
packages/design/src/components/scrollbar/__tests__/index.spec.tsx
packages/design/src/components/scrollbar/index.module.less
packages/design/src/components/scrollbar/index.ts
packages/design/src/index.ts
packages/design/src/themes/base.less

feat(design): add `Scrollbar` component

---

examples/univer-doc-ts/src/main.tsx
packages/base-docs/src/controllers/page-render.controller.ts
packages/base-render/src/basics/font-cache.ts
packages/base-render/src/basics/tools.ts
packages/base-render/src/components/docs/block/paragraph/paragraph.ts
packages/base-render/src/components/docs/common/convert-cursor.ts
packages/base-render/src/components/docs/common/line.ts
packages/base-render/src/components/docs/common/range.ts
packages/base-render/src/components/docs/common/span.ts
packages/base-render/src/components/docs/doc-skeleton.ts
packages/base-render/src/components/docs/extensions/background.ts
packages/base-render/src/components/docs/extensions/font-and-base-line.ts
packages/base-render/src/components/docs/extensions/line.ts
packages/base-render/src/components/docs/text-selection-render-manager.ts
packages/common-plugin-data/src/docs/default-document-data-cn.ts
packages/common-plugin-data/src/docs/default-document-data-simple.ts
packages/common-plugin-data/src/docs/index.ts

fix(doc): inline format optimization in render

---

packages/base-docs/src/controllers/text-selection.controller.ts
packages/base-docs/src/controllers/zoom.controller.ts
packages/base-docs/src/services/text-selection-manager.service.ts

fix(doc): no need to refresh selection

---

packages/base-docs/src/controllers/doc-render.controller.ts
packages/base-docs/src/controllers/floating-object.controller.ts
packages/base-docs/src/controllers/page-render.controller.ts
packages/base-docs/src/controllers/zoom.controller.ts
packages/base-render/src/basics/const.ts
packages/core/src/common/const.ts
packages/core/src/index.ts
packages/core/src/services/instance/instance.service.ts
packages/core/src/services/undoredo/undoredo.service.ts
packages/sheets-plugin-formula-ui/src/controllers/prompt.controller.ts
packages/ui-plugin-docs/src/doc-ui-plugin.ts
packages/ui-plugin-sheets/src/controllers/editor/end-edit.controller.ts
packages/ui-plugin-sheets/src/controllers/editor/initialize-editor.controller.ts
packages/ui-plugin-sheets/src/controllers/editor/start-edit.controller.ts
packages/ui-plugin-sheets/src/views/editor-container/EditorContainer.tsx

feat(sheet): support undo and redo in sheet cell

---

packages/base-render/src/components/sheets/sheet-skeleton.ts

fix: #524 no need to rotate text when edit

---

packages/base-docs/src/commands/commands/__tests__/replace-content.command.spec.ts
packages/base-docs/src/commands/commands/replace-content.command.ts
packages/base-docs/src/doc-plugin.ts
packages/base-docs/src/index.ts
packages/core/src/types/interfaces/i-document-data.ts

feat: add replace content command

---

packages/base-docs/src/commands/operations/cursor.operation.ts
packages/base-docs/src/commands/operations/select-all.operation.ts
packages/base-docs/src/commands/operations/set-doc-zoom-ratio.operation.ts
packages/base-docs/src/commands/operations/text-selection.operation.ts
packages/base-docs/src/doc-plugin.ts
packages/base-docs/src/shortcuts/cursor.shortcut.ts
packages/base-ui/src/services/shortcut/shortcut.service.ts

feat: support select all in doc and sheet cell when edit

---

packages/base-sheets/src/commands/commands/set-border-command.ts
packages/base-ui/src/components/menu/Menu.tsx

fix(base-sheet): fix incorrect rendering when the border type is set to outside

---

packages/ui-plugin-sheets/src/controllers/editor/end-edit.controller.ts
packages/ui-plugin-sheets/src/controllers/sheet-ui.controller.ts
packages/ui-plugin-sheets/src/controllers/shortcuts/editor.shortcut.ts

feat: use shift arrow key to select content in cell

---

packages/base-docs/src/controllers/text-selection.controller.ts
packages/base-render/src/components/docs/text-selection-render-manager.ts

feat(doc): experimental support for Chinese and English word segmentation

---

packages/base-sheets/src/commands/commands/__tests__/set-border.command.spec.ts
packages/base-sheets/src/commands/commands/set-border-command.ts
packages/base-sheets/src/index.ts
packages/base-ui/package.json
packages/base-ui/src/components/custom-label/CustomLabel.tsx
packages/base-ui/src/components/menu/Menu.tsx
packages/base-ui/src/services/menu/menu.ts
packages/base-ui/src/views/components/doc-bars/ToolbarItem.tsx
packages/base-ui/src/views/components/doc-bars/index.module.less
packages/design/src/components/input-number/InputNumber.tsx
packages/ui-plugin-sheets/src/components/border-panel/BorderPanel.tsx
packages/ui-plugin-sheets/src/components/border-panel/interface.ts
packages/ui-plugin-sheets/src/components/font-size/FontSize.tsx
packages/ui-plugin-sheets/src/components/font-size/index.module.less
packages/ui-plugin-sheets/src/controllers/menu/border.menu.ts
packages/ui-plugin-sheets/src/controllers/menu/menu.ts
pnpm-lock.yaml

feat(base-ui): separate btn and arrow interaction within dropdowns

---

packages/base-docs/src/controllers/text-selection.controller.ts
packages/base-render/src/base-object.ts
packages/base-render/src/components/docs/text-selection-render-manager.ts
packages/base-render/src/scene.input-manager.ts
packages/base-render/src/scene.ts
packages/base-render/src/thin-scene.ts
packages/common-plugin-data/src/docs/default-document-data-cn.ts

feat: triple click to select paragraph

---

packages/base-sheets/src/commands/mutations/set-range-values.mutation.ts
packages/core/src/common/array.ts
packages/core/src/index.ts
packages/core/src/services/command/command.service.ts

* for formula to decide if a mutation should trigger recalculation
* for history to figure out what action caused a mutation

feat(core): command service add trigger params to mutations

---

packages/base-ui/src/views/app.module.less
packages/base-ui/src/views/components/context-menu/ContextMenu.tsx
packages/design/src/components/popup/Popup.stories.tsx
packages/design/src/components/popup/Popup.tsx
packages/design/src/components/popup/index.module.less
packages/design/src/components/tooltip/index.module.less
packages/sheets-plugin-formula-ui/src/views/prompt/help-function/HelpFunction.tsx
packages/sheets-plugin-formula-ui/src/views/prompt/help-function/index.module.less
packages/sheets-plugin-formula-ui/src/views/prompt/search-function/SearchFunction.tsx
packages/ui-plugin-sheets/src/controllers/header-menu.controller.ts
packages/ui-plugin-sheets/src/services/editor/cell-editor-manager.service.ts
packages/ui-plugin-sheets/src/views/editor-container/EditorContainer.tsx
packages/ui-plugin-sheets/src/views/operate-container/AutoFillPopupMenu.tsx
packages/ui-plugin-sheets/src/views/operate-container/index.module.less

feat(formula-ui): replace dropdown with popup

---

examples/data/src/docs/default-document-data-cn.ts
packages/core/src/shared/lru/lru-map.ts
packages/design/src/components/scrollbar/__tests__/index.spec.tsx
packages/docs/src/controllers/move-cursor.controller.ts
packages/docs/src/services/clipboard/html-to-udm/parse-node-style.ts
packages/docs/src/services/clipboard/html-to-udm/utils.ts
packages/engine-formula/src/engine/analysis/lexer.ts
packages/engine-formula/src/services/formula-engine.service.ts
packages/engine-render/src/components/docs/common/convert-cursor.ts
packages/engine-render/src/components/docs/common/tools.ts
packages/engine-render/src/components/docs/doc-skeleton.ts
packages/engine-render/src/components/docs/text-selection-render-manager.ts
packages/engine-render/src/scene.input-manager.ts

fix(doc): move cursor in list

---

examples/data/src/slides/rich-text/page5-richtext1.ts
packages/engine-render/src/components/docs/doc-skeleton.ts
packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/engine-render/src/components/sheets/spreadsheet.ts
packages/sheets-ui/src/controllers/editor/editing.controller.ts
packages/sheets-ui/src/controllers/editor/end-edit.controller.ts
packages/sheets/src/commands/mutations/set-range-values.mutation.ts

fix(sheet): text rotation is not overflow when set overflow format

---

examples/sheets/package.json
examples/sheets/src/sheets-plugin-debugger/commands/operations/saveSnapshot.operations.ts
examples/sheets/src/sheets-plugin-debugger/controllers/debugger.controller.ts
examples/sheets/src/sheets-plugin-debugger/controllers/menu.ts
examples/sheets/src/sheets-plugin-debugger/locale/en-US.ts
examples/sheets/src/sheets-plugin-debugger/locale/zh-CN.ts
packages/core/src/index.ts
packages/core/src/services/permission/permission.service.ts
packages/core/src/services/resource-manager/type.ts
packages/local-save/README.md
packages/local-save/esbuild.config.mjs
packages/local-save/package.json
packages/local-save/src/controller/export.controller.ts
packages/local-save/src/controller/record.controller.ts
packages/local-save/src/index.ts
packages/local-save/src/services/local-snapshot.service.ts
packages/local-save/src/util/index.ts
packages/local-save/tsconfig.esbuild.json
packages/local-save/tsconfig.json
packages/local-save/vitest.config.ts
packages/sheets/src/services/numfmt/numfmt.service.ts
pnpm-lock.yaml
tsconfig.json

[2023_12_7 16_41_14 video.webm](https://github.com/dream-num/univer/assets/141617023/8db7ef93-1aaf-4770-ba4b-17f0f2932b1a)
[2023_12_7 16_41_14 commands.json](https://github.com/dream-num/univer/files/13597639/2023_12_7.16_41_14.commands.json)
比如在第八秒的时候设置了条件格式，可以在 json 中根据时间戳找到对应的commands.

feat(debug): add snapshot save

---

examples/sheets/src/main.ts
packages/core/src/basics/univer.ts
packages/core/src/index.ts
packages/core/src/services/log/log.service.ts
packages/core/src/sheets/__tests__/create-core-test-bed.ts
packages/core/src/types/interfaces/i-univer-data.ts
packages/docs/src/commands/commands/__tests__/create-command-test-bed.ts
packages/engine-formula/src/engine/analysis/__tests__/create-command-test-bed.ts
packages/sheets-formula/src/commands/operations/__tests__/create-command-test-bed.ts
packages/sheets-formula/src/controllers/__tests__/create-command-test-bed.ts
packages/sheets-ui/src/services/clipboard/__tests__/clipboard-test-bed.ts
packages/sheets/src/commands/commands/__tests__/create-command-test-bed.ts
packages/sheets/src/controllers/__tests__/util.ts
packages/sheets/src/services/__tests__/util.ts
packages/sheets/src/services/ref-range/__tests__/util.ts
packages/sheets/src/services/sheet-interceptor/__tests__/create-core-test-bed.ts

~~Doesn't seem like the most suitable configuration name, any better suggestions?~~

feat(core): add `logLevel` flag to toggle the switch of log service

---

packages/sheets-formula/src/controllers/__tests__/formula-auto-fill.controller.spec.ts
packages/sheets-formula/src/controllers/__tests__/formula-clipboard.controller.spec.ts
packages/sheets-formula/src/controllers/formula-auto-fill.controller.ts

fix(formula): auto fill twice

---

packages/engine-render/src/components/docs/text-selection-render-manager.ts

fix(doc): word segmentation in list

---

packages/engine-formula/src/functions/__tests__/create-command-test-bed.ts
packages/engine-formula/src/functions/math/sumif/__tests__/sumif.spec.ts
packages/sheets-formula/src/views/prompt/help-function/HelpFunction.tsx
packages/sheets-formula/src/views/prompt/help-function/index.module.less
packages/sheets-formula/src/views/prompt/search-function/SearchFunction.tsx
packages/sheets-formula/src/views/prompt/search-function/index.module.less

test(formula): test case for sumif

---

packages/core/src/shared/common.ts
packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts
packages/engine-formula/src/engine/reference-object/base-reference-object.ts
packages/engine-formula/src/models/formula-data.model.ts
packages/sheets-formula/src/views/more-functions/MoreFunctions.tsx
packages/sheets-formula/src/views/more-functions/function-params/index.module.less
packages/sheets-formula/src/views/more-functions/select-function/SelectFunction.tsx
packages/sheets-formula/src/views/more-functions/select-function/index.module.less

fix(formula): auto fill with formula get A0 bug

---

packages/docs/src/commands/commands/__tests__/clipboard.command.spec.ts
packages/docs/src/commands/commands/__tests__/create-command-test-bed.ts
packages/docs/src/commands/commands/__tests__/inline-format.command.spec.ts
packages/docs/src/commands/commands/__tests__/mock-text-selection-render-manager.ts
packages/docs/src/commands/commands/__tests__/replace-content.command.spec.ts
packages/docs/src/commands/operations/select-all.operation.ts
packages/docs/src/commands/operations/text-selection.operation.ts
packages/docs/src/controllers/clipboard.controller.ts
packages/docs/src/controllers/delete.controller.ts
packages/docs/src/controllers/ime-input.controller.ts
packages/docs/src/controllers/inline-format.controller.ts
packages/docs/src/controllers/line-break-input.controller.ts
packages/docs/src/controllers/move-cursor.controller.ts
packages/docs/src/controllers/normal-input.controller.ts
packages/docs/src/controllers/text-selection.controller.ts
packages/docs/src/services/text-selection-manager.service.ts
packages/engine-render/src/basics/range.ts
packages/engine-render/src/components/docs/common/range.ts
packages/engine-render/src/components/docs/text-selection-render-manager.ts
packages/sheets-formula/src/controllers/formula-input.controller.ts
packages/sheets-formula/src/controllers/prompt.controller.ts
packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts
packages/sheets-ui/src/controllers/editor/start-edit.controller.ts

refactor(doc): text selection

---

packages/engine-formula/package.json
packages/engine-formula/src/basics/inverted-index-cache.ts
packages/engine-formula/src/basics/regex.ts
packages/engine-formula/src/basics/runtime.ts
packages/engine-formula/src/engine/ast-node/base-ast-node-factory.ts
packages/engine-formula/src/engine/ast-node/reference-node.ts
packages/engine-formula/src/engine/other-object/error-value-object.ts
packages/engine-formula/src/engine/reference-object/base-reference-object.ts
packages/engine-formula/src/engine/reference-object/table-reference-object.ts
packages/engine-formula/src/engine/value-object/array-value-object.ts
packages/engine-formula/src/engine/value-object/base-value-object.ts
packages/engine-formula/src/engine/value-object/primitive-object.ts
packages/engine-formula/src/functions/meta/compare/compare.ts
packages/engine-formula/src/functions/meta/divided/divided.ts
packages/engine-formula/src/functions/meta/minus/minus.ts
packages/engine-formula/src/functions/meta/multiply/multiply.ts
packages/engine-formula/src/functions/meta/plus/plus.ts
packages/engine-formula/src/index.ts
packages/engine-formula/src/services/calculate-formula.service.ts
packages/engine-formula/src/services/current-data.service.ts
packages/engine-formula/src/services/runtime.service.ts
packages/sheets-formula/src/controllers/formula-editor-show.controller.ts
packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
packages/sheets-ui/src/controllers/status-bar.controller.ts
packages/sheets/src/services/selection-manager.service.ts
pnpm-lock.yaml

feat(sheet): add big

---

packages/core/src/types/interfaces/i-range.ts
packages/sheets-ui/src/controllers/header-resize.controller.ts
packages/sheets/src/commands/commands/set-worksheet-row-height.command.ts
packages/sheets/src/commands/mutations/set-worksheet-row-height.mutation.ts
packages/sheets/src/index.ts

fix: serialization of autoHeight mutation params

---

examples/univer-plugin-debugger/src/controllers/performance-monitor.controller.ts
packages/docs/src/index.ts
packages/sheets-ui/src/index.ts
packages/sheets-ui/src/views/sheet-canvas-view.ts

fix: add sheet fps monitor

---

packages/engine-render/src/components/docs/block/paragraph/layout-ruler.ts

fix(doc): handle cases where a word is longer than one line

---

packages/engine-render/src/components/docs/text-selection-render-manager.ts

fix(doc): segmentor error when code point length is longer than 1

---

packages/docs/src/controllers/move-cursor.controller.ts

fix: move cursor at the beginning of document

---

packages/engine-render/src/components/docs/common/range.ts
packages/engine-render/src/components/docs/text-selection-render-manager.ts

fix: should not remove the last line break in editor

---

packages/engine-formula/src/engine/utils/compare.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-object.spec.ts
packages/engine-formula/src/engine/value-object/array-value-object.ts

feat(formula): select and slice for array

---

packages/engine-formula/src/engine/utils/__tests__/compare.spec.ts
packages/engine-formula/src/engine/utils/compare.ts
packages/engine-formula/src/engine/utils/object-compare.ts
packages/engine-formula/src/engine/value-object/array-value-object.ts
packages/engine-formula/src/engine/value-object/base-value-object.ts
packages/engine-formula/src/engine/value-object/primitive-object.ts
packages/engine-formula/src/functions/math/sumif/__tests__/sumif.spec.ts
packages/engine-formula/src/functions/math/sumif/sumif.ts

feat(formula): sumif supports simple wildcard

---

.github/workflows/preview-deploy.yml
package.json
packages/design/src/components/dropdown/Dropdown.tsx
packages/design/src/components/tooltip/Tooltip.tsx
packages/ui/src/views/components/doc-bars/Toolbar.tsx
packages/ui/src/views/components/doc-bars/ToolbarItem.tsx
packages/ui/src/views/components/doc-bars/index.module.less
turbo.json

close #
Move the overflowed toolbar item to the "more" dropdown menu.
need e2e test, not done yet

feat(ui): implement toolbar overflow with 'more' button

---

examples/public/index.html
examples/src/docs/main.ts
examples/src/main.tsx
examples/src/sheets/main.ts
examples/src/slides/main.ts
packages/design/src/components/design-token/Palette.tsx
packages/design/src/components/slider/index.module.less
packages/design/src/themes/base.less
packages/design/src/themes/default.module.less
packages/sheets-ui/src/views/sheet-bar/sheet-bar-button/index.module.less
packages/ui/src/views/App.tsx
packages/ui/src/views/app.module.less
packages/ui/src/views/components/doc-bars/Toolbar.tsx

feat: update design token

---

examples/src/sheets/lazy.ts
examples/src/sheets/main.ts
packages/core/src/basics/plugin-holder.ts
packages/core/src/basics/univer-doc.ts
packages/core/src/basics/univer-sheet.ts
packages/core/src/basics/univer-slide.ts
packages/core/src/basics/univer.ts
packages/core/src/plugin/plugin.ts
packages/docs/src/controllers/page-render.controller.ts

refactor(core): support lazy load plugins

---

packages/engine-render/src/basics/draw.ts
packages/engine-render/src/components/sheets/extensions/border-auxiliary.ts
packages/engine-render/src/components/sheets/extensions/border.ts
packages/engine-render/src/components/sheets/spreadsheet.ts
packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
packages/sheets-formula/src/controllers/update-formula.controller.ts

fix(sheet): border overflow

---

packages/docs/src/controllers/page-render.controller.ts

fix(doc): error in console

---

packages/engine-render/src/shape/scroll-bar.ts
packages/engine-render/src/viewport.ts
packages/sheets-ui/src/controllers/scroll.controller.ts

feat: make scroll by bar to be operations for liveshare

---

packages/sheets-ui/src/controllers/status-bar.controller.ts
packages/sheets-ui/src/services/status-bar.service.ts
packages/sheets-ui/src/views/status-bar/CopyableStatisticItem.tsx
packages/sheets-ui/src/views/status-bar/StatusBar.tsx

feat: add preconditons of number stastics

---

packages/docs/src/controllers/doc-render.controller.ts
packages/docs/src/controllers/page-render.controller.ts
packages/engine-render/src/components/docs/extensions/line.ts
packages/engine-render/src/scene.ts

fix(doc): page boder style and page size calculation

---

packages/docs/src/controllers/doc-render.controller.ts

fix(doc): only doc need to call scene resize

---

packages/core/src/services/command/command.service.ts
packages/engine-formula/src/controller/calculate.controller.ts
packages/rpc/src/services/remote-instance/remote-instance.service.ts
packages/sheets-ui/src/controllers/active-worksheet/active-worksheet.controller.ts
packages/sheets-ui/src/controllers/editor-bridge.controller.ts
packages/sheets/src/controllers/calculate-result-apply.controller.ts

close #
This PR changes the behavior when editor would close itself when mutations those will affect sheet skeleton execute.

fix: should not close editor when collab edits happen

---

packages/sheets-ui/src/controllers/menu/menu.ts

fix: menu icons would not change when text rotation is vertical

---

packages/engine-render/src/components/sheets/spreadsheet.ts

fix(sheet): zoom blur border

---

packages/engine-render/src/components/sheets/extensions/border-auxiliary.ts
packages/engine-render/src/components/sheets/extensions/column-header-layout.ts
packages/engine-render/src/components/sheets/extensions/font.ts
packages/engine-render/src/components/sheets/extensions/row-header-layout.ts
packages/engine-render/src/components/sheets/spreadsheet.ts
packages/sheets-ui/src/controllers/editor/start-edit.controller.ts

fix(sheet): editor and border

---

packages/sheets-ui/src/controllers/header-resize.controller.ts

fix(sheet): close editor with resize

---

packages/engine-formula/src/engine/reference-object/base-reference-object.ts
packages/engine-formula/src/engine/utils/math-kit.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-abs.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-acos.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-acosh.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-asin.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-asinh.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-atan.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-atan2.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-atanh.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-cbrt.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-ceil.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-cos.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-exp.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-floor.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-log.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-object.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-sin.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-tan.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-tanh.spec.ts
packages/engine-formula/src/engine/value-object/array-value-object.ts
packages/engine-formula/src/engine/value-object/base-value-object.ts
packages/engine-formula/src/engine/value-object/primitive-object.ts

formula basic calculation
next PR  var  std  negative

fix(formula): get cell value type

---

packages/sheets-ui/src/controllers/selection.controller.ts

feat(sheet): left top click all

---

packages/engine-formula/src/engine/value-object/__tests__/array-value-object.spec.ts
packages/engine-formula/src/engine/value-object/array-value-object.ts

feat(formula): add var,std

---

.github/workflows/preview-deploy.yml
.github/workflows/release-unstable.yml

ci: fix npm registry of actions

---

packages/uniscript/src/locale/en-US.ts
packages/uniscript/src/locale/zh-CN.ts
packages/uniscript/src/views/components/ScriptEditorPanel.tsx

feat: add uniscript i18n

---

packages/engine-render/src/components/sheets/extensions/background.ts
packages/engine-render/src/components/sheets/extensions/border.ts
packages/engine-render/src/components/sheets/extensions/font.ts
packages/engine-render/src/components/sheets/extensions/sheet-extension.ts
packages/engine-render/src/components/sheets/spreadsheet.ts
packages/engine-render/src/viewport.ts

fix(sheet): rendering error

---

packages/sheets-formula/src/common/selection.ts
packages/sheets-ui/src/services/selection/selection-shape.ts
packages/sheets/src/basics/selection.ts

fix(sheet): change selection  to 1.5

---

packages/core/src/services/command/command.service.ts
packages/sheets-ui/src/controllers/active-worksheet/active-worksheet.controller.ts

fix: fix set active worksheet

---

packages/docs/src/commands/commands/clipboard.inner.command.ts
packages/docs/src/services/clipboard/clipboard.service.ts
packages/docs/src/services/clipboard/html-to-udm/converter.ts

fix: paste plain text error

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/bug_report.zh-CN.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/feature_request.zh-CN.yml

chore: update issue template

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts

fix(sheet): line disapear

---

packages/sheets-ui/src/services/clipboard/clipboard.service.ts
packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
packages/sheets-ui/src/services/clipboard/html-to-usm/utils.ts

fix: paste rich format

---

packages/sheets-ui/src/commands/commands/__tests__/set-selections.command.spec.ts
packages/sheets-ui/src/commands/commands/utils/selection-utils.ts
packages/sheets-ui/src/controllers/editor-bridge.controller.ts
packages/sheets-ui/src/controllers/selection.controller.ts
packages/sheets/src/commands/commands/set-worksheet-col-width.command.ts
packages/sheets/src/commands/commands/set-worksheet-row-height.command.ts
packages/sheets/src/services/selection-manager.service.ts

fix(sheet-ui): fix col width dragging when selection the whole sheet

---

examples/src/plugins/zen-editor/controllers/zen-editor.controller.ts
packages/docs/src/basics/component-tools.ts
packages/docs/src/controllers/doc-render.controller.ts
packages/docs/src/controllers/text-selection.controller.ts
packages/engine-render/src/components/docs/text-selection-render-manager.ts

fix: doc scale when has selection

---

packages/sheets-numfmt/src/controllers/numfmt.copy-paste.controller.ts
packages/sheets-ui/src/index.ts
packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx

fix(numfmt): paste without numfmt

---

packages/engine-render/src/viewport.ts
packages/sheets-ui/package.json
packages/sheets-ui/src/commands/commands/__tests__/auto-fill.controller.spec.ts
packages/sheets-ui/src/commands/commands/auto-fill.command.ts
packages/sheets-ui/src/controllers/auto-fill.controller.ts
packages/sheets-ui/src/controllers/mark-selection.controller.ts
packages/sheets-ui/src/controllers/status-bar.controller.ts
packages/sheets-ui/src/services/clipboard/__tests__/clipboard-test-bed.ts
packages/sheets-ui/src/services/mark-selection/mark-selection.service.ts
packages/sheets-ui/src/services/status-bar.service.ts
packages/sheets-ui/src/sheets-ui-plugin.ts
packages/sheets-ui/src/views/status-bar/StatusBar.tsx
packages/sheets-ui/src/views/status-bar/index.module.less
packages/sheets/src/services/selection-manager.service.ts
pnpm-lock.yaml

fix(sheet): status bar

---

packages/docs/src/views/doc-canvas-view.ts

fix(doc): close doc  layer cache

---

packages/sheets/src/basics/const/command-listener-const.ts

fix(sheet): merge no refresh

---

package.json
packages/core/package.json
packages/design/package.json
packages/docs-ui/package.json
packages/docs/package.json
packages/engine-formula/package.json
packages/engine-numfmt/package.json
packages/engine-render/package.json
packages/image/package.json
packages/local-save/package.json
packages/network/package.json
packages/rpc/package.json
packages/sheets-find/package.json
packages/sheets-formula/package.json
packages/sheets-import-xlsx/package.json
packages/sheets-numfmt/package.json
packages/sheets-ui/package.json
packages/sheets/package.json
packages/slides-ui/package.json
packages/slides/package.json
packages/ui/package.json
packages/uniscript/package.json

build: release v0.1.0-beta.0

---

packages/sheets-ui/src/controllers/menu/border.menu.ts

fix: border button not displaying on the toolbar

---

packages/sheets-ui/src/controllers/editor-bridge.controller.ts

fix(sheet): input

---

README-ja.md
README-zh.md
README.md

I created Japanese translated README.

docs: add Japanese README

---

packages/engine-render/src/scene.input-manager.ts
packages/sheets-ui/src/controllers/editor-bridge.controller.ts
packages/sheets-ui/src/controllers/editor/start-edit.controller.ts

1. close #845 
2. 修复双击没有时效控制的 bug

fix: show context menu no need to enter edit status

---

packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx
packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/utils/slide-tab-bar.ts

fix(sheet): change sheet tab trigger alert

---

packages/sheets-ui/src/controllers/auto-height.controller.ts

fix: change col width no need to auto height row

---

packages/core/src/services/command/command.service.ts
packages/sheets-ui/src/controllers/sheet-ui.controller.ts
packages/sheets/src/commands/operations/selection.operation.ts
packages/sheets/src/controllers/basic-worksheet.controller.ts

chore: cleanup legacy code

---

packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx

fix: #879 no need to show context menu

---

packages/sheets-formula/src/controllers/__tests__/utils.spec.ts
packages/sheets-formula/src/controllers/update-formula.controller.ts
packages/sheets-formula/src/controllers/utils.ts

fix(formula): blank object bug

---

packages/core/src/shared/array-search.ts
packages/engine-render/src/components/docs/document.ts
packages/engine-render/src/components/docs/extensions/border.ts
packages/engine-render/src/components/sheets/column-header.ts
packages/engine-render/src/components/sheets/extensions/background.ts
packages/engine-render/src/components/sheets/extensions/border.ts
packages/engine-render/src/components/sheets/extensions/column-header-layout.ts
packages/engine-render/src/components/sheets/extensions/font.ts
packages/engine-render/src/components/sheets/extensions/row-header-layout.ts
packages/engine-render/src/components/sheets/extensions/sheet-extension.ts
packages/engine-render/src/components/sheets/row-header.ts
packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/engine-render/src/components/sheets/spreadsheet.ts
packages/engine-render/src/scroll-timer.ts
packages/engine-render/src/shape/base-scroll-bar.ts
packages/engine-render/src/shape/scroll-bar.ts
packages/engine-render/src/viewport.ts
packages/sheets-ui/src/controllers/editor-bridge.controller.ts
packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts
packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
packages/sheets-ui/src/controllers/freeze.controller.ts
packages/sheets-ui/src/controllers/selection.controller.ts
packages/sheets-ui/src/views/editor-container/EditorContainer.tsx
packages/sheets-ui/src/views/sheet-canvas-view.ts
packages/sheets/src/commands/commands/set-border-command.ts

fix(render): improvement error

---

.stylelintrc.json
packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
packages/sheets-ui/src/services/selection/selection-shape.ts
packages/sheets-ui/src/views/editor-container/index.module.less

fix(sheet): editor blur

---

packages/engine-render/src/components/sheets/spreadsheet.ts
packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
packages/sheets-ui/src/services/selection/selection-shape-extension.ts

fix(sheet): formula ref update and overflow error

---

packages/sheets-formula/src/controllers/prompt.controller.ts
packages/sheets/src/basics/selection.ts

fix(sheet): selection aux size and background

---

package.json
packages/core/package.json
packages/design/package.json
packages/docs-ui/package.json
packages/docs/package.json
packages/engine-formula/package.json
packages/engine-numfmt/package.json
packages/engine-render/package.json
packages/image/package.json
packages/network/package.json
packages/rpc/package.json
packages/sheets-find/package.json
packages/sheets-formula/package.json
packages/sheets-import-xlsx/package.json
packages/sheets-numfmt/package.json
packages/sheets-ui/package.json
packages/sheets/package.json
packages/slides-ui/package.json
packages/slides/package.json
packages/ui/package.json
packages/uniscript/package.json

build: release v0.1.0-beta.1

---

examples/src/plugins/zen-editor/commands/commands/zen-editor.command.ts
examples/src/plugins/zen-editor/controllers/zen-editor.controller.ts
packages/docs/src/views/doc-canvas-view.ts
packages/engine-render/src/components/docs/common/text-range.ts
packages/engine-render/src/components/docs/text-selection-render-manager.ts
packages/engine-render/src/shape/shape.ts
packages/sheets-ui/src/controllers/editor-bridge.controller.ts
packages/sheets-ui/src/services/editor-bridge.service.ts

fix: zen editor

---

packages/sheets-numfmt/src/controllers/numfmt.auto-fill.controller.ts
packages/sheets-ui/src/commands/commands/__tests__/auto-fill.controller.spec.ts
packages/sheets-ui/src/commands/commands/auto-fill.command.ts
packages/sheets-ui/src/commands/commands/refill.command.ts
packages/sheets-ui/src/controllers/auto-fill.controller.ts
packages/sheets-ui/src/index.ts
packages/sheets-ui/src/services/auto-fill/auto-fill.service.ts
packages/sheets-ui/src/services/auto-fill/type.ts
packages/sheets-ui/src/views/operate-container/AutoFillPopupMenu.tsx

refactor: auto fill hook

---

examples/src/sheets/main.ts
packages/sheets-zen-editor/src/plugin.ts

fix: rename plugin name of zen-editor

---

packages/core/src/index.ts
packages/core/src/sheets/reference.ts
packages/sheets-formula/src/controllers/prompt.controller.ts

fix(sheet): absolute ref

---

packages/core/src/services/command/command.service.ts
packages/core/src/services/lifecycle/lifecycle.service.ts
packages/core/src/services/log/log.service.ts

refactor(core): add info level to logservice

---

packages/sheets-ui/src/services/clipboard/__tests__/clipboard-service.spec.ts
packages/sheets-ui/src/services/clipboard/clipboard.service.ts
packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
packages/sheets-ui/src/views/operate-container/AutoFillPopupMenu.tsx
packages/ui/src/utils/cell.ts

close #830 
close #868 
close #774

fix(sheet): copypaste & auto filling bugs

---

packages/engine-render/src/context.ts

fix(sheet): fill text blur

---

.eslintrc.cjs
examples/src/main.tsx
packages/engine-formula/src/controller/calculate.controller.ts
packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
packages/engine-formula/src/services/calculate-formula.service.ts
packages/engine-render/src/components/docs/common/text-range.ts
packages/engine-render/src/group.ts
packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
packages/sheets-numfmt/src/components/stories/panel.stories.tsx
packages/sheets/src/basics/utils.ts
packages/sheets/src/controllers/feature-calculation.controller.ts

chore: disable console

---

packages/core/src/shared/rectangle.ts
packages/sheets/src/commands/mutations/__tests__/move-rows-cols.mutation.spec.ts
packages/sheets/src/commands/mutations/move-rows-cols.mutation.ts

fix(sheets): fix move row col undo params

---

packages/sheets-numfmt/src/controllers/numfmt.editor.controller.ts
packages/sheets-numfmt/src/menu/menu.ts

fix(numfmt): #852 the format is not preserved after the formula is entered

---

packages/core/src/shared/__test__/object-matrix.spec.ts
packages/core/src/shared/object-matrix.ts

fix(sheet): move row remove undefined

---

packages/sheets-ui/src/controllers/header-resize.controller.ts

fix(sheet): row and column resize

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts

fix: padding top issue

---

packages/core/src/docs/data-model/apply-utils/update-apply.ts
packages/core/src/docs/data-model/document-data-model.ts
packages/core/src/index.ts
packages/core/src/shared/common.ts
packages/core/src/types/interfaces/i-style-data.ts
packages/docs/src/commands/commands/inline-format.command.ts
packages/docs/src/controllers/clipboard.controller.ts
packages/engine-render/src/basics/font-cache.ts
packages/engine-render/src/components/docs/extensions/line.ts
packages/sheets-ui/src/controllers/menu/menu.ts

fix: inline format in cell

---

CONTRIBUTING.md

close https://github.com/dream-num/docs/issues/19

docs: add asking questions and reporting issues

---

packages/engine-render/src/viewport.ts

fix(sheet): resize window viewport error

---

packages/core/src/shared/object-matrix.ts
packages/engine-render/src/base-object.ts
packages/engine-render/src/group.ts
packages/engine-render/src/layer.ts
packages/sheets-formula/src/controllers/active-dirty.controller.ts
packages/sheets-formula/src/controllers/formula-clipboard.controller.ts
packages/sheets-numfmt/src/controllers/numfmt.copy-paste.controller.ts
packages/sheets-ui/src/commands/commands/__tests__/set-format-painter.command.spec.ts
packages/sheets-ui/src/commands/commands/auto-fill.command.ts
packages/sheets-ui/src/controllers/auto-fill.controller.ts
packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
packages/sheets-ui/src/controllers/clipboard/utils.ts
packages/sheets-ui/src/controllers/format-painter/format-painter.controller.ts
packages/sheets-ui/src/controllers/mark-selection.controller.ts
packages/sheets-ui/src/controllers/status-bar.controller.ts
packages/sheets-ui/src/services/auto-fill/tools.ts
packages/sheets-ui/src/services/clipboard/clipboard.service.ts
packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
packages/sheets-ui/src/services/clipboard/type.ts
packages/sheets-ui/src/services/clipboard/usm-to-html/convertor.ts
packages/sheets-ui/src/services/mark-selection/mark-selection.service.ts
packages/sheets/src/commands/commands/move-range.command.ts
packages/sheets/src/commands/mutations/move-range.mutation.ts

close #913 
close #909 
close #885 
close #867 
close #880 
close #892 
close #883
close #777 
2024.1.3 update
close #614 
close #775

fix(sheet): some bugs on copy&past and autofill

---

examples/src/uniscript/china-id-validation.js
examples/src/uniscript/draw-univer-logo.js
packages/core/src/types/interfaces/__tests__/i-cell-data.spec.ts
packages/core/src/types/interfaces/i-cell-data.ts
packages/facade/src/apis/sheet/__tests__/create-command-test-bed.ts
packages/facade/src/apis/sheet/__tests__/create-test-bed.ts
packages/facade/src/apis/sheet/__tests__/f-range.spec.ts
packages/facade/src/apis/sheet/__tests__/utils.spec.ts
packages/facade/src/apis/sheet/f-range.ts
packages/facade/src/apis/sheet/utils.ts
packages/sheets/src/commands/commands/__tests__/set-range-values.command.spec.ts
packages/sheets/src/commands/commands/set-range-values.command.ts
packages/uniscript/src/services/script-execution.service.ts

close #
```js
const activeSheet = univerAPI.getCurrentSheet().getActiveSheet();
// A1 设置数字
const range1 = activeSheet.getRange(0, 0, 1, 1);
range1.setValue(1);
// B1:C2 都设置字符串
const range2 = activeSheet.getRange(0, 1, 2, 2);
range2.setValue({ v: 'test' });
// D1:E2 都设置数字和背景色
const range3 = activeSheet.getRange(0, 3, 2, 2);
range3.setValue({
v: 2,
s: {
bg: { rgb: 'red' }
}
});
```
```js
const activeSheet = univerAPI.getCurrentSheet().getActiveSheet();
// B3:C4 设置值
const range1 = activeSheet.getRange(2, 1, 2, 2);
range1.setValues([[1,1],[1,1]]);
// D3:E4 设置值和背景色
const range2 = activeSheet.getRange(2, 3, 2, 2);
range2.setValues({
2:{
3: { 
v: 3,
s: {
bg: { rgb: 'yellow' }
}
},
4: { 
v: 4,
s: {
bg: { rgb: 'green' }
}
},
},
3:{
3: { 
v: 5,
s: {
bg: { rgb: 'orange' }
}
},
4: { 
v: 6,
s: {
bg: { …
```

feat(facade): range api

---

packages/engine-render/src/scroll-timer.ts
packages/sheets-ui/src/commands/commands/__tests__/auto-fill.controller.spec.ts
packages/sheets-ui/src/controllers/freeze.controller.ts
packages/sheets-ui/src/controllers/selection.controller.ts
packages/sheets-ui/src/services/selection/selection-render.service.ts

fix(sheet): freeze select selection issues

---

packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts
packages/sheets-ui/src/services/editor/formula-editor-manager.service.ts
packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx

fix: fx editor cursor

---

packages/sheets-formula/src/controllers/menu.ts
packages/sheets-numfmt/src/menu/menu.ts
packages/sheets-ui/src/components/font-size/FontSize.tsx
packages/sheets-ui/src/components/font-size/interface.ts
packages/sheets-ui/src/controllers/menu/border.menu.ts
packages/sheets-ui/src/controllers/menu/menu.ts
packages/sheets-ui/src/controllers/menu/merge.menu.ts
packages/sheets/src/index.ts
packages/sheets/src/services/permission/index.ts
packages/sheets/src/services/permission/tool.ts
packages/ui/src/controllers/shortcut-display/menu.ts
packages/ui/src/services/menu/menu.ts
packages/ui/src/views/components/doc-bars/ToolbarItem.tsx
packages/ui/src/views/components/doc-bars/index.module.less
packages/uniscript/src/controllers/menu.ts

fix(sheet): add disabled status on toolbar menu items

---

packages/engine-render/src/components/sheets/extensions/font.ts

fix(sheet): text align in sheet cell

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/sheets-formula/src/controllers/prompt.controller.ts

fix(sheet): formula input

---

packages/sheets-formula/src/commands/operations/__tests__/insert-function.operation.spec.ts
packages/sheets-formula/src/commands/operations/insert-function.operation.ts

fix(formula): insert function bug

---

packages/engine-formula/src/controller/formula.controller.ts
packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
packages/engine-formula/src/index.ts
packages/engine-formula/src/plugin.ts
packages/facade/package.json
packages/facade/src/apis/sheet/__tests__/create-test-bed.ts
packages/facade/vite.config.ts
packages/sheets-formula/src/formula-ui-plugin.ts
packages/sheets-formula/src/index.ts
packages/sheets-formula/src/services/description.service.ts
pnpm-lock.yaml

fix(facade): range api test

---

packages/core/src/shared/object-matrix.ts
packages/sheets/src/commands/mutations/__tests__/create-command-test-bed.ts
packages/sheets/src/commands/mutations/__tests__/remove-row-col.mutation.spec.ts
packages/sheets/src/commands/mutations/remove-row-col.mutation.ts

fix(sheet): #1030 undo failed to restore col-row width

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/engine-render/src/components/sheets/spreadsheet.ts

fix(sheet): overflow

---

packages/sheets-ui/src/controllers/selection.controller.ts
packages/sheets-ui/src/services/selection/selection-render.service.ts

fix(sheets): editing input canvas wrong position when set freeze

---

packages/sheets-numfmt/src/__tests__/utils.test.ts
packages/sheets-numfmt/src/utils/mutation.ts

fix(nunfmt): #1034 Error moving multiple data formats

---

packages/engine-formula/src/basics/common.ts
packages/engine-formula/src/basics/runtime.ts
packages/engine-formula/src/engine/dependency/formula-dependency.ts
packages/engine-formula/src/engine/reference-object/base-reference-object.ts
packages/engine-formula/src/engine/reference-object/range-reference-object.ts
packages/engine-formula/src/models/formula-data.model.ts
packages/engine-formula/src/services/calculate-formula.service.ts
packages/engine-formula/src/services/current-data.service.ts
packages/engine-formula/src/services/other-formula-manager.service.ts
packages/engine-formula/src/services/runtime.service.ts
packages/sheets-formula/src/controllers/active-dirty.controller.ts
packages/sheets-formula/src/controllers/formula-editor-show.controller.ts
packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
packages/sheets-formula/src/controllers/update-formula.controller.ts
packages/sheets-formula/src/controllers/utils.ts
packages/sheets-ui/src/services/selection/selection-shape.ts
packages/sheets/src/controllers/calculate-result-apply.controller.ts

fix(formula): redo delete sheet

---

packages/engine-render/src/components/docs/document.ts
packages/sheets-ui/src/controllers/editor/start-edit.controller.ts

fix: render error after scale

---

packages/engine-render/src/scroll-timer.ts
packages/sheets-ui/src/controllers/freeze.controller.ts
packages/sheets-ui/src/controllers/header-move.controller.ts
packages/sheets-ui/src/services/selection/selection-render.service.ts
packages/sheets-ui/src/services/selection/selection-shape-extension.ts
packages/sheets/src/commands/mutations/set-frozen.mutation.ts

fix(sheet): auto-fill conflict with freeze

---

packages/sheets-ui/src/controllers/auto-fill.controller.ts
packages/sheets/src/commands/operations/selection.operation.ts

fix(sheet): add actualRow and actualColumn to auto fill section

---

packages/engine-formula/src/engine/analysis/__tests__/lexer.spec.ts
packages/engine-formula/src/engine/dependency/dependency-tree.ts
packages/engine-formula/src/engine/dependency/formula-dependency.ts
packages/engine-formula/src/functions/lookup/indirect/__test__/index.spec.ts
packages/engine-formula/src/functions/math/sum/index.ts
packages/engine-formula/src/services/calculate-formula.service.ts
packages/engine-formula/src/services/runtime.service.ts

fix(sheet): array formula exceed

---

packages/sheets/src/services/numfmt/numfmt.service.ts

fix(sheet): resource should be disposed when univer dispose

---

packages/engine-formula/src/engine/analysis/__tests__/parser.spec.ts
packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
packages/sheets-ui/src/controllers/clipboard/utils.ts
packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
packages/sheets-ui/src/services/clipboard/usm-to-html/convertor.ts

fix: paste line break \n will cause crash

---

packages/sheets-ui/src/controllers/editor-bridge.controller.ts
packages/sheets-ui/src/services/editor-bridge.service.ts

fix: refresh cell size after edit by zen editor

---

packages/sheets-ui/src/controllers/editor/start-edit.controller.ts

fix: word unnecessary wrap

---

packages/engine-render/src/components/docs/block/paragraph/layout-ruler.ts

fix: wrong content height calculation

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts

fix: while rendering cell content, sometimes the text is truncated

---

packages/design/src/components/pager/Pager.stories.tsx
packages/design/src/components/pager/Pager.tsx
packages/design/src/components/pager/index.module.less
packages/design/src/components/pager/index.ts
packages/design/src/index.ts

feat(design): add Pager component

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/sheets-ui/src/common/keys.ts
packages/sheets-ui/src/controllers/freeze.controller.ts
packages/sheets-ui/src/services/selection/selection-shape.ts

fix(sheet): freeze render error on initialize phase

---

examples/package.json
packages/design/package.json
packages/design/src/components/input/InputWithSlot.stories.tsx
packages/design/src/components/input/InputWithSlot.tsx
packages/design/src/components/input/index.module.less
packages/design/src/components/input/index.ts
packages/design/src/components/pager/Pager.tsx
packages/design/src/components/pager/index.module.less
packages/sheets-formula/package.json
packages/sheets-numfmt/package.json
packages/sheets-ui/package.json
packages/sheets-zen-editor/package.json
packages/ui/package.json
pnpm-lock.yaml

feat(design): implement InputWithSlot component

---

packages/sheets-ui/src/commands/commands/set-scroll.command.ts
packages/sheets-ui/src/commands/operations/scroll.operation.ts
packages/sheets-ui/src/controllers/navigation/navigation.controller.ts
packages/sheets-ui/src/controllers/scroll.controller.ts
packages/sheets-ui/src/controllers/selection.controller.ts

fix: show full cell editor

---

packages/docs/src/commands/commands/list.command.ts
packages/sheets-ui/src/controllers/editor/end-edit.controller.ts

fix(sheet): use backspace empty cell content

---

packages/engine-formula/src/models/__tests__/formula-data.model.spec.ts
packages/engine-formula/src/models/formula-data.model.ts
packages/sheets-formula/src/controllers/formula-editor-show.controller.ts
packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
packages/sheets-formula/src/controllers/update-formula.controller.ts
packages/sheets-ui/src/controllers/editor/__tests__/create-test-bed.ts
packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
packages/sheets-ui/src/controllers/editor/end-edit.controller.ts

fix(formula): remove formula when content clear

---

examples/src/plugins/debugger/commands/operations/dialog.operation.ts
examples/src/plugins/debugger/controllers/menu.ts
packages/design/src/components/dialog/Dialog.tsx
packages/design/src/components/dialog/index.module.less
packages/ui/src/services/dialog/desktop-dialog.service.ts
packages/ui/src/services/dialog/dialog.service.ts

feat(design): polish draggable dialog

---

packages/sheets-ui/src/commands/operations/activate-cell-edit.operation.ts
packages/sheets-ui/src/controllers/editor-bridge.controller.ts
packages/sheets-ui/src/controllers/editor/end-edit.controller.ts
packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts
packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
packages/sheets-ui/src/services/editor-bridge.service.ts
packages/sheets-zen-editor/src/commands/commands/zen-editor.command.ts
packages/sheets-zen-editor/src/controllers/zen-editor.controller.ts
packages/sheets/src/commands/commands/clear-selection-content.command.ts
packages/sheets/src/commands/commands/remove-row-col.command.ts
packages/sheets/src/commands/mutations/remove-row-col.mutation.ts

fix: need to empty formula bar when press backspace

---

packages/docs/src/commands/commands/__tests__/create-command-test-bed.ts
packages/docs/src/commands/mutations/core-editing.mutation.ts
packages/docs/src/controllers/doc-render.controller.ts
packages/docs/src/controllers/ime-input.controller.ts
packages/docs/src/services/doc-skeleton-manager.service.ts
packages/docs/src/services/doc-view-model-manager.service.ts
packages/docs/src/views/doc-canvas-view.ts
packages/image/src/controllers/image.load.controller.ts

refactor: reduce the use of calculate and refactor view model manager

---

examples/src/plugins/debugger/commands/operations/dialog.operation.ts
packages/design/src/components/dialog/Dialog.tsx

feat(design): dialog could assign width

---

.github/workflows/preview-deploy.yml

ci(preview-deploy): display run id in comment

---

packages/sheets-formula/src/controllers/__tests__/utils.spec.ts
packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
packages/sheets-formula/src/controllers/update-formula.controller.ts
packages/sheets-formula/src/controllers/utils/__tests__/offset-formula-data.spec.ts
packages/sheets-formula/src/controllers/utils/__tests__/redo-undo-formula-data.spec.ts
packages/sheets-formula/src/controllers/utils/offset-formula-data.ts
packages/sheets-formula/src/controllers/utils/redo-undo-formula-data.ts
packages/sheets-formula/src/views/prompt/help-function/index.module.less

close #1011
close #1100
close #1108

fix(formula): offset array formula

---

packages/docs/src/commands/commands/delete.command.ts

fix: backspace in first paragraph

---

docs/tldr/ref-range/move-rows-cols.tldr
packages/sheets/src/services/ref-range/__tests__/util.spec.ts
packages/sheets/src/services/ref-range/util.ts

fix(ref-range): regional changes need to be fully contained within the line

---

packages/sheets-numfmt/src/controllers/numfmt.editor.controller.ts

fix(numfmt): #1132 should keep the style and use real values

---

packages/design/src/components/form-layout/FormLayout.stories.tsx
packages/design/src/components/form-layout/FormLayout.tsx
packages/design/src/components/form-layout/index.module.less
packages/design/src/components/form-layout/index.ts
packages/design/src/components/input/index.module.less
packages/design/src/index.ts

feat(design): add form-layout component

---

packages/sheets-ui/src/controllers/menu/sheet.menu.ts
packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarItem.tsx
packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx
packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/index.module.less
packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/utils/slide-tab-bar.ts

fix(sheet): only one sheet, disable remove button

---

packages/sheets/src/commands/mutations/empty.mutation.ts
packages/sheets/src/index.ts
packages/sheets/src/services/ref-range/util.ts

feat(sheet): export some util functions from sheets

---

packages/sheets-ui/src/commands/commands/delete-range-move-down-confirm.command.ts
packages/sheets-ui/src/commands/commands/delete-range-move-left-confirm.command .ts
packages/sheets-ui/src/commands/commands/insert-range-move-right-confirm.command.ts
packages/sheets-ui/src/commands/commands/insert-range-move-up-confirm.command.ts
packages/sheets-ui/src/controllers/menu/delete.menu.ts
packages/sheets-ui/src/controllers/menu/insert.menu.ts
packages/sheets-ui/src/controllers/sheet-ui.controller.ts
packages/sheets-ui/src/locale/en-US.ts
packages/sheets-ui/src/locale/zh-CN.ts

feat(merge-cell): support waring when insert or delete range

---

packages/design/src/components/popup/Popup.tsx
packages/sheets-ui/src/controllers/header-menu.controller.ts
packages/sheets-ui/src/controllers/selection.controller.ts
packages/sheets-ui/src/services/selection/selection-render.service.ts

fix(sheet-ui): should not activate selection when clicking on header menu

---

packages/facade/package.json
packages/facade/src/apis/__tests__/create-test-bed.ts
packages/facade/src/apis/__tests__/facade.spec.ts
packages/facade/src/apis/facade.ts
packages/facade/src/apis/sheet/__tests__/create-test-bed.ts
pnpm-lock.yaml

close #
1. start univer local : npm run dev:demo
2. use this script to create websocket, 
```js
const ws = univerAPI.createSocket("ws://47.100.177.253:8449/ws");
ws.open$.subscribe(() => {
console.log("websocket opened");
ws.send("hello");
});
ws.message$.subscribe((message) => {
console.log("websocket message", message);
const content = JSON.parse(message.data).content
if (content.indexOf('command') === -1) {
return;
}
const commandInfo = JSON.parse(content);
const { command, options } = commandInfo;
const { id, params } = command;
// 接受到协同数据，本地落盘
univerAPI.executeCommand(id, params, options)
});
ws.close$.subscribe(() => {
console.log("websocket closed");
});
ws.error$.subscribe((error) => {
console.log("websocket error", error);
});
univerAPI.onCommandExecuted((command, options) => { …
```

feat(facade): create websocket api

---

packages/engine-render/src/components/docs/document.ts

fix(sheet): text align error when test wrap

---

packages/sheets/src/controllers/merge-cell.controller.ts

fix(sheet): #1088 columns have horizontal cells,merge cells are retained when columns are deleted

---

.github/workflows/sync-mirror.yml

ci: update sync action

---

packages/sheets-ui/src/services/auto-fill/rules.ts
packages/sheets-ui/src/services/auto-fill/tools.ts
packages/sheets-ui/src/services/clipboard/clipboard.service.ts
packages/sheets-ui/src/services/clipboard/copy-content-cache.ts
packages/sheets-ui/src/views/operate-container/AutoFillPopupMenu.tsx

fix: some bugs in autofill

---

packages/sheets/src/commands/commands/insert-range-move-down.command.ts
packages/sheets/src/commands/commands/insert-range-move-right.command.ts

fix(sheet): invalid merged cell insertion range

---

packages/design/src/components/menu/index.module.less

fix(design): fix the z-index of the submenu component

---

packages/sheets-ui/src/controllers/editor/end-edit.controller.ts
packages/sheets-ui/src/controllers/editor/start-edit.controller.ts

fix: some cell editor issues

---

packages/sheets-ui/src/commands/commands/set-zoom-ratio.command.ts
packages/sheets-ui/src/commands/operations/set-zoom-ratio.operation.ts
packages/sheets-ui/src/controllers/editor-bridge.controller.ts
packages/sheets-ui/src/views/count-bar/ZoomSlider.tsx

fix: need to refresh cell editor size after scale

---

packages/sheets-numfmt/src/controllers/__tests__/cell-content.controller.spec.ts
packages/sheets-numfmt/src/controllers/__tests__/editor.controller.spec.ts
packages/sheets-numfmt/src/controllers/__tests__/test.util.ts
packages/sheets-numfmt/src/controllers/numfmt.cell-content.controller.ts
packages/sheets-numfmt/src/controllers/numfmt.controller.ts
packages/sheets-numfmt/src/controllers/numfmt.i18n.controller.ts
packages/sheets-numfmt/src/controllers/numfmt.menu.controller.ts
packages/sheets-numfmt/src/numfmt-plugin.ts
packages/sheets/src/index.ts

test(numfmt): add test case

---

packages/core/src/sheets/column-manager.ts
packages/core/src/sheets/row-manager.ts
packages/core/src/sheets/worksheet.ts
packages/sheets-ui/src/commands/commands/__tests__/add-worksheet-merge.command.spec.ts
packages/sheets-ui/src/commands/commands/__tests__/auto-fill.controller.spec.ts
packages/sheets-ui/src/commands/commands/__tests__/create-command-test-bed.ts
packages/sheets-ui/src/commands/commands/__tests__/hide-row-col-confirm.command.spec.ts
packages/sheets-ui/src/commands/commands/__tests__/remove-row-col-confirm.command.spec.ts
packages/sheets-ui/src/commands/commands/__tests__/selection-utils.spec.ts
packages/sheets-ui/src/commands/commands/__tests__/set-format-painter.command.spec.ts
packages/sheets-ui/src/commands/commands/hide-row-col-confirm.command.ts
packages/sheets-ui/src/commands/commands/remove-row-col-confirm.command.ts
packages/sheets-ui/src/commands/commands/utils/selection-utils.ts
packages/sheets-ui/src/controllers/menu/delete.menu.ts
packages/sheets-ui/src/controllers/menu/menu.ts
packages/sheets-ui/src/controllers/sheet-ui.controller.ts
packages/sheets-ui/src/locale/en-US.ts
packages/sheets-ui/src/locale/zh-CN.ts

fix(sheet): delete all row,columns alert

---

packages/sheets-ui/src/services/auto-fill/tools.ts

fix: calc repeats error

---

packages/find-replace/src/controllers/find-replace.menu.ts

fix: hide the menu item of find-replace in docs

---

packages/sheets-ui/src/commands/commands/__tests__/create-selection-command-test-bed.ts
packages/sheets-ui/src/commands/commands/set-selection.command.ts
packages/sheets-ui/src/services/shortcut-experience.service.ts
packages/sheets-ui/src/sheets-ui-plugin.ts
packages/ui/src/index.ts
packages/ui/src/ui-plugin.ts

refactor: move ShortcutExperienceService to sheets-ui

---

examples/src/plugins/debugger/controllers/performance-monitor.controller.ts
examples/src/sheets/main.ts
packages/core/src/basics/univer.ts
packages/rpc/src/services/rpc/rpc.service.ts
packages/sheets-ui/src/controllers/header-resize.controller.ts

fix(core): fix error in univer.dispose  @wzhudev

---

packages/sheets-numfmt/vite.config.ts

test(cache): wait

---

packages/design/src/components/slider/Slider.tsx
packages/design/src/components/slider/index.module.less

feat(design): add `disabled` prop of `Slider`

---

packages/sheets-numfmt/src/controllers/__tests__/auto-fill.controller.spec.ts

test(numfmt): repeat error

---

packages/core/src/index.ts
packages/core/src/services/command/command.service.ts
packages/core/src/services/context/__tests__/context.service.spec.ts
packages/core/src/services/context/context.service.ts
packages/design/src/hooks/observable.ts
packages/find-replace/src/views/dialog/Dialog.tsx
packages/sheets-ui/src/controllers/sheet-ui.controller.ts
packages/sheets-ui/src/controllers/shortcuts/view.shortcut.ts
packages/sheets-ui/src/views/count-bar/ZoomSlider.tsx

feat(sheet): disable zooming on editing

---

packages/engine-render/src/components/docs/text-selection-render-manager.ts

fix(sheet): cursor unnecessary movement

---

sonar-project.properties

Ref: https://docs.sonarsource.com/sonarcloud/advanced-setup/analysis-scope/#restrict-the-scope-duplication-detection
close #

ci: add sonar config

---

packages/facade/src/apis/facade.ts
packages/facade/src/apis/sheet/__tests__/f-range.spec.ts

fix(facade): rename getActiveSheet to getActiveWorkbook

---

examples/src/docs/main.ts
packages/engine-render/src/components/docs/text-selection-render-manager.ts

feat(doc): use shift + click to select text

---

examples/src/data/sheets/demo/default-workbook-data-demo.ts
examples/src/data/sheets/demo/default-workbook-data-demo3.ts
packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
packages/sheets/src/commands/commands/__tests__/set-range-values.command.spec.ts

fix: cursor postion error

---

packages/sheets-zen-editor/src/controllers/shortcuts/zen-editor.shortcut.ts
packages/sheets-zen-editor/src/controllers/zen-editor-ui.controller.ts

feat: support shortcut to confirm and cancel zen editor

---

packages/sheets-ui/src/controllers/header-unhide.controller.ts

fix: fix unhide widget not dispose on worksheet change

---

packages/sheets-ui/src/commands/commands/clipboard.command.ts
packages/sheets-ui/src/controllers/shortcuts/utils.ts

fix(sheet): fix sheet paste command not working

---

packages/ui/src/services/contextmenu/contextmenu.service.ts

feat(ui): support for disabling enablement in contextmenu service

---

packages/facade/src/apis/facade.ts

fix(facade): createUniverSheet interface

---

.github/workflows/ci-lint.yml
sonar-project.properties

build: remove sonar

---

packages/sheets-formula/src/controllers/prompt.controller.ts
packages/sheets-ui/src/controllers/editor/end-edit.controller.ts
packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx

fix(editor): change sheet clone

---

common/shared/package.json
package.json
packages/core/package.json
packages/design/package.json
packages/docs-ui/package.json
packages/docs/package.json
packages/engine-formula/package.json
packages/engine-numfmt/package.json
packages/engine-render/package.json
packages/facade/package.json
packages/find-replace/package.json
packages/network/package.json
packages/rpc/package.json
packages/sheets-find-replace/package.json
packages/sheets-formula/package.json
packages/sheets-numfmt/package.json
packages/sheets-ui/package.json
packages/sheets-zen-editor/package.json
packages/sheets/package.json
packages/slides-ui/package.json
packages/slides/package.json
packages/ui/package.json
packages/uniscript/package.json

chore(release): v0.1.0-beta.3

---

packages/engine-formula/src/engine/value-object/array-value-object.ts

fix(sheet): compare cache error

---

packages/engine-formula/src/basics/common.ts
packages/engine-formula/src/engine/ast-node/reference-node.ts
packages/engine-formula/src/engine/dependency/dependency-tree.ts
packages/engine-formula/src/engine/reference-object/base-reference-object.ts
packages/engine-formula/src/services/current-data.service.ts
packages/sheets-formula/src/controllers/active-dirty.controller.ts
packages/sheets-formula/src/controllers/prompt.controller.ts
packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
packages/sheets-formula/src/controllers/update-formula.controller.ts
packages/sheets/src/basics/interfaces/mutation-interface.ts
packages/sheets/src/commands/commands/remove-sheet.command.ts
packages/sheets/src/commands/mutations/insert-sheet.mutation.ts
packages/sheets/src/services/ref-range/util.ts

close #930
close #1067
close #1005
close #978
close #1214
close #1150
close #1262

fix(sheet): sheet name update formula

---

packages/sheets/src/index.ts

feat(sheet): add export

---

packages/sheets-zen-editor/src/controllers/shortcuts/zen-editor.shortcut.ts
packages/sheets-zen-editor/src/locale/en-US.ts
packages/sheets-zen-editor/src/locale/index.ts
packages/sheets-zen-editor/src/locale/zh-CN.ts
packages/sheets-zen-editor/src/plugin.ts

feat(sheet): add zen edit shortcut i18n

---

packages/core/src/docs/data-model/action-types.ts
packages/core/src/docs/data-model/apply-utils/common.ts
packages/core/src/docs/data-model/document-data-model.ts
packages/core/src/docs/data-model/text-x/__tests__/action-iterator.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/compose.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/text-x.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/utils.spec.ts
packages/core/src/docs/data-model/text-x/action-iterator.ts
packages/core/src/docs/data-model/text-x/text-x.ts
packages/core/src/docs/data-model/text-x/utils.ts
packages/core/src/index.ts
packages/docs/src/basics/retain-delete-params.ts
packages/docs/src/commands/commands/clipboard.inner.command.ts
packages/docs/src/commands/commands/core-editing.command.ts
packages/docs/src/commands/commands/delete.command.ts
packages/docs/src/commands/commands/ime-input.command.ts
packages/docs/src/commands/commands/inline-format.command.ts
packages/docs/src/commands/commands/list.command.ts
packages/docs/src/commands/commands/replace-content.command.ts
packages/docs/src/services/ime-input-manager.service.ts

refactor: compose actions

---

packages/core/src/docs/data-model/text-x/__tests__/compose.spec.ts
packages/core/src/docs/data-model/text-x/text-x.ts
packages/docs/src/commands/commands/ime-input.command.ts
packages/docs/src/services/ime-input-manager.service.ts

refactor: ime use compose method to build undo and redo params

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/sheets-ui/src/controllers/freeze.controller.ts
packages/sheets-ui/src/controllers/zoom.controller.ts
packages/sheets-ui/src/services/selection/selection-shape.ts

fix(sheet): freeze white

---

packages/docs/src/commands/commands/clipboard.command.ts
packages/sheets-ui/src/commands/commands/clipboard.command.ts

fix: copy formula

---

packages/core/src/index.ts

feat: export doc apis

---

packages/core/src/docs/data-model/__tests__/common.spec.ts
packages/core/src/docs/data-model/apply-utils/common.ts
packages/core/src/docs/data-model/text-x/__tests__/utils.spec.ts
packages/core/src/docs/data-model/text-x/text-x.ts
packages/core/src/docs/data-model/text-x/utils.ts

refactor: optimization of TextX codes

---

packages/docs/src/commands/commands/clipboard.command.ts
packages/docs/src/controllers/clipboard.controller.ts
packages/docs/src/services/clipboard/clipboard.service.ts
packages/sheets-ui/src/commands/commands/clipboard.command.ts
packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
packages/sheets-ui/src/services/clipboard/clipboard.service.ts

feat(doc): refactor doc clipboard and support firefox

---

common/shared/vite/index.js

build: add support for chrome70

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts

perf(sheet): overflow calculation

---

CONTRIBUTING.md
README-ja.md
README-zh.md
README.md

docs: remove legacy demo link from readme

---

.github/workflows/release.yml

ci: update release script

---

packages/sheets-ui/src/commands/commands/__tests__/auto-fill.controller.spec.ts
packages/sheets-ui/src/services/auto-fill/tools.ts

fix: auto fill number error in right direction

---

packages/docs/src/commands/commands/clipboard.inner.command.ts
packages/docs/src/commands/commands/core-editing.command.ts
packages/docs/src/commands/commands/delete.command.ts
packages/docs/src/commands/commands/ime-input.command.ts
packages/docs/src/commands/commands/inline-format.command.ts
packages/docs/src/commands/commands/list.command.ts
packages/docs/src/commands/commands/replace-content.command.ts
packages/docs/src/commands/mutations/core-editing.mutation.ts
packages/docs/src/services/ime-input-manager.service.ts

refactor: rename mutations to actions

---

common/shared/vite/index.js

chore: add `BUNDLE_TYPE` env variable

---

packages/core/src/types/const/const.ts

feat(core): set appVersion to package version

---

.vscode/settings.json
packages/core/src/index.ts
packages/core/src/services/undoredo/undoredo.service.ts
packages/docs/src/commands/commands/__tests__/create-command-test-bed.ts
packages/docs/src/commands/commands/clipboard.inner.command.ts
packages/docs/src/commands/commands/core-editing.command.ts
packages/docs/src/commands/commands/delete.command.ts
packages/docs/src/commands/commands/ime-input.command.ts
packages/docs/src/commands/commands/inline-format.command.ts
packages/docs/src/commands/commands/list.command.ts
packages/docs/src/commands/commands/replace-content.command.ts
packages/docs/src/commands/mutations/core-editing.mutation.ts
packages/docs/src/controllers/ime-input.controller.ts
packages/docs/src/doc-plugin.ts
packages/docs/src/services/doc-state-change-manager.service.ts
packages/docs/src/services/ime-input-manager.service.ts

refactor: history in document

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/bug_report.zh-CN.yml

chore: update issues template

---

packages/docs/src/index.ts

feat: export IDocStateChangeParams and DocStateChangeManagerService

---

packages/ui/src/views/components/doc-bars/Toolbar.tsx

feat: hide the header menu when there is no content in it

---

packages/docs/src/commands/commands/list.command.ts
packages/docs/src/commands/mutations/core-editing.mutation.ts
packages/docs/src/index.ts
packages/docs/src/services/text-selection-manager.service.ts

refactor(doc): serilize selections in mutation

---

packages/core/src/index.ts
packages/core/src/sheets/sheet-snapshot-utils.ts
packages/core/src/sheets/workbook.ts
packages/core/src/sheets/worksheet.ts
packages/core/src/types/const/const.ts
packages/facade/src/apis/sheet/f-workbook.ts
packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
packages/sheets/src/commands/commands/__tests__/create-command-test-bed.ts
packages/sheets/src/commands/commands/__tests__/set-col-width.command.spec.ts
packages/sheets/src/commands/commands/__tests__/set-row-height.command.spec.ts
packages/sheets/src/commands/commands/insert-sheet.command.ts

fix(sheet): fix snapshot references are not consistent

---

packages/docs/src/services/doc-state-change-manager.service.ts

fix: no history no need to collaboration

---

packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
packages/sheets-ui/src/services/clipboard/__tests__/clipboard-service.spec.ts
packages/sheets-ui/src/services/clipboard/clipboard.service.ts
packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts

fix: paste row height and col width

---

README-ja.md
README-zh.md
README.md

docs: add thanks to our sponsors

---

packages/docs/src/commands/commands/inline-format.command.ts
packages/docs/src/commands/mutations/core-editing.mutation.ts

fix: inline format error

---

packages/docs/src/services/ime-input-manager.service.ts

refactor: add Apis to IME service

---

.github/dependabot.yml
.github/workflows/release.yml
.release-it.json
package.json
pnpm-lock.yaml
pnpm-workspace.yaml

chore(changelog): support changelog

---

packages/sheets-ui/src/controllers/clipboard/utils.ts
packages/sheets-ui/src/controllers/status-bar.controller.ts
packages/sheets-ui/src/services/clipboard/__tests__/clipboard-service.spec.ts
packages/sheets-ui/src/services/clipboard/__tests__/clipboard-test-bed.ts
packages/sheets-ui/src/services/clipboard/clipboard.service.ts
packages/sheets/src/commands/commands/move-range.command.ts
packages/sheets/src/commands/commands/utils/selection-utils.ts

fix: cut paste undo bug & optimize status bar calc

---

packages/sheets-formula/src/controllers/update-formula.controller.ts

fix(sheet): formula ref move

---

packages/core/src/docs/data-model/document-data-model.ts

modify doc rev default value to 1

fix: modify doc rev default value

---

packages/docs/src/commands/commands/ime-input.command.ts
packages/docs/src/controllers/ime-input.controller.ts

refactor: ime controller

---

packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts

fix(sheet): auto add bracket

---

packages/docs/src/index.ts

refactor: export IME input service

---

packages/engine-render/src/context.ts
packages/engine-render/src/shape/shape.ts
packages/sheets-ui/src/services/selection/selection-shape.ts

fix(render): context native line width

---

packages/engine-render/src/basics/tools.ts
packages/engine-render/src/components/docs/document.ts
packages/sheets-ui/src/controllers/editor/start-edit.controller.ts

fix(sheet): default vertical align

---

packages/docs-ui/src/services/clipboard/html-to-udm/parse-node-style.ts
packages/sheets-ui/src/services/clipboard/html-to-usm/parse-node-style.ts

fix: no need to convert to px

---

.vscode/settings.json
packages/core/src/sheets/range.ts

fix(sheets): inline menu highlight error

---

packages/design/src/components/dialog/Dialog.tsx

feat: add `destroyOnClose` for `Dialog`

---

packages/sheets-ui/src/views/status-bar/index.module.less

style: standardize justify-content: `start` to `flex-start`

---

.release-it.json
packages/sheets-zen-editor/src/index.ts

feat(sheets-zen-editor): export language packs

---

packages/engine-render/src/basics/text-rotation.ts
packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/sheets-ui/src/services/editor-bridge.service.ts

fix(sheet): editor input

---

common/shared/package.json
package.json
packages/core/package.json
packages/design/package.json
packages/docs-ui/package.json
packages/docs/package.json
packages/engine-formula/package.json
packages/engine-numfmt/package.json
packages/engine-render/package.json
packages/facade/package.json
packages/find-replace/package.json
packages/network/package.json
packages/rpc/package.json
packages/sheets-find-replace/package.json
packages/sheets-formula/package.json
packages/sheets-numfmt/package.json
packages/sheets-ui/package.json
packages/sheets-zen-editor/package.json
packages/sheets/package.json
packages/slides-ui/package.json
packages/slides/package.json
packages/ui/package.json
packages/uniscript/package.json
pnpm-lock.yaml

chore: correct package.json exports field

---

packages/docs-ui/src/services/clipboard/udm-to-html/__test__/convertor.spec.ts
packages/docs-ui/src/services/clipboard/udm-to-html/convertor.ts

fix(doc): copy data

---

packages/engine-formula/src/engine/ast-node/value-node.ts

fix(sheet): formula boolean value

---

examples/src/data/docs/default-document-data-cn.ts
packages/engine-render/src/components/docs/block/paragraph/layout-ruler.ts

fix: page blank screen

---

packages/core/src/sheets/__tests__/ranges.spec.ts
packages/core/src/sheets/range.ts

fix: inline menu highlight

---

packages/docs/src/commands/mutations/core-editing.mutation.ts

fix: apply mutation

---

packages/docs-ui/src/locale/en-US.ts
packages/docs-ui/src/locale/zh-CN.ts
packages/find-replace/src/locale/en-US.ts
packages/find-replace/src/locale/zh-CN.ts
packages/sheets-numfmt/src/locale/en-US.ts
packages/sheets-numfmt/src/locale/zh-CN.ts
packages/sheets-ui/src/locale/en-US.ts
packages/sheets-ui/src/locale/zh-CN.ts
packages/sheets-zen-editor/src/locale/en-US.ts
packages/sheets-zen-editor/src/locale/zh-CN.ts
packages/sheets/src/locale/en-US.ts
packages/sheets/src/locale/zh-CN.ts
packages/slides-ui/src/locale/en-US.ts
packages/slides-ui/src/locale/zh-CN.ts
packages/slides/src/locale/en-US.ts
packages/slides/src/locale/zh-CN.ts
packages/ui/src/locale/en-US.ts
packages/ui/src/locale/zh-CN.ts
packages/uniscript/src/locale/en-US.ts
packages/uniscript/src/locale/zh-CN.ts

feat(i18n): add TypeScript type checking for localization files

---

packages/docs/src/commands/mutations/core-editing.mutation.ts

feat: add trigger in the if condition for share cursor use

---

common/shared/tsconfigs/base.json

chore(tsconfig): enable `noImplicitOverride` compiler option

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/engine-render/src/layer.ts
packages/engine-render/src/scene.-transformer.ts
packages/engine-render/src/shape/base-scroll-bar.ts
packages/engine-render/src/thin-scene.ts
packages/sheets-ui/src/services/selection/selection-shape.ts
packages/sheets-zen-editor/src/controllers/zen-editor-ui.controller.ts
packages/sheets-zen-editor/src/controllers/zen-editor.controller.ts
packages/ui/src/services/editor/editor.service.ts

fix(editor): zen error and formula align

---

packages/engine-render/src/components/docs/text-selection-render-manager.ts

fix: double click to selection also need to share cursor

---

packages/engine-render/src/basics/range.ts
packages/engine-render/src/components/docs/common/text-range.ts
packages/engine-render/src/components/docs/text-selection-render-manager.ts

refactor: update dom cursor to canvas cursor

---

packages/design/src/components/menu/index.module.less

fix(design): fix z-index for `SubMenu`

---

packages/engine-formula/src/engine/value-object/array-value-object.ts

fix https://github.com/dream-num/univer/discussions/1449

fix(engine-formula): ensure super is called at the beginning of the constructor

---

packages/core/src/docs/data-model/__tests__/replacement.spec.ts

test(doc): add one more test 

---

packages/engine-render/src/components/docs/text-selection-render-manager.ts

fix: only editing need to scrll to selection

---

packages/docs-ui/src/controllers/doc-ui.controller.ts
packages/ui/src/services/editor/editor.service.ts
packages/ui/src/services/layout/layout.service.ts

feat: add focus handler for doc

---

packages/sheets-numfmt/src/commands/commands/add-decimal.command.ts
packages/sheets-numfmt/src/commands/commands/set-percent.command.ts
packages/sheets-numfmt/src/commands/commands/subtract-decimal.command.ts
packages/sheets-numfmt/src/controllers/numfmt.controller.ts
packages/sheets-numfmt/src/controllers/numfmt.menu.controller.ts
packages/sheets-numfmt/src/menu/menu.ts

feat(numfmt): support percent

---

packages/docs-ui/src/controllers/back-scroll.controller.ts
packages/docs-ui/src/docs-ui-plugin.ts
packages/engine-render/src/components/docs/common/text-range.ts
packages/engine-render/src/components/docs/text-selection-render-manager.ts

refactor: adjust scroll top when selection change

---

examples/src/data/sheets/demo/default-workbook-data-demo.ts
examples/src/data/sheets/demo/default-workbook-data-demo4.ts

fix: wrong cell value in cell data

---

examples/src/sheets-multi/main.tsx
examples/src/slides/main.ts
examples/src/uniscript/main.ts
packages/core/src/types/interfaces/i-document-data.ts

fix(examples): fix multi-instance & uniscript UI rendering error

---

packages/docs-ui/src/services/clipboard/clipboard.service.ts

fix(doc): copy error when range is empty

---

packages/docs/src/commands/commands/inline-format.command.ts

fix(doc): need to serialize text ranges

---

examples/src/docs/main.ts
packages/sheets/src/commands/mutations/set-range-values.mutation.ts

fix(sheet): inline format error when textRuns is empty

---

packages/core/src/sheets/__tests__/worksheet.spec.ts
packages/core/src/sheets/worksheet.ts

feat(sheets): add row col iterator in worksheet

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts

fix(sheets-ui): dynamically adjust row header width

---

packages/docs-ui/src/controllers/clipboard.controller.ts
packages/sheets-ui/src/commands/commands/clipboard.command.ts
packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
packages/sheets-ui/src/locale/en-US.ts
packages/sheets-ui/src/locale/zh-CN.ts
packages/sheets-ui/src/services/clipboard/__tests__/clipboard-test-bed.ts
packages/sheets-ui/src/services/clipboard/clipboard.service.ts
packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
packages/sheets-ui/src/services/clipboard/utils.ts
packages/ui/src/controllers/shared-shortcut.controller.ts
packages/ui/src/index.ts

refactor(clipboard): always use native event for pasting

---

packages/design/src/components/dialog/Dialog.tsx
packages/design/src/components/dialog/index.module.less

fix(design): restore styles for non-draggable dialog

---

examples/src/plugins/debugger/views/test-editor/TestTextEditor.tsx
packages/core/src/shared/compare.ts
packages/docs-ui/src/controllers/doc-editor-bridge.controller.ts
packages/sheets-formula/src/controllers/prompt.controller.ts
packages/sheets-ui/src/services/selection/selection-render.service.ts
packages/ui/src/components/editor/TextEditor.tsx
packages/ui/src/components/range-selector/RangeSelector.tsx
packages/ui/src/services/editor/editor.service.ts

fix(editor): cursor and menu and single choice

---

examples/src/data/docs/default-document-data-cn.ts
examples/src/docs/main.ts
packages/docs-ui/src/services/clipboard/clipboard.service.ts
packages/docs-ui/src/services/clipboard/html-to-udm/parse-node-style.ts
packages/docs-ui/src/services/clipboard/html-to-udm/paste-plugins/plugin-univer.ts
packages/docs-ui/src/services/clipboard/html-to-udm/utils.ts
packages/docs-ui/src/services/clipboard/udm-to-html/__test__/convertor.spec.ts
packages/docs-ui/src/services/clipboard/udm-to-html/convertor.ts

fix(doc): copy form univer text and paste to univer

---

packages/core/src/shared/__test__/object-matrix.spec.ts
packages/engine-render/src/components/sheets/extensions/font.ts

feat(sheet): add font method

---

examples/package.json
packages/design/package.json
packages/design/src/components/date-range-picker/DateRangePicker.stories.tsx
packages/design/src/components/date-range-picker/DateRangePicker.tsx
packages/design/src/components/date-range-picker/index.module.less
packages/design/src/components/date-range-picker/index.ts
packages/find-replace/package.json
packages/sheets-formula/package.json
packages/sheets-numfmt/package.json
packages/sheets-ui/package.json
packages/sheets-zen-editor/package.json
packages/ui/package.json
packages/ui/src/views/components/doc-bars/ToolbarItem.tsx
pnpm-lock.yaml

feat(design): add `DateRangePicker`

---

examples/src/plugins/debugger/views/test-editor/TestTextEditor.tsx
packages/docs-ui/src/controllers/text-selection.controller.ts
packages/ui/src/components/editor/TextEditor.tsx
packages/ui/src/components/range-selector/RangeSelector.tsx
packages/ui/src/services/editor/editor.service.ts

fix(editor): controlled component and readonly

---

packages/engine-render/src/basics/draw.ts
packages/engine-render/src/components/docs/extensions/background.ts
packages/engine-render/src/components/docs/extensions/line.ts
packages/engine-render/src/components/sheets/extensions/background.ts
packages/engine-render/src/components/sheets/extensions/column-header-layout.ts
packages/engine-render/src/components/sheets/extensions/font.ts
packages/engine-render/src/components/sheets/extensions/row-header-layout.ts
packages/engine-render/src/components/sheets/spreadsheet.ts
packages/engine-render/src/context.ts

fix(render): rect blurring

---

examples/src/plugins/debugger/views/test-editor/TestTextEditor.tsx
packages/ui/src/components/range-selector/RangeSelector.tsx

fix(editor): add value

---

packages/sheets-formula/src/commands/operations/editor-formula.operation.ts
packages/sheets-formula/src/controllers/formula-ui.controller.ts
packages/sheets-formula/src/controllers/prompt.controller.ts
packages/sheets-formula/src/controllers/shortcuts/prompt.shortcut.ts
packages/sheets-formula/src/controllers/utils/utils.ts

feat(editor): support shortcut

---

packages/ui/src/components/editor/TextEditor.tsx

fix(editor): value change

---

packages/engine-render/src/components/component.ts
packages/engine-render/src/components/sheets/extensions/column-header-layout.ts
packages/facade/package.json
packages/facade/src/apis/__tests__/create-test-bed.ts
packages/facade/src/apis/__tests__/facade.spec.ts
packages/facade/src/apis/__tests__/utils/sheet-extension-util.ts
packages/facade/src/apis/docs/__tests__/create-test-bed.ts
packages/facade/src/apis/facade.ts
packages/facade/src/apis/sheets/__tests__/f-range.spec.ts
packages/facade/vite.config.ts
packages/facade/vitest.setup.ts
packages/sheets-ui/src/index.ts
pnpm-lock.yaml

close #
add facade apis for sheet render extension

feat(facade): register sheet render extension

---

packages/ui/src/common/component-manager.ts

fix(ui): handle dynamic import in renderVue3Component with try-catch due to esbuild limitations

---

examples/src/plugins/debugger/components/VueI18nIcon.vue
packages/design/src/components/dialog/Dialog.tsx
packages/design/src/components/dialog/index.module.less

feat(design): implement edge avoidance for `Dialog`

---

common/shared/vite/auto-externalize-dependency-plugin.js
examples/package.json
packages/design/package.json
packages/docs-ui/package.json
packages/find-replace/package.json
packages/sheets-formula/package.json
packages/sheets-numfmt/package.json
packages/sheets-ui/package.json
packages/slides-ui/package.json
packages/ui/package.json
packages/uniscript/package.json
pnpm-lock.yaml

chore(shared): implement auto-generation of peerDependencies

---

examples/src/data/sheets/demo/default-workbook-data-demo.ts
packages/core/src/types/interfaces/i-column-data.ts
packages/core/src/types/interfaces/i-row-data.ts
packages/sheets-ui/src/controllers/header-unhide.controller.ts

fix(sheet): the icons for hiding rows and columns do not disappear.

---

packages/find-replace/src/views/dialog/Dialog.tsx
packages/sheets-ui/src/views/count-bar/ZoomSlider.tsx
packages/ui/src/components/hooks/observable.ts

fix(ui): fix menu not displaying as expected

---

packages/core/src/types/interfaces/i-document-data.ts
packages/engine-render/src/components/docs/document.ts
packages/engine-render/src/components/sheets/sheet-skeleton.ts

fix(sheet): string bool and number align

---

packages/sheets-ui/src/controllers/editor/start-edit.controller.ts

fix(sheet): editor error

---

packages/docs/src/controllers/ime-input.controller.ts

fix: system shortcut teminate ime input

---

packages/engine-render/src/components/sheets/extensions/font.ts

fix(sheet): merge align

---

packages/engine-render/src/components/sheets/extensions/font.ts
packages/engine-render/src/components/sheets/sheet-skeleton.ts

feat(sheet): support font render config

---

packages/engine-render/src/components/sheets/extensions/font.ts

fix(render): update font offset

---

packages/sheets-numfmt/src/components/index.less

fix(sheets-numfmt): warning for postcss-preset-env

---

packages/core/src/index.ts

feat(core): export function to use in exchange

---

examples/src/data/sheets/demo/default-workbook-data-demo.ts
packages/engine-render/src/components/docs/extensions/border.ts
packages/engine-render/src/components/sheets/extensions/border.ts
packages/engine-render/src/components/sheets/extensions/column-header-layout.ts
packages/engine-render/src/components/sheets/extensions/row-header-layout.ts
packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/engine-render/src/components/sheets/spreadsheet.ts
packages/engine-render/src/context.ts
packages/engine-render/src/shape/shape.ts
packages/sheets-ui/src/components/border-panel/BorderPanel.tsx
packages/sheets-ui/src/components/border-panel/index.module.less
packages/sheets/src/commands/commands/set-border-command.ts

refactor(sheet): border render and set

---

packages/design/src/components/dialog/Dialog.tsx

fix(design): fix title in `Dialog` to use passed variable

---

examples/src/data/sheets/demo/default-workbook-data-demo.ts
packages/core/src/services/locale/locale.service.ts
packages/design/src/components/dialog/Dialog.tsx
packages/engine-render/src/components/docs/extensions/border.ts
packages/engine-render/src/components/sheets/extensions/border.ts
packages/engine-render/src/components/sheets/extensions/column-header-layout.ts
packages/engine-render/src/components/sheets/extensions/row-header-layout.ts
packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/engine-render/src/components/sheets/spreadsheet.ts
packages/engine-render/src/context.ts
packages/engine-render/src/shape/shape.ts
packages/sheets-ui/src/components/border-panel/BorderPanel.tsx
packages/sheets-ui/src/components/border-panel/index.module.less
packages/sheets/src/commands/commands/set-border-command.ts

feat(sheet): support ref-range-formula service and cell custom render

---

packages/engine-formula/src/basics/common.ts
packages/engine-formula/src/basics/runtime.ts
packages/engine-formula/src/commands/mutations/set-formula-calculation.mutation.ts
packages/engine-formula/src/controller/calculate.controller.ts
packages/sheets/src/controllers/calculate-result-apply.controller.ts

https://github.com/dream-num/univer-pro/issues/349
close #

fix(formula): worker error

---

packages/engine-render/src/basics/draw.ts
packages/engine-render/src/components/docs/extensions/border.ts
packages/engine-render/src/components/sheets/extensions/border.ts
packages/engine-render/src/context.ts

fix(sheet): border corner

---

packages/design/src/components/input/Input.tsx

feat(design): add `className` props to `Input`

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/sheets-ui/src/controllers/editor-bridge.controller.ts
packages/sheets/src/commands/commands/set-border-command.ts
packages/ui/src/components/range-selector/RangeSelector.tsx
packages/ui/src/services/range-selector/range-selector.service.ts

fix(editor):  range selector

---

packages/sheets-numfmt/README-zh.md
packages/sheets-numfmt/src/locale/zh-CN.ts

docs(sheet): numfmt i18n

---

examples/src/plugins/debugger/views/test-editor/TestTextEditor.tsx
packages/ui/src/components/editor/TextEditor.tsx
packages/ui/src/components/editor/index.module.less
packages/ui/src/components/range-selector/RangeSelector.tsx
packages/ui/src/components/range-selector/index.module.less
packages/ui/src/locale/en-US.ts
packages/ui/src/locale/zh-CN.ts
packages/ui/src/services/editor/editor.service.ts

feat(editor): style and placeholder

---

packages/sheets/src/basics/selection.ts

fix(sheet): selection color

---

packages/core/src/sheets/__tests__/worksheet.spec.ts
packages/core/src/sheets/worksheet.ts

feat: add function to extract pure text from cell

---

packages/core/src/sheets/__tests__/create-core-test-bed.ts
packages/docs/src/commands/commands/__tests__/create-command-test-bed.ts
packages/engine-formula/src/engine/analysis/__tests__/create-command-test-bed.ts
packages/engine-formula/src/functions/__tests__/create-function-test-bed.ts
packages/engine-formula/src/models/__tests__/create-command-test-bed.ts
packages/facade/src/apis/__tests__/create-test-bed.ts
packages/facade/src/apis/docs/__tests__/create-test-bed.ts
packages/facade/src/apis/sheets/__tests__/create-test-bed.ts
packages/sheets-formula/src/commands/operations/__tests__/create-command-test-bed.ts
packages/sheets-formula/src/controllers/__tests__/create-command-test-bed.ts
packages/sheets-numfmt/src/controllers/__tests__/test.util.ts
packages/sheets-ui/src/commands/commands/__tests__/create-command-test-bed.ts
packages/sheets-ui/src/controllers/editor/__tests__/create-test-bed.ts
packages/sheets-ui/src/services/clipboard/__tests__/clipboard-test-bed.ts
packages/sheets-ui/src/services/selection/__test__/create-service-test-bed.ts
packages/sheets/src/commands/commands/__tests__/create-command-test-bed.ts
packages/sheets/src/commands/mutations/__tests__/create-command-test-bed.ts
packages/sheets/src/controllers/__tests__/util.ts
packages/sheets/src/services/__tests__/util.ts
packages/sheets/src/services/ref-range/__tests__/util.ts
packages/sheets/src/services/sheet-interceptor/__tests__/create-core-test-bed.ts

chore: fix test plugins in test bed factories

---

packages/engine-formula/src/engine/analysis/__tests__/create-command-test-bed.ts
packages/engine-formula/src/functions/__tests__/create-function-test-bed.ts
packages/engine-formula/src/models/__tests__/create-command-test-bed.ts
packages/sheets-formula/src/commands/operations/__tests__/create-command-test-bed.ts
packages/sheets-formula/src/controllers/__tests__/create-command-test-bed.ts
packages/sheets-numfmt/src/controllers/__tests__/test.util.ts
packages/sheets-ui/src/services/clipboard/__tests__/clipboard-test-bed.ts
packages/sheets/src/controllers/__tests__/util.ts
packages/sheets/src/services/__tests__/util.ts
packages/sheets/src/services/ref-range/__tests__/util.ts
packages/sheets/src/services/sheet-interceptor/__tests__/create-core-test-bed.ts

chore: remove useless code

---

packages/sheets/src/commands/mutations/set-range-values.mutation.ts

fix: inline format in cell with rich text

---

packages/core/src/sheets/range.ts
packages/sheets-ui/src/controllers/menu/menu.ts

fix(sheet): inline format menu display error when paste

---

packages/core/src/sheets/workbook.ts

chore(sheets): silent duplicate name error

---

packages/sheets-ui/src/views/operate-container/index.module.less

fix(sheets-ui): fix z-index value in operate-container

---

packages/docs-ui/src/views/doc-canvas-view.ts
packages/engine-render/src/components/docs/document.ts

perf(render): optimize doc render

---

package.json
packages/design/src/components/config-provider/ConfigProvider.tsx
packages/design/src/components/dialog/Dialog.tsx
packages/design/src/components/dropdown/Dropdown.tsx
packages/design/src/components/menu/Menu.tsx
packages/design/src/components/select/Select.tsx
packages/design/src/components/tooltip/Tooltip.tsx
packages/design/src/themes/theme.ts
packages/docs/vite.config.ts
packages/facade/vite.config.ts
packages/ui/src/components/notification/Notification.tsx

feat(design): ssr support

---

packages/engine-formula/src/engine/reference-object/base-reference-object.ts
packages/engine-formula/src/engine/utils/object-compare.ts
packages/engine-formula/src/engine/value-object/array-value-object.ts
packages/engine-formula/src/engine/value-object/base-value-object.ts
packages/engine-formula/src/engine/value-object/primitive-object.ts
packages/engine-formula/src/functions/base-function.ts
packages/engine-formula/src/functions/math/product/index.ts
packages/engine-formula/src/functions/math/sum/index.ts
packages/engine-formula/src/functions/statistical/average/index.ts
packages/engine-formula/src/functions/statistical/count/index.ts
packages/engine-formula/src/functions/statistical/max/index.ts
packages/engine-formula/src/functions/statistical/min/index.ts
packages/engine-formula/src/functions/text/concatenate/index.ts

refactor(formula): function simply

---

packages/engine-formula/src/engine/value-object/__tests__/array-value-divided.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-minus.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-multiply.spec.ts
packages/engine-formula/src/engine/value-object/__tests__/array-value-plus.spec.ts
packages/engine-formula/src/engine/value-object/array-value-object.ts
packages/engine-formula/src/engine/value-object/base-value-object.ts
packages/engine-formula/src/functions/base-function.ts
packages/engine-formula/src/functions/math/abs/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/abs/index.ts
packages/engine-formula/src/functions/math/acos/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/acos/index.ts
packages/engine-formula/src/functions/math/acosh/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/acosh/index.ts
packages/engine-formula/src/functions/math/acot/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/acot/index.ts
packages/engine-formula/src/functions/math/mod/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/mod/index.ts
packages/engine-formula/src/functions/math/power/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/power/index.ts
packages/engine-formula/src/functions/math/product/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/sum/index.ts
packages/engine-formula/src/functions/statistical/counta/index.ts

fix(formula): math functions support string number calculation

---

packages/engine-render/src/index.ts

refactor: add more export apis from render engine

---

packages/engine-render/src/index.ts

fix: export more types from render engine plugin

---

common/storybook/package.json
packages/design/src/components/checkbox-group/CheckboxGroup.tsx
packages/design/src/components/checkbox-group/__tests__/index.spec.tsx
packages/design/src/components/checkbox/Checkbox.tsx
pnpm-lock.yaml

fix(design): fix checkbox group value couldn't be modified

---

packages/design/package.json
packages/design/src/components/segmented/Segmented.stories.tsx
packages/design/src/components/segmented/Segmented.tsx
packages/design/src/components/segmented/index.module.less
packages/design/src/components/segmented/index.ts
pnpm-lock.yaml

feat(design): add component Segmented

---

examples/src/docs/main.ts
packages/core/src/docs/data-model/document-data-model.ts
packages/core/src/docs/data-model/empty-snapshot.ts
packages/core/src/shared/tools.ts

feat: create empty doc by pass empty object `{}`

---

packages/core/src/types/interfaces/i-document-data.ts
packages/docs-ui/src/controllers/doc-render.controller.ts
packages/docs/src/commands/mutations/core-editing.mutation.ts

feat: add disable status to doc

---

packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts

fix(ui): should not make clipboard util iframe visible

---

packages/design/src/components/dialog/Dialog.tsx
packages/design/src/components/dialog/index.module.less
packages/find-replace/src/controllers/find-replace.controller.ts
packages/ui/src/views/components/dialog-part/DialogPart.tsx

close https://github.com/dream-num/univer-pro/issues/413
close https://github.com/dream-num/univer-pro/issues/365

fix(find-replace): fix dialog issues

---

packages/engine-formula/src/functions/text/text/index.ts

ci: fix type error

---

packages/sheets-ui/src/commands/commands/add-worksheet-merge.command.ts
packages/sheets/src/commands/utils/handle-merge-operation.ts
packages/ui/src/services/layout/layout.service.ts

close #1438
修复问题 
1.合并单元格后直接编辑编辑框位置不正确
2.undo、redo之前选区是不跟随合并单元格选区变化的问题
3.合并区间内有值的情况下 点击弹出modal的button导致焦点捕获后编辑不响应问题
[#1438]

fix(sheet): fix error edit position after merging

---

packages/engine-formula/src/engine/value-object/array-value-object.ts
pnpm-lock.yaml

fix(formula): array cache error

---

packages/ui/src/components/editor/TextEditor.tsx
packages/ui/src/services/editor/editor.service.ts

fix(editor): control state

---

packages/core/src/shared/__test__/rectangle.spec.ts
packages/core/src/shared/rectangle.ts
packages/engine-render/src/basics/viewport-subtract.ts
packages/engine-render/src/viewport.ts

fix: rectangle subtract func

---

packages/sheets/src/controllers/basic-worksheet.controller.ts

chore: register empty mutation

---

packages/engine-render/src/base-object.ts
packages/engine-render/src/components/docs/document.ts
packages/engine-render/src/shape/picture.ts
packages/engine-render/src/thin-scene.ts
packages/slides/src/views/render/canvas-view.ts

- refresh thumb on image loaded
- document scroll disappear

fix(slide): image loaded

---

packages/sheets/src/services/ref-range/__tests__/util.spec.ts
packages/sheets/src/services/ref-range/util.ts

fix(sheet): handleRemoveRowsCols util func

---

packages/facade/src/apis/sheets/f-workbook.ts

close #xxx, #yyy, #zzzz
use draw logo to test
https://github.com/dream-num/univer/blob/dev/examples/src/sheets-uniscript/draw-univer-logo.js

fix(facade): should not return promise in syncExecuteCommand

---

examples/package.json
packages/design/package.json
packages/find-replace/package.json
packages/sheets-formula/package.json
packages/sheets-numfmt/package.json
packages/sheets-ui/package.json
packages/sheets-zen-editor/package.json
packages/ui/package.json
pnpm-lock.yaml

refactor: update univer icons to latest version

---

examples/src/docs-uniscript/main.ts

fix(docs): remove deprecated property standalone

---

packages/sheets-formula/src/controllers/prompt.controller.ts
packages/ui/src/services/editor/editor.service.ts

1. invalid shortkey on sheet when focused editor shift
2. formula range to normal range error

fix(editor): short key error and normal range show

---

packages/core/src/index.ts
packages/core/src/shared/__test__/common.spec.ts
packages/core/src/shared/common.ts
packages/sheets-formula/src/controllers/__tests__/update-formula.controller.spec.ts
packages/sheets-formula/src/controllers/utils/__tests__/offset-formula-data.spec.ts
packages/sheets-numfmt/src/__tests__/utils.test.ts
packages/sheets-ui/src/controllers/clipboard/utils.ts
packages/sheets/src/basics/__tests__/rangeMerge.spec.ts
packages/sheets/src/commands/commands/__tests__/move-rows-cols.command.spec.ts
packages/sheets/src/commands/commands/move-range.command.ts
packages/sheets/src/commands/mutations/numfmt-mutation.ts
packages/sheets/src/services/__tests__/numfmt.service.test.ts

chore(core): move cellToRange to core

---

packages/core/src/shared/__test__/object-matrix.spec.ts
packages/core/src/shared/object-matrix.ts

fix: null-value unexpected deleted by moving

---

packages/slides-ui/package.json
packages/slides/package.json

ci(slides): publish slides and slides-ui

---

packages/slides-ui/src/index.ts
packages/slides-ui/src/locale/en-US.ts
packages/slides-ui/src/locale/zh-CN.ts
packages/slides/src/index.ts

fix(slides): export slides and slides ui locale

---

packages/sheets-ui/src/controllers/menu/merge.menu.ts
packages/sheets-ui/src/controllers/utils/selections-tools.ts

close #1515 
选区有重合时 不应该允许合并单元格操作 工具栏置灰 （对其excel和google）
#1515

fix(sheet): fix toolbar state when there is overlapping selection

---

packages/sheets/src/commands/commands/set-worksheet-order.command.ts
packages/sheets/src/commands/mutations/set-worksheet-order.mutation.ts

fix(sheet): set-tab-order-mutation should has fromIndex in parmas for transforming

---

README-ja.md
README-zh.md
README.md

the live demo link for zen-mode is not right.

docs: correct live demo link for zen mode

---

packages/core/src/services/lifecycle/lifecycle.ts

docs: update doc on runLifecycle

---

packages/sheets-formula/src/common/selection.ts
packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
packages/sheets-ui/src/views/editor-container/EditorContainer.tsx
packages/sheets-ui/src/views/editor-container/index.module.less
packages/sheets/src/basics/selection.ts

1.  selection size to 1px 
2. editor align to cell postion

fix(sheet): selection size and editor position

---

packages/core/src/docs/data-model/document-data-model.ts
packages/core/src/sheets/empty-snapshot.ts
packages/core/src/sheets/workbook.ts
packages/core/src/types/const/const.ts

* fix: change the _snapshot of the workbook to deep clone to avoid the side effects when you new an empty sheet.

fix(sheets): fix shallow copy bugs of the sheet snapshot

---

packages/engine-render/src/components/docs/layout/block/paragraph/layout-ruler.ts

fix: the error clip the last char when linebreak

---

packages/design/src/components/tooltip/Tooltip.tsx
packages/sheets-ui/src/views/status-bar/CopyableStatisticItem.tsx
packages/ui/src/common/z-index-manager.ts
packages/ui/src/views/components/doc-bars/index.module.less

fix(design): change tooltip to not remain active after hover

---

packages/facade/src/apis/__tests__/facade.spec.ts
packages/facade/src/apis/sheets/f-workbook.ts
packages/facade/src/apis/sheets/f-worksheet.ts

feat(facade): add getSheetBySheetId API on FWorkbook

---

packages/facade/src/apis/sheets/__tests__/f-range.spec.ts
packages/facade/src/apis/sheets/f-range.ts
packages/sheets/src/commands/commands/set-style.command.ts

fix facade
-  `range.setVerticalAlignment`  
-  `range.setHorizontalAlignment`
- `range.setWrap`
- `range.setWrapStrategy`

fix(facade): fix set horizontal, vertical, warp

---

packages/design/src/components/popup/RectPopup.tsx
packages/sheets-data-validation/src/common/date-text-map.ts
packages/sheets-data-validation/src/locales/enUS.ts
packages/sheets-data-validation/src/locales/zhCN.ts
packages/sheets-data-validation/src/services/dropdown-manager.service.ts
packages/sheets-data-validation/src/validators/date-validator.ts
packages/sheets-data-validation/src/views/list-dropdown/index.module.less
packages/sheets-data-validation/src/views/list-dropdown/index.tsx
packages/sheets-ui/src/controllers/cell-custom-render.controller.ts

feat(sheet): optimize data validation i18n & dropdown bugfix

---

packages/design/src/components/slider/index.module.less

* style: add the color and text decoration on the hover condition of the slider

style(design): add color and text-decoration-line on hover condition

---

packages/facade/src/apis/__tests__/facade.spec.ts
packages/facade/src/apis/sheets/f-worksheet.ts

In order to reduce the learning cost for facade API users, it is expected to align with the Google Apps Script API, https://developers.google.com/apps-script/reference/spreadsheet/sheet#getSheetId()
#1762

feat(facade): sheet api getId rename to getSheetId

---

packages/sheets-data-validation/src/models/sheet-data-validation-manager.ts

fix(sheet): data-validation delete mutation undo-redo

---

packages/engine-render/src/components/docs/layout/block/paragraph/shaping.ts

feat(doc): support char which length is great than 1

---

packages/facade/src/apis/__tests__/create-test-bed.ts
packages/facade/src/apis/__tests__/facade.spec.ts
packages/facade/src/apis/sheets/f-worksheet.ts

feat(facade): add getMaxColumns and getMaxRows API on FWorksheet

---

packages/sheets-data-validation/src/locale/en-US.ts
packages/sheets-data-validation/src/locale/zh-CN.ts
packages/sheets-data-validation/src/views/formula-input/list-formula-input.tsx

fix(sheets-data-validation): data-validation i18n

---

packages/docs-ui/src/services/index.ts
packages/sheets-ui/package.json
packages/sheets-ui/src/controllers/auto-fill.controller.ts
packages/sheets-ui/src/services/clipboard/clipboard.service.ts
packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
packages/sheets-ui/src/services/clipboard/html-to-usm/parse-node-style.ts
packages/sheets-ui/src/services/clipboard/html-to-usm/utils.ts
packages/sheets/src/commands/commands/__tests__/remove-rows-cols.command.spec.ts
packages/sheets/src/commands/commands/remove-row-col.command.ts
pnpm-lock.yaml

close #1541 
close #1397 
close #1253

fix(sheets): some bugs about copy&paste / remove row&col / autofill

---

packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts

fix(formula): bracket nested

---

packages/engine-formula/src/commands/mutations/set-defined-name.mutation.ts
packages/engine-formula/src/controller/formula.controller.ts
packages/engine-formula/src/index.ts
packages/sheets-ui/src/controllers/selection.controller.ts

fix(sheet): remove set current mutation

---

packages/engine-render/src/engine.ts

fix(engine-render): ignore media change on printing mode

---

packages/sheets/src/commands/commands/remove-worksheet-merge.command.ts

fix(sheets): fix the issue where the editor position is incorrect after unmerging cells

---

examples/src/plugins/debugger/views/test-editor/TestTextEditor.tsx
packages/core/src/common/const.ts
packages/core/src/index.ts
packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/colorScale.tsx
packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/dataBar.tsx
packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/formula.tsx
packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/iconSet.tsx
packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/index.tsx
packages/sheets-data-validation/src/views/detail/index.tsx
packages/sheets-data-validation/src/views/formula-input/custom-formula-input.tsx
packages/sheets-data-validation/src/views/formula-input/list-formula-input.tsx
packages/sheets-ui/src/views/defined-name/DefinedNameInput.tsx
packages/ui/src/components/editor/TextEditor.tsx

fix(sheet): update internal id

---

packages/core/src/services/command/command.service.ts
packages/rpc/src/services/remote-instance/remote-instance.service.ts

fix(rpc): skip missing mutations in remote replica

---

packages/engine-render/src/shape/shape.ts
packages/sheets-ui/src/services/editor-bridge.service.ts
packages/sheets-ui/src/services/selection/selection-shape.ts
packages/sheets-ui/src/views/editor-container/EditorContainer.tsx

fix(sheet): editor and selection position

---

packages/ui/src/components/font-family/FontFamily.tsx

fix: display error in font family

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/sheets/src/commands/mutations/set-range-values.mutation.ts

fix(sheets): inline format error in cell

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/sheets-ui/src/controllers/editor/start-edit.controller.ts

fix(sheets): auto height is not work when at default column width

---

examples/src/data/docs/default-document-data-en.ts
examples/src/docs/main.ts
packages/uniscript/src/controllers/menu.ts

fix: uniscript entry is displayed in zen mode

---

packages/design/src/components/popup/Popup.tsx
packages/ui/src/components/editor/TextEditor.tsx

fix https://github.com/karlsbeard/obsidian-univer/issues/32

fix(design): ensure popup component is appended to root to prevent offset from stacking contexts

---

packages/sheets-data-validation/src/services/dropdown-manager.service.ts

fix(sheets-data-validation): fix typescript error

---

packages/engine-formula/src/services/runtime.service.ts
packages/sheets-formula/src/controllers/array-formula-display.controller.ts
packages/sheets-formula/src/controllers/formula-editor-show.controller.ts

fix(formula): null value return not zero

---

examples/src/docs/main.ts
packages/engine-render/src/basics/font-cache.ts
packages/engine-render/src/basics/tools.ts
packages/engine-render/src/components/docs/extensions/font-and-base-line.ts
packages/engine-render/src/components/docs/extensions/line.ts

fix(docs): strikethrough position is incorrect

---

eslint.config.js

https://github.com/eslint/eslint/issues/4808

ci: add complexity check

---

packages/design/src/components/checkbox/Checkbox.stories.tsx
packages/design/src/components/checkbox/Checkbox.tsx
packages/design/src/components/checkbox/__tests__/index.spec.tsx
packages/design/src/components/checkbox/index.module.less
packages/design/src/components/select/index.module.less

feat(design): add `indeterminate` property support to Checkbox component

---

eslint.config.js

refactor: ingore some files for layout and render

---

CONTRIBUTING.md
docs/NAMING_CONVENTION.md

docs: add naming convertion

---

packages/engine-formula/src/engine/analysis/__tests__/parser.spec.ts
packages/engine-formula/src/engine/analysis/parser.ts
packages/engine-formula/src/engine/ast-node/reference-node.ts

fix(sheet-formula): fix error message on missing formula

---

examples/src/data/docs/default-document-data-cn.ts
packages/engine-render/src/basics/i-document-skeleton-cached.ts
packages/engine-render/src/basics/interfaces.ts
packages/engine-render/src/basics/tools.ts
packages/engine-render/src/components/docs/document.ts
packages/engine-render/src/components/docs/extensions/background.ts
packages/engine-render/src/components/docs/layout/model/glyph.ts
packages/engine-render/src/components/docs/layout/shaping-engine/font-cache.ts
packages/engine-render/src/components/docs/layout/tools.ts

fix: text is cropped when rendered in italic style with background

---

packages/engine-render/src/components/docs/layout/block/paragraph/layout-ruler.ts
packages/engine-render/src/components/docs/layout/block/paragraph/layout.ts

refactor: optimization of text layout when ends with lots of white space

---

packages/docs-ui/src/controllers/doc-editor-bridge.controller.ts
packages/sheets-ui/src/controllers/editor-bridge.controller.ts
packages/sheets-ui/src/controllers/shortcuts/editor.shortcut.ts
packages/sheets-ui/src/services/selection/selection-shape.ts
packages/sheets/src/commands/commands/utils/selection-utils.ts

fix(sheet): range selector drag row

---

packages/sheets-conditional-formatting-ui/src/controllers/cf.render.controller.ts

fix(conditional-formatting): gradient fills may conceal cell values

---

packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
packages/engine-formula/src/engine/analysis/__tests__/lexer.spec.ts
packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts
packages/engine-formula/src/engine/analysis/lexer.ts
packages/engine-formula/src/engine/utils/__tests__/reference.spec.ts
packages/engine-formula/src/engine/utils/reference.ts
packages/engine-formula/src/engine/utils/relative-formula.ts
packages/engine-formula/src/index.ts
packages/engine-formula/src/models/formula-data.model.ts
packages/engine-formula/src/plugin.ts
packages/sheets-conditional-formatting/src/services/calculate-unit/highlight-cell.ts
packages/sheets-data-validation/src/controllers/dv-ref-range.controller.ts
packages/sheets-data-validation/src/services/dv-custom-formula.service.ts
packages/sheets-data-validation/src/validators/list-multiple-validator.ts
packages/sheets-data-validation/src/validators/list-validator.ts
packages/sheets-data-validation/src/views/formula-input/list-formula-input.tsx
packages/sheets-formula/src/controllers/__tests__/create-command-test-bed.ts
packages/sheets-formula/src/controllers/__tests__/formula-clipboard.controller.spec.ts
packages/sheets-formula/src/controllers/formula-auto-fill.controller.ts
packages/sheets-formula/src/controllers/formula-clipboard.controller.ts
packages/sheets-formula/src/controllers/formula-editor-show.controller.ts
packages/sheets-formula/src/controllers/prompt.controller.ts
packages/sheets-formula/src/controllers/update-formula.controller.ts
packages/sheets-formula/src/services/description.service.ts
packages/sheets-formula/src/services/formula-ref-range.service.ts
packages/sheets-ui/src/controllers/selection.controller.ts
packages/sheets-ui/src/views/defined-name/DefinedNameInput.tsx
packages/ui/src/components/range-selector/RangeSelector.tsx
packages/ui/src/services/editor/editor.service.ts

refactor(formula): defined name lexer

---

packages/core/src/types/interfaces/i-range.ts
packages/engine-formula/src/basics/__tests__/regex.spec.ts
packages/engine-formula/src/engine/utils/__tests__/reference.spec.ts
packages/engine-formula/src/engine/utils/reference.ts
packages/engine-formula/src/index.ts
packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/index.tsx
packages/sheets-formula/src/services/description.service.ts
packages/sheets-ui/src/controllers/selection.controller.ts
packages/sheets-ui/src/views/defined-name/DefinedNameInput.tsx
packages/ui/src/components/range-selector/RangeSelector.tsx
packages/ui/src/services/editor/editor.service.ts

refactor(sheet): defined name lexer

---

examples/src/sheets/main.ts
packages/design/src/components/popup/RectPopup.tsx
packages/design/src/components/popup/index.module.less
packages/sheets-data-validation/src/controllers/dv-alert.controller.ts
packages/sheets-data-validation/src/controllers/dv-render.controller.ts
packages/sheets-data-validation/src/controllers/dv.controller.ts
packages/sheets-ui/src/controllers/cell-custom-render.controller.ts
packages/sheets-ui/src/services/canvas-pop-manager.service.ts
packages/sheets-ui/src/services/cell-alert-manager.service.ts
packages/sheets-ui/src/views/cell-alert/CellAlertPopup.tsx
packages/ui/src/views/App.tsx
packages/ui/src/views/app.module.less
packages/ui/src/views/components/popup/CanvasPopup.tsx
packages/ui/src/views/parts.ts

feat(sheets-ui): optimize popup service

---

packages/ui/src/services/layout/layout.service.ts

fix(sheet): editor set rich error

---

packages/sheets-ui/src/controllers/editor-bridge.controller.ts
packages/ui/src/services/layout/layout.service.ts

fix(sheets): refocus sheet cell when create new sheet

---

packages/design/src/components/popup/RectPopup.tsx

fix(design): rect-popup event bind error

---

packages/ui/src/controllers/ui/ui-desktop.controller.tsx

fix(sheet): life cycle steady

---

packages/sheets-formula/src/controllers/prompt.controller.ts
packages/sheets-zen-editor/src/controllers/shortcuts/zen-editor.shortcut.ts

fix(sheet): esc key for editor

---

packages/engine-render/.vscode/settings.json
packages/engine-render/src/components/docs/layout/block/paragraph/layout-ruler.ts
packages/engine-render/src/components/docs/layout/block/paragraph/line-adjustment.ts
packages/engine-render/src/components/docs/layout/block/paragraph/linebreaking.ts
packages/engine-render/src/components/docs/layout/block/paragraph/shaping.ts
packages/engine-render/src/components/docs/layout/doc-skeleton.ts
packages/engine-render/src/components/docs/layout/tools.ts

fix(docs): the line leader punctuation is not squeezed

---

examples/src/data/docs/default-document-data-cn.ts
examples/src/data/docs/default-document-data-dreamer.ts
examples/src/data/docs/default-document-data-en.ts
examples/src/docs/main.ts
packages/engine-render/src/components/docs/document.ts
packages/engine-render/src/components/docs/layout/block/paragraph/layout-ruler.ts
packages/engine-render/src/components/docs/layout/block/paragraph/linebreaking.ts
packages/engine-render/src/components/docs/layout/doc-skeleton.ts

refactor(render-engine): columns are not rendered properly

---

examples/src/slides/main.ts
packages/engine-render/src/components/sheets/extensions/column-header-layout.ts
packages/engine-render/src/components/sheets/extensions/row-header-layout.ts

fix(sheet): header hidden

---

packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/index.tsx

fix(conditional-formatting): create cf rule error

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/image/src/plugin.ts

refactor: add plugin type to image plugin

---

examples/src/sheets/main.ts
packages/core/src/services/plugin/plugin-holder.ts
packages/core/src/services/plugin/plugin.service.ts
packages/core/src/univer.ts

fix: fix univer plugin lifecycle not triggered

---

packages/core/src/types/interfaces/i-cell-data.ts
packages/sheets-ui/src/locale/en-US.ts
packages/sheets-ui/src/locale/zh-CN.ts
packages/sheets-ui/src/services/clipboard/__tests__/clipboard-test-bed.ts
packages/sheets-ui/src/services/clipboard/clipboard.service.ts
packages/sheets/src/commands/commands/copy-worksheet.command.ts
packages/sheets/src/commands/commands/insert-range-move-down.command.ts
packages/sheets/src/commands/commands/insert-range-move-right.command.ts
packages/sheets/src/commands/commands/insert-sheet.command.ts
packages/sheets/src/commands/commands/move-range.command.ts
packages/sheets/src/commands/commands/move-rows-cols.command.ts
packages/sheets/src/commands/commands/set-worksheet-hide.command.ts
packages/sheets/src/locale/en-US.ts
packages/sheets/src/locale/zh-CN.ts

close #1334
如何测试？
国际化测试，拖动一行穿过合并单元格，中文状态下提示中文提示语

fix(sheet): add cell custom field

---

examples/src/plugins/debugger/controllers/e2e/e2e-memory.controller.ts
package.json
packages/ui/src/controllers/ui/ui-desktop.controller.tsx

fix: fix non-sheet renderer should not be set container

---

packages/network/src/index.ts

feat: export identifiers from packages index.ts

---

packages/core/src/shared/common.ts
packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-font.spec.ts
packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-form-excel.spec.ts
packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-from-google.spec.ts
packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
packages/sheets-ui/src/services/clipboard/html-to-usm/parse-node-style.ts
packages/ui/src/utils/cell.ts

fix: replace whitespace characters in html str

---

packages/engine-render/src/basics/draw.ts
packages/engine-render/src/components/docs/document.ts
packages/engine-render/src/components/docs/layout/tools.ts
packages/engine-render/src/components/sheets/extensions/font.ts

fix(render-engine): punctuation render error in sheet cell

---

packages/sheets-data-validation/README-zh.md
packages/sheets-data-validation/README.md

docs(sheets-data-validation): update readme

---

packages/ui/src/controllers/ui/ui-desktop.controller.tsx

fix: fix current render handling in desktop controller

---

examples/src/sheets/main.ts
packages/sheets-formula/src/controllers/array-formula-display.controller.ts
packages/sheets-formula/src/controllers/formula-editor-show.controller.ts
packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
packages/sheets-ui/src/views/defined-name/index.module.less
packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
packages/sheets-ui/src/views/sheet-container/SheetContainer.tsx
packages/ui/src/components/progress-bar/ProgressBar.tsx
packages/ui/src/components/progress-bar/index.module.less
packages/ui/src/index.ts
packages/ui/src/services/__tests__/progress.service.spec.ts
packages/ui/src/services/progress/progress.service.ts
packages/ui/src/ui-plugin.ts

如何测试？
表格中超过500个公式进行计算时就会出现进度条
参照 google 放在 formula bar右侧，防止与输入内容重叠

feat(formula): formula calculation progress

---

packages/data-validation/src/plugin.ts

fix(dv): fix data validation plugin type to prevent loading error

---

packages/ui/src/services/layout/layout.service.ts
packages/ui/src/ui-plugin.ts

fix(ui): fix close ui plugin config and focus capturing

---

examples/src/sheets/main.ts
packages/facade/src/apis/__tests__/facade.spec.ts
packages/facade/src/apis/facade.ts
packages/facade/src/apis/sheets/__tests__/f-workbook.spec.ts
packages/facade/src/apis/sheets/__tests__/f-worksheet.spec.ts
packages/facade/src/apis/sheets/f-workbook.ts
packages/facade/src/apis/sheets/f-worksheet.ts

close #2047
如何测试？
打开sheets，打开浏览器控制台，分别粘贴以下代码测试API
```js
// 插入工作表
const workbook = univerAPI.getActiveWorkbook();
workbook.insertSheet();
```
```js
// 激活 工作表 sheet0002
const workbook = univerAPI.getActiveWorkbook();
const sheet = workbook.getSheetByName('sheet0002')
workbook.setActiveSheet(sheet)
```
```js
// 删除第一个工作表
const workbook = univerAPI.getActiveWorkbook();
const sheets = workbook.getSheets();
workbook.deleteSheet(sheets[0]);
```

feat(facade): workbook and worksheet operation

---

packages/ui/src/services/global-zone/desktop-global-zone.service.ts
packages/ui/src/services/global-zone/global-zone.service.ts
packages/ui/src/views/components/global-zone/GlobalZone.tsx

fix: global-zone componentKey initial value error

---

packages/engine-render/src/components/docs/layout/tools.ts
packages/engine-render/src/render-manager/render-manager.service.ts
packages/slides-ui/src/views/slide-bar/SlideBar.tsx

fix: fix slide rendering

---

README.md

docs(univer): update readme

---

packages/engine-formula/src/models/__tests__/formula-data.model.spec.ts
packages/engine-formula/src/models/formula-data.model.ts
packages/facade/src/apis/__tests__/create-test-bed.ts
packages/facade/src/apis/sheets/__tests__/f-range.spec.ts
packages/facade/src/apis/sheets/f-range.ts
packages/sheets-formula/src/controllers/formula-editor-show.controller.ts

close #2090
docs https://github.com/dream-num/univer.ai/pull/128
如何测试？
1. 打开sheet
2. 新建工作表
3. A1输入=B1
4. 将A1向下下拉填充3个单元格
5. 打开浏览器控制台，打开 uniscript 面板
6. uniscript 面板输入
```js
const activeWorkbook = univerAPI.getActiveWorkbook();
const activeSheet = activeWorkbook.getActiveSheet();
const range = activeSheet.getRange(0, 0, 5, 1);
console.log(range.getFormulas());
```
执行脚本
7. 控制台打印
```js
[['=B1'],['=B2'],['=B3'],['=B4'],['']]
```

feat(facade): get formulas by range

---

packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx

fix(render-engine): fx column dose not display content

---

.github/workflows/playwright.yml

https://github.com/dream-num/univer/actions/runs/8979884768/job/24662629124
ref: https://github.com/microsoft/playwright/issues/29930#issuecomment-1996018017
`exec` means using the version defined in package.json, which is a recommended practice

fix: fix ci playwright

---

packages/facade/src/apis/facade.ts

feat(facade): refactor f-univer newAPI and add getDependencies

---

packages/engine-render/src/components/sheets/sheet-component.ts

fix(engine-render): correct skeleton dispose timing

---

packages/sheets-formula/package.json
packages/sheets-formula/src/commands/operations/__tests__/create-command-test-bed.ts
packages/sheets-formula/src/commands/operations/__tests__/insert-function.operation.spec.ts
packages/sheets-formula/src/controllers/__tests__/create-command-test-bed.ts
packages/sheets-formula/src/controllers/__tests__/formula-auto-fill.controller.spec.ts
packages/sheets-formula/src/controllers/__tests__/formula-clipboard.controller.spec.ts

test(formula): restore formula testing and add missing dependencies

---

packages/sheets-ui/src/controllers/header-unhide.render-controller.ts
packages/sheets-ui/src/controllers/menu/menu.ts

close [#2169](https://github.com/dream-num/univer/issues/2169#event-12744264054)

fix(sheet): unhide hidden icon render incorrect when headers resize

---

examples/src/data/docs/default-document-data-cn.ts
packages/engine-render/src/components/docs/layout/doc-skeleton.ts
packages/engine-render/src/components/docs/text-selection/text-selection-render-manager.ts

fix(docs): text selection in multiple columns

---

packages/facade/src/apis/sheets/f-range.ts
packages/sheets-ui/src/services/clipboard/clipboard.service.ts

feat(facade): add API to generate HTML content

---

CONTRIBUTING.md
README-ja.md
README-zh.md
README.md
packages/design/README-zh.md
packages/design/README.md
packages/docs-ui/README-zh.md
packages/docs-ui/README.md
packages/facade/README-zh.md
packages/facade/README.md
packages/facade/docs/CONTRIBUTING.md
packages/rpc/README-zh.md
packages/rpc/README.md
packages/sheets-formula/README-zh.md
packages/sheets-formula/README.md
packages/sheets-numfmt/README-zh.md
packages/uniscript/README-zh.md
packages/uniscript/README.md

fix: fix docs links

---

.vscode/settings.json
examples/src/data/sheets/demo/default-workbook-data-demo.ts
packages/network/src/index.ts
packages/network/src/services/http/headers.ts
packages/network/src/services/http/implementations/fetch.ts
packages/network/src/services/http/implementations/xhr.ts
packages/network/src/services/http/request.ts
packages/network/src/services/http/response.ts

feat(network): add fetch implementation

---

packages/ui/src/components/hooks/observable.ts

fix(ui): fix use observable not working in StrictMode

---

packages/engine-render/src/components/docs/text-selection/text-range.ts

close https://github.com/dream-num/univer-pro/issues/683

fix: the cursor is displayed incorrectly in the presence of bg color

---

packages/engine-render/src/components/docs/layout/doc-skeleton.ts
packages/engine-render/src/components/docs/layout/hyphenation/hyphen.ts
packages/engine-render/src/components/docs/layout/hyphenation/language-detector.ts

fix: use Singleton Pattern of Hyphen

---

packages/core/src/services/lifecycle/lifecycle.service.ts
packages/core/src/services/plugin/plugin-holder.ts
packages/sheets-ui/src/services/sheet-skeleton-manager.service.ts

fix: lifecycle event handling in plugin holder

---

packages/sheets-ui/src/controllers/editor/start-edit.controller.ts

close https://github.com/dream-num/univer-pro/issues/741

fix: the content is not display when enter edit cell

---

packages/core/src/sheets/workbook.ts
packages/sheets/src/commands/commands/set-workbook-name.command.ts
packages/sheets/src/commands/commands/set-worksheet-name.command.ts
packages/sheets/src/commands/mutations/set-workbook-name.mutation.ts
packages/sheets/src/controllers/basic-worksheet.controller.ts
packages/sheets/src/index.ts

This PR adds a new command to UniverSheet. This command should be intercepted by the formula system.

feat(sheets): add set workbook name command

---

packages/core/src/services/locale/locale.service.ts
packages/sheets-ui/src/locale/en-US.ts
packages/sheets-ui/src/locale/ru-RU.ts
packages/sheets-ui/src/locale/zh-CN.ts
packages/ui/src/services/shortcut/keycode.ts
packages/ui/src/views/components/shortcut-panel/ShortcutPanel.tsx

fix: fix shortcut panel content not correct

---

packages/docs-ui/src/controllers/doc-ui.controller.ts
packages/sheets-formula/src/controllers/formula-ui.controller.ts
packages/sheets-ui/src/controllers/sheet-ui.controller.ts
packages/slides-ui/src/controllers/slide-ui.controller.ts
packages/ui/src/controllers/ui/ui-desktop.controller.tsx
packages/ui/src/index.ts
packages/ui/src/services/confirm/desktop-confirm.service.ts
packages/ui/src/services/dialog/desktop-dialog.service.ts
packages/ui/src/services/notification/desktop-notification.service.ts
packages/ui/src/services/parts/parts.service.ts
packages/ui/src/ui-plugin.ts
packages/ui/src/views/App.tsx
packages/ui/src/views/parts.ts

refactor: move some global components to replaceable services

---

packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx
packages/sheets-ui/src/views/sheet-container/SheetContainer.tsx
packages/ui/src/controllers/ui/ui-desktop.controller.tsx
packages/ui/src/services/parts/parts.service.ts
packages/ui/src/views/App.tsx

fix: resolve warning about nested component updates from render methods

---

packages/ui/src/ui-plugin.ts

fix(sheets-ui): fix doc plugins not loaded before sheet editor

---

packages/engine-render/src/basics/tools.ts
packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/ui/src/services/editor/editor.service.ts

refactor(engine-render): standardize default values for BlankCellDocumentModel

---

packages/uniscript/src/index.ts
packages/uniscript/src/plugin.ts
packages/uniscript/src/services/script-execution.service.ts
packages/uniscript/src/views/components/ScriptEditorPanel.tsx

fix(uniscript): export module for pro

---

packages/ui/src/index.ts
packages/ui/src/views/components/doc-bars/Toolbar.tsx
packages/ui/src/views/components/doc-bars/ToolbarItem.tsx
packages/ui/src/views/components/doc-bars/hook.ts

feat: extract hooks for better customization

---

packages/thread-comment-ui/src/views/thread-comment-tree/index.tsx
packages/thread-comment/src/index.ts

feat(thread-comment): add data-source-service export

---

packages/design/src/components/dropdown/Dropdown.tsx
packages/ui/src/views/components/doc-bars/ToolbarItem.tsx

refactor: add disabled API to dropdown to simplify code

---

packages/design/src/components/input-number/index.module.less
packages/ui/src/index.ts

feat: add more exports from UI package

---

packages/sheets-filter-ui/src/controllers/__tests__/sheets-filter.menu.spec.ts
packages/sheets-filter/src/services/sheet-filter.service.ts
packages/sheets-formula/src/locale/en-US.ts
packages/sheets-formula/src/locale/zh-CN.ts
packages/sheets-formula/src/views/more-functions/select-function/index.module.less

如何测试？
删除第一个sheet，会切换到第二个sheet。原来不会。

fix(sheet): active next sheet when remove sheet

---

CONTRIBUTING.md

docs: fixed outdated start dev server command

---

packages/docs-ui/src/docs-ui-plugin.ts
packages/docs-ui/src/index.ts
packages/docs-ui/src/services/doc-popup-manager.service.ts

feat(docs-ui): add doc-popup.service

---

packages/sheets-zen-editor/src/controllers/zen-editor.controller.ts

close https://github.com/dream-num/univer-pro/issues/670

fix: background position error in zen editor

---

packages/engine-render/src/components/sheets/spreadsheet.ts

fix(sheet): border color

---

packages/engine-render/src/components/docs/document.ts
packages/sheets-ui/src/services/editor-bridge.service.ts

close https://github.com/dream-num/univer-pro/issues/734

fix: cell number display when set text wrap

---

packages/sheets-ui/src/controllers/clipboard/utils.ts

fix: paste special (format  only) will not paste richformat

---

packages/ui/src/views/components/doc-bars/hook.ts

feat(toolbar): add automatic calculation of toolbar gap style

---

packages/sheets-ui/src/controllers/auto-fill.controller.ts

chore: remove unless mutations

---

packages/engine-formula/src/engine/utils/object-compare.ts
packages/engine-formula/src/engine/value-object/array-value-object.ts
packages/engine-formula/src/engine/value-object/base-value-object.ts
packages/engine-formula/src/engine/value-object/primitive-object.ts
packages/engine-formula/src/functions/lookup/vlookup/__tests__/index.spec.ts
packages/engine-formula/src/functions/lookup/vlookup/index.ts

fix(formula): case sensitive

---

packages/design/src/components/select/Select.stories.tsx
packages/design/src/components/select/index.module.less

close https://github.com/dream-num/univer-pro/issues/966

fix(design): resolve text overflow issue in Select component for long content

---

packages/network/src/services/http/http.service.ts
packages/network/src/services/http/implementations/xhr.ts

feat(network): add http sse method

---

packages/network/src/services/http/http.service.ts
packages/network/src/services/http/implementations/implementation.ts

fix(network): fix http type

---

packages/core/src/docs/data-model/document-data-model.ts
packages/core/src/docs/data-model/text-x/__tests__/apply-utils.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/common.spec.ts
packages/core/src/docs/data-model/text-x/apply-utils/common.ts
packages/core/src/docs/data-model/text-x/apply-utils/update-apply.ts
packages/core/src/docs/data-model/text-x/apply.ts
packages/docs-ui/src/controllers/menu/menu.ts
packages/docs/src/commands/commands/inline-format.command.ts
packages/docs/src/commands/mutations/core-editing.mutation.ts

close https://github.com/dream-num/univer/issues/2192 
close https://github.com/dream-num/univer/issues/2191

fix: inline format support cursor

---

packages/design/src/components/message/Message.tsx
packages/ui/src/services/message/desktop-message.service.ts

feat(ui): not auto removing when duration is 0

---

packages/engine-render/src/components/docs/text-selection/convert-cursor.ts
packages/engine-render/src/components/docs/text-selection/text-range.ts

close https://github.com/dream-num/univer-pro/issues/1010

fix: cursor size follow anchor glyph

---

packages/engine-render/src/components/docs/extensions/background.ts
packages/engine-render/src/components/docs/extensions/line.ts
packages/engine-render/src/components/docs/layout/block/paragraph/bullet.ts
packages/engine-render/src/components/sheets/extensions/background.ts

close #xxx
fix issues: 1、2、5 of https://github.com/dream-num/univer-pro/issues/687

fix: no need to set background to linebreak

---

packages/sheets-hyper-link-ui/src/common/util.ts
packages/sheets-hyper-link-ui/src/controllers/copy-paste.controller.ts
packages/sheets-hyper-link-ui/src/controllers/set-range.controller.ts

fix(sheets-hyper-link-ui): email link jump error

---

packages/engine-formula/src/engine/value-object/__tests__/array-value-object.spec.ts
packages/engine-formula/src/engine/value-object/array-value-object.ts
packages/engine-formula/src/index.ts
packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
packages/ui/src/components/progress-bar/ProgressBar.tsx
packages/ui/src/services/progress/progress.service.ts

1. 有条件格式带公式的场景下，进度条有点问题，可以自建场景复测
比如 https://dev.univer.plus/sheet/?unit=jcmg_PRSTsq93LzAmT9Uwg&type=2&subunit=uni1
2. close #2331 不用QA测试

fix(formula): progress for multiple calculation

---

packages/core/src/sheets/worksheet.ts
packages/engine-render/src/components/docs/view-model/document-view-model.ts

fix: check cell data and remove linebreak in v filed

---

packages/docs-ui/src/controllers/doc-floating-object.controller.ts
packages/docs-ui/src/controllers/drawing.controller.ts
packages/docs-ui/src/shortcuts/utils.ts
packages/sheets-filter-ui/src/controllers/__tests__/sheets-filter.menu.spec.ts
packages/sheets-ui/src/controllers/menu/__tests__/create-menu-test-bed.ts
packages/sheets-ui/src/controllers/menu/menu-util.ts
packages/sheets-ui/src/controllers/menu/permission-menu-util.ts

fix: fix import error

---

packages/engine-render/src/scene.input-manager.ts

fix(render): dispose cycle

---

packages/drawing-ui/src/views/panel/DrawingArrange.tsx
packages/drawing-ui/src/views/panel/DrawingGroup.tsx
packages/drawing-ui/src/views/panel/ImageCropper.tsx
packages/drawing-ui/src/views/panel/index.module.less

close https://github.com/dream-num/univer-pro/issues/1033

fix(drawing-ui): fix incomplete display of drawing panel styles

---

packages/docs-ui/src/controllers/back-scroll.controller.ts
packages/docs-ui/src/controllers/doc-editor-bridge.controller.ts
packages/docs-ui/src/controllers/zoom.controller.ts
packages/engine-render/src/basics/scroll-xy.ts
packages/engine-render/src/components/sheets/interfaces.ts
packages/engine-render/src/components/sheets/spreadsheet.ts
packages/engine-render/src/scene.ts
packages/engine-render/src/scroll-timer.ts
packages/engine-render/src/viewport.ts
packages/sheets-ui/src/commands/commands/__tests__/create-command-test-bed.ts
packages/sheets-ui/src/commands/commands/__tests__/create-selection-command-test-bed.ts
packages/sheets-ui/src/commands/commands/__tests__/set-frozen.command.spec.ts
packages/sheets-ui/src/commands/commands/set-frozen.command.ts
packages/sheets-ui/src/commands/commands/set-scroll.command.ts
packages/sheets-ui/src/commands/operations/scroll.operation.ts
packages/sheets-ui/src/common/utils.ts
packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts
packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
packages/sheets-ui/src/controllers/render-controllers/freeze.render-controller.ts
packages/sheets-ui/src/controllers/render-controllers/scroll.render-controller.ts
packages/sheets-ui/src/controllers/render-controllers/zoom.render-controller.ts
packages/sheets-ui/src/services/drag-manager.service.ts
packages/sheets-ui/src/services/hover-manager.service.ts
packages/sheets-ui/src/services/scroll-manager.service.ts
packages/sheets-ui/src/services/sheet-skeleton-manager.service.ts
packages/sheets-zen-editor/src/controllers/zen-editor.controller.ts
packages/slides/src/views/render/adaptors/docs-adaptor.ts
packages/slides/src/views/render/adaptors/spreadsheet-adaptor.ts
packages/slides/src/views/render/canvas-view.ts

revert: add scrollLeftTop for sheet snapshot

---

packages/core/src/shared/tools.ts

close [PR 1041](https://github.com/dream-num/univer-pro/pull/1041)

feat: add Tools.set method

---

packages/core/src/index.ts
packages/core/src/services/permission/type.ts
packages/sheets-ui/src/controllers/menu/menu-util.ts
packages/sheets-ui/src/controllers/menu/sheet.menu.ts
packages/sheets/src/services/permission/workbook-permission/util.ts

feat: add workbook permission

---

packages/drawing-ui/src/plugin.ts

fix(drawing): plugin name

---

packages/core/src/services/authz-io/authz-io-local.service.ts

chore: fix list lint

---

packages/core/src/types/interfaces/i-document-data.ts
packages/docs/src/commands/commands/core-editing.command.ts
packages/docs/src/commands/commands/inline-format.command.ts
packages/docs/src/index.ts
packages/engine-render/src/components/docs/layout/tools.ts
packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts
packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx

close https://github.com/dream-num/univer-pro/issues/1021

fix: sync actions between formula editor and cell editor

---

packages/ui/src/services/message/desktop-message.service.ts

fix(meesage): fix in node env, the document not exist

---

packages/network/src/index.ts
packages/network/src/services/http/interceptor.ts
packages/network/src/services/http/interceptors/__tests__/auth-interceptor.spec.ts
packages/network/src/services/http/interceptors/__tests__/threshold-interceptor.spec.ts
packages/network/src/services/http/interceptors/auth-interceptor.ts
packages/network/src/services/http/interceptors/retry-interceptor.ts
packages/network/src/services/http/interceptors/threshold-interceptor.ts

feat(network): add http auth interceptor

---

packages/sheets-ui/src/commands/commands/range-protection.command.ts
packages/sheets-ui/src/commands/commands/worksheet-protection.command.ts
packages/sheets/src/commands/mutations/add-worksheet-protection.mutation.ts
packages/sheets/src/index.ts

chore: change add protection params

---

packages/engine-render/src/context.ts

fix(sheets-data-validation): build error

---

examples/src/data/sheets/demo/default-workbook-data-demo.ts
examples/src/sheets/main.ts
packages/sheets-hyper-link-ui/src/controllers/remove-sheet.controller.ts

fix(hyper-link): bugfix for hyper-link remove-sheet

---

packages/docs-ui/src/controllers/text-selection.controller.ts
packages/docs/src/controllers/move-cursor.controller.ts

feat: set the initial cursor at the begining of document

---

packages/umd/scripts/index.mjs

fix(umd): change dependency build order for UMD packages
