packages/core/package.json
packages/data-validation/package.json
packages/sheets-conditional-formatting-ui/package.json
packages/sheets-conditional-formatting/package.json
packages/sheets-data-validation/package.json
packages/sheets-find-replace/package.json
packages/sheets-hyper-link/package.json
packages/sheets-thread-comment-base/package.json
packages/sheets-thread-comment/package.json
packages/sheets-ui/package.json
packages/sheets/package.json
packages/thread-comment-ui/package.json
packages/thread-comment/package.json
packages/umd/package.json
packages/uniscript/package.json
pnpm-lock.yaml

chore: update protocol

---

packages/sheets-ui/src/index.ts

fix(sheet): null cell

---

packages/core/package.json
packages/data-validation/package.json
packages/sheets-conditional-formatting-ui/package.json
packages/sheets-conditional-formatting/package.json
packages/sheets-data-validation/package.json
packages/sheets-find-replace/package.json
packages/sheets-hyper-link/package.json
packages/sheets-ui/package.json
packages/sheets/package.json
packages/thread-comment-ui/package.json
packages/thread-comment/package.json
packages/umd/package.json
packages/uniscript/package.json
pnpm-lock.yaml

chore(sheet): update protocol

---

packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-base.controller.ts
packages/sheets/src/services/permission/workbook-permission/util.ts

feat: change move sheet permission

---

packages/sheets-find-replace/src/controllers/sheet-find-replace.controller.ts

fix(find): when dispose, should close panel

---

packages/design/src/components/date-picker/index.module.less
packages/design/src/components/date-range-picker/index.module.less

fix(design): fix syntax error in calculation within less file

---

packages/core/src/services/permission/permission.service.ts
packages/core/src/sheets/workbook.ts
packages/sheets-ui/src/views/sheet-bar/SheetBar.tsx

fix: change ref when user change

---

packages/sheets-ui/src/controllers/menu/sheet.menu.ts
packages/sheets/src/services/permission/permission-point/index.ts
packages/sheets/src/services/permission/workbook-permission/util.ts

chore: add request actions

---

packages/sheets-filter-ui/src/views/components/index.module.less
packages/ui/src/components/range-selector/RangeSelector.tsx
packages/ui/src/components/range-selector/index.module.less

close [#242](https://github.com/dream-num/univer-workspace/issues/242#event-13180336764)

fix: button style

---

packages/sheets-ui/src/controllers/render-controllers/header-unhide.render-controller.ts

close https://github.com/dream-num/univer-pro/issues/1143

fix(sheets-ui): fix unhide render controller RENDER_COMMANDS

---

packages/design/src/components/popup/RectPopup.tsx

close https://github.com/dream-num/univer-pro/issues/1144

fix(design): fix popup position

---

packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts

fix(sheets-drawing-ui): error delete cache when float-dom hide

---

packages/sheets-filter-ui/src/models/__tests__/conditions.spec.ts
packages/sheets-filter-ui/src/models/conditions.ts
packages/sheets-filter/src/controllers/sheets-filter.controller.ts
packages/sheets-ui/src/controllers/auto-fill.controller.ts
packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
packages/sheets-ui/src/services/selection/selection-shape-extension.ts

close https://github.com/dream-num/univer-pro/issues/1139 https://github.com/dream-num/univer-pro/issues/1106 https://github.com/dream-num/univer-pro/issues/1073 https://github.com/dream-num/univer-pro/issues/1066 https://github.com/dream-num/univer-pro/issues/1043

fix(sheets): fix some bugs

---

.github/workflows/release.yml

chore(ci): fix sync:cnpm

---

packages/design/src/components/tooltip/Tooltip.tsx

fix: tooltip is-ellipsis not working

---

packages/ui/src/components/editor/TextEditor.tsx

fix(editor): state error

---

packages/design/src/components/tooltip/Tooltip.tsx
packages/design/src/components/tooltip/index.module.less

close https://github.com/dream-num/univer-pro/issues/1137

fix(design): adjust tooltip arrow width to 4px

---

packages/docs-ui/src/services/clipboard/clipboard.service.ts
packages/docs/src/commands/commands/core-editing.command.ts
packages/docs/src/commands/mutations/core-editing.mutation.ts
packages/docs/src/services/doc-state-change-manager.service.ts

refactor: add capacity of compose change state

---

packages/sheets-ui/src/controllers/menu/sheet.menu.ts
packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-base.controller.ts

fix(permission): can not edit when have not permission in cn language

---

packages/sheets-sort-ui/src/controllers/sheets-sort-ui.controller.ts
packages/sheets-sort/src/controllers/sheets-sort.controller.ts

fix(sheet): ui dependency

---

packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx

fix(permission): change rename condition should have rename permission

---

packages/sheets-sort-ui/src/services/sheets-sort-ui.service.tsx
packages/sheets-sort/package.json
packages/sheets-sort/src/commands/__tests__/create-command-test-bed.ts
packages/sheets-sort/src/services/sheets-sort.service.ts
packages/sheets-ui/src/index.ts
packages/sheets-ui/src/services/clipboard/type.ts
packages/sheets/src/basics/selection.ts
packages/sheets/src/index.ts
pnpm-lock.yaml

fix(sheet): ui dependency in sort

---

packages/sheets-drawing-ui/src/views/sheet-image-panel/SheetDrawingPanel.tsx

close https://github.com/dream-num/univer-pro/issues/1234

fix(sheets-drawing): fix crash when editing text after inserting images and opening the sidebar

---

packages/sheets-drawing/src/index.ts

For issue [https://github.com/dream-num/univer-pro/pull/1280](https://github.com/dream-num/univer-pro/pull/1280)

chore: export drawing type

---

examples/src/data/sheets/demo/default-workbook-data-demo.ts
examples/src/sheets/main.ts
packages/sheets-ui/src/controllers/menu/sheet.menu.ts
packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx
packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/utils/slide-tab-bar.ts
packages/sheets/src/commands/commands/__tests__/copy-worksheet.command.spec.ts
packages/sheets/src/commands/commands/copy-worksheet.command.ts
packages/sheets/src/locale/en-US.ts
packages/sheets/src/locale/ru-RU.ts
packages/sheets/src/locale/zh-CN.ts

close [#938](https://github.com/dream-num/univer-pro/issues/938)
close [#1147](https://github.com/dream-num/univer-pro/issues/1147)
close [#1063](https://github.com/dream-num/univer-pro/issues/1063) 
close [#967](https://github.com/dream-num/univer-pro/issues/967)

fix(sheet): duplicate sheet name copy

---

packages/sheets-conditional-formatting-ui/src/menu/manage-rule.ts

close [1029](https://github.com/dream-num/univer-pro/issues/1029)

fix(conditional-formatting): disable clear cf

---

packages/sheets-conditional-formatting-ui/src/controllers/cf.menu.controller.ts

close [465](https://github.com/dream-num/univer-pro/issues/465)

fix(conditional-formatting): reopen panel and update panel

---

packages/facade/src/apis/__tests__/create-test-bed.ts
packages/sheets-conditional-formatting-ui/src/commands/commands/move-cf.command.ts
packages/sheets-conditional-formatting-ui/src/components/panel/rule-list/index.tsx
packages/sheets-conditional-formatting-ui/src/controllers/cf.menu.controller.ts
packages/sheets-conditional-formatting-ui/src/mobile-plugin.ts
packages/sheets-conditional-formatting-ui/src/plugin.ts
packages/sheets-conditional-formatting/src/plugin.ts
packages/sheets-conditional-formatting/src/services/__test__/test.util.ts
packages/ui/src/mobile-ui-plugin.ts

refactor(cf): change plugin structure

---

packages/core/src/sheets/workbook.ts

fix(sheet): get unhidden sheets

---

packages/sheets-numfmt/src/components/currency/index.tsx
packages/sheets-numfmt/src/components/date/index.tsx
packages/sheets-numfmt/src/components/thousandth-percentile/index.tsx

close [1981](https://github.com/dream-num/univer/issues/1981)

fix(numfmt): reselect item and throw error

---

packages/sheets-ui/src/controllers/menu/permission.menu.ts

chore: reset permission menu

---

packages/ui/src/controllers/ui/ui.controller.ts
packages/ui/src/views/DesktopApp.tsx

feat: make toolbar configurable

---

packages/engine-render/src/components/docs/extensions/line.ts

fix(sheet): line default error

---

common/shared/vite/auto-externalize-dependency-plugin.js
packages/core/src/services/locale/locale.service.ts
packages/data-validation/src/index.ts

build: fix lodash's globalName

---

packages/engine-formula/src/engine/analysis/__tests__/parser.spec.ts
packages/engine-formula/src/engine/ast-node/function-node.ts
packages/engine-render/src/components/sheets/column-header.ts
packages/engine-render/src/components/sheets/row-header.ts
packages/engine-render/src/components/sheets/spreadsheet.ts

close [#690](https://github.com/dream-num/univer-pro/issues/690)
close #2029

fix(formula): row range calculation error

---

packages/engine-formula/src/commands/mutations/set-formula-calculation.mutation.ts
packages/engine-formula/src/index.ts
packages/engine-formula/src/services/calculate-formula.service.ts
packages/engine-formula/src/services/runtime.service.ts
packages/engine-render/src/components/sheets/column-header.ts
packages/engine-render/src/components/sheets/row-header.ts
packages/engine-render/src/components/sheets/spreadsheet.ts
packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
packages/sheets/src/services/ref-range/ref-range.service.ts

feat(sheet): restart formula calculation

---

packages/sheets-drawing-ui/src/views/menu/image.menu.ts

chore: image menu show on insert position

---

packages/ui/src/components/editor/TextEditor.tsx
packages/ui/src/controllers/ui/ui-desktop.controller.tsx

fix(sheets-ui): fix formula editor's position issue in lower version of React

---

packages/core/src/sheets/range.ts
packages/facade/src/apis/facade.ts
packages/facade/src/apis/sheets/__tests__/f-range.spec.ts
packages/sheets/src/commands/commands/__tests__/set-style.command.spec.ts

fix(facade): fix implementation of `getWrap` and remove redundant `getWraps` method

---

packages/docs-thread-comment-ui/package.json
pnpm-lock.yaml

chore: fix lockfile

---

packages/core/src/docs/data-model/__tests__/replacement.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/action-iterator.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/compose.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/invert.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/utils.spec.ts
packages/docs/src/commands/commands/core-editing.command.ts

fix(core): unit test case

---

packages/drawing-ui/src/controllers/image-update.controller.ts
packages/sheets-drawing-ui/src/controllers/sheet-drawing-transform-affected.controller.ts

fix(sheet): drawing switch tab position error

---

packages/engine-formula/src/engine/value-object/primitive-object.ts
packages/engine-formula/src/functions/math/abs/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/acos/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/acos/index.ts
packages/engine-formula/src/functions/math/acosh/index.ts
packages/engine-formula/src/functions/math/acot/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/asin/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/asin/index.ts
packages/engine-formula/src/functions/math/asinh/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/asinh/index.ts
packages/engine-formula/src/functions/math/atan/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/atan/index.ts
packages/engine-formula/src/functions/math/atan2/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/atan2/index.ts
packages/engine-formula/src/functions/math/atanh/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/atanh/index.ts
packages/engine-formula/src/functions/math/cos/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/cos/index.ts
packages/engine-formula/src/functions/math/function-map.ts
packages/engine-formula/src/functions/math/tan/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/tan/index.ts
packages/engine-formula/src/functions/math/tanh/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/tanh/index.ts
packages/sheets-formula/src/controllers/formula-render.controller.ts
packages/sheets-formula/src/locale/function-list/math/en-US.ts
packages/sheets-formula/src/locale/function-list/math/ja-JP.ts
packages/sheets-formula/src/locale/function-list/math/zh-CN.ts
packages/sheets-formula/src/services/function-list/math.ts
packages/sheets/src/controllers/number-cell.controller.ts
packages/sheets/src/sheets-plugin.ts

feat(formula): add asin function

---

examples/public/sheets/index.html
examples/public/slides/index.html
examples/src/slides/main.ts
packages/engine-render/src/render-manager/render-unit.ts
packages/slides-ui/src/slides-ui-plugin.ts
packages/slides/src/slides-plugin.ts
packages/slides/src/views/render/canvas-view.ts
packages/ui/src/controllers/ui/ui-desktop.controller.tsx

fix(slide): remove duplicated calls to render.engine.setContainer

---

packages/design/src/components/scrollbar/Scrollbar.tsx
packages/slides-ui/src/views/slide-bar/SlideBar.tsx
packages/slides-ui/src/views/slide-bar/index.module.less
packages/slides/src/views/render/canvas-view.ts

feat(slides): add sidebar highlighting for selected items in slides

---

packages/design/src/components/popup/RectPopup.tsx
packages/engine-render/package.json
packages/engine-render/src/engine.ts
packages/engine-render/src/floating/util.ts
packages/sheets-ui/src/services/canvas-pop-manager.service.ts
packages/ui/src/controllers/ui/ui-desktop.controller.tsx
packages/ui/src/services/parts/parts.service.ts
packages/ui/src/views/DesktopApp.tsx
pnpm-lock.yaml

feat(ui): change floating position

---

packages/sheets-filter-ui/src/views/components/index.module.less

style(sheets-filter-ui): fix the width styling of the filter panel

---

packages/docs/src/commands/commands/break-line.command.ts

fix: backspace in header and footer

---

packages/sheets-drawing-ui/src/views/menu/image.menu.ts

revert: "chore: image menu show on insert position"

---

packages/umd/scripts/index.mjs

fix(umd): fix issue with datepicker localization not working in UMD bundle

---

packages/core/src/docs/data-model/types.ts

fix(docs): fix blank screen

---

packages/ui/src/services/sidebar/desktop-sidebar.service.ts
packages/ui/src/services/sidebar/sidebar.service.ts
packages/ui/src/views/components/sidebar/Sidebar.tsx
packages/ui/src/views/components/sidebar/interface.ts

feat: sidebar-service supports scroll-event subscription

---

packages/engine-formula/src/functions/__tests__/nested-functions.spec.ts
packages/engine-formula/src/functions/text/len/index.ts
packages/engine-formula/src/services/dependency-manager.service.ts
packages/sheets-drawing-ui/src/controllers/sheet-drawing-transform-affected.controller.ts
packages/sheets-formula/src/controllers/formula-editor-show.controller.ts

close [#1047](https://github.com/dream-num/univer-pro/issues/1047)
close [#862](https://github.com/dream-num/univer-pro/issues/862)(其它PR修复)
close [#1491](https://github.com/dream-num/univer-pro/issues/1491)

fix(formula): len counts displayed value

---

packages/docs-hyper-link/src/controllers/resource.controller.ts
packages/docs-ui/src/docs-ui-plugin.ts
packages/docs-ui/src/services/doc-popup-manager.service.ts

fix(docs-hyper-link): hyper link resource

---

packages/sheets-ui/src/controllers/render-controllers/scroll.render-controller.ts

fix: failed to get scene in scroll render controller

---

packages/ui/src/views/components/context-menu/ContextMenu.tsx

fix(ui): fix issue where context menu item cannot be selected in React 16

---

packages/sheets-drawing-ui/src/locale/en-US.ts
packages/sheets-drawing-ui/src/locale/ru-RU.ts
packages/sheets-drawing-ui/src/locale/vi-VN.ts
packages/sheets-drawing-ui/src/locale/zh-CN.ts
packages/sheets-drawing-ui/src/locale/zh-TW.ts

chore: drawing shortcut key i18n

---

packages/sheets-hyper-link-ui/src/services/popup.service.ts
packages/sheets-hyper-link-ui/src/views/CellLinkPopup/index.tsx

fix(sheets-hyper-link-ui): popup observable error on react16

---

examples/src/data/docs/default-document-data-cn.ts
examples/src/data/docs/default-document-data-dreamer.ts
examples/src/data/docs/default-document-data-en.ts
examples/src/data/docs/default-document.data-simple.ts
examples/src/data/sheets/demo/default-workbook-data-demo.ts
examples/src/data/sheets/demo/default-workbook-data-demo3.ts
examples/src/data/slides/rich-text/page3-richtext1.ts
examples/src/data/slides/rich-text/page3-richtext2.ts
examples/src/data/slides/rich-text/page3-richtext3.ts
examples/src/data/slides/rich-text/page5-richtext1.ts
packages/core/src/docs/data-model/__tests__/replacement.spec.ts
packages/core/src/docs/data-model/empty-snapshot.ts
packages/core/src/docs/data-model/preset-list-type.ts
packages/core/src/docs/data-model/text-x/__tests__/utils.spec.ts
packages/core/src/shared/doc-tool.ts
packages/core/src/types/interfaces/i-document-data.ts
packages/docs-ui/src/commands/commands/doc-header-footer.command.ts
packages/docs-ui/src/services/clipboard/html-to-udm/utils.ts
packages/docs-ui/src/services/clipboard/udm-to-html/__test__/convertor.spec.ts
packages/docs/src/commands/commands/__tests__/clipboard.command.spec.ts
packages/docs/src/commands/commands/__tests__/create-command-test-bed.ts
packages/docs/src/commands/commands/list.command.ts
packages/engine-render/src/components/docs/layout/block/paragraph/bullet.ts
packages/engine-render/src/components/docs/layout/block/paragraph/layout-ruler.ts
packages/engine-render/src/components/docs/layout/shaping-engine/__tests__/text-shaping.spec.ts
packages/engine-render/src/components/docs/layout/tools.ts
packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
packages/sheets-ui/src/services/clipboard/html-to-usm/utils.ts
packages/sheets/src/commands/commands/__tests__/set-range-values.command.spec.ts

refactor(doc): number unit

---

packages/docs-ui/src/controllers/render-controllers/text-selection.render-controller.ts
packages/sheets-formula/src/controllers/__tests__/create-command-test-bed.ts
packages/sheets-formula/src/controllers/prompt.controller.ts
packages/sheets-ui/src/commands/commands/__tests__/create-command-test-bed.ts
packages/sheets-ui/src/services/editor-bridge.service.ts
packages/sheets-ui/src/services/selection/base-selection-render.service.ts
packages/ui/src/components/editor/TextEditor.tsx
packages/ui/src/services/editor/editor.service.ts
packages/ui/src/utils/util.ts

close [#1599](https://github.com/dream-num/univer-pro/issues/1599)
close [#1556](https://github.com/dream-num/univer-pro/issues/1556)
close [#1541](https://github.com/dream-num/univer-pro/issues/1541)
close [#912](https://github.com/dream-num/univer-pro/issues/912)

fix(sheet): range selector and editor

---

packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts

fix(formula): great than equal error

---

packages/ui/src/services/message/__testing__/mock-message.service.ts
packages/ui/src/services/message/desktop-message.service.ts
packages/ui/src/services/message/message.service.ts

feat: add method to get message portal container

---

packages/engine-formula/src/engine/reference-object/base-reference-object.ts
packages/engine-formula/src/engine/utils/numfmt-kit.ts
packages/engine-formula/src/engine/value-object/primitive-object.ts
packages/sheets-formula/src/controllers/formula-editor-show.controller.ts
packages/sheets-formula/src/views/prompt/help-function/HelpFunction.tsx
packages/sheets-formula/src/views/prompt/resize-scroll-observer.ts
packages/ui/src/components/editor/TextEditor.tsx
packages/ui/src/components/editor/index.module.less

1. close [#1069](https://github.com/dream-num/univer-pro/issues/1069)
2. close [#1208](https://github.com/dream-num/univer-pro/issues/1208)(其他PR修复)
3. close [#1333](https://github.com/dream-num/univer-pro/issues/1333)
4. close [#1362](https://github.com/dream-num/univer-pro/issues/1362)(其他PR修复)
5. 公式计算出来的数字格式，如果当前单元格已经有数字格式，则使用原有格式，如果没有，则设置新的格式。匹配Google Sheets。
为什么？
由于初始化时强制计算机制，如果公式可能会覆盖原有的数字格式，那么公式单元格设置的数字格式可能永远都不会生效。

fix(formula): formula carries numfmt of ref cell

---

packages/core/src/shared/common.ts
packages/ui/src/utils/cell.ts

close #2627
&
pasting default style cell from Tencent Doc issue

fix(sheet): copy&paste clip cell

---

packages/core/src/types/interfaces/i-document-data.ts
packages/docs/src/commands/commands/list.command.ts
packages/engine-render/src/components/docs/layout/doc-skeleton.ts
packages/engine-render/src/components/docs/layout/tools.ts
packages/ui/src/services/editor/editor.service.ts

refactor(doc): move section break

---

packages/docs/src/controllers/move-cursor.controller.ts
packages/engine-render/src/components/docs/text-selection/text-range.ts

fix: min cursor height and move cursor

---

packages/core/package.json
packages/data-validation/package.json
packages/sheets-conditional-formatting-ui/package.json
packages/sheets-conditional-formatting/package.json
packages/sheets-data-validation/package.json
packages/sheets-find-replace/package.json
packages/sheets-hyper-link/package.json
packages/sheets-ui/package.json
packages/sheets/package.json
packages/sheets/src/index.ts
packages/sheets/src/services/permission/permission-point/index.ts
packages/sheets/src/services/permission/permission-point/workbook/recover-history.ts
packages/sheets/src/services/permission/permission-point/workbook/view-history.ts
packages/sheets/src/services/permission/workbook-permission/util.ts
packages/thread-comment-ui/package.json
packages/thread-comment/package.json
packages/umd/package.json
packages/uniscript/package.json
pnpm-lock.yaml

feat: init history permission point in sheet

---

packages/design/src/components/select-list/SelectList.tsx

- add some optional property  for custom css

fix(design): add class name as poperty of select list

---

packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts

fix(sheets-drawing-ui): float-dom deps error

---

packages/ui/src/utils/cell.ts

fix: fix invalid color str in paste

---

packages/sheets/src/commands/commands/insert-row-col.command.ts

close [1767](https://github.com/dream-num/univer/issues/1767)

fix(selection): selection error after insert col

---

packages/core/src/services/authz-io/authz-io-local.service.ts

fix(permission): when user exists should not set again

---

packages/docs-mention/src/controllers/doc-mention-resource.controller.ts
packages/docs-mention/src/models/doc-mention.model.ts
packages/docs-mention/src/plugin.ts

feat(docs-mention): add resource-controller

---

packages/sheets-conditional-formatting/src/services/__test__/cf.service.spec.ts
packages/sheets-conditional-formatting/src/services/conditional-formatting.service.ts

fix(conditional-formatting): adjust the frequency of calculations

---

packages/engine-render/src/components/docs/layout/tools.ts

fix(doc): default line pitch

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/sheets-data-validation/src/controllers/dv-render.controller.ts
packages/sheets-data-validation/src/views/formula-input/list-formula-input.tsx
packages/sheets-data-validation/src/views/list-dropdown/index.tsx

fix(sheets-data-validation): data-validation perf issues

---

packages/sheets-hyper-link-ui/src/controllers/render-controllers/render.controller.ts
packages/sheets-thread-comment/src/controllers/render-controllers/render.controller.ts

fix(sheets-hyper-link): re-render perf issue

---

packages/engine-numfmt/src/index.ts
packages/engine-numfmt/src/types/index.d.ts
packages/sheets-data-validation/src/validators/list-validator.ts
packages/sheets-numfmt/src/__tests__/date.test.ts
packages/sheets-numfmt/src/components/date/index.tsx
packages/sheets-numfmt/src/controllers/numfmt.editor.controller.ts
packages/sheets-numfmt/src/utils/decimal.ts
packages/sheets-numfmt/src/utils/pattern.ts
packages/sheets-ui/src/controllers/clipboard/utils.ts
packages/sheets-ui/src/services/auto-fill/rules.ts
packages/sheets-ui/src/views/status-bar/CopyableStatisticItem.tsx

chore(umd): fix numfmt in umd build

---

packages/sheets-ui/src/controllers/editor/editing.render-controller.ts

fix(ui): fix focus editor position with padding

---

packages/sheets-formula/src/controllers/prompt.controller.ts

fix  [ #1583 ](https://github.com/dream-num/univer-pro/issues/1583)

fix: ref selection

---

packages/sheets-formula/src/controllers/prompt.controller.ts

chore: fix

---

packages/sheets-ui/src/commands/commands/set-frozen.command.ts

close https://github.com/dream-num/univer-pro/issues/1712

fix: get SheetScrollManagerService from renderManagerSrv

---

packages/sheets-formula/src/controllers/prompt.controller.ts
packages/sheets-ui/src/services/selection/selection-shape-extension.ts

fix: move selection

---

packages/sheets-zen-editor/src/index.ts

chore(zen-doc): add export

---

packages/sheets-formula/src/controllers/prompt.controller.ts
packages/sheets-formula/src/views/prompt/help-function/index.module.less
packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
packages/sheets-ui/src/controllers/editor/__tests__/mock-function.service.ts
packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
packages/sheets-ui/src/controllers/utils/char-tools.ts
packages/sheets-ui/src/services/auto-fill/__tests__/tool.spec.ts
packages/sheets-ui/src/services/auto-fill/tools.ts
packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/utils/slide-tab-bar.ts

close [#1481](https://github.com/dream-num/univer-pro/issues/1481)
close [#1508](https://github.com/dream-num/univer-pro/issues/1508)(用SUMIFS检验效果)
close [#1517](https://github.com/dream-num/univer-pro/issues/1517)(未复现)
close [#1537](https://github.com/dream-num/univer-pro/issues/1537)
close [#1653](https://github.com/dream-num/univer-pro/issues/1653)
单元格编辑支持常见的自动转换，比如
1. 公式关键词转大写：输入 =true ，自动变成 =TRUE，输入 =a1，变成 =A1
2. CJK语言下全角字符会按照一定规则，部分转换为半角字符

fix(sheet): blur table name triggers slide

---

packages/engine-formula/src/commands/mutations/set-formula-calculation.mutation.ts
packages/engine-formula/src/engine/dependency/dependency-tree.ts
packages/engine-formula/src/index.ts
packages/engine-formula/src/services/calculate-formula.service.ts
packages/engine-formula/src/services/current-data.service.ts
packages/engine-formula/src/services/feature-calculation-manager.service.ts
packages/sheets-formula/src/controllers/trigger-calculation.controller.ts

feat(formula): get dirty data

---

packages/engine-formula/src/services/runtime.service.ts

fix(formula): array formula clear old value

---

packages/engine-formula/src/commands/mutations/set-feature-calculation.mutation.ts
packages/engine-formula/src/controller/set-dependency.controller.ts
packages/engine-formula/src/controller/set-feature-calculation.controller.ts
packages/engine-formula/src/engine/dependency/dependency-tree.ts
packages/engine-formula/src/engine/dependency/formula-dependency.ts
packages/engine-formula/src/plugin.ts
packages/engine-formula/src/services/calculate-formula.service.ts
packages/engine-formula/src/services/dependency-manager.service.ts
packages/engine-formula/src/services/feature-calculation-manager.service.ts

fix(formula): feature calculation update

---

packages/engine-formula/src/index.ts
packages/engine-formula/src/services/feature-calculation-manager.service.ts

-  add type import
- the has function should use undefined instead of null

fix(sheet): type import

---

packages/engine-render/src/canvas.ts

chore(render): update

---

packages/docs-ui/src/controllers/render-controllers/doc-resize.render-controller.ts

fix: doc-resize causing formula error

---

packages/sheets-ui/src/controllers/editor/editing.render-controller.ts

fix(sheets-ui): formula editor can't exit

---

packages/core/src/docs/data-model/preset-list-type.ts
packages/core/src/types/enum/text-style.ts
packages/core/src/types/interfaces/i-document-data.ts
packages/docs/src/commands/commands/list.command.ts
packages/engine-render/src/basics/i-document-skeleton-cached.ts
packages/engine-render/src/components/docs/layout/block/paragraph/bullet-ruler.ts
packages/engine-render/src/components/docs/layout/block/paragraph/bullet.ts
packages/engine-render/src/components/docs/layout/block/paragraph/layout-ruler.ts

fix(doc): list update

---

packages/docs-ui/src/controllers/render-controllers/doc-hover.render-controller.ts

feat(docs-ui): debounce doc-hover event

---

packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts

For saving to disk, `props` will be deprecated in future.

feat: deprecated float-dom.props

---

common/shared/vite/index.js

before (1x)
univer.css 154728
univer.full.umd.js 11765968  
univer.slim.umd.js 11535342  
after (bigger 1.2x)
univer.css 154728
univer.full.umd.js 14237637  
univer.slim.umd.js 14007011    
What’s the difference? A real Identifier is easier to debug.

chore(build): build add keepNames

---

packages/drawing-ui/src/controllers/drawing-update.controller.ts

close https://github.com/dream-num/univer-pro/issues/1753

fix(drawing): update

---

common/shared/eslint/index.js
packages/slides/src/views/render/canvas-view.ts
packages/ui/src/services/before-close/before-close.service.ts
packages/ui/src/services/editor/editor.service.ts
packages/ui/src/utils/cell.ts

chore: add no reassign param lint

---

packages/docs-drawing-ui/src/controllers/doc-drawing-notification.controller.ts
packages/docs-ui/src/docs-ui-plugin.ts
packages/engine-formula/src/functions/lookup/sort/index.ts
packages/engine-formula/src/functions/text/textsplit/index.ts

fix(docs-drawing): formula ts error & docs-drawing load error

---

packages/docs/src/commands/mutations/docs-rename.mutation.ts
packages/docs/src/doc-plugin.ts

feat(docs): doc-rename

---

packages/sheets-formula/src/controllers/prompt.controller.ts
packages/sheets-formula/src/services/render-services/ref-selections.render-service.ts
packages/sheets-formula/src/views/prompt/help-function/HelpFunction.tsx
packages/sheets-ui/src/index.ts
packages/sheets-ui/src/services/selection/base-selection-render.service.ts
packages/sheets-ui/src/services/selection/selection-render.service.ts
packages/sheets-ui/src/services/selection/selection-shape-extension.ts
packages/sheets-ui/src/services/selection/selection-shape.ts

close https://github.com/dream-num/univer-pro/issues/1709
close https://github.com/dream-num/univer-pro/issues/1617

fix: ref selection should call updateSelection after skelenton change

---

packages/engine-render/src/components/sheets/extensions/background.ts
packages/engine-render/src/components/sheets/extensions/border.ts
packages/engine-render/src/components/sheets/extensions/font.ts

perf: skip hidden row & col in sheet's extension drawing process

---

packages/core/src/services/snapshot/snapshot-transform.ts
packages/core/src/services/snapshot/snapshot-utils.ts

fix(sheet): parse snapshot string

---

packages/sheets-ui/src/controllers/editor/editing.render-controller.ts

fix: unitId type error in handle editor invisible

---

packages/core/package.json
packages/data-validation/package.json
packages/sheets-conditional-formatting-ui/package.json
packages/sheets-conditional-formatting/package.json
packages/sheets-data-validation/package.json
packages/sheets-find-replace/package.json
packages/sheets-hyper-link/package.json
packages/sheets-ui/package.json
packages/sheets/package.json
packages/thread-comment-ui/package.json
packages/thread-comment/package.json
packages/umd/package.json
packages/uniscript/package.json
pnpm-lock.yaml

chore(protocol): update

---

packages/sheets-conditional-formatting-ui/src/menu/manage-rule.ts
packages/sheets/src/index.ts
packages/sheets/src/services/permission/util.ts

close https://github.com/dream-num/univer-pro/issues/1913

fix(permission): permission validation performance problem

---

examples/src/data/docs/default-document-data-cn.ts
packages/docs-drawing-ui/src/controllers/render-controllers/doc-drawing-transform-update.controller.ts
packages/docs-drawing/src/controllers/doc-drawing.controller.ts
packages/drawing-ui/src/controllers/image-update.controller.ts
packages/drawing-ui/src/controllers/utils.ts

fix: image initial render

---

packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/formula.tsx

close https://github.com/dream-num/univer/issues/2911
close https://github.com/dream-num/univer-pro/issues/1354

fix(conditional-formatting): can not add custom formula

---

packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/dataBar.tsx
packages/sheets-conditional-formatting-ui/src/components/panel/rule-list/index.tsx
packages/sheets-conditional-formatting-ui/src/components/preview/index.tsx
packages/sheets-conditional-formatting-ui/src/controllers/cf.render.controller.ts
packages/sheets-conditional-formatting-ui/src/menu/manage-rule.ts
packages/sheets-conditional-formatting/src/models/conditional-formatting-rule-model.ts
packages/sheets-conditional-formatting/src/models/conditional-formatting-view-model.ts
packages/sheets-conditional-formatting/src/render/data-bar.render.ts
packages/sheets-conditional-formatting/src/services/calculate-unit/data-bar.ts

fix(conditional-formatting): fixed a performance issue during the initialization phase of the conditional format

---

packages/core/src/docs/data-model/preset-list-type.ts
packages/docs-ui/src/locale/zh-TW.ts

feat(docs-ui): optimize quick order-list

---

packages/core/src/services/snapshot/snapshot-transform.ts

fix: snapshot

---

examples/src/data/slides/default-pages/page1.ts
packages/engine-render/src/base-object.ts
packages/engine-render/src/render-manager/render-manager.service.ts
packages/engine-render/src/shape/rich-text.ts
packages/slides-ui/src/controllers/slide-editing.render-controller.ts
packages/slides-ui/src/controllers/slide-editor-bridge.render-controller.ts
packages/slides-ui/src/services/slide-editor-bridge.service.ts
packages/slides-ui/src/views/editor-container/EditorContainer.tsx
packages/slides-ui/src/views/editor-container/index.module.less

feat: editing text and save

---

packages/docs/src/services/text-selection-manager.service.ts

fix: add rect ranges to share cursor

---

examples/src/data/docs/default-document-data-cn.ts
packages/core/src/docs/data-model/text-x/apply-utils/common.ts
packages/docs-hyper-link-ui/src/commands/operations/popup.operation.ts
packages/docs-ui/src/controllers/render-controllers/doc-checklist.render-controller.ts
packages/docs/src/basics/custom-decoration-factory.ts
packages/docs/src/commands/commands/auto-format.command.ts
packages/docs/src/commands/commands/break-line.command.ts
packages/docs/src/commands/commands/list.command.ts
packages/engine-render/src/components/docs/extensions/font-and-base-line.ts
packages/engine-render/src/components/docs/layout/model/glyph.ts

fix(docs-thread-comment-ui): comment when cross table

---

packages-experimental/uni-formula-ui/src/services/uni-formula.service.ts
packages-experimental/uni-formula/src/index.ts
packages-experimental/uni-formula/src/services/uni-formula.service.ts
packages-experimental/uni-formula/src/uni-formula.plugin.ts

fix: fix uni formula collab

---

packages-experimental/uniui/src/services/unit-grid/unit-grid.service.ts

fix(uni): scale uni frame

---

packages/sheets-ui/src/controllers/utils/selections-tools.ts

chore: change variable naming

---

packages-experimental/uni-formula-ui/package.json
packages-experimental/uni-formula-ui/src/services/uni-formula.service.ts
packages-experimental/uni-formula-ui/src/uni-formula-ui.plugin.ts
packages-experimental/uni-formula/package.json
packages-experimental/uni-formula/src/services/uni-formula.service.ts
packages/docs-ui/src/controllers/menu/context-menu.ts
packages/sheets-ui/src/controllers/menu/menu.ts
packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx
packages/sheets-zen-editor/src/plugin.ts
packages/ui/src/components/menu/desktop/Menu.tsx
packages/ui/src/services/menu/menu.ts
packages/ui/src/views/components/context-menu/ContextMenu.tsx
packages/ui/src/views/components/context-menu/MobileContextMenu.tsx
packages/ui/src/views/components/doc-bars/ToolbarItem.tsx

fix: fix uni mode errors

---

packages/docs-ui/src/controllers/menu/context-menu.ts

close https://github.com/dream-num/univer-pro/issues/1975

fix: context menu disable status

---

packages/docs/src/commands/commands/list.command.ts

close https://github.com/dream-num/univer-pro/issues/1976

fix: fix create lists in table

---

packages/engine-render/src/components/docs/text-selection/convert-rect-range.ts
packages/engine-render/src/components/docs/text-selection/text-selection-render-manager.ts

close https://github.com/dream-num/univer-pro/issues/1915

fix: context menu should not clear selections

---

packages/engine-render/src/components/docs/text-selection/selection-utils.ts

close https://github.com/dream-num/univer-pro/issues/1972

fix: selection is wrong when select table

---

packages/engine-render/src/components/docs/layout/doc-skeleton.ts

close https://github.com/dream-num/univer-pro/issues/1954

fix: can not edit in footer

---

packages/engine-render/src/components/docs/layout/block/paragraph/layout-ruler.ts

close https://github.com/dream-num/univer-pro/issues/1791

fix: issue #1791

---

packages/docs-ui/src/controllers/menu/menu.ts

close https://github.com/dream-num/univer-pro/issues/1990

fix: can not insert table in link

---

packages/docs-drawing-ui/src/views/menu/image.menu.ts
packages/docs-thread-comment-ui/src/controllers/menu.ts

close https://github.com/dream-num/univer-pro/issues/1970

fix: disable image when select table

---

packages/engine-render/src/engine.ts
packages/engine-render/src/layer.ts
packages/engine-render/src/scene.ts
packages/engine-render/src/shape/rich-text.ts
packages/slides-ui/src/controllers/slide-editing.render-controller.ts
packages/slides-ui/src/controllers/slide-editor-bridge.render-controller.ts
packages/slides-ui/src/services/slide-editor-bridge.service.ts

fix: set richtext page height to inifinity
close #xxx

fix: change element to save editing state & update doc sk after resize

---

packages-experimental/uni-docs-ui/package.json
packages-experimental/uni-docs-ui/src/controllers/menu.ts
packages-experimental/uni-docs-ui/src/controllers/uni-docs-ui.controller.tsx
packages-experimental/uniui/src/controllers/menu.ts
packages-experimental/uniui/src/controllers/uniui-toolbar.controller.tsx
packages-experimental/uniui/src/services/toolbar/uni-toolbar-service.ts
packages-experimental/uniui/src/views/uni-controls/UniControls.tsx
packages-experimental/uniui/src/views/uni-toolbar/index.module.less
packages-experimental/uniui/src/views/workbench/workbench.module.less
packages/docs-drawing-ui/src/index.ts
packages/docs-ui/src/controllers/menu/menu.ts
packages/docs-ui/src/index.ts
pnpm-lock.yaml

feat: add pivot table to unitoolbar & ui fix

---

packages/docs/src/commands/commands/table/table.ts

close https://github.com/dream-num/univer-pro/issues/1963

fix: insert col right to cursor

---

packages/docs/src/commands/commands/inline-format.command.ts
packages/docs/src/commands/mutations/core-editing.mutation.ts
packages/docs/src/services/text-selection-manager.service.ts
packages/engine-render/src/basics/range.ts
packages/engine-render/src/components/docs/text-selection/selection-utils.ts
packages/engine-render/src/components/docs/text-selection/text-selection-render-manager.ts

close https://github.com/dream-num/univer-pro/issues/1994 
close https://github.com/dream-num/univer-pro/issues/1961

fix: add range type when create selection

---

packages/docs-ui/src/views/table/create/TableCreate.tsx

close https://github.com/dream-num/univer-pro/issues/1942

fix: add table create row col limit to 20

---

packages/slides-ui/src/controllers/slide-editing.render-controller.ts
packages/slides/src/views/render/canvas-view.ts

fix: slide editor disappear when moving curor by keyboard (arrow key)

---

packages/design/src/components/scrollbar/Scrollbar.tsx
packages/docs-thread-comment-ui/src/commands/operations/show-comment-panel.operation.ts
packages/docs-thread-comment-ui/src/controllers/menu.ts
packages/docs-thread-comment-ui/src/views/doc-thread-comment-panel/index.tsx
packages/sheets-data-validation/src/controllers/dv-ref-range.controller.ts
packages/sheets-data-validation/src/controllers/dv-render.controller.ts
packages/sheets-data-validation/src/services/dropdown-manager.service.ts
packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts
packages/sheets-hyper-link-ui/src/controllers/ui.controller.ts
packages/sheets-hyper-link-ui/src/index.ts
packages/sheets-hyper-link-ui/src/plugin.ts
packages/sheets-hyper-link-ui/src/services/resolver.service.ts
packages/sheets-hyper-link-ui/src/types/interfaces/i-config.ts
packages/ui/src/services/sidebar/desktop-sidebar.service.ts
packages/ui/src/services/sidebar/sidebar.service.ts

close #2852
close #2821
close https://github.com/dream-num/univer-pro/issues/1966
close https://github.com/dream-num/univer-pro/issues/1736
close https://github.com/dream-num/univer-pro/issues/1692
close https://github.com/dream-num/univer-pro/issues/1993
close https://github.com/dream-num/univer-pro/issues/1765
close https://github.com/dream-num/univer-pro/issues/1749
close https://github.com/dream-num/univer-pro/issues/1735
close https://github.com/dream-num/univer-pro/issues/1723

fix: data-validation ref-range error init form snapshot & support hyperlink target

---

packages/docs-hyper-link-ui/src/controllers/render-controllers/render.controller.ts

fix: highlight not work when select link

---

packages/engine-render/src/components/sheets/extensions/font.ts

fix: filter should not hidden col

---

packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
packages/sheets-ui/src/controllers/editor/__tests__/mock-function.service.ts
packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
packages/sheets-ui/src/controllers/utils/char-tools.ts

fix(formula): fix formula sheet name uppercase bug

---

packages/engine-render/src/components/sheets/extensions/background.ts
packages/engine-render/src/components/sheets/extensions/border.ts

fix: col visible

---

packages-experimental/uni-slides-ui/src/controllers/uni-slides-ui.controller.tsx
packages-experimental/uni-slides-ui/src/views/UniSlideSideBar.tsx
packages-experimental/uni-slides-ui/src/views/index.module.less
packages-experimental/uniui/src/controllers/menu.ts
packages-experimental/uniui/src/views/uni-controls/UniControls.tsx
packages/slides-ui/src/controllers/image.menu.ts
packages/slides-ui/src/controllers/shape.menu.ts
packages/slides-ui/src/index.ts

feat: slide toolbar&sidebar in uni-mode

---

packages/engine-formula/src/functions/information/iseven/iseven.ts
packages/engine-formula/src/functions/information/isodd/isodd.ts
packages/engine-formula/src/functions/lookup/indirect/index.ts
packages/engine-formula/src/services/runtime.service.ts
packages/sheets-formula/src/controllers/__tests__/update-formula.controller.spec.ts
packages/sheets-formula/src/controllers/array-formula-display.controller.ts
packages/sheets-formula/src/controllers/prompt.controller.ts
packages/sheets-formula/src/controllers/update-formula.controller.ts
packages/sheets-ui/src/controllers/editor/editing.render-controller.ts

close https://github.com/dream-num/univer-pro/issues/1465
close https://github.com/dream-num/univer-pro/issues/1521
close #2782
close https://github.com/dream-num/univer-pro/issues/1752
close https://github.com/dream-num/univer-pro/issues/1755
close https://github.com/dream-num/univer-pro/issues/1745
close https://github.com/dream-num/univer-pro/issues/1524

fix(formula): fix some bugs

---

packages/core/package.json
packages/core/src/shared/tools.ts
packages/engine-render/src/components/docs/layout/block/paragraph/layout-ruler.ts
packages/engine-render/src/components/docs/layout/tools.ts
packages/sheets-numfmt/src/controllers/numfmt.editor.controller.ts
pnpm-lock.yaml

close https://github.com/dream-num/univer-pro/issues/1995
close https://github.com/dream-num/univer-pro/issues/1950
close https://github.com/dream-num/univer-pro/issues/1952

feat(bullet): bullet support paragraph setting

---

packages/docs-ui/src/controllers/doc-auto-format.controller.ts
packages/docs/src/commands/commands/list.command.ts
packages/engine-render/src/components/docs/layout/tools.ts
packages/sheets-ui/src/controllers/render-controllers/freeze.render-controller.ts
packages/slides-ui/src/controllers/slide-editing.render-controller.ts

close https://github.com/dream-num/univer-pro/issues/1059
close https://github.com/dream-num/univer-pro/issues/1987
close https://github.com/dream-num/univer-pro/issues/1985
close https://github.com/dream-num/univer-pro/issues/1968
close https://github.com/dream-num/univer-pro/issues/1930
close https://github.com/dream-num/univer-pro/issues/1885

fix(sheets-ui): set frozen to max column should limited & doc list-paragraph optimize

---

packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
packages/sheets-ui/src/controllers/editor/editing.render-controller.ts

fix: modify the judgment logic of rich text

---

packages/docs-ui/src/views/header-footer/panel/DocHeaderFooterOptions.tsx

close https://github.com/dream-num/univer-pro/issues/1996

fix: default setting in header and footer

---

packages-experimental/uni-slides-ui/src/controllers/uni-slides-ui.controller.tsx
packages-experimental/uniui/src/services/toolbar/uni-toolbar-service.ts
packages-experimental/uniui/src/views/uni-toolbar/UniFloatToolbar.tsx
packages-experimental/uniui/src/views/uni-toolbar/UniToolbar.tsx

fix: adjust toolbar item position in uni-mode

---

packages/docs-drawing-ui/src/controllers/render-controllers/doc-drawing-transform-update.controller.ts
packages/docs-ui/src/controllers/render-controllers/zoom.render-controller.ts
packages/engine-render/src/components/docs/text-selection/text-range.ts

fix(docs): refresh image positions after resize

---

packages/design/src/components/draggable-list/DraggableList.tsx

fix(design): add missing css import file

---

packages/core/src/services/resource-loader/resource-loader.service.ts
packages/docs-ui/src/services/docs-render.service.ts

fix(core): fix resource loader not work for created units

---

packages-experimental/uni-slides-ui/src/controllers/uni-slides-ui.controller.tsx
packages/slides-ui/src/controllers/slide-editing.render-controller.ts
packages/slides-ui/src/controllers/slide-editor-bridge.render-controller.ts
packages/slides-ui/src/index.ts

fix: slide editing scale

---

package.json
packages/slides-ui/src/commands/operations/insert-shape.operation.ts
packages/slides-ui/src/commands/operations/update-element.operation.ts
packages/slides-ui/src/components/panels/ArrangePanel.tsx
packages/slides-ui/src/components/panels/FillPanel.tsx
packages/slides-ui/src/components/panels/TransformPanel.tsx
packages/slides-ui/src/controllers/slide-ui.controller.ts
pnpm-lock.yaml

feat(slides): add update element operation

---

packages-experimental/uniui/src/views/uni-controls/UniControls.tsx

feat: set min-zoom to 0.1

---

packages/engine-render/src/components/docs/layout/block/paragraph/linebreaking.ts
packages/sheets-hyper-link-ui/src/controllers/copy-paste.controller.ts
packages/sheets-ui/src/services/clipboard/clipboard.service.ts

close https://github.com/dream-num/univer-pro/issues/2031

fix(docs-ui): doc list indent wrong after remove list & copy paste sheet-link

---

packages-experimental/uni-formula-ui/package.json
packages-experimental/uni-slides-ui/package.json
packages/core/package.json

chore: cleanup package.json

---

packages/drawing-ui/src/controllers/image-update.controller.ts
packages/drawing-ui/src/controllers/utils.ts
packages/sheets-drawing-ui/src/basics/transform-position.ts
packages/sheets-drawing-ui/src/controllers/sheet-drawing-update.controller.ts
packages/sheets-drawing/package.json
packages/sheets-drawing/src/controllers/render-controllers/sheet-drawing.render-controller.ts
packages/sheets-drawing/src/controllers/sheet-drawing.controller.ts
packages/sheets-drawing/src/plugin.ts
pnpm-lock.yaml

fix(sheets-drawing): drawing on uni mode

---

packages/docs-ui/src/controllers/render-controllers/doc-resize.render-controller.ts

fix(doc): should not resize all internal editors except zen mode

---

packages/docs-drawing-ui/src/controllers/doc-drawing-transformer-update.controller.ts
packages/sheets-drawing-ui/src/controllers/sheet-drawing-update.controller.ts

fix: uni drawing update

---

packages/sheets-data-validation/README.md
packages/sheets-data-validation/src/index.ts
packages/sheets-ui/src/views/cell-alert/index.module.less
packages/thread-comment-ui/src/views/thread-comment-tree/index.module.less

chore: optimize data validation doc & break-word

---

packages-experimental/uni-slides-ui/src/controllers/uni-slides-ui.controller.tsx
packages-experimental/uni-slides-ui/src/views/UniSlideSideBar.tsx
packages/slides-ui/src/commands/operations/activate.operation.ts
packages/slides-ui/src/commands/operations/append-slide.operation.ts
packages/slides-ui/src/commands/operations/delete-element.operation.ts
packages/slides-ui/src/commands/operations/insert-image.operation.ts
packages/slides-ui/src/commands/operations/insert-shape.operation.ts
packages/slides-ui/src/commands/operations/insert-text.operation.ts
packages/slides-ui/src/commands/operations/update-element.operation.ts
packages/slides-ui/src/components/panels/ArrangePanel.tsx
packages/slides-ui/src/components/panels/FillPanel.tsx
packages/slides-ui/src/components/panels/TransformPanel.tsx
packages/slides-ui/src/components/slide-bar/SlideBar.tsx
packages/slides-ui/src/components/upload-component/UploadFile.tsx
packages/slides-ui/src/controllers/popup-menu.controller.ts
packages/slides-ui/src/controllers/shape.menu.ts
packages/slides-ui/src/controllers/slide-editor-bridge.render-controller.ts
packages/slides-ui/src/controllers/slide-ui.controller.ts
packages/slides-ui/src/controllers/text.menu.ts
packages/slides-ui/src/index.ts

feat(slides): add text editing and shapes transform operations

---

packages/sheets-ui/src/controllers/permission/sheet-permission-init.controller.ts

fix: fix permission initialization in multi-unit situation

---

packages/engine-formula/src/engine/ast-node/function-node.ts

fix(formula): async formula

---

packages-experimental/uniui/src/views/uni-controls/UniControls.tsx
packages/sheets-ui/src/controllers/status-bar.controller.ts

fix: filtered & hidden rows should not be calculated in statusbar

---

packages/ui/src/components/menu/desktop/Menu.tsx

close https://github.com/dream-num/univer-pro/issues/1997

fix(ui): optimize Menu component rendering and filtering logic

---

packages/docs-drawing-ui/src/controllers/render-controllers/doc-drawing-transform-update.controller.ts

fix: doc drawing load error on uni mode

---

packages/docs-drawing-ui/src/controllers/render-controllers/doc-drawing-transform-update.controller.ts
packages/docs-drawing/src/controllers/doc-drawing.controller.ts

fix(docs-drawing-ui): doc drawing load error on uni mode

---

packages/ui/src/views/components/doc-bars/Toolbar.tsx
packages/ui/src/views/components/doc-bars/ToolbarItem.tsx

close https://github.com/dream-num/univer-pro/issues/1569

fix(ui): move event bubbling prevention from "More" menu to button

---

packages/core/src/shared/__tests__/object-matrix.spec.ts
packages/core/src/shared/object-matrix.ts
packages/design/src/components/dialog/Dialog.tsx

feat(sheet): matrix test

---

packages/sheets-hyper-link-ui/src/index.ts

fix(sheets-drawing-ui): export SheetsHyperLinkCopyPasteController for usage of pro

---

packages/core/src/shared/tools.ts
packages/sheets-ui/src/controllers/clipboard/utils.ts
packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts
packages/sheets/src/commands/commands/move-range.command.ts
packages/sheets/src/commands/mutations/move-range.mutation.ts
packages/sheets/src/services/ref-range/util.ts

-  add param {fromRange, toRange} in moveRange mutation for pivot table 
- clone the cell value to resolve bugs

fix(sheet): add from & to range in moverange & clone the cellvalue

---

packages/sheets-data-validation/src/views/date-dropdown/index.tsx

close https://github.com/dream-num/univer/issues/3053

fix(sheets-data-validation): date dropdown display error on invalid value

---

packages/docs-ui/src/commands/commands/doc-header-footer.command.ts

fix(docs): insert footer

---

packages/sheets-formula/src/controllers/prompt.controller.ts

fix: add inputFormula$

---

packages/engine-formula/src/engine/reference-object/base-reference-object.ts
packages/engine-formula/src/engine/utils/get-runtime-feature-cell.ts
packages/engine-formula/src/services/runtime.service.ts

close [#2002](https://github.com/dream-num/univer-pro/issues/2002)

fix(sheet): pivot data spill

---

common/shared/package.json
packages-experimental/uni-formula-ui/src/services/uni-formula.service.ts
packages/ui/src/services/menu/menu.service.ts
pnpm-lock.yaml

feat(ui): support modifying the toolbar items through `setMenuItem`

---

.vscode/settings.json
packages/ui/src/components/hooks/virtual-list.ts
packages/ui/src/index.ts

feat(ui): add use-virtual-list hooks

---

packages/core/src/services/authz-io/authz-io-local.service.ts
packages/core/src/services/permission/permission.service.ts
packages/sheets-ui/src/controllers/permission/sheet-permission-init.controller.ts
packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-base.controller.ts
packages/sheets-ui/src/views/permission/footer/permission-detail-footer.tsx
packages/sheets/src/model/range-protection-rule.model.ts
packages/sheets/src/services/permission/range-permission/range-protection.service.ts
packages/sheets/src/services/permission/worksheet-permission/worksheet-permission-point.model.ts
packages/sheets/src/services/permission/worksheet-permission/worksheet-permission-rule.model.ts
packages/sheets/src/services/permission/worksheet-permission/worksheet-permission.service.ts

fix(permission): fix permission bugs 0815

---

packages/docs/src/commands/commands/delete.command.ts
packages/docs/src/commands/commands/table/table.ts

close https://github.com/dream-num/univer-pro/issues/2032

fix(docs): delete paragraph break in table cell

---

packages/rpc/src/plugin.ts

fix: worker not disposed

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts

fix: export resetCahce from sheet-skeleton

---

packages/engine-render/src/components/docs/document.ts
packages/engine-render/src/components/docs/extensions/line.ts
packages/engine-render/src/components/docs/text-selection/convert-text-range.ts

close https://github.com/dream-num/univer-pro/issues/1777

fix(docs): line space

---

packages/engine-render/src/components/docs/text-selection/selection-utils.ts

close https://github.com/dream-num/univer-pro/issues/2011

fix(docs): delete list between tables

---

packages/docs-ui/src/controllers/menu/menu.ts

close https://github.com/dream-num/univer-pro/issues/1737

fix(docs): disable some menu items when no selections

---

packages/docs/src/services/text-selection-manager.service.ts

close https://github.com/dream-num/univer-pro/issues/1768

fix(docs): no need to scroll to selection when resize page

---

packages/sheets-data-validation/src/views/list/index.tsx

fix(permission): optimize permission calculation logic in dv

---

packages/engine-render/src/components/docs/document.ts
packages/engine-render/src/components/docs/extensions/line.ts
packages/engine-render/src/components/docs/layout/block/paragraph/layout-ruler.ts
packages/engine-render/src/components/docs/liquid.ts
packages/engine-render/src/components/docs/text-selection/convert-text-range.ts

close https://github.com/dream-num/univer-pro/issues/1782 and https://github.com/dream-num/univer-pro/issues/1777

fix(docs): line space between image and line

---

packages/sheets-ui/src/views/defined-name/index.module.less

fix(sheet): defined name panel style

---

packages/core/src/sheets/workbook.ts

docs(sheet): add snapshot  api docs

---

packages/engine-render/src/components/docs/layout/block/paragraph/layout-ruler.ts
packages/engine-render/src/components/docs/layout/block/paragraph/linebreaking.ts
packages/engine-render/src/components/docs/text-selection/convert-text-range.ts

style(doc): rename paragraphStart with isParagraphFirstShapedText

---

packages/core/src/common/unit.ts
packages/facade/src/apis/sheets/f-workbook.ts

feat(pivot): add mixin to util

---

packages/core/src/common/mixin.ts
packages/core/src/index.ts

fix(sheet): move function to a file and export

---

packages/core/src/common/mixin.ts

- use the class self will make error

fix(sheet): mixin should not use class self

---

packages/core/src/common/unit.ts

close #xxx
Duplicate with https://github.com/dream-num/univer/blob/dev/packages/core/src/common/mixin.ts

chore: revert mixin on unit

---

packages/facade/vite.config.ts

close #xxx
/d/univer/univer/packages/facade/src/apis/sheets/__tests__ 
$ npx vitest run -t "Test FWorksheet"

chore(facade): fix vitest in vscode

---

examples/src/sheets/main.ts
packages/core/src/index.ts
packages/core/src/services/authz-io/authz-io-local.service.ts
packages/facade/src/apis/__tests__/create-test-bed.ts
packages/facade/src/apis/facade.ts
packages/facade/src/apis/sheets/__tests__/f-permission.spec.ts
packages/facade/src/apis/sheets/f-permission.ts
packages/sheets-ui/src/controllers/permission/sheet-permission-init.controller.ts
packages/sheets/src/commands/mutations/add-range-protection.mutation.ts
packages/sheets/src/services/permission/type.ts

feat(permission): add facade api

---

packages/engine-render/src/components/docs/layout/doc-skeleton.ts
packages/sheets-ui/src/services/editor/cell-editor-manager.service.ts

close https://github.com/dream-num/univer-pro/issues/2158

fix(docs): find cursor by coods

---

packages/facade/src/apis/sheets/f-permission.ts
packages/sheets/src/index.ts

chore: add permission id return

---

packages/sheets-formula/src/services/render-services/ref-selections.render-service.ts
packages/sheets-ui/src/services/selection/base-selection-render.service.ts
packages/sheets-ui/src/services/selection/mobile-selection-render.service.ts
packages/sheets-ui/src/services/selection/selection-render.service.ts

refactor: refactor selection render modules' dependencies

---

packages/ui/src/services/menu/menu.service.ts
packages/ui/src/services/menu/menu.ts
pnpm-lock.yaml

refactor(ui): add breaking change warning for `IMenuService` modifications

---

packages/engine-formula/src/engine/utils/__tests__/math-kit.spec.ts
packages/engine-formula/src/engine/utils/math-kit.ts
packages/engine-formula/src/functions/date/time/__tests__/index.spec.ts
packages/engine-formula/src/functions/text/len/index.ts
packages/engine-formula/src/index.ts
packages/facade/src/apis/__tests__/create-test-bed.ts
packages/facade/src/apis/facade.ts
packages/facade/src/apis/sheets/__tests__/create-test-bed.ts
packages/facade/src/apis/sheets/__tests__/f-formula.spec.ts
packages/facade/src/apis/sheets/f-formula.ts

feat(facade): add FFormula api

---

packages/facade/src/apis/sheets/f-workbook.ts

chore(facade): keep workbook.getSnapshot

---

packages/sheets-formula/src/controllers/formula-editor-show.controller.ts

fix: debug currentSkeleton$ if param is null

---

packages/facade/package.json
packages/sheets-crosshair-highlight/package.json
packages/umd/package.json
packages/umd/scripts/index.mjs
pnpm-lock.yaml

chore: set @univerjs/sheets-crosshair-highlight public

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/sheets-formula/src/controllers/formula-editor-show.controller.ts
packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
packages/sheets-ui/src/services/selection/base-selection-render.service.ts
packages/sheets-ui/src/services/selection/selection-render.service.ts
packages/sheets/src/commands/operations/selection.operation.ts
packages/sheets/src/services/selections/selection-manager.service.ts

close: https://github.com/dream-num/univer-pro/issues/2199

fix: multi normal selections did not refresh when changing sheets.

---

packages/core/src/sheets/typedef.ts
packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/sheets-data-validation/src/controllers/dv-render.controller.ts

fix(sheets-data-validation): data validation auto height

---

packages/engine-formula/src/basics/error-type.ts
packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
packages/engine-formula/src/engine/analysis/__tests__/parser.spec.ts
packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts
packages/engine-formula/src/engine/ast-node/ast-root-node.ts
packages/engine-formula/src/engine/ast-node/value-node.ts
packages/engine-formula/src/engine/utils/reference.ts
packages/sheets-formula/src/controllers/prompt.controller.ts
packages/sheets-formula/src/services/description.service.ts

close [#2056](https://github.com/dream-num/univer-pro/issues/2056)
close [#1684](https://github.com/dream-num/univer-pro/issues/1684)
close [#2172](https://github.com/dream-num/univer-pro/issues/2172)

fix(formula): parser error

---

packages/engine-render/src/components/docs/layout/doc-skeleton.ts
packages/engine-render/src/components/docs/text-selection/convert-rect-range.ts
packages/engine-render/src/components/docs/text-selection/convert-text-range.ts
packages/engine-render/src/components/docs/text-selection/selection-utils.ts
packages/engine-render/src/components/docs/text-selection/text-selection-render-manager.ts

close https://github.com/dream-num/univer-pro/issues/2182
close https://github.com/dream-num/univer-pro/issues/2139

fix(docs): selection error in table and paragraph

---

packages/sheets-filter-ui/src/controllers/sheets-filter-permission.controller.ts
packages/sheets-filter-ui/src/controllers/sheets-filter.menu.ts
packages/sheets-ui/src/controllers/menu/menu.ts
packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-canvas-render.controller.ts
packages/sheets-ui/src/controllers/render-controllers/freeze.render-controller.ts

fix:  some operations can be performed when have view permission

---

packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
packages/sheets-ui/src/controllers/editor/editing.render-controller.ts

close https://github.com/dream-num/univer-pro/issues/2132

fix: modify the rich text judgment logic

---

packages/ui/src/views/components/sidebar/Sidebar.tsx
packages/ui/src/views/components/sidebar/interface.ts

chore: add sidebar params

---

packages/docs-drawing-ui/src/commands/commands/insert-doc-drawing.command.ts
packages/docs-ui/src/services/clipboard/clipboard.service.ts
packages/docs/src/commands/commands/clipboard.inner.command.ts
packages/docs/src/index.ts

close https://github.com/dream-num/univer-pro/issues/1673

fix(docs): remove content and insert drawing

---

packages/sheets/src/basics/cell-style.ts
packages/sheets/src/commands/mutations/set-range-values.mutation.ts

close https://github.com/dream-num/univer-pro/issues/2233

fix(sheets): do not copy cell bg color to rich text bg

---

packages/core/src/shared/types.ts
packages/sheets-ui/src/controllers/menu/menu-util.ts
packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-base.controller.ts
packages/sheets/src/services/selections/selection-manager.service.ts

fix(sheet): insert wrong columns  when shift right

---

packages/docs-ui/src/services/clipboard/clipboard.service.ts
packages/docs-ui/src/services/clipboard/html-to-udm/converter.ts

close https://github.com/dream-num/univer-pro/issues/2238

fix(docs): paste table after table

---

packages/engine-render/src/components/docs/text-selection/convert-rect-range.ts

close https://github.com/dream-num/univer-pro/issues/2250

fix(docs): copy table only has one row and col

---

packages/sheets-sort-ui/src/services/sheets-sort-ui.service.tsx

close [#1336](https://github.com/dream-num/univer-pro/issues/1336)

fix(sheets-sort): wrong order colIndex

---

packages/docs-ui/src/services/clipboard/html-to-udm/parse-node-style.ts

close https://github.com/dream-num/univer-pro/issues/1729

fix(docs): show font family after copy from header

---

packages/core/src/docs/data-model/text-x/apply-utils/common.ts

close https://github.com/dream-num/univer-pro/issues/2044

fix(docs): reserve the first remove text run

---

packages/engine-render/src/viewport.ts
packages/sheets-zen-editor/package.json
packages/sheets-zen-editor/src/commands/commands/zen-editor.command.ts
packages/sheets-zen-editor/src/controllers/zen-editor.controller.ts
pnpm-lock.yaml

close https://github.com/dream-num/univer-pro/issues/1138

fix(docs): no need to scroll when enter zen mode

---

packages/docs-ui/src/services/clipboard/clipboard.service.ts
packages/docs/src/commands/commands/clipboard.inner.command.ts

close https://github.com/dream-num/univer-pro/issues/1733
close https://github.com/dream-num/univer-pro/issues/1670

fix(docs): copy paste image form univer doc to univer doc

---

packages/docs-ui/src/controllers/menu/menu.ts

close https://github.com/dream-num/univer-pro/issues/1262
close https://github.com/dream-num/univer-pro/issues/1461

fix(docs): wrong font family in menu

---

packages/docs-ui/src/services/clipboard/html-to-udm/parse-node-style.ts
packages/sheets-ui/src/services/clipboard/html-to-usm/parse-node-style.ts

close https://github.com/dream-num/univer-pro/issues/2081

fix(docs): paste content to univer

---

packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts

close https://github.com/dream-num/univer-pro/issues/1540

fix: add rows by paste should support undo

---

packages/ui/src/services/dialog/desktop-dialog.service.ts
packages/ui/src/services/dialog/dialog.service.ts

- add close all function in dialog service

feat(sheet): dialog close all

---

packages/sheets-drawing-ui/src/controllers/render-controllers/sheet-drawing.render-controller.ts
packages/sheets-drawing-ui/src/controllers/sheet-drawing-update.controller.ts
packages/sheets-drawing/src/controllers/sheet-drawing.controller.ts

fix(sheets-drawing): drawing snapshot error

---

examples/src/data/sheets/demo/default-workbook-data-demo.ts
packages/core/src/types/const/const.ts
packages/sheets-data-validation/src/controllers/dv-reject-input.controller.ts
packages/sheets-data-validation/src/validators/date-validator.ts
packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
packages/sheets-ui/src/controllers/editor/editing.render-controller.ts

fix(sheets-data-validation): date picker can't input by type when errorStyle is STOP

---

packages/sheets-numfmt/src/commands/commands/set-currency.command.ts
packages/sheets-numfmt/src/controllers/numfmt.menu.controller.ts
packages/sheets-numfmt/src/menu/menu.ts
packages/sheets-numfmt/src/numfmt-plugin.ts
packages/sheets-numfmt/src/service/menu.currency.service.ts

fix(numfmt): menu circular dependencies

---

packages/network/src/services/http/interceptors/retry-interceptor.ts

fix: retry interceptor params

---

packages/docs-ui/src/services/clipboard/clipboard.service.ts

close https://github.com/dream-num/univer-pro/issues/1251

fix: paste should clear style when paste to editor in sheet

---

packages/facade/src/apis/f-hooks.ts
packages/facade/src/apis/facade.ts
packages/facade/src/apis/hooks/__tests__/f-undoredo-hooks.spec.ts
packages/facade/src/apis/hooks/f-undoredo-hooks.ts

feat(facade): add redo undo facade hooks

---

packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts

fix(sheet): make dirty when only local false

---

packages/engine-formula/src/engine/utils/math-kit.ts
packages/engine-formula/src/functions/math/cot/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/coth/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/csch/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/sec/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/sech/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/subtotal/__tests__/index.spec.ts
packages/engine-formula/src/functions/statistical/avedev/__tests__/index.spec.ts
packages/engine-formula/src/functions/statistical/averagea/__tests__/index.spec.ts

fix(formula): fix operation accuracy

---

packages/sheets-data-validation/src/services/dropdown-manager.service.ts
packages/sheets-ui/src/services/canvas-pop-manager.service.ts

fix(sheets-ui): popup can't show

---

packages/data-validation/src/controllers/dv-sheet.controller.ts

fix(sheets-data-validation): cant resume data-validation on undo remove-sheet

---

packages/drawing-ui/src/services/drawing-render.service.ts
packages/drawing/src/services/drawing-manager-impl.service.ts
packages/sheets-drawing-ui/src/controllers/sheet-drawing-copy-paste.controller.ts
packages/sheets-drawing-ui/src/controllers/sheet-drawing-transform-affected.controller.ts

close
[#2236](https://github.com/dream-num/univer-pro/issues/2236)
[#2136](https://github.com/dream-num/univer-pro/issues/2136)
[#1421](https://github.com/dream-num/univer-pro/issues/1421)
[#960](https://github.com/dream-num/univer-pro/issues/960)
[#930](https://github.com/dream-num/univer-pro/issues/930)

fix: drawing issues

---

packages/network/src/services/http/interceptors/__tests__/threshold-interceptor.spec.ts
packages/network/src/services/http/interceptors/threshold-interceptor.ts

fix: fix threshold error handling

---

packages/sheets-numfmt/src/index.ts

chore(numfmt): export MenuCurrencyService

---

packages/core/src/types/interfaces/i-document-data.ts
packages/docs-ui/src/commands/commands/doc-paragraph-setting.command.ts
packages/docs-ui/src/controllers/doc-paragraph-setting.controller.ts
packages/docs-ui/src/locale/en-US.ts
packages/docs-ui/src/locale/ru-RU.ts
packages/docs-ui/src/locale/vi-VN.ts
packages/docs-ui/src/locale/zh-CN.ts
packages/docs-ui/src/locale/zh-TW.ts
packages/docs-ui/src/views/paragraph-setting/Setting.tsx
packages/docs-ui/src/views/paragraph-setting/hook/utils.ts
packages/docs-ui/src/views/paragraph-setting/index.module.less
packages/docs/src/index.ts

feat(docs): support change space rule type

---

packages/sheets-numfmt/src/commands/commands/set-currency.command.ts

close https://github.com/dream-num/univer-pro/issues/1083

chore(numfmt): switch default numfmt pattern

---

examples/src/data/slides/default-pages/page1.ts
examples/src/data/slides/default-pages/page7.ts
examples/src/data/slides/unlimited-slide-data.ts

fix(slide): 2024 width

---

packages/sheets-ui/src/controllers/render-controllers/header-unhide.render-controller.ts
packages/sheets-ui/src/services/auto-fill/auto-fill.service.ts

close https://github.com/dream-num/univer-pro/issues/2284
close https://github.com/dream-num/univer-pro/issues/1145

fix: some filter & autofill bugs

---

packages/telemetry/package.json
packages/telemetry/src/services/telemetry-service.ts

feat: telemetry interface for track function cost time

---

packages/drawing-ui/src/controllers/image-update.controller.ts
packages/sheets-drawing-ui/src/controllers/render-controllers/sheet-drawing.render-controller.ts

fix(sheets-drawing-ui): sheet-drawing-import

---

packages/sheets-ui/src/services/clipboard/__tests__/clipboard-copy-filter.spec.ts
packages/sheets-ui/src/services/clipboard/clipboard.service.ts
packages/sheets-ui/src/services/clipboard/usm-to-html/convertor.ts

close https://github.com/dream-num/univer-pro/issues/1266

fix(clipboard): copy will not use filtered-out rows content

---

packages/sheets-ui/src/services/selection/selection-render-model.ts

close https://github.com/dream-num/univer-pro/issues/2342

fix: selection type did not update when set type to normal(0)

---

packages/sheets-ui/src/services/selection/mobile-selection-shape.ts
packages/sheets-ui/src/services/selection/selection-shape.ts

close https://github.com/dream-num/univer-pro/issues/2356

fix: mobile selection did not drawing

---

packages/sheets-sort-ui/src/controllers/menu.schema.ts
packages/sheets-ui/src/controllers/menu.schema.ts

close https://github.com/dream-num/univer-pro/issues/2353

fix: fix the sorting menu item display position

---

packages/sheets-formula/src/formula-ui-plugin.ts
packages/sheets-formula/src/services/description.service.ts
packages/ui/src/views/components/ribbon/Ribbon.tsx

fix(sheets-formula): fix the issue of missing formula description list

---

packages/design/src/components/popup/RectPopup.tsx
packages/design/src/components/popup/index.module.less

fix(design): popup style

---

packages-experimental/uni-formula-ui/src/controllers/doc-formula-input.controller.ts
packages-experimental/uni-formula-ui/src/services/formula-popup.service.ts
packages/docs-drawing-ui/src/controllers/drawing-popup-menu.controller.ts
packages/docs-hyper-link-ui/src/commands/operations/popup.operation.ts
packages/docs-hyper-link-ui/src/services/hyper-link-popup.service.ts
packages/docs-mention-ui/src/commands/operations/mention-popup.operation.ts
packages/docs-mention-ui/src/controllers/doc-mention-trigger.controller.ts
packages/docs-mention-ui/src/services/doc-mention-popup.service.ts
packages/docs-mention-ui/src/services/doc-mention.service.ts
packages/docs-ui/src/services/doc-popup-manager.service.ts

fix(uni-formula-ui): uni formula deps error

---

packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts

fix(formula): bracket has more blank

---

packages/sheets-filter/src/controllers/__tests__/sheets-filter.controller.spec.ts
packages/sheets-filter/src/controllers/sheets-filter.controller.ts

close https://github.com/dream-num/univer-pro/issues/1529

fix(filter): filter range change error when remove rows/cols

---

packages/sheets-ui/src/commands/commands/__tests__/set-format-painter.command.spec.ts
packages/sheets-ui/src/controllers/format-painter/format-painter.controller.ts

close https://github.com/dream-num/univer-pro/issues/1104
close https://github.com/dream-num/univer-pro/issues/996

feat(format-painter): format pianter to single-cell will copy whole range formats

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts

close https://github.com/dream-num/univer/issues/3313

fix: skip invisible row in filtered state for performance

---

packages/sheets-drawing-ui/src/controllers/sheet-drawing-transform-affected.controller.ts
packages/sheets-ui/src/controllers/auto-fill.controller.ts
packages/sheets-ui/src/services/auto-fill/auto-fill.service.ts

close https://github.com/dream-num/univer-pro/issues/1721

feat(auto-fill): edit operation will quit auto-fill mode

---

packages/sheets-data-validation/src/services/dropdown-manager.service.ts
packages/sheets-drawing-ui/src/controllers/drawing-popup-menu.controller.ts
packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts
packages/sheets-drawing/src/services/sheet-drawing.service.ts
packages/sheets-ui/src/services/canvas-pop-manager.service.ts

close https://github.com/dream-num/univer/issues/3283

feat(sheets-drawing-ui): support disable transform on float dom

---

packages/core/src/types/interfaces/i-data-validation.ts
packages/data-validation/src/commands/commands/data-validation.command.ts
packages/data-validation/src/validators/base-data-validator.ts
packages/sheets-data-validation/src/commands/commands/data-validation.command.ts
packages/sheets-data-validation/src/controllers/dv-auto-fill.controller.ts
packages/sheets-data-validation/src/validators/date-validator.ts
packages/sheets-data-validation/src/views/formula-input/custom-formula-input.tsx
packages/sheets-data-validation/src/views/formula-input/list-formula-input.tsx

close https://github.com/dream-num/univer-pro/issues/2352
close https://github.com/dream-num/univer-pro/issues/2344
close https://github.com/dream-num/univer-pro/issues/2283

fix(sheet-data-validation): auto-format data validation  non-standard date string & data-validation auto-fill

---

packages/core/src/common/interceptor.ts
packages/sheets-conditional-formatting-ui/src/controllers/cf.render.controller.ts
packages/sheets-conditional-formatting/src/services/conditional-formatting.service.ts

close https://github.com/dream-num/univer-pro/issues/2380

fix(conditional-formatting): render cache error

---

packages/sheets-filter-ui/src/views/render-modules/sheets-filter.render-controller.ts

close https://github.com/dream-num/univer-pro/issues/1649

fix(filter): filter render controller should dispose its vars when unit disposed

---

examples/esbuild.config.mjs
examples/src/sheets/lazy.ts
packages/debugger/src/controllers/e2e/e2e-memory.controller.ts

chore: fix demo uniscript building error

---

packages/sheets-ui/src/controllers/auto-height.controller.ts
packages/sheets-ui/src/services/auto-fill/auto-fill.service.ts
packages/sheets/src/commands/commands/__tests__/create-command-test-bed.ts
packages/sheets/src/commands/commands/__tests__/set-col-width.command.spec.ts
packages/sheets/src/commands/commands/set-worksheet-col-width.command.ts
packages/sheets/src/commands/commands/set-worksheet-row-height.command.ts
packages/sheets/src/commands/mutations/__tests__/create-command-test-bed.ts
packages/sheets/src/commands/mutations/set-worksheet-col-width.mutation.ts
packages/sheets/src/commands/mutations/set-worksheet-row-height.mutation.ts
packages/sheets/src/controllers/__tests__/util.ts
packages/sheets/src/services/__tests__/util.ts
packages/sheets/src/services/ref-range/__tests__/__testing__.ts
packages/sheets/src/services/ref-range/__tests__/ref-range.service.spec.ts
packages/sheets/src/services/sheet-interceptor/__tests__/create-core-test-bed.ts

close https://github.com/dream-num/univer-pro/issues/2302

fix(sheets): undo set col width should set to the original value

---

packages/sheets-conditional-formatting-ui/src/controllers/cf.render.controller.ts

close https://github.com/dream-num/univer-pro/issues/2393

fix(conditional-formatting): init view model

---

packages/sheets/src/services/ref-range/ref-range.service.ts

close https://github.com/dream-num/univer-pro/issues/1775

fix(sheets): skip remove-sheet on watch range if skipIntersects was set

---

packages/engine-formula/src/engine/dependency/dependency-tree.ts
packages/engine-formula/src/engine/dependency/formula-dependency.ts
packages/engine-formula/src/engine/dependency/range-block-util.ts
packages/engine-formula/src/services/dependency-manager.service.ts

-  fix dependency performance issue

fix(formular): fix dependency performance issue

---

packages/engine-render/src/components/docs/text-selection/text-selection-render-manager.ts
packages/engine-render/src/scene.input-manager.ts
packages/engine-render/src/scene.transformer.ts
packages/engine-render/src/scene.ts
packages/engine-render/src/shape/scroll-bar.ts
packages/engine-render/src/thin-scene.ts
packages/sheets-ui/src/controllers/render-controllers/freeze.render-controller.ts
packages/sheets-ui/src/controllers/render-controllers/header-move.render-controller.ts
packages/sheets-ui/src/controllers/render-controllers/header-resize.render-controller.ts
packages/sheets-ui/src/controllers/utils/selections-tools.ts
packages/sheets-ui/src/index.ts
packages/sheets-ui/src/services/selection/base-selection-render.service.ts
packages/sheets-ui/src/services/selection/mobile-selection-render.service.ts
packages/sheets-ui/src/services/selection/selection-render.service.ts
packages/sheets-ui/src/services/selection/selection-shape-extension.ts

close https://github.com/dream-num/univer-pro/issues/2361

fix: detect row/col index in selection

---

packages/sheets/src/services/ref-range/util.ts

fix(sheet): adjust move range old mutation not has fromRange property

---

packages/debugger/src/commands/commands/unit.command.ts
packages/debugger/src/controllers/debugger.controller.ts
packages/debugger/src/controllers/menu.schema.ts
packages/debugger/src/controllers/menu.ts

chore: add debug command to load snapshot from local json

---

packages-experimental/uni-formula-ui/src/services/uni-formula.service.ts
packages/core/src/services/plugin/plugin.service.ts
packages/debugger/src/debugger-plugin.ts
packages/docs-drawing-ui/src/plugin.ts
packages/docs-ui/src/basics/const/plugin-name.ts
packages/docs/src/doc-plugin.ts
packages/drawing-ui/src/plugin.ts
packages/drawing/src/plugin.ts
packages/engine-formula/src/plugin.ts
packages/engine-render/src/render-engine.ts
packages/find-replace/src/plugin.ts
packages/sheets-crosshair-highlight/src/plugin.ts
packages/sheets-formula/src/common/plugin-name.ts
packages/sheets-formula/src/formula-ui-plugin.ts
packages/sheets-sort-ui/src/plugin.ts
packages/sheets-sort/src/plugin.ts
packages/sheets-thread-comment-base/src/plugin.ts
packages/sheets-thread-comment-base/src/types/const.ts
packages/sheets-zen-editor/src/plugin.ts
packages/thread-comment-ui/src/types/const.ts
packages/thread-comment/src/types/const/index.ts
packages/uniscript/src/plugin.ts

chore: change plugin names and log plugin registration info

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts

fix: cell margin top is not right

---

packages/engine-formula/src/engine/dependency/dependency-tree.ts

fix(formular): fix sheet maximum

---

packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-base.controller.ts

chore: permission error should not output to console

---

packages/sheets-ui/src/commands/commands/__tests__/add-worksheet-merge.command.spec.ts
packages/sheets-ui/src/common/utils.ts

close https://github.com/dream-num/univer-pro/issues/2426

fix: cell value should adjust rich text & function

---

packages/sheets-formula/src/controllers/update-formula.controller.ts
packages/sheets-ui/src/controllers/auto-fill.controller.ts

close https://github.com/dream-num/univer-pro/issues/2459

fix: incorrectly quit autofill mode

---

packages/engine-render/src/basics/tools.ts
packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/engine-render/src/context.ts

fix(render): fix the issue loop span many times

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts

fix(sheet): the first style of span is not set is merge to true

---

packages/engine-render/src/basics/transform.ts

fix(sheet): fix type error

---

packages/sheets/src/services/permission/permission-point/range/edit.ts
packages/ui/src/components/menu/desktop/Menu.tsx
packages/ui/src/views/components/ribbon/Ribbon.tsx
packages/ui/src/views/components/ribbon/ToolbarItem.tsx

fix(ui): prevent dropdown usage when menu bar is disabled

---

packages/docs-drawing/src/controllers/doc-drawing.controller.ts

fix(docs-drawing): drawing resource

---

.github/workflows/playwright.yml
.gitignore
examples/esbuild.config.mjs
playwright.config.ts

ci: update playwright.yml

---

packages/docs-ui/src/services/selection/doc-selection-render.service.ts

close https://github.com/dream-num/univer-pro/issues/1683

fix(docs-ui): editor focusing conflict when update content

---

packages/sheets-drawing/src/plugin.ts

chore(sheets-drawing): add missing dependent on

---

packages/sheets/src/commands/commands/__tests__/set-range-values.command.spec.ts
packages/sheets/src/commands/mutations/set-range-values.mutation.ts

custom will overwrite the original value
1. Set new custom data to A1 `univerAPI.getActiveWorkbook().getActiveSheet().getRange(0,0,1,1).setValue({custom:{a:1}})`
2. Check cell data `univer._univerInstanceService.getFocusedUnit()._snapshot`
3. Add more custom data to A1 `univerAPI.getActiveWorkbook().getActiveSheet().getRange(0,0,1,1).setValue({custom:{b:1}})`
4. Check cell data 
Updated docs: https://github.com/dream-num/univer.ai/pull/268

fix(sheet): custom will overwrite the original value

---

packages/sheets-ui/src/controllers/editor/editing.render-controller.ts

fix(sheets-ui): formula error when cross sub-sheet

---

packages/core/src/shared/__tests__/object-matrix.spec.ts
packages/core/src/shared/object-matrix.ts

fix(sheet): getDiscreteRanges filter empty cell

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts

- fix (https://github.com/dream-num/univer-pro/issues/2482)

fix(span): fix editor position not right issue

---

packages/core/src/common/unit.ts
packages/core/src/docs/data-model/document-data-model.ts
packages/core/src/services/instance/instance.service.ts
packages/core/src/sheets/workbook.ts
packages/core/src/slides/slide-model.ts

chore: add getRev to unit model

---

.github/workflows/playwright.yml

ci: add labels when e2e failed

---

packages/core/src/common/unit.ts
packages/core/src/docs/data-model/document-data-model.ts
packages/core/src/sheets/workbook.ts
packages/core/src/slides/slide-model.ts

chore(core): add rev methods on unit models

---

packages/docs-ui/src/controllers/render-controllers/doc-selection-render.controller.ts
packages/docs-ui/src/controllers/render-controllers/doc.render-controller.ts
packages/docs-ui/src/docs-ui-plugin.ts
packages/docs-ui/src/services/docs-render.service.ts
packages/docs-ui/src/services/selection/doc-selection-render.service.ts
packages/docs/src/services/doc-selection-manager.service.ts
packages/docs/src/services/doc-skeleton-manager.service.ts
packages/engine-render/src/thin-scene.ts
packages/sheets-zen-editor/src/commands/operations/zen-editor.operation.ts
packages/sheets-zen-editor/src/services/zen-editor.service.ts
packages/sheets-zen-editor/src/views/menu.ts
packages/ui/src/controllers/ui/ui-desktop.controller.tsx

fix(docs): wrong ime position after scroll

---

packages/docs-ui/src/controllers/doc-move-cursor.controller.ts
packages/docs-ui/src/controllers/render-controllers/back-scroll.render-controller.ts
packages/docs-ui/src/services/selection/doc-selection-render.service.ts
packages/sheets-zen-editor/src/commands/commands/zen-editor.command.ts

close https://github.com/dream-num/univer-pro/issues/2452

fix(docs): scroll to selection

---

packages/sheets-ui/src/controllers/menu/menu-util.ts

The previous writing was incorrect，should first determine whether there is protection

chore: fix permission ctx menu performence

---

packages/facade/src/apis/sheets/f-permission.ts

chore: add permission facade returns

---

.github/workflows/ci-test.yml

ci(test): disable cache in CI workflow

---

packages-experimental/action-recorder/src/services/replay.service.ts
packages-experimental/debugger/src/controllers/e2e/e2e-memory.controller.ts
packages/core/src/index.ts
packages/core/src/shared/timer.ts
packages/network/src/services/http/interceptors/__tests__/threshold-interceptor.spec.ts
packages/rpc/src/services/rpc/__tests__/rpc.service.spec.ts

chore: add delayed replay commands

---

packages/sheets-ui/src/controllers/editor/editing.render-controller.ts

close https://github.com/dream-num/univer-pro/issues/2392

fix: fix edit cell with remove sheet

---

packages/engine-formula/src/basics/format.ts
packages/sheets-data-validation/src/validators/list-validator.ts
packages/sheets-numfmt/src/utils/pattern.ts
packages/sheets-ui/src/views/status-bar/CopyableStatisticItem.tsx

fix(numfmt): do  not block when syntax is not supported

---

packages/docs-ui/src/controllers/render-controllers/doc-selection-render.controller.ts

close https://github.com/dream-num/univer-pro/issues/2115

fix: fix pasting twice in formula editor

---

packages/sheets-filter-ui/src/controllers/sheets-filter-permission.controller.ts

close https://github.com/dream-num/univer-pro/issues/2403

fix: add filter with one cell should adjust expend range permission

---

packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-base.controller.ts
packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-canvas-render.controller.ts

chore: change permission check row

---

packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-base.controller.ts

chore: remove the default value when permission check

---

packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-base.controller.ts
packages/sheets/src/index.ts

close https://github.com/dream-num/univer-pro/issues/2468

fix: hide sheet should operation right sheet

---

packages/core/src/shared/__tests__/range.spec.ts
packages/core/src/shared/__tests__/rectangle.spec.ts
packages/core/src/shared/object-matrix-query.ts
packages/core/src/shared/range.ts
packages/core/src/shared/rectangle.ts
packages/docs-thread-comment-ui/src/controllers/doc-thread-comment-selection.controller.ts
packages/sheets-data-validation/src/controllers/dv-auto-fill.controller.ts
packages/sheets-data-validation/src/controllers/dv-copy-paste.controller.ts
packages/sheets-data-validation/src/models/rule-matrix.ts
packages/sheets-data-validation/src/models/sheet-data-validation-model.ts

fix(sheets-data-validation): large data validation oom

---

packages/docs-ui/src/services/selection/doc-selection-render.service.ts
packages/sheets-hyper-link-ui/src/commands/commands/add-hyper-link.command.ts
packages/sheets-hyper-link-ui/src/commands/commands/update-hyper-link.command.ts
packages/sheets-hyper-link-ui/src/commands/operations/popup.operations.ts
packages/sheets-hyper-link-ui/src/controllers/menu.ts
packages/sheets-hyper-link-ui/src/utils/index.ts

close https://github.com/dream-num/univer-pro/issues/2517
close https://github.com/dream-num/univer-pro/issues/2493

fix(sheets-hyper-link-ui): link redo undo

---

packages/core/src/shared/__tests__/range.spec.ts
packages/sheets-data-validation/src/commands/commands/data-validation.command.ts
packages/sheets-data-validation/src/controllers/dv-copy-paste.controller.ts
packages/sheets-data-validation/src/controllers/dv-ref-range.controller.ts
packages/sheets-data-validation/src/models/rule-matrix.ts
packages/sheets-data-validation/src/models/sheet-data-validation-model.ts

fix(sheets-data-validation): data-validation oom on extreme-big-range

---

packages/sheets/src/services/selections/selection-manager.service.ts

- Fix the issue where cell selection is lost after unmerging cells.

fix(sheet): set selection should ensure the selection is not null

---

packages/sheets-hyper-link-ui/src/services/resolver.service.ts

fix(sheets-hyper-link): build url

---

packages/sheets-sort-ui/src/controllers/sheets-sort.menu.ts
packages/sheets-ui/src/controllers/status-bar.controller.ts

- fix sort menu show in ExclusiveRange

fix(menu): sort menu should be hide

---

packages/sheets-thread-comment/src/commands/operations/comment.operation.ts
packages/sheets-thread-comment/src/controllers/menu.ts
packages/thread-comment-ui/src/commands/operations/comment.operations.ts
packages/thread-comment-ui/src/views/thread-comment-tree/index.module.less
packages/thread-comment-ui/src/views/thread-comment-tree/index.tsx

close https://github.com/dream-num/univer-pro/issues/1361
close https://github.com/dream-num/univer-pro/issues/1358
close https://github.com/dream-num/univer-pro/issues/1308

fix(sheets-thread-comment): comment ui issues

---

packages/sheets-hyper-link-ui/src/controllers/set-range.controller.ts

fix(sheets-hyper-link-ui): input link error

---

packages/engine-render/src/shape/base-scroll-bar.ts
packages/engine-render/src/shape/scroll-bar.ts
packages/engine-render/src/viewport.ts
packages/sheets-ui/src/commands/commands/set-scroll.command.ts
packages/sheets-ui/src/commands/operations/scroll.operation.ts
packages/sheets-ui/src/controllers/render-controllers/header-resize.render-controller.ts
packages/sheets-ui/src/controllers/render-controllers/scroll.render-controller.ts
packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts
packages/sheets-ui/src/services/scroll-manager.service.ts

close https://github.com/dream-num/univer/issues/3191

fix: scroll cmd for pointer down at scrolltrack

---

packages/sheets-ui/src/controllers/render-controllers/scroll.render-controller.ts
packages/sheets/src/commands/commands/set-col-visible.command.ts
packages/sheets/src/commands/commands/set-row-visible.command.ts
packages/sheets/src/commands/operations/selection.operation.ts

close https://github.com/dream-num/univer-pro/issues/2104
close #xxx

feat(sheets-ui): undo set cols visible should scroll to cols

---

packages/sheets-ui/src/controllers/sheet-ui.controller.ts

close https://github.com/dream-num/univer-pro/issues/2566

fix: auto focus after select menu item

---

packages/docs-ui/src/docs-ui-plugin.ts

refactor: add dependon to UniverDocsUIPlugin

---

packages/sheets/src/model/range-protection-render.model.ts

- fix performance issue for get cell

fix(protect): fix protect performance

---

packages/docs-ui/src/services/editor/editor.ts

feat: set document

---

packages/sheets-ui/src/components/border-panel/BorderPanel.tsx
packages/sheets/src/commands/commands/set-border-command.ts
packages/sheets/src/services/border-style-manager.service.ts

fix(sheets-ui): fix issue causing a blank screen when clicking on the border panel

---

examples/esbuild.config.mjs
examples/package.json
packages/sheets-numfmt/src/components/index.tsx
packages/ui/src/components/custom-label/CustomLabel.tsx
pnpm-lock.yaml

fix(ui): improve handling of `CustomLabel` default values

---

packages/docs-ui/src/commands/commands/table/doc-table-insert.command.ts
packages/docs-ui/src/commands/commands/table/doc-table-tab.command.ts
packages/docs-ui/src/controllers/menu/menu.ts
packages/docs-ui/src/services/clipboard/html-to-udm/converter.ts

close https://github.com/dream-num/univer-pro/issues/2559

fix: use tab to insert new row

---

common/shared/vite/index.js

chore(build): add build env

---

packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
packages/sheets-ui/src/services/clipboard/clipboard.service.ts

close https://github.com/dream-num/univer-pro/issues/2523

fix: mark selection should remove after some commands execute

---

packages/sheets-ui/src/controllers/clipboard/utils.ts

chore: support paste custom

---

packages/sheets-thread-comment/src/index.ts

fix(sheets-thread-comment): comment export

---

packages/core/src/sheets/__tests__/span-mode.spec.ts
packages/core/src/sheets/span-model.ts

- the index should update every loop cycle

fix(sheet): fix span cache not right issue

---

packages/sheets/src/commands/commands/__tests__/add-merge-command.spec.ts

test(ut): add ut

---

packages/core/src/index.ts
packages/core/src/services/resource-manager/type.ts
packages/sheets-drawing/src/controllers/sheet-drawing.controller.ts
packages/sheets-drawing/src/index.ts

feat(sheet): support fork file

---

packages/sheets-ui/src/commands/commands/__tests__/add-worksheet-merge.command.spec.ts
packages/sheets-ui/src/commands/commands/add-worksheet-merge.command.ts
packages/sheets-ui/src/common/utils.ts
packages/sheets/src/commands/mutations/add-worksheet-merge.mutation.ts

close https://github.com/dream-num/univer-pro/issues/2540

fix: fix horizontal merge wrong value

---

packages/engine-formula/src/functions/logical/reduce/index.ts

fix: fix reduce function type error

---

packages/engine-render/src/shape/scroll-bar.ts

close https://github.com/dream-num/univer/issues/3554

fix: scrollbar offset when moving by mouse

---

packages/sheets-hyper-link-ui/src/controllers/popup.controller.ts
packages/sheets-ui/src/controllers/menu/menu-util.ts
packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-base.controller.ts

close https://github.com/dream-num/univer-pro/issues/2527 https://github.com/dream-num/univer/issues/3555

fix: permission check use compose points

---

packages/engine-formula/src/functions/logical/bycol/index.ts
packages/engine-formula/src/functions/logical/byrow/index.ts
packages/engine-formula/src/functions/logical/map/index.ts

fix(formula): fix bycol/byrow/map

---

packages/design/src/components/input-number/InputNumber.tsx
packages/sheets-ui/src/components/menu-item-input/MenuItemInput.tsx
packages/ui/src/components/custom-label/CustomLabel.tsx
packages/ui/src/components/menu/desktop/Menu.tsx
packages/ui/src/services/contextmenu/contextmenu.service.ts
packages/ui/src/views/components/context-menu/ContextMenu.tsx

close https://github.com/dream-num/univer-pro/issues/2282

fix(ui): revert column width input to initial value on menu close

---

packages/design/src/components/select/Select.stories.tsx
packages/design/src/components/select/Select.tsx
packages/design/src/components/select/index.module.less
packages/design/src/locale/en-US.ts
packages/design/src/locale/interface.ts
packages/design/src/locale/ru-RU.ts
packages/design/src/locale/vi-VN.ts
packages/design/src/locale/zh-CN.ts
packages/design/src/locale/zh-TW.ts

close https://github.com/dream-num/univer-pro/issues/1026

fix(design): improve empty options styling and messaging for Select

---

packages/sheets-ui/src/controllers/cell-custom-render.controller.ts
packages/sheets/src/index.ts

close https://github.com/dream-num/univer-pro/issues/2395

fix: fix dv custom cell permission

---

packages/core/src/types/enum/text-style.ts

refactor(core): change `BooleanNumber` to a regular enum

---

packages/facade/src/apis/sheets/__tests__/f-worksheet.spec.ts
packages/facade/src/apis/sheets/f-range.ts
packages/facade/src/apis/sheets/f-workbook.ts
packages/facade/src/apis/sheets/f-worksheet.ts
packages/sheets-ui/src/commands/commands/set-frozen.command.ts
packages/sheets/src/commands/commands/set-frozen-cancel.command.ts
packages/sheets/src/commands/commands/set-frozen.command.ts

feat(facade): add facade for freeze and getCellData

---

packages/docs-ui/src/services/editor/editor.ts
packages/docs-ui/src/services/selection/doc-selection-render.service.ts

refactor(docs): add more event to input observable

---

packages/sheets-ui/src/controllers/render-controllers/editor-bridge.render-controller.ts

fix(sheets-ui): formula across subsheet

---

e2e/perf/scroll.spec.ts
packages/engine-render/src/basics/tools.ts
packages/engine-render/src/components/sheets/sheet-skeleton.ts

fix: e2e scrolling & add missing interface for sheet skeleton

---

packages/core/src/shared/index.ts
packages/core/src/shared/rectangle.ts
packages/sheets-ui/src/controllers/status-bar.controller.ts
packages/sheets-ui/src/controllers/utils/range-tools.ts
packages/sheets-ui/src/services/selection/base-selection-render.service.ts
packages/sheets-ui/src/services/selection/selection-render.service.ts

- fix multi selection calc error
-  fix performance
- the Welford's logic:  https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance, we can use to calc stdev

fix(sheet): fix summary performance

---

packages/docs-ui/src/services/doc-page-layout.service.ts

fix(docs): flickering issues when first visit into the page

---

packages/sheets-ui/src/commands/commands/set-zoom-ratio.command.ts
packages/sheets-ui/src/commands/operations/set-zoom-ratio.operation.ts
packages/sheets-ui/src/controllers/render-controllers/zoom.render-controller.ts
packages/sheets-ui/src/views/count-bar/ZoomSlider.tsx

fix(sheets): disbale zoom ration on cell editing

---

packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-form-excel.spec.ts
packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-from-google.spec.ts
packages/sheets-ui/src/services/clipboard/__tests__/clipboard-service.spec.ts

close https://github.com/dream-num/univer-pro/issues/2330

fix: cell margin bottom should over 1

---

packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts
packages/ui/src/views/components/dom/FloatDom.tsx

fix(sheets-drawing-ui): float-dom error on scale

---

packages/docs-ui/src/services/selection/doc-selection-render.service.ts
packages/engine-render/src/components/docs/layout/doc-skeleton.ts

close https://github.com/dream-num/univer-pro/issues/2229

fix(docs): doc selection refresh

---

packages/sheets-ui/src/controllers/menu/__tests__/create-menu-test-bed.ts
packages/sheets-ui/src/controllers/permission/sheet-permission-init.controller.ts
packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-formula-render.controller.ts
packages/sheets/src/index.ts
packages/sheets/src/model/range-protection-rule.model.ts
packages/sheets/src/model/range-protection.cache.ts
packages/sheets/src/services/permission/range-permission/range-protection.ref-range.ts
packages/sheets/src/services/permission/range-permission/range-protection.service.ts
packages/sheets/src/sheets-plugin.ts

perf: fix permission perf

---

packages/core/src/docs/data-model/text-x/build-utils/selection.ts

close https://github.com/dream-num/univer-pro/issues/2701

fix(docs-link-ui): link text error

---

packages/sheets-data-validation/src/controllers/dv-sheet.controller.ts

close https://github.com/dream-num/univer-pro/issues/2710

fix(data-validation): remove useless interceptor mutations

---

packages/core/src/sheets/span-model.ts
packages/engine-render/src/components/sheets/sheet-skeleton.ts

fix: bg border return before  getCell

---

packages/core/src/services/command/command.service.ts

chore: custom error catch

---

packages/sheets/src/services/permission/range-permission/range-protection.ref-range.ts

close https://github.com/dream-num/univer-pro/issues/2711

fix: add remove sheet intercept

---

packages-experimental/uni-sheets-ui/src/controllers/uni-sheets-ui.controller.tsx
packages/sheets-ui/src/controllers/config.schema.ts
packages/sheets-ui/src/controllers/sheet-ui.controller.ts
packages/sheets-ui/src/views/sheet-container/SheetContainer.tsx
packages/sheets/src/sheets-plugin.ts

feat(sheets-ui): add `formulaBar` option

---

packages/sheets-data-validation/src/controllers/dv-ref-range.controller.ts
packages/sheets-data-validation/src/controllers/dv-render.controller.ts
packages/sheets-data-validation/src/widgets/dropdown-widget.ts
packages/sheets-hyper-link-ui/src/controllers/render-controllers/render.controller.ts
packages/sheets-hyper-link-ui/src/plugin.ts
packages/sheets-thread-comment/src/controllers/render-controllers/render.controller.ts

fix(sheets-ui): remove useless mark dirty on data-validation & thread-comment

---

packages/sheets-formula/package.json
packages/sheets-formula/src/controllers/formula-editor-show.controller.ts
packages/sheets-ui/src/services/sheet-skeleton-manager.service.ts
pnpm-lock.yaml

fix: array formula border deps

---

packages/sheets/src/services/permission/range-permission/range-protection.service.ts

fix: fix permission init should build cache

---

packages/engine-render/src/components/docs/extensions/background.ts

close https://github.com/dream-num/univer-pro/issues/2634

fix: underline was hidden by background in next line

---

packages/sheets-conditional-formatting/src/services/calculate-unit/highlight-cell.ts
packages/sheets-conditional-formatting/src/services/conditional-formatting.service.ts

close [https://github.com/dream-num/univer-pro/issues/2660)
](https://github.com/dream-num/univer-pro/issues/2660)
close [https://github.com/dream-num/univer-pro/issues/2739](https://github.com/dream-num/univer-pro/issues/2739)
#3593

fix(conditional-formatting): ranking error

---

packages/engine-render/src/scene.ts

chore: add after render hook

---

packages/ui/src/components/menu/desktop/Menu.tsx

fix(ui): resolve issue preventing custom context menus from displaying

---

packages/docs-ui/src/controllers/menu/menu.ts
packages/ui/src/common/component-manager.ts

fix(docs): wrong header footer icon

---

packages/core/src/docs/data-model/text-x/utils.ts
packages/docs-ui/src/services/clipboard/clipboard.service.ts
packages/docs-ui/src/services/selection/convert-rect-range.ts

close https://github.com/dream-num/univer-pro/issues/2448

fix(docs): copy table in univer

---

packages/docs-ui/src/services/selection/convert-text-range.ts
packages/docs-ui/src/services/selection/rect-range.ts
packages/docs-ui/src/services/selection/selection-utils.ts
packages/engine-render/src/components/docs/doc-component.ts
packages/engine-render/src/components/docs/layout/doc-skeleton.ts

close https://github.com/dream-num/univer-pro/issues/2602#issuecomment-2398664502

fix(docs): optimization of text selection

---

packages/docs-ui/src/basics/table.ts
packages/docs-ui/src/controllers/config.schema.ts
packages/docs-ui/src/controllers/doc-header-footer.controller.ts

close https://github.com/dream-num/univer-pro/issues/2752

fix(docs): arrow in table when table across two pages

---

packages/ui/src/services/zen-zone/desktop-zen-zone.service.ts
packages/ui/src/services/zen-zone/zen-zone.service.ts

fix(zen): fix zen editor cannot be opened

---

packages/engine-formula/src/basics/common.ts
packages/engine-formula/src/controller/calculate.controller.ts
packages/engine-formula/src/engine/analysis/__tests__/parser.spec.ts
packages/engine-formula/src/functions/__tests__/nested-functions.spec.ts
packages/engine-formula/src/functions/compatibility/rank/__tests__/index.spec.ts
packages/engine-formula/src/functions/information/cell/__tests__/index.spec.ts
packages/engine-formula/src/functions/information/isformula/__tests__/index.spec.ts
packages/engine-formula/src/functions/information/isref/__tests__/index.spec.ts
packages/engine-formula/src/functions/lookup/column/__tests__/index.spec.ts
packages/engine-formula/src/functions/lookup/columns/__tests__/index.spec.ts
packages/engine-formula/src/functions/lookup/index/__test__/index.spec.ts
packages/engine-formula/src/functions/lookup/indirect/__test__/index.spec.ts
packages/engine-formula/src/functions/lookup/offset/__tests__/index.spec.ts
packages/engine-formula/src/functions/lookup/row/__tests__/index.spec.ts
packages/engine-formula/src/functions/lookup/rows/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/subtotal/__tests__/index.spec.ts
packages/engine-formula/src/functions/statistical/averageif/__tests__/index.spec.ts
packages/engine-formula/src/functions/statistical/rank-avg/__tests__/index.spec.ts
packages/engine-formula/src/functions/statistical/rank-eq/__tests__/index.spec.ts
packages/engine-formula/src/models/utils/formula-data-util.ts
packages/engine-formula/src/services/current-data.service.ts
packages/engine-formula/src/services/runtime.service.ts

close https://github.com/dream-num/univer-pro/issues/2418

fix(formula): array formula spill error

---

common/shared/vite/index.js
common/shared/vite/obfuscator.js

chore(build): update obfuscator condition

---

packages/engine-render/package.json
packages/sheets-data-validation-ui/src/mobile-plugin.ts
packages/sheets-data-validation-ui/src/plugin.ts
packages/sheets-data-validation-ui/src/views/components/list-dropdown/index.tsx
packages/sheets-data-validation/src/controllers/config.schema.ts
packages/sheets-data-validation/src/plugin.ts
pnpm-lock.yaml

chore: cleanup plugins

---

common/shared/vite/index.js
packages-experimental/rpc-node/package.json
pnpm-lock.yaml

chore: add enable sourcemap flag

---

packages/docs-ui/src/services/selection/doc-selection-render.service.ts

close https://github.com/dream-num/univer-pro/issues/2764

fix(docs): no need to add cursor when select multi text ranges

---

packages/docs-drawing-ui/src/plugin.ts

fix(docs): editing drawing is not working

---

packages/engine-formula/src/engine/reference-object/column-reference-object.ts
packages/engine-formula/src/engine/reference-object/row-reference-object.ts
packages/sheets-formula-ui/src/controllers/prompt.controller.ts
packages/sheets-formula-ui/src/views/more-functions/select-function/SelectFunction.tsx

close https://github.com/dream-num/univer-pro/issues/2774
close https://github.com/dream-num/univer-pro/issues/2773
close https://github.com/dream-num/univer-pro/issues/2747

fix(formula): fix some formula bugs

---

packages/core/src/shared/clipboard.ts
packages/docs-ui/src/commands/commands/clipboard.inner.command.ts

…s and rect ranges
close https://github.com/dream-num/univer-pro/issues/2346

fix(docs): can not paste content when have both text range and rect range

---

packages/docs-ui/src/commands/commands/clipboard.inner.command.ts
packages/docs-ui/src/commands/commands/inline-format.command.ts
packages/docs-ui/src/services/selection/doc-selection-render.service.ts
packages/docs-ui/src/services/selection/selection-utils.ts
packages/docs/src/services/doc-selection-manager.service.ts

close https://github.com/dream-num/univer-pro/issues/2759

fix(docs): selection offset is wrong when refresh

---

packages/docs-drawing-ui/src/views/menu/image.menu.ts

close https://github.com/dream-num/univer-pro/issues/2767

fix(docs): insert image after table

---

packages/sheets-ui/src/controllers/menu/delete.menu.ts

- fix hidden menu when interest with  exclusive range

fix(sheet): fix can not delete when there are exclusive range

---

packages/facade/src/apis/sheets/f-range.ts
packages/sheets-data-validation-ui/src/commands/commands/data-validation-ui.command.ts
packages/sheets-data-validation/src/commands/commands/data-validation.command.ts

feat(facade): change data-validation facade api into sync

---

packages/engine-formula/src/basics/date.ts
packages/engine-formula/src/functions/date/datedif/__tests__/index.spec.ts
packages/engine-formula/src/functions/date/datedif/index.ts

fix(formula): fix datedif bug

---

packages/core/src/index.ts
packages/core/src/shared/rxjs.ts
packages/data-validation/src/index.ts
packages/data-validation/src/models/data-validation-model.ts
packages/facade/src/apis/sheets/f-workbook.ts
packages/facade/src/apis/sheets/f-worksheet.ts
packages/sheets-data-validation-ui/src/controllers/dv-render.controller.ts
packages/sheets-data-validation-ui/src/controllers/dv-rerender.controller.ts
packages/sheets-data-validation-ui/src/mobile-plugin.ts
packages/sheets-data-validation-ui/src/plugin.ts
packages/sheets-data-validation/src/index.ts
packages/sheets-data-validation/src/models/sheet-data-validation-model.ts
packages/sheets-data-validation/src/plugin.ts
packages/sheets-data-validation/src/services/dv-cache.service.ts
packages/sheets-data-validation/src/services/dv-custom-formula.service.ts
packages/sheets-data-validation/src/services/dv-formula.service.ts
packages/sheets-data-validation/src/services/dv-validator-service.ts

close https://github.com/dream-num/univer-pro/issues/2857

fix(sheets-data-validation): data validation validator status render error

---

e2e/perf/scroll.spec.ts
packages/core/src/sheets/styles.ts
packages/sheets/src/commands/commands/move-range.command.ts
packages/sheets/src/commands/mutations/move-range.mutation.ts

close https://github.com/dream-num/univer-pro/issues/2605

fix: cell style in collaboration

---

packages/docs-ui/src/services/selection/doc-selection-render.service.ts
packages/docs/src/services/doc-selection-manager.service.ts

fix: refresh selection when collapsed

---

packages/docs-ui/src/services/doc-page-layout.service.ts

fix: flickering when init page

---

packages/engine-render/src/scene.transformer.ts
packages/engine-render/src/shape/rect.ts
packages/engine-render/src/shape/shape.ts
packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts
packages/sheets-drawing/src/services/sheet-drawing.service.ts

feat(drawing): add optional property to control rotate handle of drawing element

---

packages/sheets-conditional-formatting/src/services/calculate-unit/highlight-cell.ts
packages/sheets-conditional-formatting/src/services/calculate-unit/utils.ts

fix(condition-formatting): date calculation error

---

packages/core/package.json
packages/data-validation/package.json
packages/sheets-conditional-formatting-ui/package.json
packages/sheets-conditional-formatting/package.json
packages/sheets-data-validation-ui/package.json
packages/sheets-data-validation/package.json
packages/sheets-find-replace/package.json
packages/sheets-hyper-link/package.json
packages/sheets-ui/package.json
packages/sheets/package.json
packages/thread-comment-ui/package.json
packages/thread-comment/package.json
packages/umd/package.json
packages/uniscript/package.json
pnpm-lock.yaml

chore(pb): update pb 0.1.39-alpha.30

---

packages/sheets-ui/src/services/editor-bridge.service.ts

fix(sheets-ui): can't save first edit cell

---

packages/engine-render/src/components/docs/layout/tools.ts

close https://github.com/dream-num/univer-pro/issues/2861

fix(docs): no need to cache font style when has no text run

---

packages/sheets-ui/src/controllers/editor/data-sync.controller.ts

fix(docs-ui): formula-editor should not render paragraph style

---

packages/umd/scripts/index.mjs

chore: umd build add `fa` lang

---

packages/sheets-ui/src/controllers/render-controllers/editor-bridge.render-controller.ts

fix(sheets-ui): can't edit after dispose

---

examples-node/package.json
examples/src/sheets/main.ts
examples/src/uni/main.ts
pnpm-lock.yaml
pnpm-workspace.yaml

fix: fix type-check

---

e2e/visual-comparison/sheets/sheets-visual-comparison.spec.ts
packages/engine-render/src/layer.ts
packages/sheets-drawing-ui/src/commands/commands/move-drawings.command.ts
packages/sheets-ui/src/commands/commands/__tests__/create-selection-command-test-bed.ts
packages/sheets-ui/src/commands/commands/__tests__/set-selections.command.spec.ts
packages/sheets-ui/src/commands/commands/set-selection.command.ts
packages/sheets-ui/src/services/selection/base-selection-render.service.ts
packages/sheets-ui/src/services/selection/mobile-selection-render.service.ts
packages/sheets/src/commands/operations/selection.operation.ts
packages/sheets/src/services/selections/selection-manager.service.ts

close https://github.com/dream-num/univer-pro/issues/2748

fix: trigger selectionMoveEnd$ when using keyboard to change selections.

---

packages/thread-comment/src/models/thread-comment.model.ts
packages/thread-comment/src/plugin.ts

feat(thread-comment): sync comment after rendered

---

packages/engine-render/src/components/docs/layout/shaping-engine/font-library.ts

chore: add fonts check defense

---

e2e/visual-comparison/sheets/sheets-visual-comparison.spec.ts
packages/sheets-ui/src/services/sheets-render.service.ts

fix: unitId for canvas

---

.vscode/settings.json
packages/core/package.json
packages/core/src/shared/__tests__/range.spec.ts
packages/core/src/shared/r-tree.ts
packages/core/src/shared/range.ts
packages/engine-formula/src/engine/dependency/dependency-tree.ts
packages/engine-formula/src/engine/dependency/formula-dependency.ts
packages/engine-formula/src/engine/reference-object/base-reference-object.ts
packages/engine-formula/src/engine/reference-object/column-reference-object.ts
packages/engine-formula/src/engine/reference-object/row-reference-object.ts
packages/engine-formula/src/services/calculate-formula.service.ts
packages/engine-formula/src/services/dependency-manager.service.ts
pnpm-lock.yaml

fix(formula): dependency for vlookup

---

packages/engine-formula/package.json
packages/engine-formula/src/basics/inverted-index-cache.ts
packages/engine-formula/src/engine/utils/numfmt-kit.ts
packages/engine-formula/src/engine/value-object/array-value-object.ts
packages/engine-formula/src/functions/logical/if/index.ts
packages/engine-formula/src/services/runtime.service.ts
pnpm-lock.yaml

fix(formula): fix CELL_INVERTED_INDEX_CACHE range set

---

packages/sheets-data-validation-ui/src/controllers/dv-copy-paste.controller.ts
packages/sheets-data-validation-ui/src/views/validator-views/list-multiple-view.ts

close https://github.com/dream-num/univer-pro/issues/2571
close https://github.com/dream-num/univer-pro/issues/2973

fix(sheets-data-validation): can't copy checkbox with right checked status

---

packages/core/src/docs/data-model/text-x/build-utils/__test__/custom-range.spec.ts
packages/core/src/docs/data-model/text-x/build-utils/custom-range.ts
packages/core/src/docs/data-model/text-x/build-utils/index.ts
packages/core/src/docs/data-model/text-x/build-utils/selection.ts
packages/docs-hyper-link-ui/src/commands/operations/popup.operation.ts
packages/docs-hyper-link-ui/src/views/hyper-link-edit/index.tsx
packages/docs-ui/src/services/doc-auto-format.service.ts
packages/sheets-hyper-link-ui/src/services/popup.service.ts
packages/sheets-hyper-link-ui/src/utils/index.ts
packages/sheets-hyper-link-ui/src/views/CellLinkEdit/index.tsx

close https://github.com/dream-num/univer-pro/issues/2971

fix(docs-link): error display url link when add link

---

packages/sheets-thread-comment/src/controllers/sheets-thread-comment-popup.controller.ts
packages/sheets-ui/src/common/utils.ts
packages/sheets-ui/src/services/hover-manager.service.ts

close https://github.com/dream-num/univer-pro/issues/2707

feat(thread-comment): didn't show tips on merge-cell comment

---

packages/core/src/docs/data-model/json-x/json-x.ts
packages/core/src/docs/data-model/text-x/__tests__/action-iterator.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/apply-utils.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/apply.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/compose.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/invert.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/text-x.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/transform.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/utils.spec.ts
packages/core/src/docs/data-model/text-x/apply-utils/common.ts
packages/core/src/docs/data-model/text-x/apply-utils/delete-apply.ts
packages/core/src/docs/data-model/text-x/apply-utils/insert-apply.ts
packages/core/src/docs/data-model/text-x/apply.ts
packages/docs-ui/src/basics/paragraph.ts
packages/docs-ui/src/commands/commands/auto-format.command.ts
packages/docs-ui/src/commands/commands/core-editing.command.ts
packages/docs-ui/src/commands/commands/ime-input.command.ts
packages/docs-ui/src/controllers/render-controllers/doc-ime-input.controller.ts
packages/docs-ui/src/controllers/render-controllers/doc-input.controller.ts

close https://github.com/dream-num/univer-pro/issues/2943

fix(docs): the apply result should be consistent

---

packages/sheets/src/commands/mutations/toggle-gridlines.mutation.ts

chore: fix mutation name

---

packages/sheets-ui/src/views/sheet-bar/sheet-bar-menu/SheetBarMenu.tsx
packages/sheets-ui/src/views/sheet-bar/sheet-bar-menu/index.module.less

fix(ui): improve layout and overflow handling in sheet bar menu

---

packages/sheets-ui/src/views/defined-name/DefinedNameInput.tsx
packages/sheets-ui/src/views/defined-name/index.module.less

close https://github.com/dream-num/univer-pro/issues/1352

chore: fix style of defined name input padding and margin

---

packages/docs-thread-comment-ui/src/commands/commands/add-doc-comment.command.ts
packages/docs-thread-comment-ui/src/controllers/render-controllers/render.controller.ts
packages/sheets-thread-comment-base/src/controllers/sheets-thread-comment-ref-range.controller.ts
packages/sheets-thread-comment-base/src/models/sheets-thread-comment.model.ts
packages/sheets-thread-comment/src/controllers/sheets-thread-comment-remove.controller.ts
packages/thread-comment-ui/src/views/thread-comment-panel/index.tsx
packages/thread-comment-ui/src/views/thread-comment-tree/index.tsx
packages/thread-comment/src/commands/commands/comment.command.ts
packages/thread-comment/src/controllers/tc-resource.controller.ts
packages/thread-comment/src/models/thread-comment.model.ts
packages/thread-comment/src/services/tc-datasource.service.ts

close https://github.com/dream-num/univer-pro/issues/2981

fix(docs-thread-comment-ui): doc comment ot

---

packages-experimental/uni-formula-ui/src/controllers/doc-formula-input.controller.ts
packages/docs-ui/src/services/doc-event-manager.service.ts
packages/sheets-hyper-link-ui/src/controllers/menu.ts
packages/sheets-hyper-link-ui/src/controllers/popup.controller.ts
packages/sheets-ui/src/services/editor-bridge.service.ts

fix(sheets-ui): lag when editing

---

packages/engine-render/src/components/docs/layout/shaping-engine/font-library.ts

fix(docs): undefined error when call permission query

---

packages/sheets-ui/src/views/permission/panel-list/index.tsx

chore: update some styles

---

packages/core/src/services/permission/permission.service.ts
packages/core/src/services/permission/type.ts
packages/facade/src/apis/sheets/f-permission.ts
packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-base.controller.ts

chore: update permission ui adjust position

---

packages/sheets-ui/src/controllers/menu/insert.menu.ts

chore: reset insert menu

---

packages/engine-formula/src/functions/__tests__/nested-functions.spec.ts
packages/engine-formula/src/functions/lookup/vlookup/__tests__/index.spec.ts
packages/engine-formula/src/functions/lookup/vlookup/index.ts
packages/engine-formula/src/functions/lookup/xlookup/__tests__/index.spec.ts
packages/engine-formula/src/functions/lookup/xlookup/index.ts

close https://github.com/dream-num/univer-pro/issues/2998
close https://github.com/dream-num/univer-pro/issues/2913

fix(formula): fix lookup related bugs

---

packages/sheets-ui/src/controllers/editor/editing.render-controller.ts

close https://github.com/dream-num/univer-pro/issues/3002

fix(sheets-ui): can't quit editor after enter '='

---

packages/engine-formula/src/functions/math/sumif/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/sumif/index.ts

close #3772
第一个参数和第三个参数维度不同，可以测几个case看一下
现在有个问题：第三个参数会扩展到和第一个参数范围相同，但扩展的范围内单元格值改变，因这个单元格不在公式参数选区范围内，不会触发公式的重新计算，现在google和飞书是这样的，但excel和葡萄城可以触发，所以这点待后面看怎么处理

fix(formula): fix sumif formula range and sumRange different dimensions

---

packages/design/src/components/form-layout/FormLayout.tsx
packages/design/src/components/form-layout/index.module.less
packages/design/src/components/mentions/index.module.less

feat(design): component style optimize

---

packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts

feat: func addFloatDomToPosition may not execute command

---

.vscode/settings.json
packages/core/src/docs/data-model/text-x/__tests__/apply.spec.ts
packages/docs-ui/src/services/doc-state-change-manager.service.ts

feat(doc): add more apply test case

---

packages/engine-render/src/shape/shape.ts
packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts
packages/ui/src/views/components/dom/FloatDom.tsx

- fix float dom inner size, it should smaller than wrapper

fix(drawing): fix inner dom position

---

examples/src/sheets/worker.ts

chore: temply remove filter ui from worker

---

packages/core/src/docs/data-model/text-x/__tests__/action-iterator.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/apply.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/compose.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/invert.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/text-x.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/transform-position.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/transform.spec.ts
packages/core/src/docs/data-model/text-x/action-types.ts
packages/core/src/docs/data-model/text-x/build-utils/paragraph.ts
packages/core/src/docs/data-model/text-x/build-utils/selection.ts
packages/core/src/docs/data-model/text-x/build-utils/text-x-utils.ts
packages/core/src/docs/data-model/text-x/text-x.ts
packages/docs-drawing-ui/src/commands/commands/insert-doc-drawing.command.ts
packages/docs-drawing-ui/src/commands/commands/remove-doc-drawing.command.ts
packages/docs-drawing-ui/src/commands/commands/update-doc-drawing.command.ts
packages/docs-ui/src/basics/custom-decoration-factory.ts
packages/docs-ui/src/commands/commands/clipboard.inner.command.ts
packages/docs-ui/src/commands/commands/core-editing.command.ts
packages/docs-ui/src/commands/commands/doc-delete.command.ts
packages/docs-ui/src/commands/commands/doc-paragraph-setting.command.ts
packages/docs-ui/src/commands/commands/ime-input.command.ts
packages/docs-ui/src/commands/commands/inline-format.command.ts
packages/docs-ui/src/commands/commands/list.command.ts
packages/docs-ui/src/commands/commands/paragraph-align.command.ts
packages/docs-ui/src/commands/commands/replace-content.command.ts
packages/docs-ui/src/commands/commands/table/doc-table-create.command.ts
packages/docs-ui/src/commands/commands/table/doc-table-delete.command.ts
packages/docs-ui/src/commands/commands/table/doc-table-insert.command.ts

refactor: remove segmentId and line etc in action type

---

packages/core/src/docs/data-model/text-x/__tests__/compose.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/transform-paragraph.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/transform-textrun.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/transform.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/utils.spec.ts
packages/core/src/docs/data-model/text-x/action-iterator.ts
packages/core/src/docs/data-model/text-x/apply-utils/update-apply.ts
packages/core/src/docs/data-model/text-x/text-x.ts
packages/core/src/docs/data-model/text-x/transform-utils.ts
packages/core/src/docs/data-model/text-x/utils.ts
packages/core/src/shared/command-enum.ts

refactor: transform in body

---

common/shared/vite/build-pkg.js
common/shared/vite/index.js
packages/docs-ui/package.json
packages/engine-formula/package.json
packages/sheets-crosshair-highlight/package.json
packages/sheets-data-validation/package.json
packages/sheets-drawing-ui/package.json
packages/sheets-filter/package.json
packages/sheets-formula/package.json
packages/sheets-hyper-link-ui/package.json
packages/sheets-hyper-link/package.json
packages/sheets-numfmt/package.json
packages/sheets-thread-comment/package.json
packages/sheets-ui/package.json
packages/sheets/package.json
packages/ui/package.json
packages/watermark/package.json

chore: fix d.ts files

---

packages/docs-ui/src/controllers/menu/menu.ts

close https://github.com/dream-num/univer-pro/issues/2983

fix: hide align menus in zen mode

---

common/shared/vite/auto-externalize-dependency-plugin.js

build: fix the issue of some CSS not being extracted

---

packages/docs-ui/src/basics/selection.ts
packages/docs-ui/src/commands/commands/doc-header-footer.command.ts
packages/docs-ui/src/controllers/render-controllers/doc-selection-render.controller.ts

close https://github.com/dream-num/univer-pro/issues/2965

fix: change mode set cursor

---

packages/sheets-formula-ui/src/controllers/prompt.controller.ts
packages/sheets-formula-ui/src/views/formula-editor/hooks/useSheetSelectionChange.ts

close #https://github.com/dream-num/univer-pro/issues/3093

fix(editor): formula ref selection moving not work

---

packages/sheets/src/services/permission/worksheet-permission/worksheet-permission.service.ts

chore: add permission logs

---

packages/sheets-drawing-ui/src/commands/commands/insert-sheet-drawing.command.ts
packages/sheets-drawing-ui/src/commands/commands/remove-sheet-drawing.command.ts
packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts

refactor: drawing commands support interceptors

---

packages/core/src/shared/__tests__/array-search.spec.ts
packages/core/src/shared/__tests__/search-array.spec.ts
packages/core/src/shared/array-search.ts
packages/engine-render/src/components/sheets/sheet-skeleton.ts
packages/engine-render/src/components/sheets/spreadsheet.ts
packages/sheets-ui/src/controllers/render-controllers/mobile/mobile-scroll.render-controller.ts
packages/sheets-ui/src/controllers/render-controllers/scroll.render-controller.ts
packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts
packages/sheets-ui/src/controllers/utils/component-tools.ts
packages/sheets-ui/src/services/selection/base-selection-render.service.ts

close https://github.com/dream-num/univer-pro/issues/2810
Modified the searchArray implementation to only return indices within the array. It will not return -1 or infinity.
searchArray implemention changed

fix: searcharray

---

packages/core/src/docs/data-model/text-x/text-x.ts
packages/docs-ui/src/commands/commands/table/doc-table-create.command.ts

refactor: always insert a paragraph before table

---

packages/sheets-formula-ui/src/views/formula-editor/hooks/useHighlight.ts
packages/sheets-formula-ui/src/views/formula-editor/hooks/useSheetSelectionChange.ts
packages/sheets-formula-ui/src/views/formula-editor/index.tsx
packages/sheets-formula-ui/src/views/range-selector/hooks/useSwitchSheet.ts
packages/sheets-formula-ui/src/views/range-selector/index.tsx
packages/sheets-formula-ui/src/views/range-selector/utils/unitRangesToText.ts
packages/sheets-ui/src/views/defined-name/DefinedNameInput.tsx

feat(formua-editor): support cross sheet references

---

packages/docs-ui/src/controllers/menu/context-menu.ts
packages/docs-ui/src/controllers/menu/menu.ts

close https://github.com/dream-num/univer-pro/issues/2951

fix(docs): table context menu disable status

---

packages/docs-ui/src/commands/commands/break-line.command.ts

close https://github.com/dream-num/univer-pro/issues/3099

fix(docs-ui): select all and delete then enter bug

---

packages/docs-ui/src/commands/commands/table/doc-table-create.command.ts

close https://github.com/dream-num/univer-pro/issues/3101

fix(docs-ui): init table style by the cutsor position

---

packages/docs-ui/src/commands/commands/inline-format.command.ts

close https://github.com/dream-num/univer-pro/issues/3101 场景1
close https://github.com/dream-num/univer-pro/issues/2788

fix(docs-ui): set table cell style

---

packages/docs-ui/src/controllers/menu/menu.ts

close https://github.com/dream-num/univer-pro/issues/2503

fix(docs-ui): wrong font size in menu show

---

packages/core/src/docs/data-model/text-x/build-utils/text-x-utils.ts

fix(docs): modify link

---

packages/core/src/docs/data-model/text-x/__tests__/apply.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/transform.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/utils.spec.ts
packages/core/src/docs/data-model/text-x/apply-utils/common.ts
packages/core/src/docs/data-model/text-x/transform-utils.ts
packages/core/src/docs/data-model/text-x/utils.ts

close https://github.com/dream-num/univer-pro/issues/2868

fix(docs): reserve empty textRuns when transform

---

packages/docs-ui/src/views/paragraph-setting/index.tsx

close https://github.com/dream-num/univer-pro/issues/2607
close #xxx

fix(doc): the paragraph panel is not updated in real time

---

packages/core/src/types/interfaces/i-document-data.ts

feat: add zeroWidthParagraphBreak config

---

packages/docs-ui/src/controllers/menu/menu.ts

close https://github.com/dream-num/univer-pro/issues/3131
close https://github.com/dream-num/univer-pro/issues/2959

fix(docs-ui): hide header footer menu when modern mode

---

mockdata/src/docs/default-document-data-cn.ts
packages/engine-render/src/components/docs/layout/block/paragraph/linebreaking.ts
packages/engine-render/src/components/docs/layout/block/paragraph/shaping.ts

feat: add zero width paragraph break implementation

---

packages/core/src/sheets/util.ts
packages/engine-render/src/components/sheets/util.ts

close https://github.com/dream-num/univer-pro/issues/3143

fix: destructuring assignment does not take effect for null

---

packages/docs-ui/src/controllers/menu/menu.ts

close https://github.com/dream-num/univer-pro/issues/3148

fix: hide table and header footer menu in ZEN mode

---

packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts

fix(chart): add chart wrapper border radius

---

packages/sheets-formula-ui/src/views/formula-editor/hooks/useHighlight.ts
packages/sheets-formula-ui/src/views/range-selector/hooks/useHighlight.ts

close https://github.com/dream-num/univer-pro/issues/3042
close #xxx

fix(editor): the cursor position is not correct after pasting

---

packages/sheets-ui/src/common/utils.ts

close https://github.com/dream-num/univer-pro/issues/3046

fix: empty strings should be treated as having no value when merge

---

packages/design/src/components/input-number/InputNumber.tsx

- add blur event to input  number

fix(design): add blur to input number

---

packages/sheets-ui/src/controllers/clipboard/utils.ts

close https://github.com/dream-num/univer-pro/issues/2740

fix: links pasted into cells require paragraph attributes

---

packages/sheets-filter-ui/src/views/components/index.module.less

chore: fix width in value panel

---

packages/engine-formula/src/engine/analysis/__tests__/create-command-test-bed.ts
packages/engine-formula/src/engine/ast-node/function-node.ts
packages/engine-formula/src/functions/__tests__/create-function-test-bed.ts
packages/engine-formula/src/functions/base-function.ts
packages/engine-formula/src/functions/lookup/formulatext/__tests__/index.spec.ts
packages/engine-formula/src/functions/lookup/formulatext/index.ts
packages/engine-formula/src/functions/lookup/function-map.ts
packages/sheets-formula-ui/src/locale/function-list/lookup/en-US.ts
packages/sheets-formula-ui/src/locale/function-list/lookup/ja-JP.ts
packages/sheets-formula-ui/src/locale/function-list/lookup/vi-VN.ts
packages/sheets-formula-ui/src/locale/function-list/lookup/zh-CN.ts
packages/sheets-formula-ui/src/locale/function-list/lookup/zh-TW.ts
packages/sheets-formula/src/services/function-list/lookup.ts

feat(formula): supplement FORMULATEXT formula

---

packages/docs-ui/src/controllers/doc-header-footer.controller.ts

close https://github.com/dream-num/univer-pro/issues/2966

fix(docs): header footer render after switch from modern mode to traditional model

---

packages/sheets-data-validation-ui/src/views/components/formula-input/list-formula-input.tsx
packages/sheets-data-validation-ui/src/views/components/list-dropdown/index.tsx

fix(sheets-data-validation-ui): data validation style

---

packages/docs-ui/src/services/selection/convert-rect-range.ts
packages/docs-ui/src/services/selection/doc-selection-render.service.ts
packages/docs-ui/src/services/selection/selection-utils.ts

close https://github.com/dream-num/univer-pro/issues/3150

fix(docs-ui): selection in table when across two pages

---

packages/core/src/services/context/context.ts
packages/sheets-drawing-ui/src/controllers/shortcuts/drawing.shortcut.ts

feat: add focusing-editor context value for chart panel

---

packages/engine-render/src/components/docs/layout/block/paragraph/line-adjustment.ts
packages/engine-render/src/components/docs/layout/block/section.ts
packages/engine-render/src/components/docs/layout/block/table.ts

close https://github.com/dream-num/univer-pro/issues/2930

fix(render-engine): paragraph horizontal align

---

common/shared/vite/utils.ts
packages/docs-ui/src/facade/f-document.ts
packages/engine-formula/src/facade/f-formula.ts
packages/sheets-crosshair-highlight/src/facade/f-univer.ts
packages/sheets-data-validation/src/facade/f-data-validation.ts
packages/sheets-data-validation/src/facade/f-range.ts
packages/sheets-data-validation/src/facade/f-workbook.ts
packages/sheets-data-validation/src/facade/f-worksheet.ts
packages/sheets-drawing-ui/src/facade/f-worksheet.ts
packages/sheets-filter/src/facade/f-filter.ts
packages/sheets-filter/src/facade/f-range.ts
packages/sheets-filter/src/facade/f-worksheet.ts
packages/sheets-formula/src/facade/f-formula.ts
packages/sheets-formula/src/facade/f-univer.ts
packages/sheets-hyper-link-ui/src/facade/f-workbook.ts
packages/sheets-hyper-link/src/facade/f-range.ts
packages/sheets-hyper-link/src/facade/f-workbook.ts
packages/sheets-numfmt/src/facade/f-range.ts
packages/sheets-thread-comment/src/facade/f-range.ts
packages/sheets-thread-comment/src/facade/f-thread-comment.ts
packages/sheets-thread-comment/src/facade/f-worksheet.ts
packages/sheets-ui/src/facade/f-range.ts
packages/sheets-ui/src/facade/f-sheet-hooks.ts
packages/sheets-ui/src/facade/f-univer.ts
packages/sheets/src/facade/f-range.ts
packages/sheets/src/facade/f-workbook.ts
packages/sheets/src/facade/f-worksheet.ts
packages/ui/src/facade/f-hooks.ts
packages/ui/src/facade/f-univer.ts
packages/watermark/src/facade/f-univer.ts

Resolve the issue of the unavailability of the Facade API in the built product
in /src/facade/**/*.ts
```diff
-import '../'
+import '@univerjs/pkg-name'
```
close #xxx

chore(build): fix facade API in the built product

---

packages/docs/src/utils/custom-range-factory.ts
packages/docs/src/utils/replace-selection-factory.ts
packages/sheets-filter/src/commands/commands/sheets-filter.command.ts
packages/sheets/src/commands/mutations/reorder-range.mutation.ts
packages/sheets/src/services/permission/util.ts
packages/ui/src/services/sidebar/hooks/useSidebarClick.ts

chore: fix package self import

---

packages/engine-formula/src/basics/inverted-index-cache.ts
packages/engine-formula/src/engine/value-object/__tests__/array-inverted-index-cache.spec.ts
packages/engine-formula/src/engine/value-object/array-value-object.ts

fix(formula): fix inverted-index-cache bug

---

packages/engine-formula/src/engine/value-object/__tests__/array-inverted-index-cache2.spec.ts

test(formula): supplement inverted-index-cache test

---

packages/core/src/index.ts
packages/core/src/shared/tools.ts
packages/engine-formula/src/plugin.ts
packages/sheets-formula-ui/src/sheets-formula-ui.plugin.ts
packages/sheets-formula/src/sheets-formula.plugin.ts

fix(formula): calculate after renderer

---

packages/sheets-formula/src/controllers/utils/ref-range-formula.ts

close https://github.com/dream-num/univer-pro/issues/2436

fix(formula): fix formula update operation

---

packages/sheets-formula-ui/src/views/range-selector/index.tsx

fix(range-selector): focus after confirm

---

packages/data-validation/src/validators/base-data-validator.ts
packages/sheets-data-validation-ui/src/controllers/dv-alert.controller.ts
packages/sheets-data-validation-ui/src/controllers/dv-reject-input.controller.ts
packages/sheets-data-validation-ui/src/views/components/date-dropdown/index.tsx
packages/sheets-data-validation/src/controllers/dv-formula-ref-range.controller.ts
packages/sheets-data-validation/src/models/sheet-data-validation-model.ts
packages/sheets-data-validation/src/validators/const.ts
packages/sheets-data-validation/src/validators/custom-validator.ts
packages/sheets-data-validation/src/validators/date-validator.ts
packages/sheets-data-validation/src/validators/decimal-validator.ts
packages/sheets-data-validation/src/validators/text-length-validator.ts
packages/sheets-data-validation/src/validators/util.ts
packages/sheets-data-validation/src/validators/whole-validator.ts

feat(sheets-data-validation): optimize data-validation error msg

---

packages/docs-ui/src/components/range-selector/RangeSelector.tsx

feat: reangeSelector supports className

---

README-ja.md
README-zh.md
README.md

docs: update zen-editor link

---

packages/sheets-data-validation-ui/src/views/widgets/checkbox-widget.ts
packages/sheets-data-validation-ui/src/views/widgets/dropdown-multiple-widget.ts
packages/sheets-data-validation-ui/src/views/widgets/dropdown-widget.ts
packages/sheets-ui/src/controllers/cell-custom-render.controller.ts

feat(sheets-data-validation): data validation hover optimize

---

packages/engine-formula/src/engine/ast-node/function-node.ts
packages/engine-formula/src/functions/base-function.ts
packages/engine-formula/src/functions/math/randarray/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/randarray/index.ts
packages/engine-formula/src/functions/math/sequence/__tests__/index.spec.ts
packages/engine-formula/src/functions/math/sequence/index.ts
packages/engine-formula/src/services/current-data.service.ts

fix(formula): fix formula rows and columns limit

---

common/shared/vite/index.ts

chore: add locale dts files

---

packages-experimental/uni-formula-ui/src/uni-formula-ui.plugin.ts
packages-experimental/uniui/src/plugin.ts
packages-experimental/uniui/src/views/uni-toolbar/UniFloatToolbar.tsx
packages-experimental/uniui/src/views/uni-toolbar/UniToolbar.tsx

fix(uni): uni toolbar init

---

packages/sheets-formula/package.json

chore(sheets-formula): fix exports

---

packages/sheets-data-validation-ui/src/views/components/formula-input/custom-formula-input.tsx
packages/sheets-data-validation-ui/src/views/components/formula-input/list-formula-input.tsx
packages/sheets-hyper-link/src/commands/commands/update-hyper-link.command.ts

fix(sheets-hyper-link): update hyper link fail

---

packages/core/src/services/command/command.service.ts

docs(core): fix comments

---

packages/engine-render/src/components/docs/layout/hyphenation/hyphen.ts

fix(docs-ui): load lang error

---

common/shared/vite/utils.ts

chore: update generation rules for globalName in UMD builds

---

packages/core/src/docs/data-model/text-x/__tests__/apply-consistency.spec.ts
packages/core/src/docs/data-model/text-x/__tests__/delete-apply.spec.ts
packages/core/src/docs/data-model/text-x/apply-utils/common.ts
packages/core/src/docs/data-model/text-x/apply-utils/update-apply.ts
packages/core/src/shared/__tests__/doc-tool.spec.ts
packages/core/src/shared/doc-tool.ts

fix: delete apply

---

packages/docs-ui/src/index.ts
packages/sheets-hyper-link-ui/src/services/popup.service.ts

fix(sheets-hyper-link): sheet link popup should attach to cell editor

---

packages/design/src/components/tree/index.module.less

close https://github.com/dream-num/univer-pro/issues/3303

chore: change tree selected item color

---

packages/sheets-formula/src/services/register-other-formula.service.ts

fix(sheets-formula): should register other formula on steady

---

packages/sheets/src/services/selections/selection-data-model.ts

chore: type fix

---

packages/core/package.json
packages/data-validation/package.json
packages/sheets-conditional-formatting-ui/package.json
packages/sheets-conditional-formatting/package.json
packages/sheets-data-validation-ui/package.json
packages/sheets-data-validation/package.json
packages/sheets-find-replace/package.json
packages/sheets-hyper-link/package.json
packages/sheets-ui/package.json
packages/sheets/package.json
packages/thread-comment-ui/package.json
packages/thread-comment/package.json
packages/uniscript/package.json
pnpm-lock.yaml

chore(protocol): update protocol to 0.1.39-alpha.45

---

packages/core/src/shared/dayjs.ts

fix(core): add missing localizedFormat plugin support for dayjs

---

packages/docs-ui/src/commands/commands/inline-format.command.ts
packages/docs-ui/src/controllers/menu/menu.ts

fix(docs): inline format in table

---

packages/sheets-ui/src/controllers/menu/gridlines.menu.ts

fix(sheets-ui): gridlines permission

---

.release-it.json
packages-experimental/action-recorder/package.json

chore(action-recorder): add publish action-recorder pkg

---

packages/sheets-ui/src/controllers/utils/range-tools.ts

fix(sheet): maximum call stack

---

packages/engine-render/src/components/sheets/sheet-component.ts
packages/engine-render/src/components/sheets/spreadsheet.ts
packages/engine-render/src/scene.transformer.ts
packages/engine-render/src/scene.ts

- adjust drawing bounds in sheet viewport

fix(drawing): set drawing bounding in left/top to A1 cell
