packages/core/src/facade/f-univer.ts
=> feat(facade): export syncExecuteCommand

packages/core/src/docs/data-model/text-x/build-utils/text-x-utils.ts, packages/core/src/sheets/util.ts, packages/docs-hyper-link-ui/src/commands/commands/add-link.command.ts, packages/docs-hyper-link-ui/src/commands/operations/popup.operation.ts, packages/docs-hyper-link-ui/src/controllers/menu.ts, packages/docs-hyper-link-ui/src/services/hyper-link-popup.service.ts, packages/docs/src/utils/custom-range-factory.ts, packages/sheets-hyper-link-ui/src/controllers/popup.controller.ts, packages/sheets-hyper-link-ui/src/utils/index.ts, packages/sheets-hyper-link/src/commands/commands/add-hyper-link.command.ts
close https://github.com/dream-num/univer-pro/issues/3354
=> feat(docs-link): support acrossing-paragraph add link

packages/sheets-ui/src/index.ts
close https://github.com/dream-num/univer/issues/4017
=> chore: export SheetScrollManagerService

packages/engine-render/src/basics/scroll-xy.ts, packages/engine-render/src/scroll-timer.ts
=> chore: scroll timer type fix

packages/sheets-formula-ui/src/controllers/__tests__/update-formula.controller.spec.ts, packages/sheets-formula/src/controllers/trigger-calculation.controller.ts, packages/sheets-formula/src/controllers/utils/ref-range-formula.ts
1. Write a formula `=SUM(Sheet1!A1:A3)` in Sheet2
2. Delete the second row in Sheet1
3. Expected: The formula in Sheet2 is updated to `=SUM(Sheet1!A1:A2)`
=> fix(formula): update formula string in other sheet

packages/docs-ui/src/services/clipboard/html-to-udm/converter.ts, packages/docs-ui/src/services/clipboard/udm-to-html/convertor.ts
=> fix(doc): bad image path when parsing clipboard HTML

packages/ui/src/common/component-manager.ts, packages/ui/src/facade/f-univer.ts
=> feat(facade): add component api

packages/core/src/sheets/typedef.ts, packages/core/src/types/interfaces/i-cell-custom-render.ts, packages/sheets-data-validation-ui/src/controllers/dv-alert.controller.ts, packages/sheets-data-validation-ui/src/controllers/dv-render.controller.ts, packages/sheets-data-validation-ui/src/views/components/date-dropdown/index.tsx, packages/sheets-data-validation-ui/src/views/components/drop-down/CellDropdown.tsx, packages/sheets-data-validation-ui/src/views/components/list-dropdown/index.tsx, packages/sheets-data-validation-ui/src/views/widgets/checkbox-widget.ts, packages/sheets-data-validation-ui/src/views/widgets/dropdown-multiple-widget.ts, packages/sheets-data-validation-ui/src/views/widgets/dropdown-widget.ts, packages/sheets-data-validation/src/commands/commands/data-validation.command.ts, packages/sheets-data-validation/src/facade/f-workbook.ts, packages/sheets-data-validation/src/facade/f-worksheet.ts, packages/sheets-data-validation/src/index.ts, packages/sheets-data-validation/src/models/sheet-data-validation-model.ts, packages/sheets-data-validation/src/services/dv-cache.service.ts, packages/sheets-data-validation/src/services/dv-validator-service.ts, packages/sheets-hyper-link-ui/package.json, packages/sheets-hyper-link-ui/src/controllers/menu.ts, packages/sheets-hyper-link-ui/src/utils/index.ts, packages/sheets-ui/src/services/canvas-pop-manager.service.ts, packages/ui/src/views/components/popup/CanvasPopup.tsx, pnpm-lock.yaml
=> feat(sheets-data-validation): optimize data validation memory usage

packages/sheets-hyper-link/src/commands/mutations/update-hyper-link.mutation.ts, packages/sheets-hyper-link/src/controllers/rich-text-ref-range.controller.ts, packages/sheets-hyper-link/src/controllers/sheet-hyper-link.controller.ts, packages/sheets/src/commands/commands/insert-range-move-down.command.ts
=> fix(sheets-hyper-link-ui): link ref -range

examples/src/docs/main.ts, packages/docs-ui/src/services/selection/selection-utils.ts
close https://github.com/dream-num/univer-pro/issues/3437
=> fix: selection before table

packages/docs-ui/src/services/selection/doc-selection-render.service.ts
=> fix: doc text selection begin from list marker

packages/engine-formula/src/basics/date.ts, packages/engine-formula/src/functions/date/networkdays-intl/__tests__/index.spec.ts
=> fix(formula): fix networkdays.intl

packages/docs-ui/src/services/selection/selection-utils.ts
=> fix(docs-ui): cursor valished at paragraph beginning

mockdata/src/docs/default-document-data-cn.ts, packages/core/src/docs/data-model/empty-snapshot.ts
=> fix: optimization of create empty doc

packages/rpc/src/services/rpc/channel.service.ts, packages/rpc/src/services/rpc/rpc.service.ts
=> fix: fix client may miss the INITIALIZE event

packages/core/src/docs/data-model/preset-list-type.ts, packages/core/src/types/interfaces/i-document-data.ts, packages/engine-render/src/components/docs/layout/block/paragraph/bullet-ruler.ts, packages/engine-render/src/components/docs/layout/model/glyph.ts
=> fix: dup list glyph type name

packages/facade/src/apis/__tests__/create-test-bed.ts, packages/facade/src/apis/sheets/__tests__/create-worksheet-test-bed.ts, packages/sheets-conditional-formatting-ui/src/controllers/cf.auto-fill.controller.ts, packages/sheets-conditional-formatting-ui/src/controllers/cf.copy-paste.controller.ts, packages/sheets-conditional-formatting-ui/src/controllers/cf.painter.controller.ts, packages/sheets-conditional-formatting-ui/src/controllers/cf.render.controller.ts, packages/sheets-conditional-formatting-ui/src/controllers/cf.viewport.controller.ts, packages/sheets-conditional-formatting/src/index.ts, packages/sheets-conditional-formatting/src/models/calculate-unit-v2/__test__/test.util.ts, packages/sheets-conditional-formatting/src/models/calculate-unit-v2/utils.ts, packages/sheets-conditional-formatting/src/models/conditional-formatting-view-model.ts, packages/sheets-conditional-formatting/src/plugin.ts, packages/sheets-conditional-formatting/src/services/conditional-formatting.service.ts
=> fix(conditional-formatting): fix type

packages-experimental/uni-docs-ui/src/controllers/menu.schema.ts, packages-experimental/uni-docs-ui/src/controllers/uni-docs-ui.controller.tsx, packages-experimental/uni-sheets-ui/src/controllers/menu.schema.ts, packages-experimental/uni-sheets-ui/src/controllers/uni-sheets-ui.controller.tsx, packages-experimental/uni-slides-ui/src/controllers/menu.schema.ts, packages-experimental/uni-slides-ui/src/controllers/uni-slides-ui.controller.tsx, packages-experimental/uniui/src/controllers/menu.schema.ts, packages/docs-drawing-ui/src/controllers/menu.schema.ts, packages/docs-drawing-ui/src/index.ts, packages/docs-drawing-ui/src/views/menu/image.menu.ts, packages/docs-ui/src/index.ts, packages/sheets-drawing-ui/src/controllers/menu.schema.ts, packages/sheets-drawing-ui/src/index.ts, packages/sheets-drawing-ui/src/views/menu/image.menu.ts, packages/sheets-ui/src/index.ts, packages/slides-ui/src/controllers/image.menu.ts, packages/slides-ui/src/controllers/menu.schema.ts, packages/slides-ui/src/index.ts, packages/ui/src/index.ts
=> refactor(uni)!: rename image menu id and IMenuSchema

packages/ui/src/views/components/zen-zone/ZenZone.tsx, packages/ui/src/views/workbench/Workbench.tsx
=> feat: remove zen-zone sidebar

.gitignore, common/shared/package.json, packages/core/package.json, packages/core/src/services/image-io/image-io.service.ts, packages/data-validation/package.json, packages/sheets-data-validation/package.json, packages/sheets-hyper-link/package.json, packages/sheets-ui/package.json, packages/sheets/package.json, packages/thread-comment/package.json, pnpm-lock.yaml
=> chore: prepare for release 0.5.1

examples/esbuild.config.ts
=> chore: optimize startup performance during development

packages/sheets-drawing-ui/src/plugin.ts
=> fix(sheets-drawing-ui): add missing `DocsDrawingController` dependency

packages/facade/src/apis/sheets/__tests__/f-range.spec.ts, packages/sheets-numfmt/src/facade/f-range.ts
=> fix(facade): fix setNumberFormat facade

packages/engine-formula/src/engine/utils/value-object.ts, packages/engine-formula/src/functions/__tests__/nested-functions.spec.ts, packages/engine-formula/src/functions/math/sumif/index.ts, packages/engine-formula/src/functions/math/sumifs/index.ts, packages/engine-formula/src/functions/statistical/averageif/index.ts, packages/engine-formula/src/functions/statistical/countif/index.ts
=> fix(formula): fix compare of range and criteria in related formulas

packages/sheets-data-validation-ui/src/controllers/dv-alert.controller.ts, packages/sheets-ui/src/facade/__tests__/f-sheet-hooks.spec.ts, packages/sheets-ui/src/services/cell-alert-manager.service.ts, packages/sheets-ui/src/services/hover-manager.service.ts
=> fix(sheets-ui): hover-manager-service memory leak

examples/src/mobile-s/main.ts, examples/src/sheets/main.ts, examples/src/uni/main.ts, packages/core/src/shared/lifecycle.ts, packages/core/src/univer.ts
=> fix(examples): fix external worker not terminated on Univer disposing

packages/sheets/src/commands/commands/set-style.command.ts
=> fix(sheets-ui): resolve issue where text color could not be reset

packages/sheets-data-validation/src/commands/commands/data-validation.command.ts, packages/sheets-hyper-link-ui/src/services/popup.service.ts, packages/sheets-hyper-link/src/commands/commands/add-hyper-link.command.ts, packages/sheets-ui/src/services/hover-manager.service.ts, packages/sheets-ui/src/services/utils/doc-skeleton-util.ts, packages/ui/src/views/components/popup/RectPopup.tsx
close https://github.com/dream-num/univer-pro/issues/3626
close https://github.com/dream-num/univer-pro/issues/3592
close https://github.com/dream-num/univer-pro/issues/3162
close https://github.com/dream-num/univer-pro/issues/3120
close https://github.com/dream-num/univer-pro/issues/3112
close https://github.com/dream-num/univer-pro/issues/3097
close https://github.com/dream-num/univer-pro/issues/3121
close https://github.com/dream-num/univer-pro/issues/3633
=> fix(sheets-hyper-link-ui): number link popup hover position error

packages/engine-formula/src/engine/dependency/dependency-tree.ts, packages/engine-formula/src/engine/dependency/formula-dependency.ts, packages/engine-formula/src/functions/lookup/choose/index.ts
=> fix(formula): indirect dependency

packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts
- support custom chart backgroud
=> fix(drawing): chart can custom backgroud

examples-node/package.json, examples-node/src/sdk/facade.ts, pnpm-lock.yaml
=> chore: add missing facade API import in examples-node

packages/network/src/plugin.ts, packages/network/src/services/web-socket/web-socket.service.ts, packages/sheets/src/facade/f-univer.ts
=> fix: fix facade API not implemented

e2e/visual-comparison/sheets/sheets-visual-comparison.spec.ts
=> fix: sheet e2e too long

packages/sheets-ui/src/commands/commands/add-worksheet-merge.command.ts, packages/sheets/src/commands/commands/add-worksheet-merge.command.ts, packages/sheets/src/facade/f-range.ts
=> chore: add params to resolve confirm dialog show

packages/rpc/src/services/rpc/__tests__/rpc.service.spec.ts, packages/rpc/src/services/rpc/rpc.service.ts
=> fix: rpc support multiple params

packages/sheets-data-validation/src/facade/f-data-validation-builder.ts, packages/sheets-data-validation/src/facade/f-data-validation.ts
=> feat(facade): update data validation facade

packages/sheets-formula-ui/src/controllers/__tests__/create-command-test-bed.ts, packages/sheets-formula-ui/src/controllers/__tests__/formula-auto-fill.controller.spec.ts, packages/sheets-formula-ui/src/controllers/formula-auto-fill.controller.ts
Match Excel xml data format:
The formula fills upwards, and the cell containing f and si must be at the top. 
The formula fills leftwards, and the cell containing f and si must be at the left.
=> fix(formula): formula auto fill up

packages/engine-formula/src/basics/common.ts, packages/engine-formula/src/controller/calculate.controller.ts, packages/engine-formula/src/controller/config.schema.ts, packages/engine-formula/src/facade/f-formula.ts, packages/engine-formula/src/index.ts, packages/engine-formula/src/services/calculate-formula.service.ts, packages/engine-formula/src/services/current-data.service.ts, packages/sheets-formula/src/controllers/trigger-calculation.controller.ts, packages/sheets/src/facade/f-workbook.ts
=> feat(sheet): add facade api

e2e/e2e.d.ts, e2e/memory/memory.spec.ts, e2e/memory/util.ts, examples/src/sheets/very-lazy.ts, packages/sheets-ui/src/facade/f-univer.ts, packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/utils/slide-tab-bar.ts, packages/uniscript/src/services/script-editor.service.ts, playwright.config.ts
=> fix: fix last memory leak and make memory CI more strict

packages/sheets-hyper-link/src/commands/commands/remove-hyper-link.command.ts, packages/sheets-hyper-link/src/commands/commands/update-hyper-link.command.ts
=> fix(facade): fix hyperlink update and remove command

packages/sheets-hyper-link-ui/src/facade/f-workbook.ts, packages/sheets-hyper-link-ui/src/facade/index.ts, packages/sheets-hyper-link/src/facade/f-range.ts
=> fix: fix facade not exported

packages/telemetry/src/services/telemetry-service.ts
=> feat: add methods to telemetry service

packages/sheets/src/facade/f-permission.ts
=> chore: recover delete api

examples/esbuild.config.ts, packages/sheets-hyper-link-ui/src/services/resolver.service.ts, packages/sheets-ui/src/services/selection/selection-control.ts, packages/sheets-ui/src/services/selection/selection-render-model.ts, packages/sheets-ui/src/services/selection/util.ts
close https://github.com/dream-num/univer-pro/issues/3531
=> fix: cell link postion should clear primary

packages/design/src/components/message/Message.tsx
=> fix(ui): if two messages share the same key, the later should replace the earlier

packages/core/package.json, packages/network/src/plugin.ts, pnpm-lock.yaml
=> fix(network): work in ancestor env

packages/sheets-ui/src/commands/commands/set-selection.command.ts, packages/sheets/src/facade/f-range.ts, packages/sheets/src/facade/f-selection.ts, packages/sheets/src/facade/f-worksheet.ts, packages/sheets/src/index.ts, packages/sheets/src/services/__tests__/move-active-cell.spec.ts, packages/sheets/src/services/selections/move-active-cell-util.ts
- fix multiple selection tab not right issue
=> fix(selection): fix multiple selection use tab not right issue

packages/ui/src/facade/f-menu-builder.ts, packages/ui/src/facade/f-univer.ts
=> feat(ui): add URL facade

packages/network/src/services/http/implementations/fetch.ts, packages/network/src/services/http/implementations/xhr.ts, packages/network/src/services/http/interceptors/__tests__/auth-interceptor.spec.ts, packages/network/src/services/http/interceptors/__tests__/retry-interceptor.spec.ts, packages/network/src/services/http/interceptors/__tests__/threshold-interceptor.spec.ts, packages/network/src/services/http/response.ts, packages/sheets-formula/src/services/register-function.service.ts
=> chore: should and request to http error instance

packages/ui/src/views/components/ribbon/Button/ToolbarButton.tsx, packages/ui/src/views/components/ribbon/Button/index.module.less, packages/ui/src/views/components/ribbon/ToolbarItem.tsx
=> feat(ui): support no icon toolbar button

packages/network/src/services/http/implementations/fetch.ts, packages/network/src/services/http/implementations/util.ts, packages/network/src/services/http/implementations/xhr.ts, packages/network/src/services/http/request.ts
=> chore: add network logging

examples/src/sheets/main.ts, examples/uniscripts/vim.js, packages/sheets-ui/src/controllers/shortcuts/selection.shortcut.ts, packages/ui/src/common/lifecycle.ts, packages/ui/src/facade/f-shortcut.ts, packages/ui/src/facade/f-univer.ts, packages/ui/src/services/shortcut/shortcut.service.ts
=> feat(ui): export shortcut facade API

packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
close https://github.com/dream-num/univer-pro/issues/3401
=> fix: fix paste besides border should keep rich text

packages/ui/src/services/parts/parts.service.ts, packages/ui/src/views/mobile-app.module.less, packages/ui/src/views/workbench/Workbench.tsx, packages/ui/src/views/workbench/workbench.module.less
=> feat(sheet): add user header part

packages/sheets/src/facade/f-worksheet.ts
=> fix(facade): calculate the correct number of displayable sheet

packages/sheets-hyper-link/src/commands/commands/remove-hyper-link.command.ts, packages/sheets-hyper-link/src/commands/commands/update-hyper-link.command.ts, packages/sheets-hyper-link/src/facade/f-range.ts
=> fix(sheets-hyper-link): hyper-link-facade

packages/core/src/index.ts, packages/thread-comment/src/index.ts
=> chore(core): add type export

packages/engine-render/src/components/sheets/sheet-skeleton.ts
=> fix: use drawing range not visible range

packages/sheets-ui/src/services/clipboard/clipboard.service.ts
=> fix: copy plain should get cell value

packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
close https://github.com/dream-num/univer-pro/issues/3606
=> fix: fix become rich text when end edit

packages/sheets-ui/src/services/selection/selection-render.service.ts
close https://github.com/dream-num/univer-pro/issues/3799
=> fix: row col selection for merged cell

packages/sheets-ui/src/services/clipboard/clipboard.service.ts
=> chore: revert some fixes

packages-experimental/action-recorder/src/controllers/action-recorder.controller.tsx, packages/sheets-formula-ui/src/controllers/__tests__/formula-auto-fill.controller.spec.ts, packages/sheets-ui/src/commands/commands/__tests__/auto-fill.controller.spec.ts, packages/sheets-ui/src/commands/commands/auto-fill.command.ts, packages/sheets-ui/src/commands/commands/refill.command.ts, packages/sheets-ui/src/controllers/auto-fill.controller.ts, packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-base.controller.ts, packages/sheets-ui/src/services/auto-fill/auto-fill.service.ts
=> refactor: redesign autofill command

.github/CODEOWNERS
=> docs: change Facade API owners

packages/rpc/package.json, packages/rpc/src/services/rpc/__tests__/rpc.service.spec.ts
=> test: add more rpc tests for remote subscription

packages/sheets-ui/src/services/clipboard/html-to-usm/utils.ts
=> fix: only change the style when have ts

packages/rpc/src/services/rpc/__tests__/rpc.service.spec.ts
=> test: add subscription closed test

packages/core/src/facade/f-usermanager.ts, packages/core/src/services/theme/theme.service.ts, packages/sheets-crosshair-highlight/src/views/widgets/crosshair-highlight.render-controller.ts, packages/sheets-formula-ui/src/controllers/prompt.controller.ts, packages/sheets-formula-ui/src/services/render-services/ref-selections.render-service.ts, packages/sheets-formula-ui/src/views/range-selector/hooks/useRefactorEffect.ts, packages/sheets-ui/src/facade/f-workbook.ts, packages/sheets-ui/src/facade/f-worksheet.ts, packages/sheets-ui/src/services/selection/base-selection-render.service.ts, packages/sheets-ui/src/services/selection/mobile-selection-render.service.ts, packages/sheets-ui/src/services/selection/selection-render.service.ts, packages/sheets/src/commands/utils/selection-command-util.ts, packages/sheets/src/facade/f-range.ts, packages/sheets/src/facade/f-worksheet.ts, packages/sheets/src/index.ts, packages/sheets/src/services/selections/index.ts, packages/sheets/src/services/selections/selection.service.ts
close #xxx
Add two more API, transparentSelection & showSelection.
May be more easily to use.
Selection function still works, but you can not see them. 
Users can still edit cells,  select diffrent cells. 
Seleciton functions is not working after previous API "disableSelection"
That means users can not even select different cells.
=> fix:  better disable selection ---> transparent selection

packages/ui/src/services/menu/menu-manager.service.ts
=> fix: update merge logic to create new objects instead of mutating existing ones

packages/sheets-data-validation-ui/src/controllers/dv-alert.controller.ts, packages/sheets-data-validation-ui/src/controllers/dv-render.controller.ts, packages/sheets-data-validation/src/controllers/dv-formula-ref-range.controller.ts, packages/sheets-data-validation/src/controllers/dv-ref-range.controller.ts
=> fix(sheets-data-validation): error relayout on ref-range change

packages/sheets-ui/src/facade/f-workbook.ts, packages/sheets-ui/src/facade/f-worksheet.ts
=> chore: better comments

packages/sheets-data-validation-ui/src/views/components/detail/index.tsx, packages/sheets-data-validation/src/models/rule-matrix.ts
=> fix(sheets-data-validation): data-validation range set error

packages/watermark/src/plugin.ts
=> fix(watermark): fix invalid plugin configuration

packages/ui/src/views/components/ribbon/Ribbon.tsx
=> fix(ui): update animation class condition to improve Ribbon styling

packages/core/package.json, pnpm-lock.yaml
=> chore(core): update redi version

packages/core/src/sheets/typedef.ts, packages/engine-formula/src/basics/is-null-cell.ts, packages/engine-formula/src/engine/reference-object/base-reference-object.ts, packages/engine-formula/src/services/runtime.service.ts
=> fix(formula): use different isNullCell for formula modules

packages/engine-formula/src/functions/date/datevalue/__tests__/index.spec.ts
=> test: update test and hello 2025

packages/core/src/sheets/typedef.ts, packages/engine-render/src/components/sheets/sheet-skeleton.ts, packages/sheets-ui/src/commands/commands/set-scroll.command.ts, packages/sheets-ui/src/commands/operations/scroll.operation.ts, packages/sheets-ui/src/controllers/render-controllers/scroll.render-controller.ts, packages/sheets-ui/src/controllers/sheet-ui.controller.ts, packages/sheets-ui/src/services/scroll-manager.service.ts
close https://github.com/dream-num/univer-pro/issues/3884
scrolling by wheel in no freeze.
scrolling by drag the scrollbar in no freeze.
scrolling by arrow key to change the current cell in no freeze.
scrolling by wheel after freeze.
scrolling by drag the scrollbar after freeze.
scrolling by arrow key to change the current cell after freeze.
TODO
=> fix: vp start sheet view column

packages/sheets-ui/src/services/clipboard/clipboard.service.ts
=> fix: fix snapshot after cut & paste

packages/core/src/sheets/worksheet.ts
=> chore: fix celldata reference

packages/engine-render/src/components/sheets/extensions/font.ts
=> revert: get fontExtension from cache,  revert to worksheet.getCell

packages/sheets-sort/src/facade/f-event.ts, packages/sheets-sort/src/facade/f-range.ts, packages/sheets-sort/src/facade/f-worksheet.ts, packages/sheets-sort/src/facade/index.ts
=> feat(sort)!: optimize sort facade api

packages/core/src/facade/f-enum.ts, packages/core/src/facade/f-event.ts
=> fix(facade): f-event & f-enum extend error

packages/core/src/facade/f-event.ts, packages/sheets-filter/src/facade/f-event.ts
=> fix(sheet): fix spell error

packages/sheets-filter/src/facade/f-event.ts
=> fix: extend feventname

packages/core/src/facade/f-event.ts, packages/core/src/facade/f-univer.ts, packages/sheets-ui/src/facade/f-event.ts, packages/sheets-ui/src/facade/f-univer.ts, packages/sheets-ui/src/facade/index.ts, packages/sheets-ui/src/index.ts, packages/sheets/src/commands/commands/add-worksheet-merge.command.ts, packages/sheets/src/facade/f-permission.ts, packages/sheets/src/facade/f-range.ts, packages/sheets/src/facade/f-worksheet.ts, packages/ui/src/index.ts
=> chore: add clipboard event & merge example

packages/sheets-ui/src/index.ts
=> chore: update export

common/shared/eslint/index.js, eslint.config.js
=> chore: jsdoc only on facade

.vscode/extensions.json
=> chore: add markdownlint as a recommend extension

packages/sheets-ui/src/services/selection/base-selection-render.service.ts, packages/sheets-ui/src/services/selection/selection-render.service.ts, packages/sheets/src/services/selections/selection.service.ts
close https://github.com/dream-num/univer-pro/issues/3763
=> fix: ref selection clear

packages/ui/src/views/components/sidebar/Sidebar.tsx
=> fix: sidebar visible shoule be false when close

packages/design/src/components/color-picker/ColorSpectrum.tsx
=> fix(design): ensure colorpicker trigger onChanged callback on mouseup event

packages/engine-formula/src/facade/f-formula.ts
=> feat(facade): add lexer-tree-builder

packages/sheets-ui/src/services/selection/selection-render.service.ts
=> test: try to fix pivot selection end

packages/ui/src/views/components/ribbon/Ribbon.tsx, packages/ui/src/views/components/ribbon/ToolbarItem.tsx
close https://github.com/dream-num/univer-pro/issues/3890
=> fix(ui): improve the style of Ribbon

packages/engine-render/src/components/sheets/extensions/font.ts
=> fix: font interceptor

packages/sheets-data-validation/src/facade/f-worksheet.ts, packages/sheets-drawing-ui/src/facade/f-univer.ts, packages/sheets-thread-comment/src/facade/f-thread-comment.ts, packages/sheets-thread-comment/src/facade/f-worksheet.ts, packages/sheets-ui/src/facade/f-univer.ts, packages/sheets/src/facade/f-univer.ts
=> feat(facade): univer-sheet change to workbook

packages/sheets-hyper-link-ui/src/services/side-panel.service.ts, packages/sheets-hyper-link/src/commands/commands/add-hyper-link.command.ts, packages/sheets-hyper-link/src/commands/mutations/add-hyper-link.mutation.ts, packages/sheets-hyper-link/src/controllers/ref-range.controller.ts, packages/sheets-hyper-link/src/controllers/sheet-hyper-link-resource.controller.ts, packages/sheets-hyper-link/src/index.ts, packages/sheets-hyper-link/src/models/hyper-link.model.ts, packages/sheets-hyper-link/src/types/interfaces/i-hyper-link.ts, packages/sheets/src/facade/f-workbook.ts, packages/sheets/src/facade/index.ts
Multiple exports of the same name but different structures
close #xxx
=> refactor(sheets-hyper-link)!: rename ICellHyperLink to ISheetHyperLink

packages/design/src/components/tooltip/Tooltip.stories.tsx, packages/design/src/components/tooltip/Tooltip.tsx
close https://github.com/dream-num/univer-pro/issues/3912
=> fix(design): improve styling of Tooltip

packages/sheets-ui/src/facade/f-range.ts
=> fix(sheet): fix facade throw error

packages/core/src/shared/index.ts, packages/core/src/shared/numfmt.ts, packages/core/src/shared/types/numfmt.type.ts, packages/sheets-numfmt-ui/src/controllers/numfmt.controller.ts, packages/sheets-numfmt/src/controllers/numfmt-cell-content.controller.ts, packages/sheets-numfmt/src/facade/f-workbook.ts, packages/sheets-numfmt/src/facade/index.ts, packages/sheets-numfmt/src/utils/pattern.ts
=> feat(numfmt): support set numfmt local

packages/sheets-numfmt-ui/src/views/components/more-numfmt-type/MoreNumfmtType.tsx, packages/sheets-numfmt/src/facade/f-workbook.ts
=> feat(numfmt): add numfmt local enum

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/bug_report.zh-CN.yml
=> docs(issue-template): update bug report templates to include UMD online template

packages/sheets/src/model/range-theme-util.ts
=> fix(sheet): fix doc error

packages/core/src/docs/data-model/rich-text-builder.ts, packages/docs-mention-ui/src/views/mention-edit-popup/index.tsx, packages/docs-ui/src/basics/paragraph.ts, packages/docs-ui/src/controllers/menu/context-menu.ts, packages/docs-ui/src/views/rich-text-editor/index.tsx, packages/sheets-data-validation/src/facade/f-range.ts, packages/sheets-data-validation/src/services/dv-validator-service.ts, packages/sheets-data-validation/src/validators/custom-validator.ts, packages/sheets-formula-ui/src/views/formula-editor/index.tsx, packages/sheets-formula-ui/src/views/range-selector/hooks/useRefactorEffect.ts, packages/sheets-ui/src/controllers/editor/editing.render-controller.ts, packages/sheets-ui/src/views/editor-container/EditorContainer.tsx, packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx, packages/sheets/src/facade/f-range.ts
close https://github.com/dream-num/univer-pro/issues/3773
close https://github.com/dream-num/univer-pro/issues/3697
close https://github.com/dream-num/univer-pro/issues/3832
close https://github.com/dream-num/univer-pro/issues/2829
close https://github.com/dream-num/univer-pro/issues/3874
close https://github.com/dream-num/univer-pro/issues/3875
=> fix(sheets): data validation validator issues

e2e/memory/memory.spec.ts, examples/src/main.tsx, examples/src/sheets/very-lazy.ts, playwright.config.ts
This pull request increases the memory overflow temporarily and removes retry from CI to better catch PRs that may cause memory leaks.
=> test: add temp more zoom for memory testing

e2e/memory/memory.spec.ts, packages/engine-render/src/render-manager/render-unit.ts, packages/facade/src/apis/__tests__/create-test-bed.ts, packages/sheets-data-validation/src/facade/f-univer.ts, packages/sheets-ui/src/facade/f-event.ts, packages/sheets-ui/src/facade/f-univer.ts, packages/sheets-ui/src/facade/f-workbook.ts, packages/sheets-ui/src/facade/f-worksheet.ts, packages/sheets-ui/src/services/selection/selection-render.service.ts, packages/sheets/src/facade/f-event.ts, packages/sheets/src/facade/f-workbook.ts, packages/sheets/src/facade/f-worksheet.ts, packages/sheets/src/services/selections/selection-data-model.ts, packages/sheets/src/services/selections/selection.service.ts
close https://github.com/dream-num/univer/issues/4414
=> fix: add selection facade API

packages/sheets-ui/src/facade/f-univer.ts, packages/sheets-ui/src/facade/f-workbook.ts, packages/sheets/src/facade/f-workbook.ts, packages/sheets/src/facade/f-worksheet.ts
=> fix(facade): sheets event facade

common/shared/package.json, common/shared/postcss/postcss.config.mjs, packages/design/src/components/color-picker/AlphaSlider.tsx, pnpm-lock.yaml
=> feat: add postcss-preset-env for enhanced CSS features and refactor AlphaSlider styles

packages/sheets-crosshair-highlight/src/facade/f-univer.ts, packages/sheets-crosshair-highlight/src/index.ts, packages/sheets-ui/src/controllers/hover-render.controller.ts, packages/sheets-ui/src/facade/f-event.ts, packages/sheets-ui/src/facade/f-univer.ts, packages/sheets-ui/src/facade/f-worksheet.ts, packages/sheets-ui/src/index.ts, packages/sheets-ui/src/services/hover-manager.service.ts, packages/sheets-ui/src/services/selection/selection-render.service.ts, packages/sheets/src/basics/const/command-listener-const.ts, packages/sheets/src/commands/commands/remove-sheet.command.ts, packages/sheets/src/facade/f-event.ts, packages/sheets/src/facade/f-selection.ts, packages/sheets/src/facade/f-univer.ts, packages/sheets/src/facade/f-workbook.ts, packages/sheets/src/facade/f-worksheet.ts, packages/sheets/src/index.ts
=> feat(facade): add event support for sheets & sheets-ui

common/shared/eslint/index.js, packages/core/src/facade/f-base.ts, packages/sheets/src/facade/f-range.ts
=> fix(*): disable jsdoc/tag-lines rule and add ignore comments in FBase classes

packages/core/src/facade/f-enum.ts, packages/facade/src/apis/__tests__/create-test-bed.ts, packages/sheets-ui/src/facade/__tests__/f-sheet-hooks.spec.ts, packages/sheets-ui/src/facade/f-univer.ts, packages/sheets/src/commands/commands/set-border-command.ts, packages/sheets/src/facade/f-defined-name.ts, packages/sheets/src/facade/f-event.ts, packages/sheets/src/facade/f-range.ts, packages/sheets/src/facade/f-workbook.ts
=> feat(facade): add sheet facade functions

e2e/memory/memory.spec.ts, examples/src/sheets/main.ts
=> test: optimize comparison

packages/sheets-ui/src/facade/f-univer.ts
=> fix: bind multiple times for UIEvent after dispose and create again

packages/sheets-thread-comment/src/facade/f-range.ts, packages/sheets-thread-comment/src/facade/f-workbook.ts
=> feat(facade): add comment example on facade

packages/engine-formula/src/engine/utils/numfmt-kit.ts, packages/engine-formula/src/functions/__tests__/nested-functions.spec.ts
=> fix(formula): fix bug in judging whether the value is in number format

packages-experimental/sheets-source-binding/src/model/source-model.ts
=> fix: fix source error

packages/core/src/facade/f-hooks.ts
=> feat(facade): deprecated comment

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/bug_report.zh-CN.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/feature_request.zh-CN.yml
=> chore: update issue templates to use 'type' instead of 'labels'

packages/design/src/components/color-picker/ColorPicker.tsx
=> feat(design): add hex format support for color output of `ColorPicker`

packages-experimental/sheets-source-binding/README-zh.md, packages-experimental/sheets-source-binding/src/model/source-model.ts
- add readme docs
- fix cell date not set 'T'
=> fix(sheet): fix binding type not set & add readme.

packages/sheets-formula-ui/src/views/formula-editor/hooks/useSheetSelectionChange.ts, packages/sheets-formula-ui/src/views/formula-editor/index.tsx
close https://github.com/dream-num/univer-pro/issues/3941
=> fix(sheets-ui): modify selection when need to add one

packages/ui/src/components/menu/desktop/Menu.tsx
=> fix(ui): menu hidden error

packages/design/src/components/color-picker/ColorPicker.tsx
=> fix(design): add hex format support for HSV conversion of `ColorPicker`

packages/sheets-hyper-link/src/facade/f-range.ts, packages/sheets/src/facade/f-range.ts
=> fix(facade): support get rich-text by getValue

packages/sheets/src/facade/__tests__/utils.spec.ts, packages/sheets/src/facade/utils.ts
=> fix(sheets): set value error on formula cell

packages-experimental/uniui/package.json, packages/docs-ui/package.json, packages/thread-comment-ui/package.json, pnpm-lock.yaml
=> chore: update package.json

packages/sheets-ui/src/commands/commands/set-worksheet-auto-col-width.command.ts
=> fix(sheets): make auto-width sync

packages-experimental/sheets-source-binding/src/services/source-binding-service.ts
=> fix(bind): fix bind mode loss text style

packages-experimental/sheets-source-binding/src/services/source-binding-service.ts
=> chore: add api to get source nodes

packages-experimental/sheets-source-binding/src/controllers/binding-manager.ts, packages-experimental/sheets-source-binding/src/facade/f-workbook.ts, packages-experimental/sheets-source-binding/src/index.ts, packages/sheets/src/facade/f-workbook.ts, packages/sheets/src/index.ts
=> chore: update source facade

packages/sheets-ui/src/facade/f-event.ts
=> fix(facade): add doc for sheets-ui event

packages/docs-ui/src/basics/paragraph.ts, packages/docs-ui/src/controllers/render-controllers/doc-input.controller.ts
=> fix(sheets-ui): style error when save text from cell-editor

packages/ui/src/controllers/ui/ui-desktop.controller.tsx, packages/ui/src/services/parts/parts.service.ts, packages/ui/src/views/components/ComponentContainer.tsx, packages/ui/src/views/workbench/Workbench.tsx, packages/ui/src/views/workbench/workbench.module.less
=> feat(ui): support hiding footer and header

packages/sheets-filter/src/facade/f-enum.ts
=> fix(filter): fix filter enum

packages/docs-ui/src/basics/paragraph.ts, packages/docs-ui/src/controllers/render-controllers/doc-input.controller.ts
=> fix: revert set text style

packages/ui/src/views/components/ComponentContainer.tsx
=> fix(ui): add return type for ComponentContainer function

examples/src/sheets/main.ts, packages/sheets-ui/src/views/sheet-container/SheetContainer.tsx, packages/ui/src/facade/f-menu-builder.ts
Change `appendTo` API, so users can specify where the menu will be appended to.
=> feat(ui): add ui facade menu position

packages/core/src/facade/f-univer.ts, packages/sheets-crosshair-highlight/src/facade/f-univer.ts, packages/sheets-data-validation/src/facade/f-data-validation-builder.ts, packages/sheets-data-validation/src/facade/f-event.ts, packages/sheets-data-validation/src/facade/f-range.ts, packages/sheets-data-validation/src/facade/f-univer.ts, packages/sheets-data-validation/src/facade/f-workbook.ts, packages/sheets-data-validation/src/facade/f-worksheet.ts, packages/sheets-thread-comment/src/facade/f-event.ts, packages/sheets-thread-comment/src/facade/f-range.ts, packages/sheets-thread-comment/src/facade/f-thread-comment.ts, packages/sheets-thread-comment/src/facade/f-univer.ts, packages/sheets-thread-comment/src/facade/f-workbook.ts, packages/sheets-thread-comment/src/facade/f-worksheet.ts, packages/ui/src/facade/f-enum.ts, packages/ui/src/facade/f-hooks.ts, packages/ui/src/facade/f-menu-builder.ts, packages/ui/src/facade/f-univer.ts
=> fix(facade): hidden mixin in ui & data-validation & thread-comment

common/shared/vite/index.ts, packages/core/src/facade/f-enum.ts, packages/core/src/facade/f-event.ts, packages/core/src/facade/f-util.ts, packages/sheets-conditional-formatting/src/facade/conditional-formatting-builder.ts, packages/sheets-data-validation/src/facade/f-univer.ts, packages/sheets/src/facade/f-workbook.ts
=> feat: cleanup jsdoc

packages/core/src/facade/f-univer.ts, packages/network/src/facade/f-network.ts, packages/network/src/facade/f-univer.ts, packages/sheets-filter/src/facade/f-worksheet.ts, packages/sheets-sort/src/facade/f-worksheet.ts, packages/sheets-ui/src/facade/f-workbook.ts, packages/sheets-ui/src/facade/f-worksheet.ts, packages/sheets/src/facade/f-range.ts, packages/sheets/src/facade/f-selection.ts, packages/sheets/src/facade/f-workbook.ts, packages/sheets/src/facade/f-worksheet.ts, packages/ui/src/facade/f-menu-builder.ts, packages/ui/src/facade/f-shortcut.ts
=> docs(core): add description to Facade API

packages/facade/src/apis/sheets/__tests__/f-permission.spec.ts, packages/sheets/src/facade/f-permission.ts, packages/sheets/src/model/range-protection-rule.model.ts, packages/sheets/src/services/permission/permission-point/const.ts, packages/sheets/src/services/permission/worksheet-permission/worksheet-permission-rule.model.ts
=> chore: update permission facade

packages/sheets-ui/src/services/clipboard/clipboard.service.ts, packages/sheets-ui/src/services/clipboard/utils.ts
=> feat: paste image if no excel html

CONTRIBUTING.md, docs/CONTRIBUTING-FACADE.md, packages/core/src/services/log/log.service.ts, packages/find-replace/docs/README.md
=> chore(core): add deprecate API

packages/core/package.json, pnpm-lock.yaml
=> chore(core): update redi version for better error msg

packages-experimental/sheets-source-binding/src/facade/f-enum.ts, packages/sheets-drawing-ui/src/facade/f-enum.ts, packages/sheets-drawing-ui/src/facade/f-event.ts, packages/sheets-filter/src/facade/f-event.ts, packages/sheets-find-replace/src/facade/f-univer.ts, packages/sheets-hyper-link/src/facade/f-event.ts, packages/sheets-sort/src/facade/f-event.ts, packages/sheets-ui/src/facade/f-event.ts, packages/sheets-zen-editor/src/facade/f-univer.ts, packages/sheets-zen-editor/src/facade/f-workbook.ts, packages/sheets/src/facade/f-event.ts, packages/watermark/src/facade/f-univer.ts
=> fix(*): add ignore comments for facade

packages/engine-render/src/components/sheets/extensions/column-header-layout.ts, packages/engine-render/src/components/sheets/interfaces.ts, packages/sheets-ui/src/commands/commands/headersize-changed.command.ts, packages/sheets-ui/src/controllers/render-controllers/freeze.render-controller.ts, packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts, packages/sheets-ui/src/controllers/render-controllers/zoom.render-controller.ts, packages/sheets-ui/src/controllers/sheet-ui.controller.ts, packages/sheets-ui/src/facade/f-univer.ts, packages/sheets-ui/src/facade/f-worksheet.ts, packages/sheets-ui/src/index.ts, packages/sheets-ui/src/services/sheet-skeleton-manager.service.ts, packages/sheets/src/commands/commands/insert-range-move-right.command.ts, packages/ui/src/views/components/popup/RectPopup.tsx
=> fix: better col header facade

.github/workflows/setup.yml
=> ci: update artifact to v4

packages/core/src/univer.ts
=> fix(facade): hide constructor and ignore injector getter

common/shared/vite/index.ts
Resolve the build issue with go-workspace
close #xxx
=> chore: remove keepNames

packages/sheets-formula-ui/src/controllers/formula-clipboard.controller.ts
=> fix(formula): fix cut paste bug of formula

packages/engine-formula/src/engine/dependency/formula-dependency.ts
=> fix(formula): skip processing tree when there is no formula

packages/core/src/sheets/sheet-skeleton.ts, packages/engine-render/src/basics/tools.ts
=> chore: fix export problem

packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts, packages/sheets-ui/src/controllers/render-controllers/clipboard.render-controller.ts, packages/sheets-ui/src/plugin.ts, packages/sheets-ui/src/services/clipboard/clipboard.service.ts, packages/sheets-ui/src/views/clipboard/ClipboardPopupMenu.tsx
=> chore: fix clipboard menu memory leak

packages/core/src/index.ts
=> chore: export fix

packages/sheets-drawing-ui/src/controllers/sheet-drawing-permission.controller.ts
=> fix(drawing): drawing permission memory leak

packages/engine-formula/src/commands/mutations/set-formula-calculation.mutation.ts, packages/engine-formula/src/controller/calculate.controller.ts, packages/engine-formula/src/controller/computing-status.controller.ts, packages/engine-formula/src/index.ts, packages/engine-formula/src/plugin.ts, packages/engine-formula/src/services/global-computing-status.service.ts, packages/engine-formula/src/services/runtime.service.ts
=> feat(engine-formula): add global computing status service

packages/engine-formula/src/facade/f-formula.ts, packages/engine-formula/src/services/global-computing-status.service.ts
=> feat(engine-formula): add whenComputingCompleteAsync facade

packages/ui/src/controllers/menus/menus.ts
close #4608
Support separate disable states for undo and redo actions.
=> fix(ui): improve undo/redo menu item disable logic

examples/src/sheets/main.ts, packages/core/src/facade/f-event-registry.ts, packages/core/src/facade/f-univer.ts, packages/sheets-crosshair-highlight/src/facade/f-univer.ts, packages/sheets-data-validation/src/facade/f-univer.ts, packages/sheets-drawing-ui/src/facade/f-univer.ts, packages/sheets-filter/src/facade/f-event.ts, packages/sheets-hyper-link/src/facade/f-univer.ts, packages/sheets-sort/src/facade/f-event.ts, packages/sheets-thread-comment/src/facade/f-univer.ts, packages/sheets-ui/src/facade/f-univer.ts, packages/sheets-zen-editor/src/facade/f-univer.ts, packages/sheets/src/facade/f-univer.ts
=> feat(facade): facade event memory usage optimize

packages/sheets-ui/src/facade/f-univer.ts
close #4627
```
univerAPI.addEvent(univerAPI.Event.CellClicked, console.log)
```
=> fix(sheets-ui/facade): fix cell event not triggering when listening through the facade API

e2e/visual-comparison/sheets/sheets-switching-render-unit.spec.ts, packages/network/src/services/web-socket/web-socket.service.ts
=> chore: use Event to prevent Node.js error

examples/src/sheets-multi/main.tsx, packages/sheets-formula-ui/src/views/formula-editor/hooks/use-formula-selection.ts, packages/sheets-formula-ui/src/views/formula-editor/hooks/use-sheet-selection-change.ts, packages/sheets-formula-ui/src/views/formula-editor/index.tsx, packages/sheets-formula-ui/src/views/range-selector/hooks/use-highlight.ts, packages/sheets-formula-ui/src/views/range-selector/utils/find-index-from-sequence-nodes.ts
=> fix(sheets-formula-ui): selecion error on formula-editor

packages/sheets/src/facade/f-worksheet.ts
=> fix(facade): set default style

packages/core/src/services/plugin/plugin.service.ts
=> chore: validate plugin dependency type

packages/core/src/facade/f-blob.ts, packages/core/src/facade/f-enum.ts, packages/core/src/facade/f-event-registry.ts, packages/core/src/facade/f-event.ts, packages/core/src/facade/f-hooks.ts, packages/core/src/facade/f-univer.ts, packages/core/src/facade/f-util.ts, packages/core/src/shared/rectangle.ts, packages/engine-formula/src/facade/f-formula.ts, packages/sheets-formula-ui/src/controllers/formula-clipboard.controller.ts, packages/sheets-thread-comment/src/facade/f-univer.ts, packages/sheets-thread-comment/src/facade/f-workbook.ts, packages/sheets/src/facade/f-defined-name.ts, packages/sheets/src/facade/f-enum.ts, packages/sheets/src/facade/f-event.ts, packages/sheets/src/facade/f-permission.ts, packages/sheets/src/facade/f-range.ts, packages/sheets/src/facade/f-selection.ts, packages/sheets/src/facade/f-univer.ts, packages/sheets/src/facade/f-workbook.ts, packages/sheets/src/facade/f-worksheet.ts, packages/sheets/src/index.ts
=> docs(facade): supplement notes and example

packages/sheets-ui/src/commands/commands/set-selection.command.ts, packages/sheets-ui/src/controllers/defined-name/defined-name.controller.ts, packages/sheets-ui/src/controllers/render-controllers/mobile/mobile-scroll.render-controller.ts, packages/sheets-ui/src/controllers/render-controllers/scroll.render-controller.ts, packages/sheets/src/commands/operations/scroll-to-cell.operation.ts, packages/sheets/src/index.ts
=> fix: scroll cmd should consider about unitId

packages/sheets-ui/src/controllers/permission/sheet-permission-init-ui.controller.ts, packages/sheets-ui/src/plugin.ts, packages/sheets/src/controllers/permission/sheet-permission-init.controller.ts
=> chore: update permission init method

packages/sheets-ui/src/services/clipboard/clipboard.service.ts, packages/sheets-ui/src/services/clipboard/utils.ts
=> fix: paste value from excel incorrect

packages/sheets/src/model/range-theme-model.ts, packages/sheets/src/model/range-themes/default.ts
-  support default theme style with no footer style
=> fix(style): fix defualt theme style

packages/core/src/common/boolean.ts, packages/core/src/shared/generate.ts, packages/sheets-ui/src/controllers/status-bar.controller.ts
=> fix(sheet): fix some performance issue

packages/core/src/services/plugin/plugin.service.ts
=> fix: fix plugin lazy loading not working

e2e/visual-comparison/sheets/sheets-visual-comparison.spec.ts, packages/engine-formula/src/engine/reference-object/base-reference-object.ts, packages/engine-formula/src/engine/utils/__tests__/numfmt-kit.spec.ts, packages/engine-numfmt/src/index.ts, packages/engine-numfmt/src/util.ts, packages/sheets-numfmt-ui/src/controllers/menu.ts, packages/sheets-numfmt-ui/src/controllers/numfmt-alert-render.controller.ts, packages/sheets-numfmt-ui/src/controllers/numfmt.editor.controller.ts, packages/sheets-numfmt/src/commands/commands/set-numfmt.command.ts, packages/sheets-numfmt/src/controllers/numfmt-cell-content.controller.ts, packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts, packages/sheets-ui/src/controllers/editor/editing.render-controller.ts, packages/sheets/src/basics/cell-type.ts, packages/sheets/src/commands/commands/__tests__/set-range-values.command.spec.ts, packages/sheets/src/services/__tests__/numfmt.service.test.ts, packages/sheets/src/services/__tests__/util.ts
|Univer Before|Univer After|Excel|
|----|----|----|
|![企业微信截图_17398711097599](https://github.com/user-attachments/assets/9127e804-3b3d-46c5-b245-7180e30ef27b)|![企业微信截图_17398711779240](https://github.com/user-attachments/assets/c239c079-d5d6-4765-b803-7a4fa9301e97)|![企业微信截图_173986837692](https://github.com/user-attachments/assets/7884610e-ac92-4099-bfbb-43c3d4538eaf)|
=> fix(numfmt): text format excel, default format

packages/engine-formula/src/basics/cache-lru.ts, packages/network/src/services/http/implementations/xhr.ts
=> chore: optimize XHR impl log

packages/ui/src/facade/f-shortcut.ts, packages/ui/src/services/shortcut/shortcut.service.ts
=> fix(ui): fix the issue where disabling shortcuts through the facade API does not work

packages/design/src/components/dropdown/DropdownOverlay.tsx, packages/sheets-ui/src/index.ts
=> chore: export some config for dropdown overlay

packages/sheets-formula-ui/src/views/formula-editor/hooks/use-formula-selection.ts, packages/sheets-formula-ui/src/views/formula-editor/hooks/use-sheet-selection-change.ts, packages/sheets-formula-ui/src/views/range-selector/hooks/use-left-and-right-arrow.ts
close https://github.com/dream-num/univer-pro/issues/4004
=> fix(sheets-formula-ui): edit other sheet range error

packages/sheets-ui/src/controllers/status-bar.controller.ts
=> fix: use number value in stats calculation

packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
close https://github.com/dream-num/univer/issues/4454
=> fix: paste rich text with br should keep line break

packages/engine-render/src/shape/scroll-bar.ts
=> fix: scrollbar size may be 0

packages/sheets-ui/src/controllers/auto-height.controller.ts, packages/sheets-ui/src/controllers/config.schema.ts
- fix select a column set font size cause performance
=> fix(sheet): avoid auto height too many rows

packages/sheets-ui/src/controllers/auto-height.controller.ts
=> fix(sheet): fix auto heigt cause some code error

examples/esbuild.config.ts, examples/src/main.tsx, examples/src/sheets-multi-units/lazy.ts, examples/src/sheets-multi-units/main.ts, examples/src/sheets-multi-units/styles.ts, examples/src/sheets-multi-units/very-lazy.ts, packages/engine-formula/src/services/calculate-formula.service.ts, packages/engine-formula/src/services/current-data.service.ts, packages/engine-formula/src/services/defined-names.service.ts, packages/engine-formula/src/services/dependency-manager.service.ts, packages/engine-formula/src/services/feature-calculation-manager.service.ts, packages/engine-formula/src/services/function.service.ts, packages/engine-formula/src/services/global-computing-status.service.ts, packages/engine-formula/src/services/other-formula-manager.service.ts, packages/engine-formula/src/services/super-table.service.ts, packages/sheets-formula-ui/src/sheets-formula-ui.plugin.ts, packages/sheets-formula/src/controllers/trigger-calculation.controller.ts, packages/sheets-formula/src/facade/f-formula.ts, packages/sheets-formula/src/sheets-formula.plugin.ts
close https://github.com/dream-num/univer-pro/issues/4021
=> chore: add multi units playground

packages/sheets-conditional-formatting-ui/src/components/panel/rule-list/index.module.less
close [3636](https://github.com/dream-num/univer-pro/issues/3636)
=> fix(sheets-conditional-formatting-ui): fix panel background color issue

packages/sheets-ui/src/controllers/auto-height.controller.ts
- fix code error, the ranges may be undefined
close https://github.com/dream-num/univer-pro/issues/4032
=> fix(sheet): the range may be undefined

packages/engine-render/src/basics/draw.ts, packages/engine-render/src/components/sheets/extensions/border.ts
close https://github.com/dream-num/univer-pro/issues/4048
=> fix: dashline drawing incorrect when adjust col width

packages/engine-render/src/components/sheets/extensions/border.ts, packages/sheets-ui/src/controllers/status-bar.controller.ts
close https://github.com/dream-num/univer-pro/issues/4055
=> fix: status bar also needs to consider the date format, where t=number.

packages/facade/src/apis/sheets/__tests__/f-range.spec.ts, packages/sheets-numfmt/src/facade/f-range.ts, packages/sheets-ui/src/facade/f-worksheet.ts, packages/sheets/src/commands/commands/append-row.command.ts, packages/sheets/src/commands/commands/set-style.command.ts, packages/sheets/src/controllers/basic-worksheet.controller.ts, packages/sheets/src/facade/f-range.ts, packages/sheets/src/facade/f-workbook.ts, packages/sheets/src/facade/f-worksheet.ts, packages/sheets/src/facade/utils.ts, packages/sheets/src/index.ts
=> feat(facade): supplement f-workbook f-worksheet f-range facade

packages/thread-comment/src/controllers/tc-resource.controller.ts, packages/thread-comment/src/index.ts
=> feat(thread-comment): export sheet thread comment plugin constant

packages/sheets-formula-ui/src/services/render-services/ref-selections.render-service.ts, packages/sheets-ui/src/controllers/render-controllers/header-menu.render-controller.ts, packages/sheets-ui/src/controllers/render-controllers/header-unhide.render-controller.ts, packages/sheets-ui/src/services/selection/selection-render-model.ts, packages/sheets-ui/src/services/selection/selection-render.service.ts
=> fix: fix context menu cannot trigger selection change

packages/sheets-ui/src/controllers/sheet-ui.controller.ts, packages/sheets-ui/src/controllers/shortcuts/editor.shortcut.ts, packages/sheets-ui/src/controllers/shortcuts/value.shortcut.ts, packages/ui/src/services/shortcut/shortcut.service.ts, packages/ui/src/views/components/shortcut-panel/ShortcutPanel.tsx
Fixed issues:
1. fn+backspace not work on mac
2. backspace not work on windows
=> fix(sheets-ui): backspace shortcut not work

packages/sheets-ui/src/facade/f-univer.ts
=> fix(sheets-ui): resolve the issue where related events fail to trigger under specific conditions

packages/docs-ui/src/controllers/render-controllers/doc-editor-bridge.controller.ts
=> fix(docs-ui): doc editor mem leak

.github/workflows/dev-performance-log.yml, .vscode/settings.json, e2e/memory/memory.spec.ts, e2e/utils/report-performance.ts, package.json, pnpm-lock.yaml
=> ci: report memory overflow to posthog

.github/workflows/dev-performance-log.yml
=> fix: fix secrets is not set to env

e2e/memory/memory.spec.ts
=> ci: fix event name

e2e/memory/memory.spec.ts, packages/docs-ui/src/controllers/doc-ui.controller.ts, packages/docs-ui/src/views/doc-footer/DocFooter.tsx
=> fix(docs-ui): error display doc-toolbar on sheet

packages-experimental/uni-formula-ui/package.json, packages-experimental/uni-slides-ui/package.json, packages/docs-mention-ui/package.json, packages/sheets-crosshair-highlight/package.json, packages/sheets-formula-ui/package.json, packages/sheets-zen-editor/package.json, pnpm-lock.yaml
=> chore: fix pnpm-lock file

packages/sheets-ui/src/controllers/auto-fill.controller.ts
close https://github.com/dream-num/univer-pro/issues/4062
=> fix: issue for autofill not working

packages/sheets-ui/src/controllers/config.schema.ts, packages/sheets-ui/src/plugin.ts, packages/sheets-ui/src/views/status-bar/StatusBar.tsx
=> fix: change config hide statistic to show statistic

packages/sheets-formula-ui/src/services/range-selector.service.ts, packages/sheets-formula-ui/src/views/range-selector/global.tsx
=> fix(sheets-formula-ui): range selector callback not triggered

packages/sheets-ui/src/services/permission/sheet-permission-user-list.service.ts, packages/sheets-ui/src/views/permission/user-dialog/index.tsx
=> feat(sheets-ui): add reactive user list for permission management

packages/sheets/src/facade/f-worksheet.ts
=> feat(facade): get custom meta data

common/shared/vite/data.ts
=> chore(uniscript): add monaco-editor to peer dependencies

e2e/memory/memory.spec.ts, e2e/utils/report-performance.ts
=> fix: await posthog

packages/sheets-ui/src/commands/operations/cell-edit.operation.ts, packages/sheets-ui/src/controllers/editor/editing.render-controller.ts, packages/sheets-ui/src/controllers/shortcuts/editor.shortcut.ts
=> fix(sheets-ui): mac delete shortcut work error

packages/uniscript/package.json
=> chore(uniscript): update package json

packages/sheets-formula-ui/src/facade/f-univer.ts
=> fix(facade): showRangeSelectorDialog document

packages/sheets-ui/src/plugin.ts
=> fix: update permission init timing

packages/design/src/components/cascader-list/CascaderList.tsx, packages/design/src/components/date-range-picker/DateRangePicker.tsx, packages/design/src/components/input-number/InputNumber.tsx, packages/design/src/index.ts
=> chore: add some components props

packages/core/src/shared/after-init-apply.ts, packages/engine-numfmt/src/util.ts, packages/sheets-numfmt-ui/src/controllers/menu.ts
=> feat(sheets-numfmt): add percentage as default option

packages/sheets-formula/src/facade/f-formula.ts
=> fix: fix facade example

packages/sheets-data-validation/src/facade/f-univer.ts, packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts
=> fix: dep detect only in event handler not before register event

e2e/memory/memory.spec.ts, e2e/utils/report-performance.ts
=> chore: always report regardless of expects

packages/engine-formula/src/basics/cache-lru.ts, packages/engine-formula/src/services/function.service.ts, packages/sheets-formula/src/services/register-function.service.ts, packages/sheets-formula/src/services/remote/remote-register-function.service.ts
After disposing the registered formula, there is no prompt information for the formula, but manual input can still be used
=> fix(formula): fix dispose register function bug

packages/core/src/services/undoredo/undoredo.service.ts, packages/core/src/shared/rectangle.ts, packages/sheets-data-validation-ui/src/controllers/dv-reject-input.controller.ts, packages/sheets-data-validation-ui/src/views/components/detail/index.tsx, packages/sheets-data-validation/src/services/dv-cache.service.ts, packages/sheets-data-validation/src/services/dv-custom-formula.service.ts, packages/sheets-formula/src/services/register-other-formula.service.ts, packages/sheets-hyper-link/src/commands/commands/add-hyper-link.command.ts, packages/sheets-hyper-link/src/commands/commands/update-hyper-link.command.ts, packages/sheets-ui/src/controllers/editor/editing.render-controller.ts, packages/sheets/src/commands/commands/set-range-values.command.ts, packages/sheets/src/index.ts, packages/sheets/src/services/sheet-interceptor/sheet-interceptor.service.ts, packages/slides-ui/src/services/slide-editor-bridge.service.ts
close https://github.com/dream-num/univer/issues/4676
=> fix(sheets-data-validation): data validation valid error on custom formula

packages/core/src/services/undoredo/undoredo.service.ts, packages/sheets-ui/src/controllers/editor/editing.render-controller.ts, packages/sheets/src/commands/commands/set-range-values.command.ts
=> feat(sheets-ui): check before undo-redo rollback

e2e/visual-comparison/sheets/sheets-formula-related.spec.ts
=> fix: formula e2e

packages/docs-ui/src/commands/commands/doc-select-all.command.ts
close https://github.com/dream-num/univer-pro/issues/4065
=> fix(docs-ui): select all on empty doc

mockdata/src/sheets/demo/default-workbook-data-demo.ts, packages/core/src/sheets/worksheet.ts
=> chore: remove demo's default style as it is not working

packages/core/src/facade/f-univer.ts, packages/sheets-filter/src/facade/f-filter.ts, packages/sheets-filter/src/facade/f-range.ts, packages/sheets-numfmt/src/facade/f-range.ts, packages/sheets-ui/src/facade/f-range.ts, packages/sheets/src/facade/f-range.ts, packages/sheets/src/facade/f-selection.ts, packages/sheets/src/facade/f-workbook.ts
=> feat: supplement facade example

packages-experimental/action-recorder/package.json, packages-experimental/debugger/package.json, packages-experimental/uni-formula-ui/package.json, packages-experimental/uni-sheets-ui/package.json, packages-experimental/uni-slides-ui/package.json, packages-experimental/uniui/package.json, packages/design/package.json, packages/docs-drawing-ui/package.json, packages/docs-hyper-link-ui/package.json, packages/docs-thread-comment-ui/package.json, packages/docs-ui/package.json, packages/drawing-ui/package.json, packages/find-replace/package.json, packages/sheets-conditional-formatting-ui/package.json, packages/sheets-crosshair-highlight/package.json, packages/sheets-data-validation-ui/package.json, packages/sheets-drawing-ui/package.json, packages/sheets-filter-ui/package.json, packages/sheets-formula-ui/package.json, packages/sheets-formula-ui/src/sheets-formula-ui.plugin.ts, packages/sheets-hyper-link-ui/package.json, packages/sheets-numfmt-ui/package.json, packages/sheets-sort-ui/package.json, packages/sheets-thread-comment-ui/package.json, packages/sheets-ui/package.json, packages/sheets-zen-editor/package.json, packages/slides-ui/package.json, packages/thread-comment-ui/package.json, packages/ui/package.json, pnpm-lock.yaml
=> fix(sheets-formula-ui): fix component registration

packages/core/src/common/request-immediate-macro-task.ts, packages/engine-render/src/engine.ts, packages/sheets-ui/src/services/hover-manager.service.ts, packages/sheets-ui/src/services/utils/doc-skeleton-util.ts
close https://github.com/dream-num/univer/issues/4801
=> fix(sheets-ui): hover service error

packages/sheets-ui/src/services/clipboard/usm-to-html/convertor.ts
=> fix(sheets-ui): fix sheet clipboard col tag not closed

packages/sheets-drawing-ui/src/controllers/sheet-cell-image.controller.ts
=> feat(sheets-drawing-ui): change cell-image resize to render phase

packages/sheets/src/model/range-theme-model.ts
=> fix(sheet): fix fromjson error

.github/workflows/preview-deploy.yml
=> ci: fix markdown table

packages/sheets-ui/src/controllers/render-controllers/freeze.render-controller.ts, packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts, packages/sheets-ui/src/services/selection/selection-control.ts
close https://github.com/dream-num/univer-pro/issues/4087
=> fix: header line

packages-experimental/debugger/package.json, packages-experimental/debugger/src/commands/commands/float-dom.command.ts, packages/docs-drawing-ui/src/commands/commands/insert-doc-drawing.command.ts, packages/docs-drawing-ui/src/controllers/doc-float-dom.controller.ts, packages/docs-drawing-ui/src/index.ts, packages/docs-drawing-ui/src/plugin.ts, packages/docs-drawing/src/index.ts, packages/docs-drawing/src/services/doc-drawing.service.ts, packages/drawing-ui/src/controllers/image-update.controller.ts, packages/drawing-ui/src/services/drawing-render.service.ts, packages/drawing/src/index.ts, packages/drawing/src/models/image-model-interface.ts, packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts, packages/ui/src/services/dom/canvas-dom-layer.service.ts, packages/ui/src/views/components/dom/FloatDom.tsx, pnpm-lock.yaml
=> feat(docs-drawing-ui): support float-dom on doc-canvas

packages/core/src/types/interfaces/i-drawing.ts, packages/docs-drawing-ui/src/controllers/doc-drawing-transformer-update.controller.ts, packages/docs-drawing-ui/src/controllers/doc-float-dom.controller.ts, packages/docs-drawing-ui/src/controllers/drawing-popup-menu.controller.ts, packages/docs-drawing-ui/src/controllers/render-controllers/doc-drawing-update.render-controller.ts, packages/drawing-ui/src/services/drawing-render.service.ts, packages/engine-render/src/shape/rect.ts, packages/ui/src/services/dom/canvas-dom-layer.service.ts, packages/ui/src/views/components/dom/FloatDom.tsx
=> feat(docs-drawing-ui): optimize float-dom on doc canvas

packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
close https://github.com/dream-num/univer-pro/issues/4077
=> fix(sheets-ui): formlua-bar edit error

packages/core/src/facade/f-enum.ts, packages/sheets/src/facade/f-range.ts
=> feat(facade): supplement getA1Notation api params

packages/docs-ui/src/components/float-toolbar/FloatToolbar.stories.tsx, packages/docs-ui/src/components/float-toolbar/FloatToolbar.tsx, packages/docs-ui/src/controllers/menu/menu.ts, packages/sheets-numfmt-ui/src/views/components/stories/Panel.stories.tsx, packages/ui/src/services/menu/menu-manager.service.ts
=> feat(docs-ui): add FloatToolbar component and its stories

packages/sheets-ui/src/controllers/auto-height.controller.ts
close https://github.com/dream-num/univer-pro/issues/4097
=> fix: get skeleton by subUnit if subUnit exists, not get current skeleton

packages/docs-ui/src/components/float-toolbar/FloatToolbar.tsx, packages/docs-ui/src/controllers/float-menu.controller.ts, packages/docs-ui/src/docs-ui-plugin.ts, packages/docs-ui/src/services/doc-popup-manager.service.ts
=> feat(docs-ui): support float menu on doc

packages/docs-ui/src/components/float-toolbar/FloatToolbar.tsx
=> fix(docs-ui): remove hack to make hidden menu visible of FloatToolbar

packages/docs-ui/src/commands/commands/auto-format.command.ts, packages/docs-ui/src/commands/commands/insert-custom-range.command.ts, packages/docs-ui/src/commands/commands/replace-content.command.ts, packages/docs-ui/src/docs-ui-plugin.ts, packages/docs-ui/src/index.ts
=> feat(docs-ui): add custom-range insert command

packages/docs-quick-insert-ui/package.json, packages/docs-quick-insert-ui/src/controllers/doc-quick-insert-ui.controller.ts, packages/docs-quick-insert-ui/src/locale/en-US.ts, packages/docs-quick-insert-ui/src/locale/fr-FR.ts, packages/docs-quick-insert-ui/src/locale/ru-RU.ts, packages/docs-quick-insert-ui/src/locale/vi-VN.ts, packages/docs-quick-insert-ui/src/locale/zh-CN.ts, packages/docs-quick-insert-ui/src/locale/zh-TW.ts, packages/docs-quick-insert-ui/src/services/doc-quick-insert-popup.service.ts, packages/docs-quick-insert-ui/src/views/KeywordInputPlaceholder.tsx, packages/docs-quick-insert-ui/src/views/QuickInsertPlaceholder.tsx, packages/docs-quick-insert-ui/src/views/QuickInsertPopup.tsx, packages/docs-ui/src/services/doc-popup-manager.service.ts, pnpm-lock.yaml
=> feat: doc quick insert placeholder

packages/docs-quick-insert-ui/src/controllers/doc-quick-insert-ui.controller.ts, packages/docs-quick-insert-ui/src/services/doc-quick-insert-popup.service.ts
=> chore: remove unused variables in quick insert

packages/docs-ui/src/services/doc-popup-manager.service.ts
=> fix(docs-ui): popup direction

packages/docs-quick-insert-ui/src/controllers/doc-quick-insert-ui.controller.ts, packages/docs-quick-insert-ui/src/index.ts, packages/docs-quick-insert-ui/src/views/KeywordInputPlaceholder.tsx, packages/docs-quick-insert-ui/src/views/QuickInsertPlaceholder.tsx, packages/docs-quick-insert-ui/src/views/QuickInsertPopup.tsx
=> chore: rename quick insert component key

packages/core/src/docs/data-model/document-data-model.ts, packages/docs-ui/src/controllers/float-menu.controller.ts
=> feat(docs-ui): disable float-menu if doc was disabled

packages/docs-quick-insert-ui/src/views/QuickInsertPopup.tsx
=> chore: init quick insert menu state

.github/actions/setup-node/action.yml
=> ci: fix ci

examples/src/sheets/main.ts, packages/sheets-numfmt-ui/src/controllers/config.schema.ts, packages/sheets-numfmt-ui/src/controllers/numfmt-alert-render.controller.ts, packages/sheets-numfmt/src/controllers/config.schema.ts, packages/sheets-numfmt/src/controllers/numfmt-cell-content.controller.ts, packages/sheets-numfmt/src/index.ts, packages/sheets-numfmt/src/numfmt-plugin.ts
=> feat: supplement sheets-numfmt text format alert and mark config

packages/sheets-ui/src/views/defined-name/DefinedName.tsx, packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
=> feat(sheets-ui): support disable defined name

packages/docs-drawing-ui/src/controllers/drawing-popup-menu.controller.ts, packages/docs-ui/src/controllers/float-menu.controller.ts
=> feat(docs-drawing-ui): optimize float-dom menu

packages/engine-render/src/shape/scroll-bar.ts, packages/sheets-ui/src/controllers/config.schema.ts, packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts
=> chore: set min thumb size config

packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
=> chore: use final cell when end edit

packages/core/src/docs/data-model/text-x/build-utils/text-x-utils.ts, packages/sheets-formula-ui/src/views/formula-editor/index.tsx
close https://github.com/dream-num/univer-pro/issues/4112
=> fix(sheets-formula-ui): formula highlight display error when delete function name

packages/sheets-ui/src/controllers/menu/menu-util.ts
close https://github.com/dream-num/univer/issues/4866
=> fix(sheets-hyper-link-ui): menu disable status error

packages/docs-ui/src/commands/commands/insert-custom-range.command.ts, packages/docs-ui/src/commands/commands/replace-content.command.ts, packages/engine-render/src/components/docs/layout/style/custom-range.ts
=> fix(docs-ui): insert custom range error

packages/ui/src/views/components/dom/FloatDom.tsx
=> feat(ui): add unitId props to float-dom component

packages/docs-ui/src/controllers/float-menu.controller.ts, packages/docs-ui/src/services/doc-popup-manager.service.ts, packages/ui/src/views/components/popup/RectPopup.tsx
=> fix(docs-ui): popup float menu position

.github/workflows/build.yml
=> ci: improve error message for uncommitted changes in build workflow

packages/ui/src/views/components/dom/FloatDom.tsx
=> feat: add float dom id to Comp

packages/sheets-ui/src/controllers/move-range.controller.ts, packages/sheets-ui/src/services/selection/selection-control.ts, packages/sheets-ui/src/services/selection/selection-shape-extension.ts
=> feat(pivot): support custom sort

packages/core/src/docs/data-model/preset-list-type.ts, packages/core/src/docs/data-model/text-x/build-utils/index.ts, packages/core/src/docs/data-model/text-x/build-utils/paragraph.ts, packages/core/src/docs/data-model/text-x/build-utils/selection.ts, packages/design/src/components/side-menu/index.tsx, packages/design/src/components/side-menu/side-menu.stories.tsx, packages/design/src/index.ts, packages/docs-ui/src/basics/interfaces/component-config/i-doc-ui-plugin-config.ts, packages/docs-ui/src/commands/commands/break-line.command.ts, packages/docs-ui/src/commands/commands/list.command.ts, packages/docs-ui/src/commands/commands/set-heading.command.ts, packages/docs-ui/src/controllers/doc-auto-format.controller.ts, packages/docs-ui/src/controllers/doc-ui.controller.ts, packages/docs-ui/src/docs-ui-plugin.ts, packages/docs-ui/src/services/doc-event-manager.service.ts, packages/docs-ui/src/views/side-menu/index.tsx
=> feat(docs-ui): support doc heading menu

packages/docs-drawing-ui/src/controllers/doc-drawing-notification.controller.ts
=> fix(docs-drawing-ui): remove custom-block error

packages/docs-quick-insert-ui/src/views/QuickInsertPopup.tsx
=> chore: quick insert menu title ellipsis

packages/sheets-numfmt-ui/src/controllers/menu.ts, packages/sheets-numfmt-ui/src/locale/en-US.ts, packages/sheets-numfmt-ui/src/locale/fa-IR.ts, packages/sheets-numfmt-ui/src/locale/fr-FR.ts, packages/sheets-numfmt-ui/src/locale/ru-RU.ts, packages/sheets-numfmt-ui/src/locale/vi-VN.ts, packages/sheets-numfmt-ui/src/locale/zh-CN.ts, packages/sheets-numfmt-ui/src/locale/zh-TW.ts
=> feat: number format menu item adds scientific notation

packages/design/src/components/side-menu/index.tsx, packages/docs-ui/src/views/side-menu/index.tsx
=> feat(docs-ui): open menu default

packages/sheets-ui/src/commands/commands/__tests__/add-worksheet-merge.command.spec.ts, packages/sheets-ui/src/commands/commands/__tests__/create-command-test-bed.ts, packages/sheets-ui/src/common/utils.ts, packages/sheets/src/commands/commands/add-worksheet-merge.command.ts
=> fix: fix merge cell bug

packages/engine-formula/src/engine/utils/cell.ts, packages/engine-formula/src/engine/value-object/primitive-object.ts
=> fix: fix formula calculation for empty strings

examples/src/docs/main.ts, mockdata/src/docs/default-document.data-simple.ts, packages/core/src/types/interfaces/i-document-data.ts, packages/engine-render/src/components/docs/document.ts
=> feat(doc): table support border and bg

packages/docs-ui/src/controllers/float-menu.controller.ts
=> feat(docs-ui): skip float-menu flash

packages/docs-ui/src/services/selection/doc-selection-render.service.ts, packages/docs-ui/src/services/selection/text-range.ts, packages/engine-render/src/components/docs/document.ts
=> feat(docs): update draw cursor and horizontal line

packages/docs-drawing-ui/src/controllers/doc-float-dom.controller.ts, packages/docs-ui/src/controllers/render-controllers/zoom.render-controller.ts, packages/docs-ui/src/services/doc-event-manager.service.ts
=> fix(docs-ui): calc range position error & scale by mouse

packages/engine-render/src/components/docs/document.ts
=> fix(docs): render table cell bg

packages/core/src/docs/data-model/document-data-model.ts, packages/docs-ui/src/views/side-menu/index.tsx
=> feat(docs-ui): optimize doc heading-menu 

packages/design/src/components/side-menu/index.tsx, packages/docs-ui/src/commands/commands/doc-delete.command.ts, packages/docs-ui/src/views/side-menu/index.tsx
=> fix(docs-ui): docs heading-menu auto scroll

packages/docs-ui/src/controllers/menu/menu.ts, packages/docs-ui/src/views/side-menu/index.tsx
=> fix(docs-ui): menu default value calculate error

packages/design/src/components/side-menu/index.tsx, packages/design/src/components/side-menu/side-menu.stories.tsx, packages/docs-ui/src/views/side-menu/index.tsx
=> feat(docs-ui): optimize doc menu scroller

packages/docs-ui/src/controllers/menu/menu.ts
=> fix(docs-ui): menu font-size calc error on heading case

packages/design/src/components/tree/Tree.tsx, packages/sheets-filter-ui/src/views/components/SheetsFilterByValuesPanel.tsx
=> fix(sheets-filter): fix the style issues of the filter panel

packages/core/src/types/const/const.ts, packages/core/src/types/interfaces/i-document-data.ts, packages/docs-ui/src/commands/commands/set-heading.command.ts, packages/docs-ui/src/views/side-menu/index.tsx, packages/engine-render/src/components/docs/layout/block/paragraph/layout-ruler.ts, packages/ui/src/components/font-size/interface.ts
=> fix(docs-ui): support heading spacing style

packages/docs-drawing-ui/src/controllers/render-controllers/doc-drawing-transform-update.controller.ts
=> feat(docs-drawing-ui): mount drawing on rendered phase

packages/core/src/types/const/const.ts, packages/docs-ui/src/commands/commands/inline-format.command.ts, packages/docs-ui/src/controllers/menu/menu.ts
=> fix(docs-ui): float-menu and heading space

packages/core/src/shared/tools.ts, packages/docs-ui/src/commands/commands/inline-format.command.ts, packages/docs-ui/src/controllers/float-menu.controller.ts, packages/docs-ui/src/controllers/menu/menu.ts
=> fix(docs-ui): doc float menu font size calc error

packages/docs-quick-insert-ui/src/controllers/doc-quick-insert-trigger.controller.ts, packages/docs-quick-insert-ui/src/services/doc-quick-insert-popup.service.ts
=> fix: menu popup priority greater than placeholder

packages/core/src/sheets/worksheet.ts, packages/sheets-ui/src/controllers/menu/menu.ts, packages/sheets/src/facade/f-range.ts
=> fix(sheets): facade should return composed style info

packages/design/src/components/tree/Tree.tsx, packages/sheets-filter-ui/src/views/components/index.module.less
=> fix: label hidden in filter panel

packages/core/src/docs/data-model/text-x/build-utils/paragraph.ts
=> fix: build core type error

packages/sheets-numfmt-ui/src/plugin.ts, packages/ui/src/controllers/config.schema.ts, packages/ui/src/ui-plugin.ts, packages/ui/src/views/components/popup/RectPopup.tsx, packages/ui/src/views/workbench/Workbench.tsx
=> feat(ui): optimize popup portal to support multi-instance

packages/sheets-data-validation/src/models/sheet-data-validation-model.ts
=> fix(sheets-data-validation): data-validation status change event not triggered

packages/ui/src/views/workbench/Workbench.tsx
=> fix(ui): replace use with useContext for ConfigContext

packages/docs-quick-insert-ui/src/views/QuickInsertPopup.tsx
=> feat: auto-scroll to the selected menu

packages/sheets/src/controllers/permission/sheet-permission-init.controller.ts, packages/sheets/src/services/permission/workbook-permission/workbook-permission.service.ts
=> chore: add unit permission init state

packages/engine-render/src/components/sheets/extensions/font.ts
close [#4936 ](https://github.com/dream-num/univer/issues/4936)
=> fix: document size do not affected by overflow

packages/sheets-formula/src/facade/f-enum.ts, packages/sheets-formula/src/facade/index.ts, packages/sheets/src/facade/f-defined-name.ts, packages/sheets/src/facade/f-workbook.ts, packages/sheets/src/facade/f-worksheet.ts
=> feat: supplement defined names facade example and notes

packages/core/src/facade/f-event.ts, packages/core/src/facade/f-univer.ts, packages/sheets/src/facade/f-univer.ts
=> feat(facade): command execute event callback add options parameters

packages/engine-render/src/scene.input-manager.ts
=> fix(engine-render): remove duplicated dbClick event

packages/docs-quick-insert-ui/package.json, packages/docs-quick-insert-ui/src/controllers/built-in-menus.ts, packages/docs-quick-insert-ui/src/locale/en-US.ts, packages/docs-quick-insert-ui/src/locale/fa-IR.ts, packages/docs-quick-insert-ui/src/locale/fr-FR.ts, packages/docs-quick-insert-ui/src/locale/ru-RU.ts, packages/docs-quick-insert-ui/src/locale/vi-VN.ts, packages/docs-quick-insert-ui/src/locale/zh-CN.ts, packages/docs-quick-insert-ui/src/locale/zh-TW.ts, packages/docs-quick-insert-ui/src/plugin.ts, pnpm-lock.yaml
=> feat(docs-quick-insert-ui): quick-insert support table and image

packages/docs-ui/src/commands/commands/break-line.command.ts, packages/docs-ui/src/commands/commands/set-heading.command.ts, packages/docs-ui/src/components/paragraph-menu/index.tsx, packages/docs-ui/src/controllers/render-controllers/doc-checklist.render-controller.ts, packages/docs-ui/src/services/doc-event-manager.service.ts, packages/docs-ui/src/services/doc-paragraph-menu.service.ts
close https://github.com/dream-num/univer-pro/issues/4209
close https://github.com/dream-num/univer-pro/issues/4207
close https://github.com/dream-num/univer-pro/issues/4206
close https://github.com/dream-num/univer-pro/issues/4205
close https://github.com/dream-num/univer-pro/issues/4204
close https://github.com/dream-num/univer-pro/issues/4203
=> fix(docs-ui): paragraph menu issues

packages/ui/src/controllers/ui/ui.controller.ts, packages/ui/src/views/components/ribbon/Ribbon.tsx, packages/ui/src/views/workbench/Workbench.tsx
=> chore: add config to hide menu header

packages/design/src/components/menu/index.module.less, packages/docs-ui/src/components/paragraph-menu/index.tsx, packages/docs-ui/src/controllers/menu.schema.ts, packages/docs-ui/src/controllers/menu/paragraph-menu.ts, packages/ui/src/components/menu/desktop/Menu.tsx
=> fix(docs-ui): ui issues about paragraph menu

packages/design/src/components/side-menu/index.tsx, packages/docs-ui/src/components/paragraph-menu/index.tsx, packages/docs-ui/src/docs-ui-plugin.ts, packages/docs-ui/src/services/doc-event-manager.service.ts, packages/docs-ui/src/services/doc-paragraph-menu.service.ts, packages/docs-ui/src/services/float-menu.service.ts
=> feat(docs-ui): optimize paragraph-menu and float-menu interact

packages/core/src/docs/data-model/text-x/build-utils/paragraph.ts, packages/core/src/docs/data-model/text-x/build-utils/selection.ts, packages/docs-ui/src/commands/commands/doc-delete.command.ts, packages/docs-ui/src/commands/commands/doc-paragraph-setting.command.ts, packages/docs-ui/src/commands/commands/insert-below/insert-bullet-below.command.ts, packages/docs-ui/src/commands/commands/list.command.ts, packages/docs-ui/src/commands/commands/paragraph-align.command.ts, packages/docs-ui/src/commands/commands/set-heading.command.ts, packages/docs-ui/src/commands/commands/util.ts, packages/docs-ui/src/controllers/menu/menu.ts, packages/docs-ui/src/services/doc-auto-format.service.ts, packages/docs-ui/src/views/paragraph-setting/hook/utils.ts
=> fix(docs-ui): delete paragraph error on table

packages/core/src/facade/f-univer.ts
=> feat(facade): add Proxy for method existence check in newAPI

packages/docs-ui/src/components/paragraph-menu/index.tsx, packages/docs-ui/src/services/doc-paragraph-menu.service.ts
=> feat(docs-ui): optimize paragraph menu hover

packages/sheets-formula-ui/src/controllers/formula-reorder.controller.ts, packages/sheets-formula-ui/src/index.ts, packages/sheets-formula-ui/src/sheets-formula-ui.plugin.ts, packages/sheets-sort-ui/package.json, packages/sheets-sort-ui/src/commands/commands/__tests__/create-command-test-bed.ts, packages/sheets-sort-ui/src/commands/commands/__tests__/formula-reorder.spec.ts, packages/sheets/src/commands/commands/reorder-range.command.ts, pnpm-lock.yaml
=> fix(formula): fixed the issue where the formula in the range is messed up after the range reorder

packages/design/src/components/select/Select.tsx
=> feat(design): add dropdownClassName prop for custom select dropdown styling

packages/core/src/docs/data-model/text-x/utils.ts, packages/docs-ui/src/services/doc-paragraph-menu.service.ts, packages/docs-ui/src/services/doc-popup-manager.service.ts, packages/docs-ui/src/views/side-menu/index.tsx, packages/ui/src/views/components/popup/CanvasPopup.tsx
…mprove CanvasPopup integration
close #xxx
=> feat(docs-ui): optimize doc side-menu active item calc logic

packages/docs-ui/src/services/doc-paragraph-menu.service.ts
=> feat(docs-ui): add click event handling to hide paragraph menu

README-ja.md, README-zh.md, README.md, SECURITY.md
=> docs: add security doc

packages/design/src/components/menu/Menu.tsx, packages/docs-quick-insert-ui/src/controllers/doc-quick-insert-menu.controller.ts, packages/docs-quick-insert-ui/src/controllers/doc-quick-insert-ui.controller.ts, packages/docs-quick-insert-ui/src/plugin.ts, packages/docs-quick-insert-ui/src/services/doc-quick-insert-popup.service.ts, packages/docs-quick-insert-ui/src/views/QuickInsertPopup.tsx, packages/docs-quick-insert-ui/src/views/menu/index.tsx, packages/docs-ui/src/components/paragraph-menu/index.tsx, packages/docs-ui/src/controllers/menu/paragraph-menu.ts, packages/docs-ui/src/services/doc-paragraph-menu.service.ts
=> feat(docs-quick-insert-ui): implement quick insert menu functionality

packages/core/src/docs/data-model/text-x/utils.ts, packages/docs-quick-insert-ui/src/controllers/doc-quick-insert-menu.controller.ts, packages/docs-ui/src/services/clipboard/clipboard.service.ts, packages/docs-ui/src/services/doc-paragraph-menu.service.ts
=> feat(docs-ui): disable paragraph-menu on disabled

packages/design/src/components/side-menu/index.tsx
=> fix(docs-ui): update side-menu color style

packages/docs-quick-insert-ui/src/services/doc-quick-insert-popup.service.ts, packages/docs-ui/src/services/doc-event-manager.service.ts
=> fix(docs-ui): quick insert menu not show in table cell

packages/drawing-ui/src/controllers/image-update.controller.ts
=> feat(drawing-ui): refresh transform after rendering images

packages/sheets-formula-ui/src/views/formula-editor/hooks/use-highlight.ts, packages/sheets-ui/src/controllers/editor/editing.render-controller.ts, packages/sheets-ui/src/controllers/render-controllers/editor-bridge.render-controller.ts
=> fix(sheets-ui): cell-edit short cut move selection error when content no changed

packages/sheets-drawing-ui/src/controllers/render-controllers/sheet-celll-image-hover.render-controller.ts
=> fix: should not get sheet selection when it was disposed

packages/core/src/facade/f-univer.ts
=> fix: improve property access handling in FUniver class proxy

packages/docs-ui/src/controllers/render-controllers/doc-selection-render.controller.ts, packages/sheets-formula-ui/src/views/formula-editor/index.tsx, packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
=> fix(docs-ui): first move-selection on fx-bar sometimes not working

packages/sheets/src/facade/f-workbook.ts
=> feat: create new sheet API supplement parameters

packages/sheets-hyper-link-ui/src/controllers/menu.ts
=> fix(sheets-hyper-link-ui): link menu not enabled after edit cell end

packages/sheets/src/basics/const/command-listener-const.ts, packages/sheets/src/commands/commands/set-worksheet-column-count.command.ts, packages/sheets/src/commands/commands/set-worksheet-row-count.command.ts, packages/sheets/src/commands/mutations/set-worksheet-column-count.mutation.ts, packages/sheets/src/commands/mutations/set-worksheet-row-count.mutation.ts, packages/sheets/src/controllers/basic-worksheet.controller.ts, packages/sheets/src/facade/f-worksheet.ts, packages/sheets/src/index.ts
=> feat(facade): supplement setRowCount setColumnCount facade

packages/sheets/src/commands/commands/set-worksheet-column-count.command.ts, packages/sheets/src/commands/commands/set-worksheet-row-count.command.ts, packages/sheets/src/commands/mutations/set-worksheet-column-count.mutation.ts, packages/sheets/src/commands/mutations/set-worksheet-row-count.mutation.ts
=> fix: fix setRowCount setColumnCount command

packages/sheets-ui/src/controllers/editor/editing.render-controller.ts, packages/sheets-ui/src/controllers/shortcuts/editor.shortcut.ts
=> fix: fix shortcut ctrl+enter

packages/design/src/components/tree/Tree.stories.tsx, packages/sheets-numfmt-ui/src/views/components/accounting/index.tsx
=> fix: update InputNumber component to include step and precision props

packages/sheets-ui/src/controllers/sheet-ui.controller.ts, packages/sheets-ui/src/controllers/shortcuts/value.shortcut.ts
close https://github.com/dream-num/univer/issues/4038
=> feat(sheets-ui): add Shift and Alt clear selection shortcuts

packages/sheets-ui/src/controllers/sheet-ui.controller.ts, packages/sheets-ui/src/controllers/shortcuts/editor.shortcut.ts
=> feat(sheets-ui): add Shift + Backspace shortcut for deleting left

e2e/perf/scroll.spec.ts, e2e/visual-comparison/sheets/sheets-scroll.spec.ts, packages-experimental/uniui/src/views/workbench/UniWorkbench.tsx, packages/design/src/components/button/Button.tsx, packages/docs-ui/src/services/editor/editor-manager.service.ts, packages/docs-ui/src/services/selection/doc-selection-render.service.ts, packages/engine-render/src/canvas.ts, packages/sheets-ui/src/views/sheet-bar/sheet-bar-button/SheetBarButton.tsx, packages/ui/src/services/layout/layout.service.ts, packages/ui/src/views/mobile-workbench/MobileWorkbench.tsx, packages/ui/src/views/workbench/Workbench.tsx
=> refactor: update component selectors to use data attributes for consistency

packages/docs-ui/src/controllers/doc-ui.controller.ts, packages/docs-ui/src/views/doc-footer/DocFooter.tsx, packages/docs-ui/src/views/side-menu/index.tsx, packages/sheets-data-validation-ui/src/services/dropdown-manager.service.ts, packages/sheets-ui/src/controllers/config.schema.ts, packages/sheets-ui/src/controllers/sheet-ui.controller.ts, packages/sheets-ui/src/views/dropdown/list-dropdown/index.tsx, packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx, packages/sheets-ui/src/views/sheet-container/SheetContainer.tsx, packages/sheets-ui/src/views/status-bar/StatusBar.tsx, packages/ui/src/components/hooks/index.ts, packages/ui/src/components/hooks/layout.ts, packages/ui/src/views/workbench/Workbench.tsx
=> feat(ui): make config dynamic to support set by user through facade

packages/sheets-ui/src/controllers/sheet-ui.controller.ts, packages/sheets-ui/src/controllers/shortcuts/value.shortcut.ts
=> feat(sheets-ui): add Shift + Delete shortcut for cut selection

packages/sheets-ui/src/controllers/config.schema.ts, packages/sheets-ui/src/index.ts, packages/sheets-ui/src/plugin.ts, packages/sheets-ui/src/views/permission/panel-detail/PermissionDetailUserPart.tsx, packages/ui/src/common/component-manager.ts
=> feat(sheets-ui): optimize permission ui custom api

common/shared/package.json, examples/src/sheets/main.ts, package.json, packages/design/package.json, packages/design/src/components/confirm/Confirm.tsx, packages/design/src/components/kbd/Kbd.stories.tsx, packages/design/src/components/kbd/Kbd.tsx, packages/design/src/components/kbd/index.ts, packages/design/src/index.ts, packages/sheets-formula-ui/src/views/range-selector/index.module.less, packages/sheets-formula-ui/src/views/range-selector/index.tsx, packages/sheets-numfmt-ui/src/views/components/custom-format/index.module.less, packages/ui/src/common/menu-merge-configs.ts, packages/ui/src/services/shortcut/shortcut.service.ts, packages/ui/src/views/components/shortcut-panel/ShortcutPanel.tsx, pnpm-lock.yaml
=> feat(design): add KBD component

packages/design/src/components/segmented/Segmented.tsx
=> feat(ui): add segmented component dark mode

packages/design/src/components/input/Input.stories.tsx, packages/design/src/components/input/Input.tsx
=> feat(ui): input support dark mode

e2e/visual-comparison/const.ts, examples/scripts/generate-html.ts, playwright.config.ts
=> chore: disable esbuild hot reload in CI

packages/sheets-ui/src/commands/commands/__tests__/auto-fill.controller.spec.ts, packages/sheets/src/basics/cell-style.ts
=> fix: fix transformStyle

e2e/visual-comparison/docs/docs-visual-comparison.spec.ts, e2e/visual-comparison/sheets/sheets-formula-related.spec.ts, examples/src/sheets/custom-plugin/import-csv-button.ts, examples/src/sheets/main.ts, packages/sheets/src/commands/commands/set-worksheet-column-count.command.ts, packages/sheets/src/commands/commands/set-worksheet-row-count.command.ts, packages/sheets/src/commands/mutations/set-worksheet-column-count.mutation.ts, packages/sheets/src/commands/mutations/set-worksheet-row-count.mutation.ts, packages/sheets/src/facade/index.ts, packages/sheets/src/index.ts
=> chore: demo add import-csv-plugin

packages/sheets-ui/src/controllers/permission/sheet-permission-render.controller.ts
=> chore: no background is needed to mark dirty

packages/design/src/components/button/Button.stories.tsx, packages/design/src/components/button/Button.tsx, packages/design/src/components/button/ButtonGroup.stories.tsx, packages/design/src/components/button/ButtonGroup.tsx
=> feat(design): add ButtonGroup component

e2e/visual-comparison/sheets/sheets-formula-related.spec.ts, packages/design/src/components/button/Button.stories.tsx, packages/design/src/components/button/Button.tsx
=> feat(design): add danger button variant

packages/design/src/components/menu/Menu.tsx, packages/docs-quick-insert-ui/src/views/QuickInsertPlaceholder.tsx, packages/docs-quick-insert-ui/src/views/menu/index.tsx, packages/docs-ui/src/views/side-menu/index.tsx
=> fix(docs-quick-insert-ui): hide empty heading and quck-insert menu filter

common/shared/vite/data.ts, packages/core/package.json, packages/ui/package.json, pnpm-lock.yaml
=> feat: upgrade redi

examples/src/sheets/lazy.ts, examples/src/sheets/main.ts
=> refactor: make more plugins lazy loaded

packages/ui/src/views/components/dom/FloatDom.tsx
=> fix(ui): float-dom error disposed on zen-mode

mockdata/src/sheets/demo/default-workbook-data-demo.ts, packages/docs-ui/src/commands/commands/replace-content.command.ts, packages/docs-ui/src/services/editor/editor.ts, packages/thread-comment-ui/src/locale/en-US.ts, packages/thread-comment-ui/src/locale/fa-IR.ts, packages/thread-comment-ui/src/locale/fr-FR.ts, packages/thread-comment-ui/src/locale/ru-RU.ts, packages/thread-comment-ui/src/locale/vi-VN.ts, packages/thread-comment-ui/src/locale/zh-CN.ts, packages/thread-comment-ui/src/locale/zh-TW.ts, packages/thread-comment-ui/src/views/thread-comment-editor/index.tsx, packages/thread-comment-ui/src/views/thread-comment-editor/util.ts, packages/thread-comment-ui/src/views/thread-comment-panel/index.tsx, packages/thread-comment-ui/src/views/thread-comment-tree/index.tsx, packages/ui/src/controllers/config.schema.ts
=> feat(thread-comment-ui): use tailwindcss to rewrite the style of thread-comment-ui

packages-experimental/uni-formula-ui/package.json, packages/design/src/components/input/Input.stories.tsx, packages/design/src/components/input/Input.tsx, packages/find-replace/src/views/dialog/FindReplaceDialog.tsx, packages/find-replace/src/views/dialog/SearchInput.tsx, pnpm-lock.yaml
=> feat(design): input support slot usage

mockdata/src/sheets/demo/default-workbook-data-demo.ts, packages/sheets-data-validation/src/validators/date-validator.ts, packages/sheets-data-validation/src/validators/decimal-validator.ts, packages/sheets-numfmt/src/controllers/numfmt-cell-content.controller.ts, packages/sheets-numfmt/src/utils/pattern.ts
=> fix(sheets-numfmt-ui): numfmt display NaN if undefind is given

packages/sheets-ui/src/controllers/render-controllers/zoom.render-controller.ts
close https://discord.com/channels/1136129819961217077/1286143813118595166/1356280874190115027
=> fix(sheets-ui): fix zoom not changed on skeleton change

packages/sheets-table-ui/src/commands/operations/open-table-selector.operation.ts, packages/sheets-table-ui/src/controllers/sheet-table-anchor.controller.ts, packages/sheets-table-ui/src/views/components/SheetTableSelector.tsx
=> fix(table): update table anchor display time

packages/docs-ui/src/commands/commands/switch-doc-mode.command.ts, packages/docs-ui/src/index.ts
=> feat(docs-ui): export switch mode command

packages/sheets-table-ui/src/views/components/SheetTableItemsFilterPanel.tsx
=> chore: add table filter search

packages/core/src/types/const/const.ts, packages/docs-drawing-ui/src/controllers/doc-drawing-printing.controller.tsx, packages/drawing/src/models/image-model-interface.ts, packages/sheets-drawing-ui/src/controllers/sheet-drawing-printing.controller.tsx, packages/sheets-drawing/src/services/sheet-drawing.service.ts, packages/ui/src/views/components/confirm-part/ConfirmPart.tsx
=> feat(drawing-ui): support custom printing

packages/docs-drawing-ui/src/controllers/doc-drawing-printing.controller.tsx, packages/docs-ui/src/services/doc-print-interceptor-service.ts, packages/drawing/src/models/image-model-interface.ts, packages/sheets-drawing-ui/src/controllers/sheet-drawing-printing.controller.tsx, packages/sheets-drawing/src/services/sheet-drawing.service.ts, packages/sheets-ui/src/services/print-interceptor.service.ts
=> feat(drawing-ui): support custom printing component

packages/docs-drawing-ui/src/views/printing-float-dom/index.tsx, packages/docs-ui/src/index.ts, packages/sheets-drawing-ui/src/views/printing-float-dom/index.tsx
=> fix(docs-ui): export command from wrong path

packages/docs-drawing-ui/src/controllers/doc-drawing-printing.controller.tsx, packages/docs-drawing-ui/src/views/printing-float-dom/index.tsx, packages/docs-ui/src/services/doc-print-interceptor-service.ts
=> fix(docs-ui): doc print layout calc error

packages/ui/src/index.ts, packages/ui/src/services/message/__testing__/mock-message.service.ts
=> chore(ui): export mock service for testing

packages/design/src/components/dropdown-menu/DropdownMenu.tsx, packages/design/src/components/select/Select.tsx, packages/sheets-filter-ui/src/views/components/SheetsFilterPanel.tsx, packages/sheets-ui/src/views/dropdown/list-dropdown/index.tsx
=> refactor(design): improve type definitions and refactor components for better clarity

examples/src/main.tsx, examples/src/sheets/main.ts, packages/sheets-note-ui/src/index.ts, packages/sheets-note-ui/src/plugin.ts, packages/sheets-note/src/index.ts, packages/sheets-note/src/plugin.ts, packages/sheets-table-ui/src/plugin.ts
=> fix(sheets-note): rename SheetsNotePlugin to UniverSheetsNotePlugin for consistency

packages/engine-formula/src/basics/inverted-index-cache.ts, packages/engine-formula/src/engine/value-object/array-value-object.ts, packages/engine-formula/src/services/runtime.service.ts, packages/sheets/src/controllers/__tests__/formula/array-inverted-index-cache.spec.ts, packages/sheets/src/controllers/__tests__/formula/array-inverted-index-cache2.spec.ts, packages/sheets/src/controllers/__tests__/formula/array-inverted-index-cache3.spec.ts, packages/sheets/src/controllers/__tests__/formula/create-function-test-bed.ts
=> fix(formula): fix CELL_INVERTED_INDEX_CACHE bug

packages/sheets-numfmt-ui/src/controllers/numfmt.editor.controller.ts
=> fix: fixed the issue where the cell number format was cleared after a non-number was entered into the cell

packages-experimental/uniui/src/views/uni-toolbar/UniFormulaBar.tsx, packages/design/src/components/checkbox/Checkbox.tsx, packages/design/src/components/radio/Radio.tsx, packages/design/src/components/select/Select.tsx, packages/drawing-ui/src/views/image-popup-menu/ImagePopupMenu.tsx, packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/ColorScale.tsx, packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/DataBar.tsx, packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/Formula.tsx, packages/sheets-data-validation-ui/src/views/components/formula-input/CustomFormulaInput.tsx, packages/sheets-data-validation-ui/src/views/components/formula-input/ListFormulaInput.tsx, packages/sheets-table-ui/src/views/components/SheetTableConditionPanel.tsx, packages/sheets-ui/src/views/clipboard/ClipboardPopupMenu.tsx, packages/sheets-ui/src/views/defined-name/DefinedNameInput.tsx, packages/slides-ui/src/components/image-popup-menu/ImagePopupMenu.tsx, packages/ui/src/views/workbench/Workbench.tsx
=> fix(*): fix styles

packages/design/src/components/accordion/Accordion.stories.tsx, packages/design/src/components/accordion/Accordion.tsx, packages/design/src/components/dropdown-menu/DropdownMenu.tsx, packages/design/src/components/select-list/SelectList.tsx, packages/design/src/components/select/MultipleSelect.tsx, packages/design/src/components/select/Select.stories.tsx, packages/design/src/components/select/Select.tsx, packages/design/src/index.ts, packages/sheets-filter-ui/src/views/components/SheetsFilterPanel.tsx
=> feat(design): add Accordion

packages/sheets-drawing-ui/src/controllers/render-controllers/sheet-drawing.render-controller.ts
-fix code error for init drawing data
=> fix(drawing): fix some data lost make throw eror

packages/design/src/components/menu/Menu.tsx, packages/docs-ui/src/components/float-toolbar/FloatToolbar.tsx, packages/ui/src/views/components/popup/RectPopup.tsx
=> feat(docs-ui): add doc float toolbar dark mode

packages/sheets-thread-comment-ui/src/controllers/sheets-thread-comment-popup.controller.ts
=> fix(sheets-comment): fix color to adapt dark mode

packages/docs-ui/src/components/paragraph-menu/index.tsx, packages/docs-ui/src/components/side-menu/index.tsx
=> fix(docs-ui): fix dark ui dark mode

packages/core/src/common/invert-color/invert-hsl.ts, packages/core/src/common/invert-color/invert-rgb.ts, packages/core/src/common/invert-color/utils.ts, packages/core/src/index.ts, packages/engine-render/src/services/canvas-color.service.ts
=> feat(color): move invert to core package

packages/ui/src/components/custom-label/CustomLabel.tsx
=> fix(ui): remove unnecessary className for icon component

packages/sheets-ui/src/controllers/menu/menu-util.ts
=> fix(sheets-ui): range disable status error after switch menus

examples/esbuild.config.ts, examples/package.json, examples/src/main.tsx, examples/src/sheets-webcomponent/main.tsx, examples/src/sheets-webcomponent/univer.tsx, pnpm-lock.yaml
=> feat(examples): add webcomponent demo

packages/sheets-data-validation-ui/src/views/components/detail/index.tsx, packages/sheets-data-validation-ui/src/views/components/item/index.tsx, packages/sheets-formula-ui/src/views/range-selector/index.tsx
=> fix(sheets-data-validation-ui): data validation support dark mode

packages/design/src/components/date-picker/index.css, packages/design/src/components/date-range-picker/index.css, packages/design/src/components/select/MultipleSelect.tsx, packages/design/src/components/select/Select.tsx, packages/sheets-table-ui/src/views/components/SheetTableConditionPanel.tsx
=> fix(design): fix border color for dark mode styling

packages/docs-ui/src/services/clipboard/clipboard.service.ts, packages/sheets-table-ui/src/views/menu.ts, packages/sheets-ui/src/controllers/menu/permission-menu-util.ts
=> chore: fix icon disable status when edit not focus

packages/design/src/components/input/Input.tsx, packages/docs-hyper-link-ui/src/views/hyper-link-edit/index.tsx, packages/docs-ui/src/components/side-menu/index.tsx
=> fix: enhance dark mode styles for input and side menu components

packages/sheets-drawing-ui/src/controllers/sheet-drawing-update.controller.ts
…merged cell(#5198)
close #5198
=> fix(sheets-drawing-ui): use start row and col when upload image to a merged cell

packages/core/src/sheets/util.ts, packages/core/src/sheets/worksheet.ts, packages/sheets-formula-ui/src/controllers/formula-ui.controller.ts, packages/sheets-formula-ui/src/controllers/shortcuts/quick-sum.shortcut.ts, packages/sheets-formula-ui/src/locale/en-US.ts, packages/sheets-formula-ui/src/locale/fa-IR.ts, packages/sheets-formula-ui/src/locale/fr-FR.ts, packages/sheets-formula-ui/src/locale/ru-RU.ts, packages/sheets-formula-ui/src/locale/vi-VN.ts, packages/sheets-formula-ui/src/locale/zh-CN.ts, packages/sheets-formula-ui/src/locale/zh-TW.ts, packages/sheets-formula/src/commands/commands/quick-sum.command.ts, packages/sheets-formula/src/controllers/formula.controller.ts, packages/sheets-formula/src/index.ts, packages/sheets/src/basics/expand-range.ts, packages/sheets/src/basics/utils.ts, packages/sheets/src/index.ts
=> feat(sheets-formula): support quick sum method

packages/docs-quick-insert-ui/src/views/menu/index.tsx, packages/sheets-formula-ui/src/views/formula-editor/help-function/HelpFunction.tsx
=> fix(sheets-formula-ui): fix darkmode styles

packages/sheets-ui/src/controllers/menu/clear.menu.ts
=> fix(sheets-ui): fix clear all tooltip

packages/ui/src/views/components/confirm-part/ConfirmPart.tsx
=> fix(ui): confirm-part crash when merge cells

packages/engine-formula/src/basics/token.ts, packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts, packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts
=> fix: fix priority checking

packages/sheets-table-ui/src/views/components/SheetTableThemePanel.tsx, packages/sheets-table/src/facade/f-enum.ts, packages/sheets-table/src/facade/f-workbook.ts, packages/sheets-table/src/facade/f-worksheet.ts, packages/sheets-table/src/facade/index.ts
=> chore: add table facade

examples/src/sheets/lazy.ts, examples/src/sheets/main.ts, packages-experimental/uniui/src/views/uni-toolbar/UniToolbar.tsx, packages/ui/src/services/menu/menu-manager.service.ts, packages/ui/src/views/components/ribbon/Ribbon.tsx
=> perf: (design): enhance menu change handling and improve fake toolbar rendering

packages/docs-ui/src/commands/commands/list.command.ts, packages/docs-ui/src/commands/commands/set-heading.command.ts
=> fix(docs-ui): error set line-spacing & indent

packages/sheets-table/src/facade/f-workbook.ts, packages/sheets-table/src/facade/f-worksheet.ts
=> feat: update sheets-table facade example

packages/sheets-filter-ui/src/views/components/SheetsFilterPanel.tsx
=> fix(sheets-filter-ui): fix panel layout

packages/sheets-formula-ui/src/views/formula-editor/search-function/SearchFunction.tsx, packages/sheets-ui/src/views/editor-container/EditorContainer.tsx
=> fix(sheets-ui): remove unnecessary className for EditorContainer

examples/src/sheets/custom-plugin/import-csv-button.ts, packages/core/src/shared/common.ts, packages/sheets/src/facade/__tests__/utils.spec.ts, packages/sheets/src/facade/f-range.ts, packages/sheets/src/facade/f-worksheet.ts, packages/sheets/src/facade/index.ts, packages/sheets/src/facade/utils.ts
=> feat: move function covertCellValue and covertCellValues to core package

packages/docs-ui/src/commands/commands/replace-content.command.ts, packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts
=> fix(sheets-ui): cursor error when edit started by fx btn

packages/action-recorder/src/controllers/action-recorder.controller.tsx, packages/core/src/facade/f-univer.ts, packages/docs-hyper-link-ui/src/controllers/ui.controller.ts, packages/docs-thread-comment-ui/src/controllers/doc-thread-comment-ui.controller.ts, packages/find-replace/src/controllers/find-replace.controller.ts, packages/sheets-conditional-formatting-ui/src/controllers/cf.panel.controller.ts, packages/sheets-filter-ui/src/controllers/sheets-filter-ui-desktop.controller.ts, packages/sheets-note-ui/src/controllers/sheets-note-ui.controller.ts, packages/sheets-numfmt-ui/src/controllers/numfmt.controller.ts, packages/sheets-numfmt-ui/src/controllers/numfmt.menu.controller.ts, packages/sheets-sort-ui/src/controllers/sheets-sort-ui.controller.ts, packages/sheets-thread-comment-ui/src/controllers/sheets-thread-comment.controller.ts, packages/sheets-ui/src/controllers/cell-alert.controller.ts, packages/sheets-ui/src/plugin.ts, packages/ui/src/controllers/ui/ui-desktop.controller.tsx, packages/ui/src/services/global-zone/desktop-global-zone.service.ts, packages/ui/src/services/zen-zone/desktop-zen-zone.service.ts
=> refactor: optimize component registration

packages/sheets-ui/src/views/sheet-container/SheetContainer.tsx
=> fix: update footer layout and improve menu rendering logic

packages/engine-render/src/shape/scroll-bar.ts
=> fix: fix scroll bar config

packages/sheets/src/model/range-theme-model.ts
Close #5260
- fix code error, the object maybe null
=> fix(univer): fix from json error

packages/core/src/services/resource-manager/resource-manager.service.ts
=> fix: fix resource manager reporting error

packages/sheets-numfmt-ui/src/controllers/numfmt-alert-render.controller.ts, packages/sheets-numfmt/src/controllers/numfmt-cell-content.controller.ts
=> fix: fixed the issue that the numfmt setting for numeric strings does not take effect

packages/sheets-formula-ui/src/controllers/menu.schema.ts
=> fix(sheets-formula-ui): update order of menu items in formula schema for consistency

packages/engine-render/src/components/docs/layout/doc-simple-skeleton.ts
=> fix(engine-render): handle the case that one word would be too long in break-line algo

packages/sheets-ui/src/components/menu-item-input/MenuItemInput.tsx, packages/sheets-ui/src/controllers/menu/menu.ts
=> fix(sheets-ui): enforce min/max constraints for row and column height settings

examples/src/sheets/worker.ts, packages/engine-formula/src/engine/analysis/__tests__/create-command-test-bed.ts, packages/engine-formula/src/engine/value-object/base-value-object.ts, packages/engine-formula/src/engine/value-object/primitive-object.ts, packages/engine-formula/src/functions/__tests__/create-function-test-bed.ts, packages/engine-formula/src/functions/__tests__/nested-functions.spec.ts, packages/engine-formula/src/functions/lookup/function-map.ts, packages/engine-formula/src/functions/lookup/hyperlink/index.ts, packages/engine-formula/src/index.ts, packages/engine-formula/src/models/__tests__/create-command-test-bed.ts, packages/engine-formula/src/plugin.ts, packages/engine-formula/src/services/hyperlink-engine-formula.service.ts, packages/engine-formula/src/services/runtime.service.ts, packages/sheets-formula-ui/src/controllers/__tests__/create-command-test-bed.ts, packages/sheets-formula-ui/src/facade/__tests__/create-formula-test-bed.ts, packages/sheets-formula-ui/src/locale/function-list/lookup/en-US.ts, packages/sheets-formula-ui/src/locale/function-list/lookup/fr-FR.ts, packages/sheets-formula-ui/src/locale/function-list/lookup/ja-JP.ts, packages/sheets-formula-ui/src/locale/function-list/lookup/vi-VN.ts, packages/sheets-formula-ui/src/locale/function-list/lookup/zh-CN.ts, packages/sheets-formula-ui/src/locale/function-list/lookup/zh-TW.ts, packages/sheets-formula/src/services/function-list/lookup.ts, packages/sheets-hyper-link-ui/src/controllers/popup.controller.ts, packages/sheets-sort-ui/src/commands/commands/__tests__/create-command-test-bed.ts, packages/sheets-ui/src/services/clipboard/__tests__/clipboard-test-bed.ts, packages/sheets/src/controllers/__tests__/formula/create-function-test-bed.ts
=> feat(formula): supplement HYPERLINK formula

packages-experimental/debugger/src/views/Fab.tsx, packages/ui/src/services/theme-switcher/theme-switcher.service.ts
=> fix(debugger): conditionally include useUser() based on unitType

packages/core/src/types/interfaces/i-style-data.ts
=> fix(core): update comments for td and pd properties to indicate incomplete implementation

packages/sheets-formula-ui/src/views/formula-editor/hooks/use-highlight.ts
=> fix(sheets-formula-ui): formula-editor highlight error

packages/find-replace/src/views/dialog/FindReplaceDialog.tsx, packages/find-replace/src/views/dialog/SearchInput.tsx
=> fix(find-replace): debounce find string input to improve performance

packages/engine-formula/src/engine/value-object/cube-value-object.ts, packages/engine-formula/src/functions/__tests__/nested-functions.spec.ts, packages/engine-formula/src/functions/lookup/index/__test__/index.spec.ts, packages/engine-formula/src/functions/lookup/index/index.ts
=> fix(formula): fix INDEX formula calculation error

packages/sheets-formula/src/services/function-list/lookup.ts
=> fix(formula): fix INDEX formula description

packages/ui/src/services/menu/menu-manager.service.ts, packages/ui/src/views/components/ribbon/TooltipButtonWrapper.tsx
=> fix(ui): improve hidden state management for menu items

e2e/memory/memory.spec.ts, packages/core/src/index.ts, packages/core/src/services/lifecycle/__tests__/lifecycle.service.spec.ts, packages/core/src/services/lifecycle/lifecycle.service.ts, packages/ui/src/controllers/ui/ui-shared.controller.ts
=> test: ensure no error on disposing tests

mockdata/src/slides/default-pages/page1.ts, mockdata/src/slides/default-pages/page2.ts, mockdata/src/slides/default-pages/page3.ts, mockdata/src/slides/default-pages/page4.ts, mockdata/src/slides/default-pages/page5.ts, mockdata/src/slides/default-pages/page6.ts, mockdata/src/slides/default-pages/page7.ts, mockdata/src/slides/unlimited-slide-data.ts
=> fix: change image cdn

packages/sheets/src/basics/cell-value.ts
- fix value `null`  became string 'null' when set range value
=> fix(value): fix set range value change the null value to string null

packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
=> chore: fix paste text should remove f

packages/network/src/services/http/http.service.ts, packages/network/src/services/http/interceptors/__tests__/merge-interceptor.spec.ts, packages/network/src/services/http/interceptors/__tests__/retry-interceptor.spec.ts, packages/network/src/services/http/interceptors/__tests__/threshold-interceptor.spec.ts
=> feat(network): add stream method for SSE

packages/core/src/shared/rectangle.ts, packages/sheets-formula-ui/src/controllers/__tests__/update-formula.controller.spec.ts, packages/sheets/src/commands/commands/insert-row-col.command.ts
=> fix(formula): fix the calculation error of formula range absolute reference type moving offset

common/shared/vite/data.ts, packages/core/package.json, packages/ui/package.json, pnpm-lock.yaml
=> chore: upgrade redi

examples/src/sheets/main.ts, packages-experimental/uniui/src/views/workbench/UniWorkbench.tsx, packages/sheets-filter-ui/src/controllers/sheets-filter.menu.ts, packages/ui/src/components/menu/mobile/MobileMenu.tsx, packages/ui/src/mobile-plugin.ts, packages/ui/src/views/mobile-workbench/MobileWorkbench.tsx, packages/ui/src/views/workbench/Workbench.tsx
=> chore(mobile): add theme switch service

packages/design/src/components/button/ButtonGroup.tsx, packages/sheets-sort-ui/src/views/EmbedSortBtn.tsx
=> fix(design): fix the styling issue of ButtonGroup

packages/core/src/common/shims.ts, packages/docs-ui/src/services/doc-event-manager.service.ts
fix(core): add polyfill for String.prototype.at
fix(docs-ui): optimize paragraph retrieval logic in DocEventManagerService
=> fix(*): fix compatibility

packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarItem.tsx
=> fix(sheet-ui): optimize the styling of the SheetBarItem

packages/sheets-ui/src/services/editor/cell-editor-resize.service.ts
=> fix(editor): fix footerBarHeight calculation

packages/docs-ui/src/commands/operations/open-page-setting.operation.ts
=> fix(docs-ui): add localized confirm and cancel text for `DocOpenPageSettingCommand`

packages/sheets-numfmt/src/controllers/numfmt-cell-content.controller.ts
=> fix(numfmt): if cell type specified number type, do not determine the type of v

packages/core/src/common/error.ts, packages/engine-render/src/components/sheets/extensions/font.ts, packages/engine-render/src/components/sheets/sheet.render-skeleton.ts, packages/sheets-drawing-ui/src/facade/f-univer.ts
=> fix: padding rendering & not throw cancel error

packages/sheets-formula-ui/src/views/formula-editor/hooks/use-sheet-selection-change.ts
=> fix(sheet-formula-ui): select selection across workbook

packages/sheets-formula-ui/src/controllers/__tests__/update-formula.controller.spec.ts, packages/sheets-formula/src/controllers/update-formula.controller.ts, packages/sheets-formula/src/controllers/utils/ref-range-formula.ts, packages/sheets-formula/src/controllers/utils/ref-range-move.ts, tests/formula-integration/src/__snapshots__/test-formula-move---move-formula-cell-result.json, tests/formula-integration/src/__snapshots__/test-formula-move---move-formula-cell.json, tests/formula-integration/src/__snapshots__/test-formula-move---move-formula-rows-result.json, tests/formula-integration/src/__snapshots__/test-formula-move---move-formula-rows.json, tests/formula-integration/src/__testing__/test-formula-move.ts, tests/formula-integration/src/__tests__/test-formula-move.spec.ts
=> fix(formula): fixed the issue of formula range reference calculating offset when moving rows, columns or ranges

packages/core/src/types/interfaces/i-style-data.ts
=> chore: remove pd property not implemented description

packages/sheets-ui/src/services/selection/selection-shape-extension.ts
=> fix:  fixed the issue where scrolling was reset when the auto fill passed through the freeze line

packages/sheets-ui/src/controllers/editor/editing.render-controller.ts, packages/sheets-ui/src/views/editor-container/hooks.ts
=> fix: fixed the issue where the SheetEditEnded event listener returned incorrect row and column

packages/sheets-table-ui/src/controllers/sheet-table-component.controller.ts
=> feat: use portal to show filter panel

packages/engine-render/src/components/sheets/column-header.ts, packages/engine-render/src/components/sheets/extensions/column-header-layout.ts, packages/engine-render/src/components/sheets/extensions/row-header-layout.ts, packages/engine-render/src/components/sheets/row-header.ts, packages/sheets-ui/src/commands/commands/headersize-changed.command.ts, packages/sheets-ui/src/facade/f-univer.ts, packages/sheets-ui/src/facade/f-workbook.ts, packages/sheets-ui/src/facade/f-worksheet.ts
=> fix(facade): fix customizeColumnHeader and customizeRowHeader api

packages-experimental/debugger/src/components/VueComponent.vue, packages-experimental/debugger/src/components/WebComponent.ts, packages-experimental/debugger/src/controllers/debugger.controller.ts, packages/ui-adapter-vue3/package.json, packages/ui-adapter-vue3/src/plugin.ts, packages/ui-adapter-web-component/package.json, packages/ui-adapter-web-component/src/plugin.ts, packages/ui/src/common/component-manager.ts, pnpm-lock.yaml
=> fix(ui-adapter): remove react dependency from ui adapter packages

packages/sheets-formula-ui/src/views/formula-editor/help-function/HelpFunction.tsx, packages/sheets-formula-ui/src/views/formula-editor/hooks/use-formula-describe.ts, packages/sheets-formula-ui/src/views/formula-editor/index.tsx
close https://github.com/dream-num/univer-pro/issues/3991
=> fix: fix the issue where formula helpfunction does not display

examples/src/sheets/main.ts, packages/thread-comment-ui/src/views/thread-comment-panel/index.tsx
=> fix: fix thread-comment-ui add comment i18n

packages/engine-render/src/components/docs/layout/tools.ts
=> fix(doc): fix some code error

common/shared/vite/data.ts, packages/ui-adapter-vue3/package.json, pnpm-lock.yaml
=> fix(ui-adapter-vue3): update peerDependencies to require Vue 3.0.0 or higher

packages/sheets-note/src/facade/f-event.ts, packages/sheets-note/src/facade/f-range.ts, packages/sheets-note/src/facade/f-univer.ts, packages/sheets-note/src/facade/f-worksheet.ts, packages/sheets-table/src/facade/f-worksheet.ts
=> fix(dts): simplify interface declarations and improve method overrides in event and range modules

packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts
=> feat(sheets-drawing-ui): add updateFloatDomProps

README-ja.md, README-zh.md, README.md, packages/design/src/components/button/ButtonGroup.tsx, packages/sheets-filter-ui/src/views/components/SheetsFilterPanel.tsx
=> fix(sheets-filter-ui): adjust width of filter panel component

examples/src/mobile-s/main.ts, packages/sheets-ui/src/controllers/mobile/mobile-sheet-ui.controller.ts, packages/sheets-ui/src/mobile-plugin.ts, packages/ui/src/mobile-plugin.ts
=> feat: enhance mobile UI by adding new plugins and improving component registration

packages/sheets-data-validation-ui/src/services/dropdown-manager.service.ts, packages/sheets-ui/src/views/dropdown/date-dropdown/index.tsx
=> fix(sheets-data-validation-ui): reorder `SetCellEditVisibleOperation` command execution

common/shared/package.json, package.json, packages-experimental/uniui/package.json, packages/core/src/common/di.ts, packages/sheets-formula-ui/src/views/formula-editor/index.tsx, packages/ui/src/views/mobile-workbench/MobileWorkbench.tsx, packages/ui/src/views/workbench/Workbench.tsx, pnpm-lock.yaml
=> fix(ui): add dark mode support for custom header

packages/sheets-ui/src/views/dropdown/list-dropdown/index.tsx
=> fix(sheets-ui): improve layout and styling of SelectList component

packages/sheets-data-validation-ui/src/services/dropdown-manager.service.ts
=> fix(sheets-data-validation-ui): set default color for dropdown options when color is not provided

packages/core/src/docs/data-model/document-data-model.ts, packages/docs-ui/src/basics/component-tools.ts, packages/docs-ui/src/commands/operations/set-doc-zoom-ratio.operation.ts, packages/sheets-ui/src/services/editor-bridge.service.ts
=> refactor(docs-ui): refactor zoom ratio handling in document operations

packages/sheets-formula-ui/src/locale/function-list/math/en-US.ts, packages/sheets-formula-ui/src/locale/function-list/math/ru-RU.ts, packages/sheets-formula-ui/src/locale/function-list/statistical/en-US.ts, packages/sheets-formula-ui/src/locale/ru-RU.ts
Localize the data contained in Math sheets formula UI
Change locales to LocaleType.RU_RU
Before:
After:
d
=> feat: add ru localization in math sheets formula UI

packages/sheets/src/facade/f-permission.ts
=> chore: add getPermissionInfoWithCell facade api example

packages/design/package.json, packages/sheets-sort-ui/src/controllers/sheets-sort-ui.controller.ts, pnpm-lock.yaml
=> fix(sheets-sort-ui): update default position calculation for custom sort dialog

packages/slides-ui/src/commands/operations/insert-shape.operation.ts, packages/slides-ui/src/controllers/menu.schema.ts, packages/slides-ui/src/controllers/shape.menu.ts, packages/slides-ui/src/controllers/slide-ui.controller.ts, packages/slides-ui/src/index.ts, packages/slides-ui/src/locale/ca-ES.ts, packages/slides-ui/src/locale/en-US.ts, packages/slides-ui/src/locale/es-ES.ts, packages/slides-ui/src/locale/fa-IR.ts, packages/slides-ui/src/locale/fr-FR.ts, packages/slides-ui/src/locale/ko-KR.ts, packages/slides-ui/src/locale/zh-CN.ts, packages/slides/src/views/render/adaptors/shape-adaptor.ts
Allows you to connect a circle shape.
Run Demo, go to Slides, press the buttons figure, press insert ellipse. I left a video of an example of work in Discord.
=> feat: add insert ellipse in Slides

examples/src/sheets/main.ts, examples/src/sheets/worker.ts, packages/core/src/univer.ts
=> feat(core): add register multi plugins API

examples/package.json, package.json, pnpm-lock.yaml
=> chore(deps): update dependencies

packages/sheets-ui/src/views/permission/panel-detail/PermissionDetailUserPart.tsx, packages/sheets-ui/src/views/permission/panel-list/index.tsx
=> fix(sheets-ui): fix permssion panel styles for better readability

examples/src/sheets/main.ts, packages/engine-render/src/base-object.ts, packages/engine-render/src/scene.input-manager.ts, packages/engine-render/src/scene.ts, packages/engine-render/src/shape/rect.ts, packages/engine-render/src/shape/scroll-bar.ts, packages/engine-render/src/shape/shape.ts, packages/sheets-formula-ui/src/services/render-services/ref-selections.render-service.ts, packages/sheets-ui/src/services/selection/base-selection-render.service.ts, packages/sheets-ui/src/services/selection/selection-render.service.ts, packages/sheets-ui/src/services/selection/selection-shape-extension.ts
=> fix: no need disable event in scrollbar and selection

packages/sheets/src/services/permission/workbook-permission/util.ts
=> chore: update default workbook point

packages/engine-render/src/components/sheets/extensions/font.ts
=> fix(render): fix true and false render

packages/engine-formula/src/engine/utils/value-object.ts, packages/sheets/src/controllers/__tests__/formula/countifs.spec.ts, packages/sheets/src/controllers/__tests__/formula/sumifs.spec.ts
…ncorrectly with <> operator
close #5593
=> fix(formula): fixed the issue that formulas such as COUNTIFS would calculate incorrectly with <> operator

packages/sheets-filter-ui/src/views/components/SheetsFilterByValuesPanel.tsx
=> chore: fix filter panel width

packages/core/src/shared/tools.ts, packages/engine-render/src/components/docs/layout/shaping-engine/font-library.ts
=> fix(engine-render): disable queryLocalFonts in Electron to prevent memory overflow

packages/design/src/components/calendar/Calendar.tsx
=> fix(design): fix DayButton styles for Calendar

packages/sheets-ui/src/controllers/menu/insert.menu.ts
=> fix: fix context menu insert control

examples/src/sheets/main.ts, packages/engine-render/src/base-object.ts, packages/engine-render/src/scene.input-manager.ts, packages/engine-render/src/scene.ts, packages/engine-render/src/shape/scroll-bar.ts, packages/engine-render/src/shape/shape.ts, packages/sheets-formula-ui/src/services/render-services/ref-selections.render-service.ts, packages/sheets-ui/src/services/selection/base-selection-render.service.ts, packages/sheets-ui/src/services/selection/selection-render.service.ts, packages/sheets-ui/src/services/selection/selection-shape-extension.ts
=> refactor: revert "fix: no need disable event in scrollbar and selection"

packages/engine-formula/src/functions/financial/xnpv/__tests__/index.spec.ts, packages/engine-formula/src/functions/financial/xnpv/index.ts, packages/engine-formula/src/functions/math/sumproduct/__tests__/index.spec.ts, packages/engine-formula/src/functions/math/sumproduct/index.ts, packages/sheets-formula-ui/src/views/formula-editor/hooks/use-formula-describe.ts, packages/sheets-numfmt-ui/src/controllers/numfmt-alert-render.controller.ts, packages/sheets-ui/src/controllers/status-bar.controller.ts, packages/sheets/src/facade/f-range.ts
=> fix: fixed some formula and 0 value judgment issues

packages/engine-render/src/components/sheets/sheet.render-skeleton.ts
=> fix(render): fix auto height calculate

packages/engine-render/src/components/sheets/extensions/font.ts, packages/engine-render/src/shape/text.ts
close #3112
close https://github.com/dream-num/univer-pro/issues/4260
=> feat: optimized number rendering when cell width less than text width

packages/engine-render/src/components/sheets/extensions/font.ts
=> fix: fix number render when cell type is undefined or null

packages/core/src/sheets/util.ts
=> fix(editor): fix after delete cell content using backspace, the cell does not enter edit mode

packages/sheets-filter-ui/src/views/render-modules/sheets-filter.render-controller.ts
=> chore: remove unused code

packages/sheets-filter-ui/src/views/render-modules/sheets-filter.render-controller.ts
- fix filter style not effect range theme style
=> fix(filter): fix filter button style not effect range theme

packages/sheets-numfmt-ui/src/controllers/__tests__/editor.controller.spec.ts, packages/sheets-numfmt-ui/src/controllers/numfmt.editor.controller.ts, packages/sheets-numfmt/src/index.ts, packages/sheets-numfmt/src/utils/pattern.ts
=> fix(numfmt): filter some erroneous numfmt pattern conversions

packages/sheets-ui/src/services/cell-popup-manager.service.ts
=> fix(sheets-ui): make disposable property optional and handle undefined case

packages/sheets-ui/src/locale/ru-RU.ts
=> fix(locale): uppcase for text panel ui

.vscode/settings.json, packages/sheets-data-validation/src/services/dv-cache.service.ts
=> fix(sheets-data-validation): performance issues when edit whole cells on large scale

CONTRIBUTING.md
This small PR fixes the Facade contribution guide reference in `CONTRIBUTING.md`.
=> fix: update Facade contribution guide

packages/sheets-numfmt-ui/package.json, packages/sheets-numfmt-ui/src/controllers/numfmt.editor.controller.ts, packages/sheets-numfmt/src/controllers/numfmt-cell-content.controller.ts, packages/sheets-numfmt/src/utils/pattern.ts, packages/sheets/src/controllers/number-cell.controller.ts, packages/sheets/src/controllers/permission/sheet-permission-view-model.controller.ts, packages/sheets/src/model/range-theme-model.ts, pnpm-lock.yaml
=> fix: fix the issue of digital precision display

packages/sheets-data-validation/src/facade/f-range.ts, packages/sheets-data-validation/src/facade/f-workbook.ts, packages/sheets-data-validation/src/facade/f-worksheet.ts, packages/sheets-data-validation/src/services/dv-validator-service.ts
=> feat: add data validation error handling in workbook and worksheet mixins

packages/ui/src/views/components/ribbon/Ribbon.tsx
=> fix(ui): adjust grid class to prevent shrinking in active group display of Ribbon

packages/design/src/components/switch/Switch.tsx, packages/sheets-ui/src/views/permission/permission-dialog/index.tsx
=> fix(design): update background color for unchecked state in Switch component

packages/sheets-formula-ui/src/views/formula-editor/hooks/use-formula-search.ts, packages/sheets-formula-ui/src/views/formula-editor/search-function/SearchFunction.tsx, packages/sheets-formula/src/index.ts, packages/sheets-formula/src/services/description.service.ts
- #5800   fix the define name been treat as function
=> fix(formular): fix define name should not add (

packages/sheets-table-ui/src/locale/ca-ES.ts, packages/sheets-table-ui/src/locale/en-US.ts, packages/sheets-table-ui/src/locale/es-ES.ts, packages/sheets-table-ui/src/locale/fa-IR.ts, packages/sheets-table-ui/src/locale/fr-FR.ts, packages/sheets-table-ui/src/locale/ko-KR.ts, packages/sheets-table-ui/src/locale/ru-RU.ts, packages/sheets-table-ui/src/locale/vi-VN.ts, packages/sheets-table-ui/src/locale/zh-CN.ts, packages/sheets-table-ui/src/locale/zh-TW.ts, packages/sheets-table-ui/src/views/components/SheetTableFilterPanel.tsx, packages/sheets-table-ui/src/views/components/SheetTableItemsFilterPanel.tsx, packages/sheets-table/src/controllers/config.schema.ts, packages/sheets-table/src/controllers/sheet-table-theme.controller.ts, packages/sheets-table/src/facade/f-workbook.ts, packages/sheets-table/src/facade/f-worksheet.ts, packages/sheets-table/src/model/table-manager.ts, packages/sheets-table/src/model/table.ts, packages/sheets-table/src/types/type.ts
=> fix(table): fix sheets-table facade api

packages/design/src/components/tree/Tree.tsx, packages/sheets-filter-ui/src/views/components/SheetsFilterSyncSwitch.tsx, packages/ui/src/components/slider/Slider.tsx
=> fix(ui): update Tooltip and span classes for better styling

README-es.md, README-ja.md, README-zh.md, README.md
=> docs: add univer mcp repository

packages/engine-render/src/components/sheets/sheet.render-skeleton.ts, packages/engine-render/src/components/sheets/spreadsheet.ts
=> fix(engine-render): fix sheets print issue

packages/sheets-drawing-ui/src/controllers/sheet-drawing-transform-affected.controller.ts, packages/sheets/src/commands/commands/delete-range-move-left.command.ts, packages/sheets/src/commands/commands/delete-range-move-up.command.ts, packages/sheets/src/commands/commands/insert-range-move-down.command.ts, packages/sheets/src/commands/commands/insert-range-move-right.command.ts, packages/sheets/src/commands/commands/insert-row-col.command.ts, packages/sheets/src/commands/commands/move-range.command.ts, packages/sheets/src/commands/commands/move-rows-cols.command.ts, packages/sheets/src/commands/commands/remove-row-col.command.ts, packages/sheets/src/commands/commands/set-col-visible.command.ts, packages/sheets/src/commands/commands/set-row-visible.command.ts, packages/sheets/src/commands/commands/set-worksheet-col-width.command.ts, packages/sheets/src/commands/commands/set-worksheet-row-height.command.ts
=> fix(drawing): fix sheets drawing transform when insert rows, columns, etc.

CONTRIBUTING.md, README-es.md, README-ja.md, README-zh.md, README.md, packages/core/README.md, packages/design/README.md, packages/rpc/README.md, packages/sheets-formula-ui/README.md, packages/sheets-formula/README.md, packages/ui/src/facade/f-univer.ts, packages/uniscript/README.md
=> chore: fix some links

packages/sheets-ui/src/controllers/format-painter/format-painter.controller.ts
=> fix: fix format painter selection issue

packages/core/src/shared/name.ts, packages/sheets-table/src/commands/commands/set-sheet-table.command.ts, packages/sheets-table/src/model/table-manager.ts
- fix table name check function error
- fix #5870
=> fix(table): fix table name error

mockdata/src/sheets/demo/default-workbook-data-demo.ts, packages/core/src/shared/index.ts, packages/core/src/shared/numfmt.ts, packages/engine-formula/src/engine/value-object/primitive-object.ts, packages/sheets-numfmt-ui/src/controllers/numfmt.editor.controller.ts, packages/sheets-numfmt/src/index.ts, packages/sheets-numfmt/src/utils/pattern.ts, packages/sheets-ui/src/controllers/force-string-alert-render.controller.ts, packages/sheets-ui/src/controllers/force-string-render.controller.ts
=> fix(formula): fix the issue where +-*/ formula could not calculate text that can be converted to numbers

packages/sheets-data-validation-ui/src/views/widgets/dropdown-widget.ts
=> fix(dropdown-widget): adjust padding calculations and clipping areas for better text rendering

packages/sheets-table/src/index.ts
=> fix(type): add table type

packages/sheets-formula-ui/src/views/formula-editor/hooks/use-refactor-effect.ts
=> fix(sheets-formula-ui): handle potential null reference for currentDoc in useRefactorEffect
