dream-num/univer

- .gitignore
- package.json
- pnpm-lock.yaml
- scripts/common.js
- used the `alias` option to replace the `preactCompatPlugin`.
- removed the exclusion of the `pnpm-lock.yaml` from the `.gitignore` to ensure consistency between the local env and the CI env dependencies.
> chore(esbuild): remove preactCompatPlugin & remove pnpm-lock.yaml from .gitignore

- .eslintrc.js
- package.json
- pnpm-lock.yaml
New dependencies:
- simple-import-sort
> chore(lint): add import sorting rules & magic number warnings

- examples/univer-sheet-ts/src/locales.ts
- examples/univer-sheet-ts/src/main.tsx
- packages/base-docs/src/DocPlugin.ts
- packages/base-docs/src/index.ts
- packages/base-sheets/src/SheetPlugin.ts
- packages/base-sheets/src/index.ts
- packages/base-slides/src/SlidePlugin.ts
- packages/base-slides/src/index.ts
- packages/base-ui/src/index.ts
- packages/base-ui/src/views/app.tsx
- packages/core/src/Basics/Univer.ts
- packages/core/src/Shared/Locale.ts
- packages/core/src/Types/Interfaces/IUniverData.ts
- packages/core/src/services/locale.service.ts
- packages/sheets-plugin-filter/src/index.ts
- packages/sheets-plugin-find/src/FindPlugin.ts
- packages/sheets-plugin-find/src/index.ts
- packages/sheets-plugin-formula/src/FormulaPlugin.tsx
- packages/sheets-plugin-formula/src/index.ts
- packages/sheets-plugin-import-xlsx/src/ImportXlsxPlugin.tsx
- packages/sheets-plugin-import-xlsx/src/index.ts
- packages/sheets-plugin-numfmt/src/NumfmtPlugin.ts
- packages/sheets-plugin-numfmt/src/index.ts
- packages/sheets-plugin-operation/src/OperationPlugin.ts
- packages/sheets-plugin-operation/src/index.ts
- packages/ui-plugin-docs/src/doc-ui-plugin.ts
- packages/ui-plugin-sheets/src/sheet-ui-plugin.ts
- packages/ui-plugin-slides/src/SlideUIPlugin.ts
close #70 
- Default language is set to `en`.
- Exported locale modules for each plugin.
- Provided configuration for injecting language packs.
- Introduced a method to modify the language: `setLocale(locale): void => {}`.
TODO:
1. Specification language codes
zh => zh-CN
en => en-US
2. Drop `Shared/Locale.ts`
> refactor(i18n): redesign i18n

- packages/base-sheets/src/Controller/auto-height.controller.ts
- packages/base-sheets/src/Controller/header-menu.controller.ts
- packages/base-sheets/src/commands/commands/__tests__/add-worksheet-merge.command.spec.ts
- packages/base-sheets/src/commands/commands/__tests__/clear-selection.command.spec.ts
- packages/base-sheets/src/commands/commands/add-worksheet-merge.command.ts
- packages/base-sheets/src/commands/commands/clear-selection-all.command.ts
- packages/base-sheets/src/commands/commands/clear-selection-content.command.ts
- packages/base-sheets/src/commands/commands/clear-selection-format.command.ts
- packages/base-sheets/src/commands/commands/copy-format-to-range.command.ts
- packages/base-sheets/src/commands/commands/copy-range-to.command.ts
- packages/base-sheets/src/commands/commands/copy-values-to-range.command.ts
- packages/base-sheets/src/commands/commands/delete-range-move-left.command.ts
- packages/base-sheets/src/commands/commands/delete-range-move-up.command.ts
- packages/base-sheets/src/commands/commands/insert-range-move-down.command.ts
- packages/base-sheets/src/commands/commands/insert-range-move-right.command.ts
- packages/base-sheets/src/commands/commands/move-range-to.command.ts
- packages/base-sheets/src/commands/commands/remove-worksheet-merge.command.ts
- packages/base-sheets/src/commands/commands/set-border-command.ts
- packages/base-sheets/src/commands/commands/set-border-styles-command.ts
- packages/base-sheets/src/commands/commands/set-range-formatted-value.command.ts
- packages/base-sheets/src/commands/commands/set-range-values.command.ts
- packages/base-sheets/src/commands/commands/set-style.command.ts
- packages/base-sheets/src/commands/commands/set-worksheet-col-width.command.ts
- packages/base-sheets/src/commands/commands/set-worksheet-row-height.command.ts
- packages/base-sheets/src/commands/commands/trim-whitespace.command.ts
- packages/base-sheets/src/services/selection/selection-manager.service.ts
rename gitRangeDatas to getSelectionRanges
> refactor(sheet): rename gitRangeDatas to getSelectionRanges

- packages/base-docs/src/Controller/move-cursor.controller.ts
- packages/base-docs/src/DocPlugin.ts
- packages/base-docs/src/commands/operations/cursor.operation.ts
- packages/base-docs/src/commands/operations/text-selection.operation.ts
- packages/base-docs/src/index.ts
- packages/base-docs/src/shortcuts/cursor.shortcut.ts
- packages/base-render/src/Component/Docs/text-selection-render-manager.ts
- packages/base-ui/src/services/shortcut/shortcut.service.ts
> feat(doc): move selection by shift + arrow keys

- packages/base-render/src/basics/draw.ts
- packages/base-render/src/components/sheets/sheet-skeleton.ts
- packages/base-render/src/components/sheets/spreadsheet.ts
> fix: calculate the document height when text rotated

- packages/base-docs/src/commands/mutations/__tests__/apply-utils.spec.ts
- packages/base-docs/src/commands/mutations/functions/common.ts
> fix: if textRuns doesn't intersect, they shouldn't be merged

- packages/ui-plugin-sheets/src/commands/commands/rename.command.ts
- packages/ui-plugin-sheets/src/locale/en-US.ts
- packages/ui-plugin-sheets/src/locale/zh-CN.ts
- packages/ui-plugin-sheets/src/views/sheet-bar/SheetBar.tsx
- packages/ui-plugin-sheets/src/views/sheet-bar/index.module.less
- packages/ui-plugin-sheets/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx
- packages/ui-plugin-sheets/src/views/sheet-bar/sheet-bar-tabs/utils/slide-tab-bar.ts
> fix(sheet): sheet bar scroll button's state

- packages/base-render/src/components/docs/document.ts
- packages/base-render/src/components/docs/extensions/font-and-base-line.ts
- packages/base-render/src/components/docs/extensions/line.ts
> fix: underline position offset is wrong when has margin top

- packages/sheets-ui/src/controllers/editor/end-edit.controller.ts
- packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
- packages/sheets-ui/src/services/editor-bridge.service.ts
> fix(sheet): no need to modify sheet cell data when cell editor is not dirty

- packages/sheets-ui/src/commands/commands/__tests__/set-format-painter.command.spec.ts
- packages/sheets-ui/src/commands/commands/add-worksheet-merge.command.ts
- packages/sheets-ui/src/commands/commands/auto-fill.command.ts
- packages/sheets-ui/src/commands/commands/set-format-painter.command.ts
- packages/sheets-ui/src/common/utils.ts
- packages/sheets-ui/src/controllers/format-painter/format-painter.controller.ts
- packages/sheets-ui/src/controllers/sheet-ui.controller.ts
- packages/sheets-ui/src/services/clipboard/clipboard.service.ts
- packages/sheets-ui/src/services/format-painter/format-painter.service.ts
- packages/sheets-ui/src/services/mark-selection/mark-selection.service.ts
- packages/sheets/src/services/selection-manager.service.ts
1. format painter set merges
2. set cursor when format painter is enabled
3. range mark conflicts between format-painter and clipboard
4. delete useless merge mutation
5. set copy range style
> fix: bugs in format painter

- packages/rpc/src/plugin.ts
Provide a direct way to pass instance of worker into build tools like Vite and webpack that naturally support web workers
https://vitejs.dev/guide/features#web-workers
https://webpack.js.org/guides/web-workers
```diff 
+ import UniverWorker from './worker?worker'
univer.registerPlugin(UniverRPCMainThreadPlugin, {
-    workerURL: './worker.js',
+    workerUrl: new UniverWorker()
} as IUniverRPCMainThreadConfig);
```
> feat(rpc): allow passing an existing Worker

- examples/src/plugins/local-save/controller/record.controller.ts
- packages/sheets-numfmt/src/components/more-numfmt-type/MoreNumfmtType.tsx
- packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx
- packages/ui/src/views/components/context-menu/ContextMenu.tsx
- packages/ui/src/views/components/doc-bars/ToolbarItem.tsx
> fix: #911 using the undo shortcut after you clear the content goes into edit mode

- packages/docs/src/views/doc-canvas-view.ts
- packages/engine-render/src/scene.ts
- packages/engine-render/src/shape/scroll-bar.ts
- packages/engine-render/src/thin-scene.ts
- packages/engine-render/src/viewport.ts
- packages/sheets-ui/src/views/sheet-canvas-view.ts
- packages/slides/src/views/render/adaptors/docs-adaptor.ts
- packages/slides/src/views/render/adaptors/spreadsheet-adaptor.ts
- packages/slides/src/views/render/canvas-view.ts
> fix(render): horizon scroll bar

- .github/workflows/ci-test.yml
> ci: only report coverage when node-version is 18

- examples/src/uniscript/change-font-style.js
- packages/facade/src/apis/sheet/__tests__/f-range.spec.ts
- packages/facade/src/apis/sheet/f-range.ts
- packages/sheets/src/index.ts
#1009 
```js
const activeSheet = univerAPI.getCurrentSheet().getActiveSheet();
// Set A1:B2 to bold
activeSheet.getRange(0, 0, 2, 2).setFontWeight('bold');
// Set B2 to normal
activeSheet.getRange(1, 1, 1, 1).setFontWeight('normal');
// reset A1 to normal
activeSheet.getRange(0, 0, 1, 1).setFontWeight(null);
```
> feat(facade): range API add setFontWeight

- packages/sheets-ui/src/controllers/selection.controller.ts
- packages/sheets-ui/src/services/selection/selection-render.service.ts
> fix(sheet): update for change

- packages/sheets-ui/src/components/menu-item-input/MenuItemInput.tsx
- packages/sheets-ui/src/components/menu-item-input/interface.ts
- packages/sheets-ui/src/controllers/header-menu.controller.ts
- packages/sheets-ui/src/controllers/menu/__tests__/create-menu-test-bed.ts
- packages/sheets-ui/src/controllers/menu/menu.ts
close #1068
close #1076
1. Univer will now selected the column if the context menu is not triggerred in the selected range
2. Row height & column width has a minimum value of 2px
> fix(header): fix selected range not changed when clicking menu

- examples/src/data/sheets/demo/default-workbook-data-demo.ts
- packages/core/src/sheets/__tests__/create-core-test-bed.ts
- packages/core/src/sheets/__tests__/workbook.spec.ts
- packages/core/src/sheets/workbook.ts
- packages/sheets-ui/src/views/sheet-bar/sheet-bar-menu/index.module.less
- packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarItem.tsx
- packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/index.module.less
- packages/sheets/src/commands/commands/__tests__/create-command-test-bed.ts
- packages/sheets/src/commands/commands/insert-sheet.command.ts
- packages/sheets/src/locale/en-US.ts
- packages/sheets/src/locale/zh-CN.ts
> fix(sheet): sheet bar menu style

- packages/core/src/sheets/__tests__/reference.spec.ts
- packages/core/src/sheets/reference.ts
> fix(formula): deserializeRangeWithSheet add rangeType

- packages/core/src/shared/object-matrix.ts
- packages/sheets/src/commands/commands/__tests__/insert-range.command.spec.ts
- packages/sheets/src/commands/commands/insert-range-move-down.command.ts
- packages/sheets/src/commands/commands/insert-range-move-right.command.ts
- packages/sheets/src/commands/commands/insert-row-col.command.ts
- packages/sheets/src/commands/commands/move-range.command.ts
- packages/sheets/src/commands/commands/remove-row-col.command.ts
- packages/sheets/src/commands/mutations/insert-row-col.mutation.ts
- packages/sheets/src/commands/mutations/remove-row-col.mutation.ts
> feat: change insert/delete row/col mutation implement

- packages/core/src/sheets/row-manager.ts
- packages/core/src/types/interfaces/i-row-data.ts
- packages/engine-render/src/components/sheets/sheet-skeleton.ts
- packages/sheets-ui/src/services/selection/__test__/create-service-test-bed.ts
- packages/sheets/src/commands/commands/__tests__/set-row-height.command.spec.ts
- packages/sheets/src/commands/commands/set-worksheet-row-height.command.ts
- packages/sheets/src/commands/mutations/__tests__/create-command-test-bed.ts
- packages/sheets/src/commands/mutations/__tests__/remove-row-col.mutation.spec.ts
- packages/sheets/src/commands/mutations/set-worksheet-row-height.mutation.ts
> refactor: rename isAutoHeight to `ia` and change its TS type

- packages/engine-render/src/components/docs/text-selection-render-manager.ts
- packages/engine-render/src/components/sheets/extensions/font.ts
- packages/engine-render/src/engine.ts
- packages/engine-render/src/thin-engine.ts
- packages/sheets-formula/src/controllers/prompt.controller.ts
> fix(sheet): formula offscreen

- packages/core/src/docs/data-model/document-data-model.ts
- packages/core/src/docs/data-model/mutation-types.ts
- packages/core/src/docs/data-model/text-x/README.md
- packages/core/src/docs/data-model/text-x/__tests__/text-x.spec.ts
- packages/core/src/docs/data-model/text-x/text-x.ts
- packages/core/src/docs/data-model/types.ts
- packages/core/src/index.ts
- packages/docs/src/basics/retain-delete-params.ts
- packages/docs/src/commands/commands/clipboard.inner.command.ts
- packages/docs/src/commands/commands/core-editing.command.ts
- packages/docs/src/commands/commands/delete.command.ts
- packages/docs/src/commands/commands/ime-input.command.ts
- packages/docs/src/commands/commands/inline-format.command.ts
- packages/docs/src/commands/commands/list.command.ts
- packages/docs/src/commands/commands/replace-content.command.ts
- packages/docs/src/commands/mutations/core-editing.mutation.ts
> refactor: add textX to build and serialize actions

- packages/facade/src/apis/sheet/__tests__/f-range.spec.ts
- packages/facade/src/apis/sheet/f-range.ts
- packages/facade/src/index.ts
- packages/sheets/src/commands/mutations/set-range-values.mutation.ts
close #1009
Add Facade range APIs:
```ts
const activeSheet = univerAPI.getActiveWorkbook().getActiveSheet();
const range = activeSheet.getRange(0, 0);
range.setValue('a');
// 获取单元格数据
const cellData = range .getCellData(); // like { v : "a" }
```
```ts
const activeSheet = univerAPI.getActiveWorkbook().getActiveSheet();
// 获取单元格样式数据
const range = activeSheet.getRange(0, 0);
range.setFontWeight('bold');
const cellStyleData = activeSheet.getRange(0, 0).getCellStyleData(); // reuslt like { bl: 1 }
```
```ts
const activeSheet = univerAPI.getActiveWorkbook().getActiveSheet();
// 设置单元格样式数据
const range = activeSheet.getRange(0, 0, 2, 2);
range
.setFontWeight('bold')
.setFontLine('underline')
.setFontFamily('Arial')
.setFontSize(24)
.setFontColor('red');
//移除单元格样式数据
range
.setFontWeight(null) …
```
> feat(facade): add set font apis and get cell model data api

- packages/ui/src/services/clipboard/clipboard-interface.service.ts
- packages/ui/src/services/clipboard/clipboard-utils.ts
> fix(sheet-ui): fix clipboard not available in unsecure context

- packages/sheets/src/index.ts
- packages/sheets/src/services/ref-range/util.ts
> feat(ref-range): support default range change util

- packages/engine-formula/src/engine/reference-object/base-reference-object.ts
- packages/engine-formula/src/engine/utils/__tests__/cell.spec.ts
- packages/engine-formula/src/engine/utils/cell.ts
- packages/sheets-formula/src/commands/operations/__tests__/insert-function.operation.spec.ts
- packages/sheets-formula/src/commands/operations/insert-function.operation.ts
> fix(formula): get rich text data stream as content

- packages/engine-formula/src/engine/reference-object/base-reference-object.ts
- packages/engine-formula/src/engine/utils/__tests__/cell.spec.ts
- packages/engine-formula/src/engine/utils/cell.ts
- packages/engine-formula/src/engine/value-object/__tests__/array-value-object.spec.ts
- packages/engine-formula/src/engine/value-object/array-value-object.ts
- packages/engine-formula/src/engine/value-object/primitive-object.ts
- packages/sheets-formula/src/commands/operations/__tests__/insert-function.operation.spec.ts
- packages/sheets-formula/src/commands/operations/insert-function.operation.ts
> fix(formula): sum get error when cell has error 

- packages/docs/src/commands/commands/inline-format.command.ts
> fix(doc): ts check

- packages/docs/src/commands/mutations/core-editing.mutation.ts
- packages/docs/src/controllers/doc-render.controller.ts
- packages/docs/src/services/doc-skeleton-manager.service.ts
> fix: cursor position

- packages/core/src/services/locale/__tests__/locale.service.spec.ts
- packages/core/src/services/locale/locale.service.ts
```typescript
const locales = {
welcome: 'hello, {0}'
}
console.log(t('welcome', 'world')) // 'hello, world'
```
> feat: add string interpolation support for locale service

- packages/design/src/components/select/index.module.less
fix https://github.com/dream-num/univer-pro/issues/274
> fix(design): remove duplicate z-index property from Select's dropdown CSS definition

- packages/core/src/types/interfaces/i-selection-data.ts
- packages/docs/src/commands/operations/text-selection.operation.ts
- packages/docs/src/services/text-selection-manager.service.ts
> feat: export is active for share cursor use

- packages/docs/src/commands/operations/select-all.operation.ts
- packages/docs/src/commands/operations/text-selection.operation.ts
- packages/docs/src/controllers/move-cursor.controller.ts
- packages/docs/src/services/text-selection-manager.service.ts
- packages/engine-render/src/components/docs/text-selection-render-manager.ts
> feat: add isEditing param

- packages/docs-ui/src/controllers/page-render.controller.ts
- packages/docs-ui/src/views/doc-canvas-view.ts
- packages/docs/src/controllers/text-selection.controller.ts
- packages/docs/src/services/doc-skeleton-manager.service.ts
- packages/docs/src/services/doc-view-model-manager.service.ts
- packages/engine-render/src/base-object.ts
- packages/engine-render/src/layer.ts
- packages/engine-render/src/render-manager.service.ts
- packages/engine-render/src/scene.-transformer.ts
- packages/engine-render/src/scene.input-manager.ts
- packages/engine-render/src/scene.ts
- packages/engine-render/src/shape/base-scroll-bar.ts
- packages/engine-render/src/thin-scene.ts
- packages/sheets-ui/src/controllers/editor/end-edit.controller.ts
- packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts
- packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
- packages/sheets-ui/src/controllers/freeze.controller.ts
- packages/sheets-ui/src/services/selection/selection-render.service.ts
- packages/sheets-ui/src/services/selection/selection-shape.ts
- packages/sheets-ui/src/services/sheet-skeleton-manager.service.ts
- packages/sheets-ui/src/views/sheet-canvas-view.ts
- packages/ui/src/components/editor/TextEditor.tsx
- packages/ui/src/services/editor/editor.service.ts
> fix(sheet): optimize memory release and resolve issues with the editor being recreated repeatedly

- packages/core/src/docs/data-model/__tests__/replacement.spec.ts
- packages/core/src/docs/data-model/replacement.ts
- packages/core/src/docs/data-model/text-x/text-x.ts
- packages/core/src/index.ts
close https://github.com/dream-num/univer-pro/issues/286
> feat: replacement in document body

- .github/workflows/preview-deploy.yml
- .vscode/extensions.json
- examples/src/plugins/debugger/commands/operations/dialog.operation.ts
- packages/design/src/components/dialog/Dialog.stories.tsx
- packages/design/src/components/dialog/Dialog.tsx
close https://github.com/dream-num/univer-pro/issues/285
Test cases will be added once Storybook integration is complete.
> feat(design): add `preservePositionOnDestroy` & `defaultPosition` to Dialog

- packages/sheets/src/commands/commands/insert-row-col.command.ts
> fix(sheet): insert row/col undo bug

- packages/sheets-ui/src/commands/commands/__tests__/add-worksheet-merge.command.spec.ts
- packages/sheets-ui/src/commands/commands/add-worksheet-merge.command.ts
- packages/sheets-ui/src/commands/commands/utils/selection-utils.ts
> fix(sheet): fix unreasonable merged selections

- packages/sheets-ui/src/controllers/freeze.controller.ts
> fix(sheet): insert row col with effect freeze

- packages/engine-formula/src/basics/token.ts
- packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
- packages/engine-formula/src/engine/analysis/__tests__/parser.spec.ts
- packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts
- packages/engine-formula/src/engine/analysis/parser.ts
- packages/engine-formula/src/engine/ast-node/ast-root-node.ts
- packages/engine-formula/src/engine/ast-node/function-node.ts
- packages/engine-formula/src/engine/ast-node/operator-node.ts
- packages/engine-formula/src/engine/ast-node/reference-node.ts
- packages/engine-formula/src/engine/dependency/formula-dependency.ts
- packages/engine-formula/src/engine/utils/ast-node-tool.ts
- packages/engine-formula/src/engine/utils/prefixHandler.ts
- packages/engine-formula/src/functions/meta/compare/index.ts
- packages/engine-formula/src/functions/meta/divided/index.ts
- packages/sheets-formula/src/services/prompt.service.ts
- packages/sheets-zen-editor/src/controllers/zen-editor.controller.ts
> fix(formula): formula select and negative

- examples/src/plugins/debugger/views/test-editor/TestTextEditor.tsx
- packages/ui/src/components/editor/TextEditor.tsx
- packages/ui/src/components/range-selector/RangeSelector.tsx
> fix(sheet): add focus change

- packages/engine-render/src/components/docs/document.ts
- packages/engine-render/src/components/sheets/extensions/font.ts
> fix(sheet): wrap and rotation

- packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts
- packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
> feat(sheet): empty formular bar when in array range

- packages/core/src/sheets/workbook.ts
> fix(sheet): first sheet hidden

- examples/src/data/sheets/demo/default-workbook-data-demo.ts
- packages/core/src/index.ts
- packages/core/src/shared/color/color-kit.ts
- packages/engine-render/src/components/sheets/sheet-skeleton.ts
- packages/sheets/src/commands/commands/set-border-command.ts
https://github.com/dream-num/univer-pro/issues/344
When the top border of a cell and the bottom border of the cell above it (r-1) overlap, if the top border of cell r is white, then the rendering is ignored.
close #
> fix(sheet): border excel compatibility

- packages/core/src/services/locale/locale.service.ts
> feat(core): add `getCurrentLocale` to LocaleService

- packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
- packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts
- packages/engine-formula/src/engine/ast-node/function-node.ts
> fix(formula): check syntax

- packages/engine-render/src/basics/text-rotation.ts
- packages/engine-render/src/components/docs/document.ts
- packages/engine-render/src/components/sheets/extensions/font.ts
- packages/engine-render/src/components/sheets/interfaces.ts
- packages/engine-render/src/components/sheets/sheet-skeleton.ts
- packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
for https://github.com/dream-num/univer-pro/issues/334
close #
> fix(sheet): keep consistent with excel rotation

- packages/engine-formula/src/engine/analysis/__tests__/create-command-test-bed.ts
- packages/engine-formula/src/engine/analysis/__tests__/parser.spec.ts
- packages/engine-formula/src/engine/ast-node/function-node.ts
- packages/engine-formula/src/engine/ast-node/reference-node.ts
> fix(formula): token uppercase

- .github/pull_request_template.md
- packages/core/src/index.ts
- packages/core/src/sheets/__tests__/worksheet.spec.ts
- packages/core/src/sheets/worksheet.ts
- packages/engine-render/src/components/sheets/sheet-skeleton.ts
- packages/sheets/src/commands/mutations/set-range-values.mutation.ts
close #1534
BREAKING CHANGE:
Before:
Boolean values ("TRUE" "FALSE") were stored in the IWorkbooData as strings.
After:
Boolean values would be store as number (0, 1).
> fix(sheets): boolean should store as number

- examples/esbuild.config.mjs
- packages/core/src/shared/common.ts
- packages/docs-ui/src/controllers/text-selection.controller.ts
- packages/engine-render/src/components/docs/text-selection/text-selection-render-manager.ts
> fix(editor): optimize editor focus

- packages/sheets-numfmt/src/components/more-numfmt-type/MoreNumfmtType.tsx
- packages/sheets-numfmt/src/controllers/numfmt.cell-content.controller.ts
- packages/sheets-numfmt/src/controllers/numfmt.controller.ts
- packages/sheets-numfmt/src/locale/en-US.ts
- packages/sheets-numfmt/src/locale/zh-CN.ts
- packages/sheets-numfmt/src/utils/pattern.ts
> feat(sheet): numfmt support i18n

- examples/src/docs/main.ts
- packages/core/src/basics/univer.ts
- packages/engine-formula/src/plugin.ts
1. Add type checking for `Plugin` parameters
```ts
univer.registerPlugin(UniverUIPlugin, {
container: "app",
header: true,
toolbar: true,
footor: true, // Error, 'footor' does not exist in type <...>. Did you mean to write 'footer'?
})
```
2. `IUniverFormulaEngine.config`  can be optional
```ts
// packages/engine-formula/src/plugin.ts#L95
useFactory: () => this._injector.createInstance(FormulaController, this._config?.function)
```
3. `standalone` is a deprecated property in `UniverDocsPlugin`
> feat(core): add registerPlugin config types

- packages/sheets-ui/src/services/clipboard/clipboard.service.ts
- packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
- packages/ui/src/views/App.tsx
When the univer is destroyed and then re created, there are residual doms that have not been cleaned up
remove iframe and .univer-theme when univer dispose called
Replace the file `\examples\src\sheets\main.ts` with the following content and run `setupUniver()` multiple times in the console
```ts
import { LocaleType, LogLevel, Univer } from '@univerjs/core';
import { defaultTheme } from '@univerjs/design';
import { UniverDocsPlugin } from '@univerjs/docs';
import { UniverDocsUIPlugin } from '@univerjs/docs-ui';
import { UniverFormulaEnginePlugin } from '@univerjs/engine-formula';
import { UniverRenderEnginePlugin } from '@univerjs/engine-render';
import { UniverFindReplacePlugin } from '@univerjs/find-replace';
import type { IUniverRPCMainThreadConfig } from '@univerjs/rpc';
import { …
```
> fix(ui): cleanup DOMs when dispose

- packages/sheets-ui/src/index.ts
- packages/sheets-ui/src/services/clipboard/__tests__/utils.spec.ts
- packages/sheets-ui/src/services/clipboard/clipboard.service.ts
- packages/sheets-ui/src/services/clipboard/utils.ts
> fix(sheets-ui): merge setRangeValuesMutation at clipboardservice

- packages/sheets-ui/src/commands/commands/add-worksheet-merge.command.ts
- packages/sheets-ui/src/controllers/clipboard/utils.ts
- packages/sheets/src/commands/commands/remove-worksheet-merge.command.ts
1. remove的时候直接remove正确的合并单元格 而不是remove选区
2. add/remove merge选区为空的时候过滤该mutation的发送
> fix: fixing the range of remove merged selection and filter empty ranges

- packages/ui/package.json
- packages/ui/src/components/font-size/FontSize.tsx
- packages/ui/src/components/hooks/__tests__/observable.spec.ts
- packages/ui/src/components/hooks/observable.ts
- packages/ui/src/components/menu/Menu.tsx
- packages/ui/src/views/components/doc-bars/ToolbarItem.tsx
- packages/ui/src/views/hooks/active.ts
- pnpm-lock.yaml
> fix(ui): fix use observable

- packages/design/package.json
- packages/design/src/components/input/InputWithSlot.tsx
- packages/design/src/components/input/index.module.less
- packages/design/src/components/textarea/Textarea.stories.tsx
- packages/design/src/components/textarea/Textarea.tsx
- packages/design/src/components/textarea/index.module.less
- packages/design/src/components/textarea/index.ts
- packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/highlightCell.tsx
- packages/ui/src/components/range-selector/RangeSelector.tsx
- packages/uniscript/package.json
- pnpm-lock.yaml
> feat(design): add `Textarea` component

- packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
- packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts
- packages/engine-formula/src/engine/reference-object/base-reference-object.ts
> fix(formula): today fill error

- packages/design/package.json
- packages/design/src/components/draggable-list/DraggableList.stories.tsx
- packages/design/src/components/draggable-list/DraggableList.tsx
- packages/design/src/components/draggable-list/index.ts
- packages/design/src/index.ts
- packages/sheets-data-validation/package.json
- packages/sheets-data-validation/src/views/formula-input/list-formula-input.tsx
- pnpm-lock.yaml
> feat(sheets-data-validation): move draggable-list to design

- packages/engine-formula/src/engine/value-object/__tests__/array-value-object.spec.ts
- packages/engine-formula/src/engine/value-object/array-value-object.ts
- packages/sheets-formula/src/controllers/__tests__/formula-clipboard.controller.spec.ts
- packages/sheets-formula/src/controllers/formula-clipboard.controller.ts
- packages/sheets-formula/src/controllers/formula-editor-show.controller.ts
> fix(formula): copy paste range with formulas

- packages/design/src/components/slider/Slider.tsx
> fix(design): fix slider to stop responding to mouse movement after release during zoom operations

- packages/core/src/shared/__test__/common.spec.ts
- packages/core/src/shared/common.ts
- packages/core/src/types/interfaces/i-range.ts
- packages/engine-formula/src/commands/mutations/set-array-formula-data.mutation.ts
- packages/engine-formula/src/commands/mutations/set-formula-data.mutation.ts
- packages/engine-formula/src/controller/calculate.controller.ts
- packages/engine-formula/src/index.ts
- packages/engine-formula/src/models/formula-data.model.ts
- packages/engine-formula/src/models/utils/formula-data-util.ts
- packages/sheets-formula/README-zh.md
- packages/sheets-formula/README.md
- packages/sheets-formula/src/controllers/__tests__/update-formula.controller.spec.ts
- packages/sheets-formula/src/controllers/update-formula.controller.ts
- packages/sheets-formula/src/controllers/utils/__tests__/ref-range-formula.spec.ts
- packages/sheets-formula/src/controllers/utils/offset-formula-data.ts
- packages/sheets-formula/src/controllers/utils/ref-range-formula.ts
- packages/sheets/src/commands/commands/delete-range-move-left.command.ts
- packages/sheets/src/commands/commands/delete-range-move-up.command.ts
- packages/sheets/src/commands/commands/insert-range-move-down.command.ts
- packages/sheets/src/commands/commands/insert-range-move-right.command.ts
- packages/sheets/src/commands/commands/insert-row-col.command.ts
- packages/sheets/src/commands/commands/move-range.command.ts
- packages/sheets/src/commands/commands/move-rows-cols.command.ts
- packages/sheets/src/commands/commands/remove-sheet.command.ts
- packages/sheets/src/commands/commands/set-worksheet-name.command.ts
close #963
close #1086
close #1129
Reference Ticket #1659
修复导入后公式 si 未识别公式问题
> fix(formula): use ref range formula

- packages/docs-ui/src/controllers/doc-ui.controller.ts
- packages/docs-ui/src/controllers/menu/menu.ts
- packages/docs-ui/src/locale/en-US.ts
- packages/docs-ui/src/locale/zh-CN.ts
- packages/docs/src/commands/commands/inline-format.command.ts
- packages/docs/src/doc-plugin.ts
- packages/docs/src/index.ts
> feat(docs): support background color in doc

- packages/core/src/shared/lifecycle.ts
- packages/sheets-ui/src/services/canvas-pop-manager.service.ts
> feat(sheets-ui): sheet popup service should respond to row col changes

- packages/engine-formula/src/index.ts
- packages/sheets-conditional-formatting-ui/src/commands/commands/add-data-bar-cf.command.ts
- packages/sheets-conditional-formatting-ui/src/commands/operations/open-conditional-formatting-panel.ts
- packages/sheets-conditional-formatting-ui/src/components/hook/useHighlightRange.ts
- packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/dataBar.tsx
- packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/highlightCell.tsx
- packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/index.module.less
- packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/index.tsx
- packages/sheets-conditional-formatting-ui/src/components/panel/rule-list/index.module.less
- packages/sheets-conditional-formatting-ui/src/components/panel/rule-list/index.tsx
- packages/sheets-conditional-formatting-ui/src/controllers/cf.render.controller.ts
- packages/sheets-conditional-formatting-ui/src/locale/en-US.ts
- packages/sheets-conditional-formatting-ui/src/locale/zh-CN.ts
- packages/sheets-conditional-formatting/src/models/icon-map.ts
- packages/sheets-conditional-formatting/src/models/type.ts
- packages/sheets-conditional-formatting/src/render/type.ts
- packages/sheets-conditional-formatting/src/services/__test__/cf.service.spec.ts
- packages/sheets-conditional-formatting/src/services/calculate-unit/data-bar.ts
- packages/sheets-conditional-formatting/src/services/calculate-unit/highlight-cell.ts
- packages/sheets-conditional-formatting/src/services/conditional-formatting.service.ts
1. When you hover the rule panel with the mouse, highlight the area where the rule works. 
3. Data bar supports hidden value 
4. Conditional format supports matching formula error
5.  Support for whole row and whole column selection
> feat(conditional-formatting): bugfix

- examples/src/data/sheets/demo/default-workbook-data-demo.ts
- packages/core/src/types/const/const.ts
- packages/sheets-ui/src/controllers/menu/menu.ts
- packages/sheets/src/commands/commands/__tests__/set-style.command.spec.ts
- packages/ui/src/components/font-family/interface.ts
* fix: correct the default font size
* fix: correct the default font family
close #1655 
close #588
> fix(sheet-ui): make the default font family and font size correct

- examples/src/data/docs/default-document-data-cn.ts
- packages/docs-ui/src/controllers/page-render.controller.ts
- packages/docs-ui/src/views/doc-canvas-view.ts
- packages/engine-render/src/components/docs/document.ts
- packages/engine-render/src/components/docs/layout/doc-skeleton.ts
- packages/engine-render/src/components/sheets/extensions/font.ts
- packages/engine-render/src/components/sheets/sheet-skeleton.ts
- packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
- packages/sheets-ui/src/services/editor-bridge.service.ts
- packages/sheets-ui/src/views/editor-container/EditorContainer.tsx
- packages/sheets-ui/src/views/editor-container/index.module.less
- packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
> fix(sheets): the text is aligned at editorial and non-editorial states 

- packages/engine-render/src/components/docs/document.ts
- packages/engine-render/src/components/sheets/sheet-skeleton.ts
- packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
- packages/sheets-ui/src/views/defined-name/DefinedName.tsx
- packages/sheets-ui/src/views/defined-name/DefinedNameInput.tsx
- packages/sheets-ui/src/views/defined-name/index.module.less
- packages/ui/src/components/editor/TextEditor.tsx
- packages/ui/src/components/range-selector/RangeSelector.tsx
- packages/ui/src/services/layout/layout.service.ts
> fix(sheet): range selector error

- packages/sheets-formula/src/controllers/prompt.controller.ts
- packages/sheets-formula/src/controllers/shortcuts/prompt.shortcut.ts
> fix(editor): formula input esc invalid

- packages/engine-formula/src/engine/ast-node/function-node.ts
- packages/engine-formula/src/functions/base-function.ts
- packages/engine-formula/src/functions/lookup/indirect/index.ts
> feat(sheet): indirect support defined name

- packages/engine-formula/src/engine/analysis/parser.ts
- packages/sheets-formula/src/controllers/active-dirty.controller.ts
- packages/sheets-ui/src/views/defined-name/DefinedNameContainer.tsx
> fix(sheet): defined name update name

- packages/engine-render/src/components/docs/extensions/line.ts
- packages/engine-render/src/components/docs/layout/shaping-engine/font-cache.ts
> fix: the strickthough position is wrong when fontsize is different

- packages/engine-render/src/components/sheets/sheet-skeleton.ts
- packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
- packages/sheets-ui/src/controllers/editor/end-edit.controller.ts
- packages/sheets-ui/src/controllers/force-string-alert.controller.ts
- packages/sheets-ui/src/controllers/force-string-render.controller.ts
- packages/sheets-ui/src/controllers/utils/__tests__/cell-tools.spec.ts
- packages/sheets-ui/src/controllers/utils/cell-tools.ts
- packages/sheets-ui/src/locale/en-US.ts
- packages/sheets-ui/src/locale/zh-CN.ts
- packages/sheets-ui/src/sheets-ui-plugin.ts
close #1921
如何测试？
输入 `'1` ，hover 出现提示信息
> feat(sheet): force string adds popup

- packages/engine-formula/src/functions/text/function-map.ts
- packages/engine-formula/src/functions/text/lower/__test__/index.spec.ts
- packages/engine-formula/src/functions/text/lower/index.ts
- packages/sheets-formula/src/locale/function-list/text/en-US.ts
- packages/sheets-formula/src/locale/function-list/text/ja-JP.ts
- packages/sheets-formula/src/locale/function-list/text/zh-CN.ts
- packages/sheets-formula/src/services/function-list/text.ts
1. feat: add the formula algorithm
2. feat: add the unit test
3. feat: add the locale configs and descriptions
close #1951
> feat(formula): add the Lower function

- packages/core/src/types/interfaces/i-cell-data.ts
- packages/sheets/src/commands/commands/__tests__/set-range-values.command.spec.ts
- packages/sheets/src/commands/mutations/set-range-values.mutation.ts
cell custom supports updating from mutation
如何测试？
打开浏览器控制台，打开Uniscript脚本编辑器，输入
```js
const range = univerAPI.getActiveWorkbook()?.getActiveSheet()?.getRange(1, 1, 1, 1);
if(range){
range.setValue({
v: 1,
// custom 对象中可以放置任何 JSON 内容
custom:{
id: 1
}
})
console.info(range.getCellData())
}
```
可以看到打印出的结果中包含自定义的数据即成功
> fix(sheet): cell custom supports updating from mutation

- packages/core/src/shared/common.ts
- packages/core/src/shared/range.ts
- packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
- packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts
- packages/engine-formula/src/engine/utils/reference.ts
=VLOOKUP($L6,$1:$1,1) 
error after fill
=VLOOKUP($L7,#REF!,1)
> fix(sheet): move formula ref

- .github/workflows/playwright.yml
- packages/engine-render/src/render-manager/render-unit.ts
- packages/sheets-ui/src/controllers/freeze.render-controller.ts
- packages/sheets-ui/src/controllers/utils/component-tools.ts
> fix: fix unit cannot be destroyed or recreate

- packages/sheets-ui/src/views/operate-container/AutoFillPopupMenu.tsx
> fix: skeleton change will remove autofill popupmenu

- packages/core/src/services/plugin/__tests__/plugin-override.spec.ts
- packages/core/src/services/plugin/plugin-override.ts
- packages/ui/src/index.ts
- packages/ui/src/services/dialog/desktop-dialog.service.ts
- packages/ui/src/services/dialog/dialog.service.ts
- packages/ui/src/ui-plugin.ts
- packages/ui/src/views/components/dialog-part/DialogPart.tsx
- pnpm-lock.yaml
> feat: ui plugin support override dependencies

- packages/engine-render/src/base-object.ts
- packages/engine-render/src/layer.ts
- packages/engine-render/src/scene.input-manager.ts
> fix(render): memory leak and capture

- packages/facade/src/apis/__tests__/create-test-bed.ts
- packages/facade/src/apis/facade.ts
- packages/facade/src/apis/sheets/__tests__/f-sheet-hooks.spec.ts
- packages/facade/src/apis/sheets/f-sheet-hooks.ts
- packages/sheets-ui/src/index.ts
close #1176
close #1425
通过监听 HoverManagerService 的 currentCell 变化来抛出当前单元格信息，便于用户在外部做拖拽放置
如何测试？
1. 打开uniscript
2. 粘贴以下代码，运行
```js
window.univerAPI.getSheetHooks().onCellPointerMove((cell) => {
const { location, position } = cell
window.univerAPI?.getActiveWorkbook()?.getActiveSheet()?.getRange(location.row, location.col)?.setBackgroundColor('red');
})
```
3. 鼠标在sheet区域内移动，会将经过的单元格设置为红色背景
> feat(facade): add sheet hooks, onCellPointerMove hook

- packages/sheets-find-replace/src/controllers/sheet-find-replace.controller.ts
- packages/sheets/src/commands/commands/set-range-values.command.ts
close [#2163](https://github.com/dream-num/univer/issues/2163#event-12744250664)
> fix(sheet): find-replace replaceAll only effect on the active sheet

- packages/design/src/components/menu/Menu.tsx
- packages/design/src/components/menu/index.ts
- packages/design/src/index.ts
- packages/ui/src/components/hooks/layout.ts
- packages/ui/src/components/menu/Menu.tsx
- packages/ui/src/views/components/doc-bars/ToolbarItem.tsx
To resolve the below problem
The height of the dropdown menu on the Toolbar is greater than the height of the viewport. 
It brings an unexpected scroller.
> feat(sheet): allow menu scroll when it over viewport

- packages/sheets/src/commands/commands/set-style.command.ts
- packages/sheets/src/commands/commands/utils/selection-utils.ts
- packages/ui/src/components/hooks/layout.ts
close [#685](https://github.com/dream-num/univer-pro/issues/685#event-12768432550)
> fix(sheet): skip filtered row on setting style

- packages/sheets-filter-ui/src/controllers/sheets-filter-render.controller.ts
- packages/sheets-ui/src/services/selection/__test__/selection-render.test.ts
- packages/sheets-ui/src/services/selection/selection-render.service.ts
close [2108](https://github.com/dream-num/univer/issues/2108#event-12794297602)
The code needs to run online, Just got env ready for QA verification. cc @oumomomo
> fix: filterRenderController works after selectionRenderService is usable

- packages/core/src/types/interfaces/i-cell-data.ts
- packages/sheets/src/commands/commands/clear-selection-all.command.ts
- packages/sheets/src/commands/commands/clear-selection-content.command.ts
- packages/sheets/src/commands/commands/clear-selection-format.command.ts
> fix(sheet): clear custom field of selection

- packages/docs/src/commands/commands/delete.command.ts
- packages/engine-render/src/basics/document-node-tools.ts
> fix: backspace in list when select all list content

- examples/src/data/docs/default-document-data-cn.ts
- examples/src/docs/main.ts
- packages/core/src/docs/data-model/__tests__/apply-utils.spec.ts
- packages/core/src/docs/data-model/apply-utils/common.ts
- packages/core/src/docs/data-model/apply-utils/update-apply.ts
> fix: inline style undo error at the doc end

- packages/docs-ui/src/controllers/text-selection.controller.ts
- packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
> fix(editor): focusing error

- examples/src/docs-uniscript/main.ts
- examples/src/docs/main.ts
- examples/src/sheets-multi/main.tsx
- examples/src/sheets-uniscript/main.ts
- examples/src/sheets/main.ts
- examples/src/slides/main.ts
- packages/ui/src/controllers/ui/ui.controller.ts
- packages/ui/src/views/App.tsx
- packages/ui/src/views/parts.ts
BREAKING CHANGE: The default values for `header` and `footer` are now set to true.
> feat(ui)!: add support for hiding context menu

- packages/docs-ui/src/controllers/doc-ui.controller.ts
- packages/sheets-formula/src/controllers/formula-ui.controller.ts
- packages/sheets-ui/src/controllers/sheet-ui.controller.ts
- packages/slides-ui/src/controllers/slide-ui.controller.ts
- packages/ui/src/index.ts
- packages/ui/src/services/confirm/desktop-confirm.service.ts
- packages/ui/src/services/dialog/desktop-dialog.service.ts
- packages/ui/src/services/notification/desktop-notification.service.ts
- packages/ui/src/services/parts/parts.service.ts
- packages/ui/src/ui-plugin.ts
- packages/ui/src/views/App.tsx
> feat(ui): ui parts service support more generic situations

- packages/design/src/components/message/Message.stories.tsx
- packages/design/src/components/message/Message.tsx
- packages/design/src/components/message/index.module.less
- packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
- packages/ui/src/components/progress-bar/ProgressBar.tsx
- packages/ui/src/index.ts
> fix(sheet): add info type for Message component, use barColor in ProgressBar

- examples/public/sheets/index.html
- packages/engine-render/src/base-object.ts
- packages/engine-render/src/basics/i-events.ts
- packages/engine-render/src/engine.ts
- packages/engine-render/src/scene.input-manager.ts
- packages/engine-render/src/scene.ts
- packages/engine-render/src/thin-scene.ts
- packages/facade/src/apis/sheets/__tests__/f-sheet-hooks.spec.ts
- packages/facade/src/apis/sheets/f-sheet-hooks.ts
- packages/sheets-formula/src/views/more-functions/MoreFunctions.tsx
- packages/sheets-ui/src/common/utils.ts
- packages/sheets-ui/src/controllers/drag-render.controller.ts
- packages/sheets-ui/src/index.ts
- packages/sheets-ui/src/services/drag-manager.service.ts
- packages/sheets-ui/src/sheets-ui-plugin.ts
如何测试？
分别在控制台粘贴以下代码测试 API，测试一个刷新一次页面
```js
window.univerAPI.getSheetHooks().onCellPointerMove((cell) => {
// 拿到当前鼠标指向的单元格
console.log(cell?.location.row, cell?.location.col);
})
```
鼠标hover在sheet区域，跟随鼠标移动触发
```js
window.univerAPI.getSheetHooks().onCellPointerOver((cell) => {
// 拿到当前鼠标指向的单元格
console.log(cell?.location.row, cell?.location.col);
})
```
鼠标hover在sheet区域，打中不同单元格时才触发
```js
window.univerAPI.getSheetHooks().onCellDragOver((cell) => {
// 拿到当前鼠标指向的单元格
console.log(cell?.location.row, cell?.location.col);
})
```
从外部拖拽一个可拖拽元素（比如本地记事本的文本）到sheet区域，打中不同单元格时触发
```js
window.univerAPI.getSheetHooks().onCellDrop((cell) => {
// 拿到当前鼠标指向的单元格
console.log(cell?.location.row, cell?.location.col);
})
```
从外部拖拽一个可拖拽元素（比如本地记事本的文本）到sheet区域，松开鼠标时触发
> feat(render-engine): facade adds onCellPointerOver,onCellDragOver,onCellDrop

- packages/ui/src/views/components/doc-bars/hook.ts
The `resize()` of the toolbar should not be implemented by listening to `document.body`.
Doing so may cause issues with correctly triggering the resize calculation in scenarios involving toggling visibility, such as when using Univer within Ant Design's Tabs component.
> fix(ui): correct the resize listener target in toolbar

- packages/ui/src/components/editor/TextEditor.tsx
> fix(editor): add valid attribute

- packages/design/src/components/message/Message.tsx
- packages/design/src/components/message/index.ts
- packages/design/src/index.ts
- packages/find-replace/src/views/dialog/FindReplaceDialog.tsx
- packages/ui/src/components/notification/Notification.tsx
- packages/ui/src/services/message/__testing__/mock-message.service.ts
- packages/ui/src/services/message/desktop-message.service.ts
- packages/ui/src/services/message/message.service.ts
- packages/ui/src/services/notification/notification.service.ts
Breaking changes:
- `IMessageMethodOptions` is renamed to `IMessageOptions`
> feat: change message and notification API

- packages/core/src/observer/__tests__/observable.spec.ts
- packages/core/src/observer/observable.ts
- packages/slides/src/views/render/canvas-view.ts
How to test?
```js
const activeSheet = univerAPI.getActiveWorkbook()?.getActiveSheet();
univerAPI.getSheetHooks().onCellDrop((cell) => {
console.log('onCellDrop', cell);
if (cell?.location.row !== undefined && cell?.location.col !== undefined) {
const range = activeSheet?.getRange(cell?.location.row, cell?.location.col, 1, 1);
if (range) {
range.setValue('Dropped');
}
}
});
```
> fix(core): observer remove unregisterOnNextCall

- packages/core/src/docs/data-model/json-x/json-x.ts
- packages/core/src/docs/data-model/text-x/__tests__/text-x.spec.ts
- packages/core/src/docs/data-model/text-x/text-x.ts
> fix: storybook failed because can not override name property

- packages/ui/src/services/dialog/desktop-dialog.service.ts
close [#777](https://github.com/dream-num/univer-pro/issues/777)
> fix: fix multiple dialogs being opened at the same time

- packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
- packages/sheets/src/commands/commands/clear-selection-format.command.ts
- packages/sheets/src/commands/commands/set-range-values.command.ts
- packages/sheets/src/commands/mutations/set-range-values.mutation.ts
close https://github.com/dream-num/univer/issues/1231
> fix: clear format failed when not change selections

- packages/ui/src/views/App.tsx
> chore(ui): remove deprecation warning about built-in language support

- packages/sheets-data-validation/src/validators/decimal-validator.ts
- packages/sheets-data-validation/src/validators/whole-validator.ts
> fix(sheets-data-validation): fix data-validation type `number` and `whole` title display error

- packages/engine-render/src/basics/i-document-skeleton-cached.ts
- packages/engine-render/src/components/docs/extensions/line.ts
- packages/engine-render/src/components/docs/layout/model/line.ts
- packages/engine-render/src/components/docs/layout/tools.ts
> fix(render-engine): optimize underline postion

- packages/facade/src/apis/sheets/__tests__/f-range.spec.ts
- packages/facade/src/apis/sheets/f-range.ts
- packages/facade/src/apis/sheets/f-workbook.ts
- packages/facade/src/apis/sheets/utils.ts
> feat(facade): click to get cell information, whether to merge and coordinates

- packages/core/src/shared/color/color-kit.ts
- packages/engine-render/src/basics/range.ts
- packages/engine-render/src/basics/tools.ts
- packages/engine-render/src/components/docs/text-selection/text-range.ts
- packages/engine-render/src/components/docs/text-selection/text-selection-render-manager.ts
> feat: support for tilting the cursor when italicized

- packages/docs-ui/src/controllers/doc-editor-bridge.controller.ts
- packages/sheets-formula/src/controllers/prompt.controller.ts
- packages/sheets-ui/src/controllers/editor/end-edit.controller.ts
- packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
- packages/sheets-ui/src/services/selection/selection-render.service.ts
- packages/sheets-ui/src/views/defined-name/DefinedName.tsx
- packages/sheets-ui/src/views/editor-container/EditorContainer.tsx
- packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
- packages/sheets/src/services/selection-manager.service.ts
close https://github.com/dream-num/univer/issues/1824
> fix: formular confirm error

- packages/facade/src/apis/__tests__/f-hooks.spec.ts
- packages/facade/src/apis/f-hooks.ts
- packages/facade/src/apis/facade.ts
为什么要新增 lifecycle 钩子？
注册 canvas 扩展的 Facade API，必须在渲染完成之后才能调用，可以抛出生命周期的钩子，让用户知道已经渲染完成，再调用 canvas 扩展的API
文档待补充
> feat(facade): add lifecycle hooks for facade

- packages/design/src/components/message/Message.tsx
- packages/ui/src/index.ts
- packages/ui/src/services/message/desktop-message.service.ts
- packages/ui/src/views/components/ComponentContainer.tsx
> feat(ui): enhance component container

- packages/docs-ui/src/controllers/back-scroll.controller.ts
- packages/docs-ui/src/controllers/doc-editor-bridge.controller.ts
- packages/docs-ui/src/controllers/zoom.controller.ts
- packages/engine-render/src/basics/scroll-xy.ts
- packages/engine-render/src/components/sheets/interfaces.ts
- packages/engine-render/src/components/sheets/spreadsheet.ts
- packages/engine-render/src/scene.ts
- packages/engine-render/src/scroll-timer.ts
- packages/engine-render/src/viewport.ts
- packages/sheets-ui/src/commands/commands/__tests__/create-command-test-bed.ts
- packages/sheets-ui/src/commands/commands/__tests__/create-selection-command-test-bed.ts
- packages/sheets-ui/src/commands/commands/__tests__/set-frozen.command.spec.ts
- packages/sheets-ui/src/commands/commands/set-frozen.command.ts
- packages/sheets-ui/src/commands/commands/set-scroll.command.ts
- packages/sheets-ui/src/commands/operations/scroll.operation.ts
- packages/sheets-ui/src/common/utils.ts
- packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts
- packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
- packages/sheets-ui/src/controllers/render-controllers/freeze.render-controller.ts
- packages/sheets-ui/src/controllers/render-controllers/scroll.render-controller.ts
- packages/sheets-ui/src/controllers/render-controllers/zoom.render-controller.ts
- packages/sheets-ui/src/services/drag-manager.service.ts
- packages/sheets-ui/src/services/hover-manager.service.ts
- packages/sheets-ui/src/services/scroll-manager.service.ts
- packages/sheets-ui/src/services/sheet-skeleton-manager.service.ts
- packages/sheets-ui/src/views/sheet-canvas-view.ts
- packages/sheets-zen-editor/src/controllers/zen-editor.controller.ts
- packages/slides/src/views/render/adaptors/docs-adaptor.ts
- packages/slides/src/views/render/adaptors/spreadsheet-adaptor.ts
- packages/slides/src/views/render/canvas-view.ts
close #2116 
https://github.com/dream-num/univer/issues/2116
Add scrollLeft scrollTop to sheet snapshot after scroll command.
check scrollLeft and scrollTop value in `univer._univerInstanceService.getFocusedUnit()._snapshot`
> feat: add scrollLeftTop for sheet snapshot

- packages/design/src/components/message/Message.tsx
- packages/ui/src/services/message/desktop-message.service.ts
> fix: message node env

- packages/ui/src/common/menu-merge-configs.ts
> fix(ui): fix ineffective `hidden` property in menu configurations

- packages/sheets-conditional-formatting/src/render/data-bar.render.ts
- packages/sheets-conditional-formatting/src/render/icon.render.ts
close #483
https://github.com/dream-num/univer-pro/issues/483
> fix: icon extension index should be higher than data-bar extension

- packages/sheets/src/commands/commands/insert-sheet.command.ts
> feat(InsertSheetCommand): allow using partial sheet from params as sheetconfig

- packages/sheets-ui/src/services/clipboard/clipboard.service.ts
- packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
- packages/sheets-ui/src/services/clipboard/usm-to-html/convertor.ts
> fix: not escape when copy content

- packages/core/src/common/request-immediate-macro-task.ts
- packages/engine-formula/src/engine/utils/__tests__/math-kit.spec.ts
- packages/engine-formula/src/engine/utils/math-kit.ts
- packages/engine-formula/src/engine/value-object/__tests__/array-value-ceil.spec.ts
- packages/engine-formula/src/engine/value-object/__tests__/array-value-floor.spec.ts
- packages/engine-formula/src/engine/value-object/__tests__/array-value-minus.spec.ts
- packages/engine-formula/src/engine/value-object/__tests__/array-value-object.spec.ts
- packages/engine-formula/src/engine/value-object/__tests__/array-value-round.spec.ts
- packages/engine-formula/src/engine/value-object/primitive-object.ts
- packages/engine-formula/src/functions/__tests__/create-function-test-bed.ts
- packages/engine-formula/src/functions/math/mod/__tests__/index.spec.ts
- packages/engine-formula/src/functions/math/power/__tests__/index.spec.ts
- packages/engine-formula/src/functions/math/subtotal/__tests__/index.spec.ts
- packages/engine-formula/src/functions/math/sum/__tests__/index.spec.ts
- packages/engine-formula/src/functions/statistical/average/__tests__/index.spec.ts
- packages/engine-formula/src/functions/statistical/stdev-p/__tests__/index.spec.ts
- packages/engine-formula/src/index.ts
- packages/engine-formula/src/services/calculate-formula.service.ts
- packages/sheets-formula/src/controllers/array-formula-display.controller.ts
- packages/sheets-formula/src/controllers/formula-render.controller.ts
- packages/sheets-formula/src/controllers/utils/__tests__/utils.spec.ts
- packages/sheets-formula/src/controllers/utils/utils.ts
close #1712
1. 移除 Big.js 的使用。由于 Excel 计算也遵循 IEEE 754 规范，计算过程无需处理精度
2. Excel仅展示前15位数字，但是XML中存储了原始值，我们参照这个做法，仅在公式结果展示的时候处理 15位舍入
如何测试？
1. js控制台测试会出问题的计算，比如 0.1+0.2，0.07/0.1
2. 在单元格中输入公式计算：=0.1+0.2，=0.07/0.1
close #2344
safari下反复缩放 sheet，查看是否有内存持续增长问题。自测已经OK
> fix(formula): js precision problem

- packages/network/README.md
- packages/network/src/index.ts
- packages/network/src/services/http/http.service.ts
- packages/network/src/services/http/implementations/fetch.ts
- packages/network/src/services/http/interceptors/__tests__/retry-interceptor.spec.ts
- packages/network/src/services/http/request.ts
- packages/network/src/services/http/response.ts
- pnpm-lock.yaml
> feat(network): support sse in network fetch

- packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
- packages/sheets-ui/src/views/permission/user-dialog/index.module.less
- packages/sheets-ui/src/views/sheet-bar/SheetBar.tsx
> fix(permission): rename change permission

- packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts
- packages/ui/src/services/dom/canvas-dom-layer.service.ts
- packages/ui/src/views/components/dom/FloatDom.tsx
> feat: support props on float dom component

- packages/core/src/types/interfaces/i-row-data.ts
- packages/core/src/types/interfaces/i-selection-data.ts
- packages/engine-render/src/basics/tools.ts
- packages/engine-render/src/components/sheets/sheet-skeleton.ts
- packages/sheets-formula/src/controllers/prompt.controller.ts
- packages/sheets-ui/src/controllers/auto-fill.controller.ts
- packages/sheets-ui/src/controllers/format-painter/format-painter.controller.ts
- packages/sheets/package.json
- packages/sheets/src/basics/selection.ts
- packages/sheets/src/commands/mutations/set-worksheet-row-height.mutation.ts
- pnpm-lock.yaml
> refactor: remove sheets dependency on engine-render

- common/shared/vite/auto-externalize-dependency-plugin.js
- packages/core/src/services/authz-io/authz-io-local.service.ts
- packages/docs-drawing/package.json
- packages/engine-numfmt/package.json
- packages/sheets-drawing/package.json
- packages/umd/package.json
- packages/umd/scripts/index.mjs
- pnpm-lock.yaml
> chore(release): fix in pre-release-v0.1.15

- packages/engine-formula/src/models/formula-data.model.ts
- packages/engine-formula/src/models/utils/formula-data-util.ts
- packages/sheets-formula/src/controllers/__tests__/update-formula.controller.spec.ts
- packages/sheets-formula/src/controllers/prompt.controller.ts
- packages/sheets-formula/src/controllers/utils/__tests__/ref-range-formula.spec.ts
- packages/sheets-formula/src/controllers/utils/ref-range-formula.ts
如何测试？
输入公式 `=SUM(1)` 后，按`Enter`光标移动到下方，或者 `Tab` 后光标移动到右侧。原先是跳了2格。
> fix(formula): reverse undo range list

- packages/sheets-filter-ui/src/views/components/index.module.less
- packages/ui/src/components/range-selector/index.module.less
close [#1116](https://github.com/dream-num/univer-pro/issues/1116)
Other styling issues have been fixed, with the exception of this button styling issue.
> fix(sheet): button class priority

- packages/core/src/shared/common.ts
- packages/core/src/types/interfaces/i-cell-data.ts
- packages/engine-render/src/components/sheets/sheet-skeleton.ts
- packages/sheets-data-validation/src/controllers/dv-render.controller.ts
- packages/sheets-hyper-link-ui/src/common/util.ts
- packages/sheets-hyper-link-ui/src/controllers/set-range.controller.ts
close  
https://github.com/dream-num/univer-pro/issues/1186
https://github.com/dream-num/univer-pro/issues/1205
https://github.com/dream-num/univer-pro/issues/1179
> fix(sheets): bugfix for data-validation and hyper-link

- packages/sheets-hyper-link-ui/src/controllers/set-range.controller.ts
- packages/sheets-ui/src/controllers/force-string-render.controller.ts
- packages/sheets/src/commands/mutations/__tests__/set-range-values.mutation.spec.ts
- packages/sheets/src/commands/mutations/set-range-values.mutation.ts
如何测试？
输入`'1` 得到强制字符串，再设置样式（比如字体颜色），检验是否强制字符串消失
> fix(sheet): force string sets style

- packages/sheets-formula/src/controllers/formula-clipboard.controller.ts
- packages/sheets-ui/src/common/utils.ts
- packages/sheets/src/commands/commands/remove-worksheet-merge.command.ts
- packages/sheets/src/commands/mutations/set-range-values.mutation.ts
- packages/ui/src/utils/cell.ts
> fix(sheets): fix some bugs

- packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-formula-render.controller.ts
> fix: fix status bar performance

- packages/sheets/src/commands/commands/__tests__/set-row-col-visible.command.spec.ts
- packages/sheets/src/commands/commands/set-col-visible.command.ts
- packages/sheets/src/commands/commands/set-row-visible.command.ts
> fix(sheets): hide rows cols should skip over already hidden ranges

- packages/sheets-hyper-link-ui/src/views/CellLinkPopup/index.tsx
- packages/sheets-thread-comment/src/views/sheets-thread-comment-panel/index.tsx
- packages/ui/src/views/components/shortcut-panel/ShortcutPanel.tsx
> fix: use @univerjs/ui useObservable

- packages/engine-render/src/components/sheets/column-header.ts
- packages/engine-render/src/components/sheets/extensions/column-header-layout.ts
- packages/engine-render/src/components/sheets/interfaces.ts
- packages/engine-render/src/components/sheets/sheet-skeleton.ts
- packages/facade/src/apis/__tests__/facade.spec.ts
- packages/facade/src/apis/facade.ts
close #859
https://github.com/dream-num/univer-pro/issues/859
Customize column header in render layer.
```
univerAPI.customizeColumnHeader({ headerStyle:{backgroundColor: 'pink', fontSize: 9}, columnsCfg: ['ASC', 'MokaII', undefined, {text: 'Size', textAlign: 'left'}, {text: 'MUJI', fontSize: 15, textAlign: 'right'}, {text: 'SRI-RESOLVE', fontSize: 10, textAlign: 'left', fontColor: 'blue', backgroundColor: 'wheat'}, null, null, 'ss', {fontSize: 29, fontColor:'red', text: 'hash'}]})
```
Use headerStyle to set the style for all columns, and use columnsCfg to customize the style of each column in order.
> feat: customize column header

- packages/docs-drawing-ui/src/views/doc-image-panel/DocDrawingPanel.tsx
> fix(docs-drawing): fix crash when editing text after inserting images and opening the sidebar

- packages/drawing-ui/src/services/drawing-render.service.ts
- packages/drawing/src/services/drawing-manager-impl.service.ts
- packages/drawing/src/services/drawing-manager.service.ts
- packages/sheets-drawing-ui/src/controllers/sheet-drawing-permission.controller.ts
- packages/sheets-drawing-ui/src/plugin.ts
- packages/sheets-hyper-link-ui/src/controllers/popup.controller.ts
- packages/sheets-hyper-link-ui/src/services/popup.service.ts
- packages/sheets-hyper-link-ui/src/views/CellLinkPopup/index.tsx
- packages/sheets-thread-comment/src/controllers/menu.ts
- packages/sheets-thread-comment/src/controllers/sheets-thread-comment-hover.controller.ts
- packages/sheets-thread-comment/src/controllers/sheets-thread-comment.controller.ts
- packages/sheets-ui/src/commands/commands/worksheet-protection.command.ts
- packages/sheets-ui/src/controllers/menu/permission-menu-util.ts
- packages/sheets-ui/src/controllers/permission/sheet-permission-init.controller.ts
- packages/sheets-ui/src/views/permission/panel-detail/index.module.less
- packages/sheets/src/services/permission/worksheet-permission/utils.ts
- packages/sheets/src/services/permission/worksheet-permission/worksheet-permission.service.ts
> feat: add sheet drawing permission

- packages/sheets-ui/src/services/clipboard/clipboard.service.ts
- packages/sheets/src/commands/commands/__tests__/set-range-values.command.spec.ts
- packages/sheets/src/commands/mutations/set-range-values.mutation.ts
> fix: set style should not clear p

- packages/sheets-ui/src/controllers/render-controllers/selection.render-controller.ts
- packages/sheets/src/services/selection-manager.service.ts
[close #1250](https://github.com/dream-num/univer-pro/issues/1250)
> fix(sheet): selection order

- packages/engine-formula/src/functions/__tests__/nested-functions.spec.ts
- packages/engine-formula/src/functions/lookup/address/__tests__/index.spec.ts
- packages/engine-formula/src/functions/lookup/address/index.ts
- packages/engine-formula/src/functions/lookup/index/index.ts
- packages/engine-formula/src/functions/lookup/offset/index.ts
- packages/engine-formula/src/models/formula-data.model.ts
- packages/sheets-formula/src/controllers/formula-alert-render.controller.ts
- packages/sheets-formula/src/formula-ui-plugin.ts
- packages/sheets-formula/src/views/prompt/help-function/HelpFunction.tsx
close [#654](https://github.com/dream-num/univer-pro/issues/654)
close [#656](https://github.com/dream-num/univer-pro/issues/656)
close [#659](https://github.com/dream-num/univer-pro/issues/659)
close [#693](https://github.com/dream-num/univer-pro/issues/693)
> fix(formula): remove non-existent formula ids

- packages/sheets-ui/src/sheets-ui-plugin.ts
close [714](https://github.com/dream-num/univer-pro/issues/714)
> fix(move-range): add move range controller

- packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/index.tsx
- packages/ui/src/components/editor/TextEditor.tsx
close [466](https://github.com/dream-num/univer-pro/issues/466)
> fix(range-selector): placeholder flush

- packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/formula.tsx
- packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/highlightCell.tsx
- packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/index.tsx
- packages/sheets-conditional-formatting-ui/src/components/wrapper-error/WrapperError.tsx
- packages/sheets-conditional-formatting-ui/src/locale/en-US.ts
- packages/sheets-conditional-formatting-ui/src/locale/ru-RU.ts
- packages/sheets-conditional-formatting-ui/src/locale/zh-CN.ts
close [1133](https://github.com/dream-num/univer-pro/issues/1133)
close [1257](https://github.com/dream-num/univer-pro/issues/1257)
close [735](https://github.com/dream-num/univer-pro/issues/735)
close [434](https://github.com/dream-num/univer-pro/issues/434)
> feat(conditional-formatting): add error interceptor

- packages/sheets-numfmt/src/controllers/numfmt.cell-content.controller.ts
close [2005](https://github.com/dream-num/univer/issues/2005)
> fix(numfmt): numfmt not render after auto fill

- packages/core/src/index.ts
- packages/core/src/types/const/clipboard.ts
- packages/docs-ui/src/services/clipboard/html-to-udm/converter.ts
- packages/docs-ui/src/services/clipboard/html-to-udm/parse-node-style.ts
- packages/docs-ui/src/services/clipboard/html-to-udm/paste-plugins/plugin-word.ts
- packages/engine-render/src/components/sheets/sheet-skeleton.ts
- packages/engine-render/src/index.ts
- packages/sheets-formula/src/controllers/formula-clipboard.controller.ts
- packages/sheets-ui/src/controllers/clipboard/utils.ts
- packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
- packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-form-excel.spec.ts
- packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-from-google.spec.ts
- packages/sheets-ui/src/services/clipboard/__tests__/clipboard-service.spec.ts
- packages/sheets-ui/src/services/clipboard/clipboard.service.ts
- packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
- packages/sheets-ui/src/services/clipboard/usm-to-html/convertor.ts
- packages/ui/src/utils/cell.ts
close #1998 https://github.com/dream-num/univer-pro/issues/1323 https://github.com/dream-num/univer-pro/issues/1322 https://github.com/dream-num/univer-pro/issues/1342
> fix: fix some paste bugs

- packages/engine-formula/src/functions/statistical/averageif/index.ts
> fix(formula): ts error in averageif

- packages/sheets-data-validation/src/controllers/dv-auto-fill.controller.ts
- packages/sheets-ui/src/controllers/auto-fill.controller.ts
- packages/sheets-ui/src/services/auto-fill/auto-fill.service.ts
- packages/sheets-ui/src/services/auto-fill/rules.ts
- packages/sheets-ui/src/services/auto-fill/tools.ts
- packages/sheets-ui/src/services/auto-fill/type.ts
close https://github.com/dream-num/univer-pro/issues/1265
colse #2597
> fix: optimize the the menu and prefer apply-type of auto-fill

- packages/engine-render/src/components/sheets/column-header.ts
- packages/engine-render/src/components/sheets/row-header.ts
- packages/engine-render/src/components/sheets/spreadsheet.ts
- packages/sheets-ui/src/controllers/render-controllers/freeze.render-controller.ts
> fix(sheet): freeze invalid

- packages/core/src/index.ts
- packages/core/src/shared/__tests__/name.spec.ts
- packages/core/src/shared/common.ts
- packages/core/src/shared/name.ts
- packages/sheets-ui/src/locale/en-US.ts
- packages/sheets-ui/src/locale/ru-RU.ts
- packages/sheets-ui/src/locale/zh-CN.ts
- packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx
- packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/utils/slide-tab-bar.ts
> feat(sheet): sheet name check

- packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/utils/slide-tab-bar.ts
> fix(sheets-ui): fix focusout issue with rename input box in lower version of React

- packages/facade/src/apis/sheets/f-workbook.ts
> chore: add sheet permission facade api

- packages/sheets-ui/src/views/sheet-bar/SheetBar.tsx
- packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx
- packages/ui/src/controllers/ui/ui-desktop.controller.tsx
- packages/ui/src/controllers/ui/ui.controller.ts
- packages/ui/src/index.ts
- packages/ui/src/views/DesktopApp.tsx
> fix(sheets-ui): ensure context menu does not open on sheets tab when `contextMenu` is set to false

- packages/engine-formula/src/engine/dependency/dependency-tree.ts
- packages/engine-formula/src/engine/dependency/formula-dependency.ts
- packages/engine-formula/src/services/calculate-formula.service.ts
- packages/engine-formula/src/services/dependency-manager.service.ts
- packages/sheets-formula/src/controllers/update-formula.controller.ts
> fix(sheet): dependency error

- packages/debugger/src/commands/operations/sidebar.operation.ts
- packages/debugger/src/views/test-editor/TestTextEditor.tsx
- packages/ui/src/components/editor/TextEditor.tsx
> fix(editor):  fix the wrong position of validate messages on initialization when the sidebar is open

- packages/docs/src/commands/commands/delete.command.ts
> fix(docs): backspace in header

- examples/src/docs/main.ts
- packages/docs-hyper-link-ui/README-zh.md
- packages/docs-hyper-link-ui/README.md
- packages/docs-hyper-link-ui/src/index.ts
- packages/docs-hyper-link-ui/src/plugin.ts
- packages/docs-hyper-link/src/index.ts
- packages/docs-hyper-link/src/plugin.ts
> refactor: rename `UniverDocHyperLinkPlugin` to `UniverDocsHyperLinkPlugin`

- examples/src/sheets/main.ts
- packages/engine-formula/src/engine/value-object/array-value-object.ts
- packages/sheets-formula/src/controllers/__tests__/update-formula.controller.spec.ts
- packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
- packages/sheets-formula/src/controllers/update-formula.controller.ts
- packages/sheets-formula/src/controllers/utils/__tests__/ref-range-formula.spec.ts
- packages/sheets-formula/src/controllers/utils/ref-range-formula.ts
- packages/ui/src/components/progress-bar/ProgressBar.tsx
- packages/ui/src/components/progress-bar/index.module.less
> feat(formula): enable cancellation of ongoing formula calculations

- examples/esbuild.config.mjs
- examples/src/sheets/lazy.ts
- packages/core/src/common/request-immediate-macro-task.ts
- packages/core/src/services/command/command.service.ts
- packages/debugger/package.json
- packages/debugger/src/commands/commands/unit.command.ts
- packages/debugger/src/controllers/e2e/e2e-memory.controller.ts
- packages/engine-render/src/components/docs/text-selection/text-selection-render-manager.ts
- packages/engine-render/src/engine.ts
- packages/engine-render/src/layer.ts
- packages/rpc/src/services/rpc/channel.service.ts
- packages/rpc/src/services/rpc/rpc.service.ts
- packages/sheets-conditional-formatting/src/services/conditional-formatting-formula.service.ts
- packages/sheets-data-validation/src/controllers/dv.controller.ts
- packages/sheets-formula/src/services/register-other-formula.service.ts
- packages/sheets-ui/src/services/selection/base-selection-render.service.ts
- packages/ui/src/common/component-manager.ts
- packages/ui/src/controllers/ui/ui-desktop.controller.tsx
- pnpm-lock.yaml
> fix: tons of memory leak

- packages/sheets-ui/src/controllers/permission/sheet-permission-init.controller.ts
- packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-base.controller.ts
- packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-canvas-render.controller.ts
- packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
close [2746](https://github.com/dream-num/univer/issues/2746)
> fix(permission): optimize formula bar permission & resize header permission

- packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/index.tsx
- packages/sheets-conditional-formatting-ui/src/components/panel/rule-list/index.tsx
close https://github.com/dream-num/univer-pro/issues/1708
> fix(conditional-formatting): close panel when switch subunit

- packages/sheets-data-validation/src/views/date-dropdown/index.tsx
- packages/sheets-data-validation/src/views/list-dropdown/index.tsx
- packages/sheets-data-validation/src/widgets/checkbox-widget.ts
> feat(sheet-data-valiation): using cell-raw on data-validation

- packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
- packages/sheets-ui/src/services/selection/selection-render.service.ts
- packages/sheets/src/services/selections/selection-manager.service.ts
> fix: use new selectionData not workbook._worksheetSelections

- packages/drawing-ui/src/controllers/image-update.controller.ts
> fix(image): switch tab error

- packages/engine-render/src/components/docs/layout/tools.ts
close https://github.com/dream-num/univer-pro/issues/1946
> fix: can not select text when the last page ends with table

- packages/docs/src/commands/commands/list.command.ts
> fix(docs): change list type error when cross table

- packages/core/src/services/resource-loader/resource-loader.service.ts
- packages/core/src/services/resource-manager/resource-manager.service.ts
- packages/core/src/services/resource-manager/type.ts
- packages/core/src/types/interfaces/i-workbook-data.ts
> fix(core): fix resource manager get unrelated data

- packages/sheets-data-validation/src/locale/en-US.ts
- packages/sheets-data-validation/src/locale/ru-RU.ts
- packages/sheets-data-validation/src/locale/vi-VN.ts
- packages/sheets-data-validation/src/locale/zh-CN.ts
- packages/sheets-data-validation/src/locale/zh-TW.ts
- packages/sheets-data-validation/src/views/detail/index.tsx
- packages/sheets-hyper-link-ui/src/controllers/auto-fill.controller.ts
- packages/sheets-thread-comment/src/controllers/sheets-thread-comment.controller.ts
- packages/ui/src/services/editor/editor.service.ts
close https://github.com/dream-num/univer-pro/issues/1554
close https://github.com/dream-num/univer-pro/issues/1629
close https://github.com/dream-num/univer-pro/issues/1549
> fix(sheets-data-validation): data validation validator empty ranges & comment active issue & sheet-hyper-link autofill

- packages/slides-ui/src/components/upload-component/component-name.ts
> fix: slide&sheet image component-name duplicated 

- packages-experimental/uni-slides-ui/src/controllers/uni-slides-ui.controller.tsx
- packages/docs/src/services/doc-skeleton-manager.service.ts
- packages/slides-ui/src/const.ts
- packages/slides-ui/src/controllers/slide-editing.render-controller.ts
- packages/slides-ui/src/controllers/slide-editor-bridge.render-controller.ts
- packages/slides-ui/src/controllers/slide-ui.controller.ts
- packages/slides-ui/src/index.ts
- packages/slides-ui/src/services/slide-editor-bridge.service.ts
- packages/slides-ui/src/views/editor-container/EditorContainer.tsx
> fix(editor): slide editor should use a different id from sheet cell editor

- packages/drawing-ui/src/views/panel/DrawingTransform.tsx
> fix: update drawing panel state at end of changing

- packages/ui/src/components/menu/desktop/Menu.tsx
> fix: fix issue where custom menu items are hidden by default when `hidden$` is not configured

- examples/src/sheets/main.ts
- packages/sheets-conditional-formatting/src/plugin.ts
close https://github.com/dream-num/univer/issues/3036
> fix(conditional-formatting): initialization timing problem

- packages/design/src/components/popup/index.module.less
- packages/sheets-hyper-link/src/controllers/ref-range.controller.ts
- packages/sheets-thread-comment-base/src/controllers/sheets-thread-comment-ref-range.controller.ts
- packages/sheets/src/commands/commands/remove-row-col.command.ts
- packages/sheets/src/index.ts
- packages/sheets/src/services/ref-range/__tests__/utils.spec.ts
- packages/sheets/src/services/ref-range/util.ts
close https://github.com/dream-num/univer-pro/issues/2152
> fix: hyper-link ref-range error on filter

- packages/core/src/services/snapshot/snapshot-transform.ts
- packages/engine-formula/src/engine/dependency/formula-dependency.ts
> fix(formula): skip tree after add to formula run list

- packages/sheets-numfmt/src/controllers/numfmt.cell-content.controller.ts
close https://github.com/dream-num/univer/issues/2971
> fix(numfmt): numfmt skip null or undefined

- packages/sheets/src/basics/__tests__/expand.data.ts
- packages/sheets/src/basics/__tests__/expand.spec.ts
- packages/sheets/src/basics/expand-range.ts
- packages/sheets/src/index.ts
-  if the sheet has none span, we can ignore span check logic
- we treat the span merge cells has same value just like the [left, top] cell
- we should check the span which may be added in the most left , top, right, bottom, so that can avoid the part of span be added in result range.
the count is how many times we called ` matrix.getValue(row, col)`
before:
after with span check:
without checked span:
> feat(sheet): performan the expand range

- packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
- packages/sheets-ui/src/controllers/clipboard/utils.ts
- packages/sheets-ui/src/services/clipboard/__tests__/clipboard-service.spec.ts
- packages/sheets-ui/src/services/clipboard/clipboard.service.ts
- packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
> fix: paste col should keep wider column width

- packages/core/src/shared/numfmt.ts
- packages/core/src/shared/types/numfmt.type.ts
- packages/engine-formula/src/basics/date.ts
- packages/engine-formula/src/functions/date/datevalue/index.ts
- packages/engine-formula/src/functions/date/timevalue/index.ts
- packages/sheets-numfmt/src/controllers/numfmt.editor.controller.ts
close https://github.com/dream-num/univer/issues/3043
> fix(numfmt): support edit percent with numfmt

- packages/sheets-numfmt/src/commands/commands/add-decimal.command.ts
- packages/sheets-numfmt/src/commands/commands/subtract-decimal.command.ts
close https://github.com/dream-num/univer/issues/1597
> fix(numfmt): add or substract decimal inheritance

- packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
close https://github.com/dream-num/univer-pro/issues/2227
> fix(editor): boolean values do not need to be processed

- .vscode/redi.code-snippets
- examples/src/sheets/lazy.ts
- packages/core/src/services/command/command.service.ts
- packages/sheets-filter-ui/src/controllers/sheets-filter-ui-desktop.controller.ts
- packages/sheets-filter-ui/src/controllers/sheets-filter-ui-mobile.controller.ts
- packages/sheets-filter-ui/src/filter-ui-desktop.plugin.ts
- packages/sheets-filter-ui/src/views/render-modules/sheets-filter.render-controller.ts
- packages/sheets-filter/src/controllers/sheets-filter.controller.ts
- packages/sheets-filter/src/services/sheet-filter.service.ts
- packages/sheets-numfmt/src/controllers/__tests__/test.util.ts
- packages/sheets-ui/src/commands/commands/__tests__/create-selection-command-test-bed.ts
- packages/sheets-ui/src/commands/commands/__tests__/set-selections.command.spec.ts
- packages/sheets-ui/src/commands/commands/set-selection.command.ts
- packages/sheets-ui/src/controllers/permission/sheet-permission-render.controller.ts
- packages/sheets-ui/src/controllers/sheet-ui.controller.ts
- packages/sheets-ui/src/mobile-sheets-ui-plugin.ts
- packages/sheets-ui/src/services/select-all/select-all.service.ts
- packages/sheets-ui/src/services/selection/base-selection-render.service.ts
- packages/sheets-ui/src/services/selection/mobile-selection-render.service.ts
- packages/sheets-ui/src/sheets-ui-plugin.ts
- packages/sheets/src/services/permission/range-permission/range-protection.ref-range.ts
- packages/sheets/src/services/permission/range-permission/range-protection.service.ts
- packages/sheets/src/services/sheet-interceptor/__tests__/create-core-test-bed.ts
- packages/sheets/src/services/sheet-interceptor/__tests__/sheet-interceptor.service.spec.ts
- packages/sheets/src/services/sheet-interceptor/sheet-interceptor.service.ts
- packages/sheets/src/sheets-plugin.ts
- packages/ui/src/services/shortcut/shortcut.service.ts
> refactor(filter): refactor filter for demo

- packages/design/src/components/scrollbar/Scrollbar.tsx
- packages/sheets-ui/src/index.ts
- packages/sheets-ui/src/services/format-painter/format-painter.service.ts
- fix scroll height to be a interger
- add before apply format hooks
> feat(pivot): fix scroll height & add hooks to format paint

- packages/engine-render/src/components/sheets/sheet-skeleton.ts
- packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
close https://github.com/dream-num/univer-pro/issues/993
close https://github.com/dream-num/univer-pro/issues/2069
> fix(sheets): no style in blank cell

- packages/docs-ui/src/commands/commands/clipboard.command.ts
- packages/docs-ui/src/controllers/clipboard.controller.ts
- packages/docs-ui/src/services/clipboard/clipboard.service.ts
- packages/docs-ui/src/services/clipboard/html-to-udm/converter.ts
- packages/engine-render/src/components/sheets/sheet-skeleton.ts
- packages/sheets-ui/src/services/clipboard/clipboard.service.ts
- packages/sheets-ui/src/views/editor-container/EditorContainer.tsx
- packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
- packages/sheets-zen-editor/src/controllers/zen-editor.controller.ts
close https://github.com/dream-num/univer-pro/issues/2006
> fix: copy paste between sheet and doc

- packages/drawing-ui/src/controllers/image-cropper.controller.ts
- packages/engine-render/src/components/sheets/column-header.ts
- packages/engine-render/src/components/sheets/extensions/column-header-layout.ts
- packages/engine-render/src/group.ts
- packages/engine-render/src/layer.ts
- packages/engine-render/src/scene.ts
- packages/engine-render/src/shape/shape.ts
- packages/engine-render/src/viewport.ts
- packages/sheets-conditional-formatting-ui/src/components/panel/rule-list/index.tsx
- packages/sheets-drawing-ui/src/controllers/drawing-popup-menu.controller.ts
- packages/sheets-drawing-ui/src/controllers/sheet-drawing-permission.controller.ts
- packages/sheets-filter-ui/src/views/render-modules/sheets-filter.render-controller.ts
- packages/sheets-formula/src/controllers/formula-editor-show.controller.ts
- packages/sheets-formula/src/services/render-services/ref-selections.render-service.ts
- packages/sheets-ui/src/index.ts
- packages/sheets-ui/src/services/mark-selection/mark-selection.service.ts
- packages/sheets-ui/src/services/selection/base-selection-render.service.ts
- packages/sheets-ui/src/services/selection/const.ts
- packages/sheets-ui/src/services/selection/mobile-selection-render.service.ts
- packages/sheets-ui/src/services/selection/mobile-selection-shape.ts
- packages/sheets-ui/src/services/selection/selection-shape.ts
- packages/sheets-ui/src/services/selection/util.ts
- packages/sheets-ui/src/views/editor-container/index.module.less
close https://github.com/dream-num/univer-pro/issues/2225
close https://github.com/dream-num/univer-pro/issues/2215
> fix: sheet text

- packages/sheets-formula/src/controllers/__tests__/formula-clipboard.controller.spec.ts
- packages/sheets-formula/src/controllers/formula-clipboard.controller.ts
close https://github.com/dream-num/univer-pro/issues/1665
close https://github.com/dream-num/univer-pro/issues/1355
> fix(formula): fix formula paste

- packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts
- packages/telemetry/package.json
- packages/telemetry/src/services/telemetry-service.ts
- pnpm-lock.yaml
> fix: fix dependencies of telemetry

- packages/engine-render/src/scroll-timer.ts
- packages/sheets-ui/src/services/selection/base-selection-render.service.ts
close https://github.com/dream-num/univer-pro/issues/2304
> fix: unexpected cross viewport selection because it counts rowheader

- packages/facade/src/apis/sheets/__tests__/f-range.spec.ts
- packages/facade/src/apis/sheets/__tests__/f-worksheet.spec.ts
- packages/facade/src/apis/sheets/f-range.ts
- packages/facade/src/apis/sheets/f-worksheet.ts
- packages/sheets/src/commands/commands/add-worksheet-merge.command.ts
- packages/sheets/src/commands/commands/remove-worksheet-merge.command.ts
- packages/sheets/src/index.ts
> feat(facade): add merge facade api

- packages/engine-formula/src/functions/information/function-map.ts
- packages/engine-formula/src/functions/information/isformula/__tests__/index.spec.ts
- packages/engine-formula/src/functions/information/isformula/index.ts
- packages/engine-formula/src/functions/information/n/__tests__/index.spec.ts
- packages/engine-formula/src/functions/information/n/index.ts
- packages/engine-formula/src/functions/information/na/__tests__/index.spec.ts
- packages/engine-formula/src/functions/information/na/index.ts
- packages/sheets-formula/src/locale/function-list/information/en-US.ts
- packages/sheets-formula/src/locale/function-list/information/ja-JP.ts
- packages/sheets-formula/src/locale/function-list/information/vi-VN.ts
- packages/sheets-formula/src/locale/function-list/information/zh-CN.ts
- packages/sheets-formula/src/locale/function-list/information/zh-TW.ts
- packages/sheets-formula/src/services/function-list/information.ts
> feat(formula):  isformula/n/na

- examples/src/docs/main.ts
- packages/facade/src/apis/docs/f-document.ts
- packages/facade/src/apis/f-hooks.ts
- packages/facade/src/apis/facade.ts
- packages/facade/src/apis/hooks/__tests__/f-clipboard-hooks.spec.ts
- packages/facade/src/apis/hooks/f-clipboard-hooks.ts
- packages/facade/src/apis/sheets/__tests__/f-active-range.spec.ts
- packages/facade/src/apis/sheets/__tests__/f-range.spec.ts
- packages/facade/src/apis/sheets/f-workbook.ts
- packages/facade/src/apis/sheets/f-worksheet.ts
close #xxx
clipboard 
docs
sheets
> feat(facade): add clipboard hooks and selection api

- packages/facade/src/apis/sheets/__tests__/f-range.spec.ts
- packages/facade/src/apis/sheets/f-range.ts
> feat(facade): add FRange.getValues api

- packages/core/src/shared/rectangle.ts
- packages/sheets-conditional-formatting-ui/src/controllers/cf.painter.controller.ts
- packages/sheets-conditional-formatting-ui/src/plugin.ts
- packages/sheets-ui/src/index.ts
- packages/sheets-ui/src/services/clipboard/utils.ts
close https://github.com/dream-num/univer/issues/3404
> feat(conditional-formatting): support formatting painter

- packages/docs-ui/src/controllers/render-controllers/doc.render-controller.ts
- packages/engine-render/src/components/sheets/extensions/background.ts
- packages/engine-render/src/components/sheets/extensions/row-header-layout.ts
- packages/engine-render/src/components/sheets/row-header.ts
- packages/engine-render/src/engine.ts
- packages/engine-render/src/layer.ts
- packages/engine-render/src/render-manager/render-manager.service.ts
- packages/engine-render/src/scene.ts
- packages/engine-render/src/viewport.ts
- packages/facade/src/apis/__tests__/create-test-bed.ts
- packages/facade/src/apis/__tests__/facade.spec.ts
- packages/sheets-ui/src/controllers/render-controllers/freeze.render-controller.ts
- packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts
- packages/slides-ui/src/controllers/slide.render-controller.ts
- packages/slides/src/views/render/adaptors/docs-adaptor.ts
- packages/slides/src/views/render/adaptors/slide-adaptor.ts
- packages/slides/src/views/render/adaptors/spreadsheet-adaptor.ts
close https://github.com/dream-num/univer-pro/issues/2479
> fix: the viewport size is too big after cancel filter rule, then viewport main is blank because graphic mem is full.

- packages/sheets-data-validation/src/views/list-dropdown/index.tsx
- packages/sheets-hyper-link-ui/src/views/CellLinkEdit/index.tsx
- packages/thread-comment-ui/src/views/thread-comment-editor/index.tsx
> feat(sheets-ui): optimize shortcut for comment & hyperlink editor

- packages/engine-formula/src/engine/utils/compare.ts
- packages/engine-formula/src/engine/value-object/array-value-object.ts
- packages/engine-formula/src/functions/base-function.ts
- packages/engine-formula/src/functions/lookup/hlookup/__tests__/index.spec.ts
- packages/engine-formula/src/functions/lookup/lookup/__tests__/index.spec.ts
- packages/engine-formula/src/functions/lookup/vlookup/__tests__/index.spec.ts
- packages/engine-formula/src/functions/lookup/xlookup/__tests__/index.spec.ts
- packages/engine-formula/src/functions/lookup/xlookup/index.ts
- packages/engine-formula/src/functions/lookup/xmatch/index.ts
close https://github.com/dream-num/univer-pro/issues/2345
> fix(formula): binary search supports match type

- packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
> chore: change rx subscribe when mult unit

- packages/sheets-thread-comment/src/plugin.ts
- packages/sheets-thread-comment/src/views/sheets-thread-comment-panel/index.tsx
- packages/thread-comment-ui/src/views/thread-comment-panel/index.tsx
- packages/thread-comment-ui/src/views/thread-comment-tree/index.tsx
- packages/thread-comment/src/commands/commands/comment.command.ts
- packages/thread-comment/src/models/thread-comment.model.ts
close https://github.com/dream-num/univer-pro/issues/2437
> fix(sheets-thread-comment-ui): delete comment error

- packages/data-validation/src/models/data-validation-model.ts
- packages/docs-thread-comment-ui/src/controllers/doc-thread-comment-selection.controller.ts
- packages/sheets-data-validation/src/models/sheet-data-validation-model.ts
close https://github.com/dream-num/univer-pro/issues/2557
close https://github.com/dream-num/univer-pro/issues/2553
close https://github.com/dream-num/univer-pro/issues/2549
> fix(sheets-data-validation): data validation event trigger before data applied

- packages/engine-render/src/components/docs/layout/block/paragraph/language-ruler.ts
- packages/engine-render/src/components/docs/layout/block/paragraph/linebreaking.ts
- packages/engine-render/src/components/docs/layout/block/paragraph/paragraph-layout.ts
- packages/engine-render/src/components/docs/layout/block/paragraph/shaping.ts
> fix(docs): support special emoticons

- packages/sheets-ui/src/controllers/menu.schema.ts
- packages/ui/src/components/custom-label/CustomLabel.tsx
close https://github.com/dream-num/univer-pro/issues/2588
> fix(ui): fix display values for certain menu items

- packages/sheets-conditional-formatting/src/render/data-bar.render.ts
close https://github.com/dream-num/univer-pro/issues/2564
> fix(conditional-formatting): data bar render error

- packages/sheets/src/commands/commands/__tests__/set-border.command.spec.ts
- packages/sheets/src/commands/commands/set-border-command.ts
- packages/sheets/src/commands/commands/utils/target-util.ts
close https://github.com/dream-num/univer-pro/issues/2561
close https://github.com/dream-num/univer/issues/3391
> fix: border for merged cell

- packages/sheets/src/commands/commands/__tests__/insert-range.command.spec.ts
- packages/sheets/src/commands/commands/insert-range-move-right.command.ts
- packages/sheets/src/controllers/merge-cell.controller.ts
- packages/sheets/src/sheets-plugin.ts
close https://github.com/dream-num/univer/issues/3567
> chore: change controller register timing

- examples/src/docs/main.ts
- packages-experimental/debugger/src/commands/operations/save-snapshot.operations.ts
- packages/sheets/src/controllers/merge-cell.controller.ts
> refactor: remove redundant code

- packages/core/src/shared/array-search.ts
- packages/core/src/shared/object-matrix.ts
- packages/core/src/shared/rectangle.ts
- packages/core/src/sheets/span-model.ts
- packages/core/src/sheets/worksheet.ts
- packages/engine-formula/src/engine/reference-object/base-reference-object.ts
- packages/engine-formula/src/functions/meta/compare/__tests__/index.spec.ts
- packages/engine-render/src/basics/tools.ts
- packages/engine-render/src/components/docs/layout/doc-skeleton.ts
- packages/engine-render/src/components/docs/layout/shaping-engine/font-cache.ts
- packages/engine-render/src/components/extension.ts
- packages/engine-render/src/components/sheets/extensions/background.ts
- packages/engine-render/src/components/sheets/extensions/border.ts
- packages/engine-render/src/components/sheets/extensions/font.ts
- packages/engine-render/src/components/sheets/extensions/sheet-extension.ts
- packages/engine-render/src/components/sheets/interfaces.ts
- packages/engine-render/src/components/sheets/sheet-skeleton.ts
- packages/engine-render/src/components/sheets/spreadsheet.ts
- packages/engine-render/src/viewport.ts
- packages/sheets-data-validation/src/models/sheet-data-validation-model.ts
- packages/sheets-data-validation/src/services/dv-custom-formula.service.ts
- packages/sheets-hyper-link/src/models/hyper-link.model.ts
- packages/sheets-ui/src/services/hover-manager.service.ts
- packages/sheets/src/basics/expand-range.ts
- packages/sheets/src/basics/rangeMerge.ts
- packages/sheets/src/basics/utils.ts
close  https://github.com/dream-num/univer-pro/issues/2529
close  https://github.com/dream-num/univer/issues/3475
Now _getCellDocumentModel() is called too frequenctly.
_getCellDocumentModel() ---> fontString(font family) ---> set font cache matrix by font family.
Each render frame calc fontString(font family) in _getCellDocumentModel in _setStylesCache.
Return condition deps on fontString(font family). That costs a lot of time.
No need to do this. Just using font Matrix.
> fix: perf improving in set style cache

- packages/core/src/shared/__tests__/range.spec.ts
- packages/core/src/shared/object-matrix-query.ts
- packages/core/src/shared/range.ts
- packages/core/src/shared/rectangle.ts
- packages/sheets/src/services/ref-range/util.ts
> feat(core): optimize split into grid function

- packages/sheets-filter-ui/src/commands/commands/sheets-filter.command.ts
- packages/sheets-filter-ui/src/views/components/SheetsFilterByValuesPanel.tsx
- packages/sheets-filter-ui/src/views/components/SheetsFilterPanel.tsx
- packages/sheets-filter/src/controllers/__tests__/sheets-filter.controller.spec.ts
- packages/sheets-filter/src/controllers/sheets-filter.controller.ts
- packages/sheets/src/commands/commands/copy-worksheet.command.ts
- packages/sheets/src/index.ts
close https://github.com/dream-num/univer-pro/issues/940 https://github.com/dream-num/univer-pro/issues/2624 https://github.com/dream-num/univer-pro/issues/2210 https://github.com/dream-num/univer-pro/issues/2232
> fix: copy sheet should copy filter

- packages/sheets/src/commands/commands/insert-row-col.command.ts
close https://github.com/dream-num/univer-pro/issues/2288
close #xxx
> fix(sheets): fix insert row col range type

- packages/sheets-hyper-link-ui/src/views/CellLinkEdit/index.tsx
- packages/sheets-thread-comment/src/controllers/sheets-thread-comment-hover.controller.ts
- packages/sheets-thread-comment/src/controllers/sheets-thread-comment-popup.controller.ts
- packages/sheets-thread-comment/src/views/sheets-thread-comment-panel/index.tsx
- packages/sheets-ui/src/services/canvas-pop-manager.service.ts
- packages/sheets-ui/src/services/hover-manager.service.ts
- packages/sheets-ui/src/services/utils/doc-skeleton-util.ts
close https://github.com/dream-num/univer-pro/issues/2641
> fix(sheets-hyper-link-ui): link & doc markSelection error on merged cell

- packages/sheets-ui/src/controllers/auto-fill.controller.ts
close https://github.com/dream-num/univer-pro/issues/2575
close https://github.com/dream-num/univer-pro/issues/2574
> fix(auto-fill): merge-cell bugs in auto-fill

- packages/core/src/sheets/span-model.ts
> feat(sheet): add flag to get better performance

- packages/engine-render/src/canvas.ts
- packages/engine-render/src/engine.ts
- packages/engine-render/src/viewport.ts
- packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts
close https://github.com/dream-num/univer/issues/3555
Way to reproduce this issue:
first
univerAPI.disposeUnit('workbook-01')
then
univerAPI.createUniverSheet()
> fix: dispose and createUnit cause viewport height collapse

- packages-experimental/action-recorder/src/controllers/config.schema.ts
- packages-experimental/action-recorder/src/plugin.ts
> feat: add replay-only mode to actionRecordPlugin

- packages/sheets/src/commands/commands/__tests__/set-style.command.spec.ts
- packages/sheets/src/commands/commands/set-style.command.ts
close #3502
```ts
const sheet1 = univerAPI.getActiveWorkbook().insertSheet();
const sheet2 = univerAPI.getActiveWorkbook().insertSheet();
const marks = [
{
id: sheet1.getSheetId(),
row: 0,
col: 0,
},
{
id: sheet2.getSheetId(),
row: 1,
col: 1,
},
];
marks.forEach((m) => {
console.log(m);
if (m.id === sheet1.getSheetId()) {
univerAPI
.getActiveWorkbook()
?.getSheetBySheetId(m.id)
?.getRange(m.row, m.col, 1, 1)
.setBackgroundColor('red');
}
if (m.id === sheet2.getSheetId()) {
univerAPI
.getActiveWorkbook()
?.getSheetBySheetId(m.id)
?.getRange(m.row, m.col, 1, 1)
.setBackgroundColor('green');
}
});
```
> fix(sheets): correct unitId and subUnitId usage in SetStyleCommand

- packages/sheets-data-validation-ui/src/views/detail/index.tsx
- packages/sheets-formula-ui/src/controllers/prompt.controller.ts
- packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
- packages/sheets-ui/src/services/editor-bridge.service.ts
> fix(sheets-ui): set focus editing mode when dbclick & error resize when change sub sheet

- packages-experimental/action-recorder/src/commands/commands/record.command.ts
- packages-experimental/action-recorder/src/commands/commands/replay.command.ts
- packages-experimental/action-recorder/src/controllers/action-recorder.controller.tsx
- packages-experimental/action-recorder/src/controllers/action-recorder.menu.ts
- packages-experimental/action-recorder/src/services/action-recorder.service.ts
- packages-experimental/action-recorder/src/services/replay.service.ts
- packages-experimental/action-recorder/src/views/components/RecorderPanel.tsx
- packages-experimental/action-recorder/src/views/components/index.module.less
> feat: record & replay commands with multi-mode

- packages/engine-formula/src/engine/value-object/array-value-object.ts
> fix(formula): fix ArrayValueObject compare cache bug

- packages/sheets-ui/src/controllers/menu/insert.menu.ts
- packages/sheets-ui/src/controllers/permission/sheet-permission-init.controller.ts
- packages/sheets-ui/src/views/permission/panel-detail/index.tsx
close https://github.com/dream-num/univer-pro/issues/2874
> fix: fix permission rangeSelector & insert menu

- packages/engine-formula/src/engine/utils/reference.ts
- packages/engine-formula/src/engine/value-object/array-value-object.ts
- packages/engine-formula/src/engine/value-object/primitive-object.ts
- packages/engine-formula/src/functions/math/power/__tests__/index.spec.ts
- packages/engine-formula/src/services/runtime.service.ts
- packages/sheets-formula-ui/src/controllers/formula-alert-render.controller.ts
- packages/sheets-formula-ui/src/controllers/formula-render.controller.ts
- packages/sheets-formula-ui/src/controllers/utils/utils.ts
- packages/sheets-formula/src/controllers/utils/utils.ts
close #3772 
close https://github.com/dream-num/univer-pro/issues/2894
close https://github.com/dream-num/univer-pro/issues/2440
close https://github.com/dream-num/univer-pro/issues/2212
> fix(formula): fix some bug

- packages/docs-ui/src/commands/commands/list.command.ts
- packages/docs/src/commands/mutations/core-editing.mutation.ts
close https://github.com/dream-num/univer-pro/issues/2863
> fix(docs-ui): don't refresh-selection after set list

- packages/docs-ui/src/commands/commands/doc-header-footer.command.ts
- packages/docs-ui/src/views/header-footer/panel/DocHeaderFooterOptions.tsx
close https://github.com/dream-num/univer-pro/issues/2782
> fix(docs): header footer setting not focus

- packages/core/src/docs/data-model/text-x/build-utils/custom-range.ts
- packages/core/src/docs/data-model/text-x/build-utils/selection.ts
- packages/core/src/docs/data-model/text-x/build-utils/text-x-utils.ts
- packages/docs-hyper-link-ui/src/views/hyper-link-edit/index.tsx
- packages/docs-ui/src/services/doc-state-change-manager.service.ts
- packages/docs/src/commands/mutations/core-editing.mutation.ts
- packages/docs/src/services/doc-state-emit.service.ts
- packages/sheets-data-validation-ui/src/views/components/date-dropdown/index.tsx
- packages/sheets-data-validation-ui/src/views/components/list-dropdown/index.tsx
- packages/sheets-hyper-link-ui/src/commands/commands/add-hyper-link.command.ts
- packages/sheets-hyper-link-ui/src/controllers/menu.ts
- packages/sheets-hyper-link-ui/src/controllers/popup.controller.ts
- packages/sheets-hyper-link-ui/src/utils/index.ts
- packages/sheets-hyper-link-ui/src/views/CellLinkEdit/index.tsx
- packages/sheets-ui/src/commands/commands/inline-format.command.ts
- packages/sheets-ui/src/commands/commands/set-frozen.command.ts
- packages/sheets-ui/src/controllers/editor/data-sync.controller.ts
- packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
- packages/sheets-ui/src/controllers/menu/menu-util.ts
- packages/sheets-ui/src/controllers/menu/menu.ts
- packages/sheets-ui/src/controllers/menu/permission-menu-util.ts
- packages/sheets-ui/src/controllers/sheet-ui.controller.ts
- packages/sheets-ui/src/index.ts
- packages/sheets/src/commands/commands/set-style.command.ts
- packages/sheets/src/commands/mutations/set-frozen.mutation.ts
- packages/ui/src/views/components/zen-zone/ZenZone.tsx
实现方案
1. toolbar + context-menu在editing的状态时将sheet的菜单。
2. 编辑时context处于doc中，无法匹配到sheet的shortcut - 无需改动。
3. facade api 的调用不应该导致editing的退出，除非手动调用退出命令 - 无需改动。
close https://github.com/dream-num/univer-pro/issues/2918
close https://github.com/dream-num/univer-pro/issues/2500
close https://github.com/dream-num/univer-pro/issues/2870
close https://github.com/dream-num/univer-pro/issues/2919
close https://github.com/dream-num/univer-pro/issues/2899
close https://github.com/dream-num/univer-pro/issues/2904
close https://github.com/dream-num/univer-pro/issues/2639
close https://github.com/dream-num/univer-pro/issues/2917
close https://github.com/dream-num/univer-pro/issues/2926
close https://github.com/dream-num/univer-pro/issues/2924
These issues are not reproducible.
close …
> fix(sheets-ui): should disable sheet menus on cell editing

- packages/core/src/docs/data-model/text-x/__tests__/apply.spec.ts
- packages/core/src/docs/data-model/text-x/__tests__/transform.spec.ts
- packages/core/src/docs/data-model/text-x/text-x.ts
- packages/core/src/docs/data-model/text-x/transform-utils.ts
- packages/docs-ui/src/commands/commands/doc-paragraph-setting.command.ts
close https://github.com/dream-num/univer-pro/issues/2963
> fix(doc): transform with REPLACE type

- packages/core/src/docs/data-model/preset-list-type.ts
- packages/core/src/docs/data-model/text-x/__tests__/apply.spec.ts
- packages/core/src/docs/data-model/text-x/transform-utils.ts
close https://github.com/dream-num/univer-pro/issues/2859
> fix(docs): transform in bullet list

- packages/core/src/docs/data-model/text-x/__tests__/apply-utils.spec.ts
- packages/core/src/docs/data-model/text-x/__tests__/apply.spec.ts
- packages/core/src/docs/data-model/text-x/__tests__/common.spec.ts
- packages/core/src/docs/data-model/text-x/apply-utils/common.ts
- packages/docs-ui/src/basics/paragraph.ts
- packages/docs-ui/src/commands/commands/__tests__/create-command-test-bed.ts
- packages/docs-ui/src/commands/commands/ime-input.command.ts
- packages/docs-ui/src/commands/commands/inline-format.command.ts
- packages/docs-ui/src/controllers/menu/menu.ts
- packages/docs-ui/src/controllers/render-controllers/doc-input.controller.ts
- packages/docs-ui/src/docs-ui-plugin.ts
- packages/docs-ui/src/services/doc-ime-input-manager.service.ts
- packages/docs-ui/src/services/doc-menu-style.service.ts
close https://github.com/dream-num/univer-pro/issues/2979
> feat(docs): set inline style at cursor

- packages/engine-formula/src/engine/ast-node/function-node.ts
- packages/engine-formula/src/functions/base-function.ts
- packages/engine-formula/src/functions/information/function-map.ts
- packages/engine-formula/src/functions/information/sheet/__tests__/index.spec.ts
- packages/engine-formula/src/functions/information/sheet/index.ts
- packages/engine-formula/src/functions/information/sheets/__tests__/index.spec.ts
- packages/engine-formula/src/functions/information/sheets/index.ts
- packages/engine-formula/src/services/current-data.service.ts
- packages/sheets-formula-ui/src/locale/function-list/information/en-US.ts
- packages/sheets-formula-ui/src/locale/function-list/information/ja-JP.ts
- packages/sheets-formula-ui/src/locale/function-list/information/vi-VN.ts
- packages/sheets-formula-ui/src/locale/function-list/information/zh-CN.ts
- packages/sheets-formula-ui/src/locale/function-list/information/zh-TW.ts
- packages/sheets-formula/src/services/function-list/information.ts
> feat(formula): supplement sheet and sheets formula

- packages/sheets-hyper-link-ui/src/controllers/rich-text-ref-range.controller.ts
- packages/sheets-hyper-link-ui/src/views/CellLinkEdit/index.tsx
close https://github.com/dream-num/univer-pro/issues/3033
> fix(sheets-hyper-link): link ref range behavior error

- packages/network/src/plugin.ts
> feat(network): network plugin support overrides

- packages/sheets-numfmt/src/controllers/numfmt.editor.controller.ts
- packages/sheets-ui/package.json
- packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
- packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
- packages/sheets/src/services/__tests__/numfmt.service.test.ts
- packages/sheets/src/services/numfmt/numfmt.service.ts
- pnpm-lock.yaml
> fix(cell): fix cell string type

- packages/core/src/common/__tests__/interceptor.spec.ts
- packages/core/src/common/interceptor.ts
- packages/core/src/index.ts
> feat: add async interceptor

- packages/docs-ui/src/basics/paragraph.ts
- packages/docs-ui/src/commands/commands/break-line.command.ts
- packages/docs-ui/src/commands/commands/ime-input.command.ts
- packages/docs-ui/src/controllers/menu/menu.ts
- packages/docs-ui/src/controllers/render-controllers/doc-input.controller.ts
- packages/docs-ui/src/services/doc-menu-style.service.ts
- packages/engine-render/src/components/docs/layout/block/paragraph/language-ruler.ts
- packages/engine-render/src/components/docs/layout/block/paragraph/layout-ruler.ts
- packages/engine-render/src/components/docs/layout/block/paragraph/paragraph-layout.ts
- packages/engine-render/src/components/docs/layout/block/paragraph/shaping.ts
close https://github.com/dream-num/univer-pro/issues/3052
close https://github.com/dream-num/univer-pro/issues/2835
> fix(docs): default text style in doc

- examples/src/uni/main.ts
> fix(uni): fix formula editor

- .vscode/settings.json
- packages/core/src/shared/array-search.ts
- packages/engine-render/src/components/sheets/sheet-skeleton.ts
- packages/engine-render/src/components/sheets/spreadsheet.ts
- packages/engine-render/src/components/skeleton.ts
- packages/sheets-filter/src/models/filter-model.ts
- packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts
- packages/sheets-ui/src/services/sheet-skeleton-manager.service.ts
close https://github.com/dream-num/univer-pro/issues/2310
close https://github.com/dream-num/univer-pro/issues/2791
> fix: filter rollback in another worksheet

- packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
- packages/sheets-ui/src/services/clipboard/html-to-usm/utils.ts
close https://github.com/dream-num/univer-pro/issues/2604
> fix: some case rich text style should convert to cell style

- packages/sheets-ui/src/controllers/clipboard/utils.ts
close https://github.com/dream-num/univer-pro/issues/2736
> fix: cutting to the target range does not require filtering merge cells of the same size

- packages/sheets-numfmt-ui/src/controllers/__tests__/editor.controller.spec.ts
- packages/sheets-numfmt-ui/src/controllers/numfmt.editor.controller.ts
- packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
- packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
> fix: parsing of number formats should be done in plugins

- examples/src/docs/main.ts
- mockdata/src/docs/default-document.data-simple.ts
- packages/core/src/types/interfaces/i-document-data.ts
- packages/docs-ui/src/commands/commands/table/table.ts
- packages/docs-ui/src/services/selection/convert-rect-range.ts
- packages/engine-render/src/basics/i-document-skeleton-cached.ts
- packages/engine-render/src/basics/interfaces.ts
- packages/engine-render/src/components/docs/document.ts
- packages/engine-render/src/components/docs/extensions/font-and-base-line.ts
- packages/engine-render/src/components/docs/layout/block/paragraph/layout-ruler.ts
- packages/engine-render/src/components/docs/layout/block/paragraph/linebreaking.ts
- packages/engine-render/src/components/docs/layout/block/section.ts
- packages/engine-render/src/components/docs/layout/block/table.ts
- packages/engine-render/src/components/docs/layout/doc-skeleton.ts
- packages/engine-render/src/components/docs/layout/model/line.ts
- packages/engine-render/src/components/docs/layout/model/page.ts
- packages/engine-render/src/components/docs/layout/tools.ts
> feat(render-engine): table wrap layout type

- packages/sheets-drawing-ui/src/locale/zh-CN.ts
- packages/sheets-drawing-ui/src/locale/zh-TW.ts
> fix(sheets-drawing-ui): fix `drawing-move-right` translation in zh-CN & zh-TW

- packages/core/src/docs/data-model/text-x/build-utils/custom-decoration.ts
- packages/core/src/docs/data-model/text-x/build-utils/index.ts
- packages/docs-ui/src/basics/custom-decoration-factory.ts
close https://github.com/dream-num/univer-pro/issues/3071
> feat(docs-thread-comment): disable undo redo on docs comment

- docs/FIX_MEMORY_LEAK.md
- packages/sheets-ui/src/views/sheet-container/SheetContainer.tsx
> docs: guidance on how to fix memory leaks

- packages/engine-render/src/components/sheets/extensions/background.ts
close https://github.com/dream-num/univer-pro/issues/3280
> fix: mixed policy in rendering cells in bg extension

- mockdata/src/sheets/demo/default-workbook-data-demo.ts
- packages/sheets-drawing-ui/src/controllers/sheet-drawing-update.controller.ts
- packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts
- packages/ui/src/views/components/dom/FloatDom.tsx
close https://github.com/dream-num/univer-pro/issues/3296
> fix(sheets-drawing-ui): sheet-drawing memory leak

- packages/docs-mention-ui/src/commands/commands/doc-mention.command.ts
- packages/docs-ui/src/commands/commands/core-editing.command.ts
- packages/docs/src/utils/replace-selection-factory.ts
> fix(doc-mention): doc mention error

- packages/core/src/docs/data-model/text-x/__tests__/apply-consistency.spec.ts
- packages/core/src/docs/data-model/text-x/apply-utils/common.ts
- packages/core/src/docs/data-model/text-x/apply-utils/delete-apply.ts
- packages/core/src/docs/data-model/text-x/text-x.ts
> fix(docs): invert action issue

- packages/sheets-ui/src/services/selection/selection-render.service.ts
- packages/sheets-ui/src/services/selection/selection-shape-extension.ts
> fix: move range selection not showing when dragging a selection

- packages/core/src/docs/data-model/text-x/utils.ts
- packages/docs-ui/src/commands/commands/__tests__/inline-format.command.spec.ts
- packages/docs-ui/src/commands/commands/inline-format.command.ts
- packages/docs-ui/src/controllers/menu/menu.ts
close https://github.com/dream-num/univer-pro/issues/2536
> fix(docs-ui): cache menu style

- packages/design/src/components/input-number/InputNumber.tsx
> feat(ui): support onFocus event in InputNumber

- packages/sheets-ui/src/controllers/clipboard/utils.ts
> fix: bugs in cut-paste undo scenario

- packages/sheets-ui/src/facade/f-range.ts
- packages/sheets-ui/src/facade/f-workbook.ts
- packages/sheets-ui/src/services/hover-manager.service.ts
* fWorkbook.onCellHover
* fWorkbook.onCellClick
* fRange.highlight
> feat(sheets-ui): add hover facade api

- packages/engine-render/src/basics/i-events.ts
- packages/engine-render/src/components/component.ts
- packages/engine-render/src/engine.ts
- packages/engine-render/src/scene.input-manager.ts
- packages/engine-render/src/scene.ts
- packages/engine-render/src/thin-scene.ts
- packages/engine-render/src/viewport.ts
- packages/sheets-ui/src/controllers/render-controllers/scroll.render-controller.ts
- packages/sheets-ui/src/services/selection/base-selection-render.service.ts
close https://github.com/dream-num/univer-pro/issues/3338
> fix: set pointer caputure when pointer out 

- packages/docs-drawing-ui/src/controllers/render-controllers/doc-drawing-update.render-controller.ts
- packages/docs-drawing/src/index.ts
- packages/docs-ui/package.json
- packages/docs-ui/src/controllers/render-controllers/doc-clipboard.controller.ts
- packages/docs-ui/src/services/clipboard/__test__/html-and-udm-convert.spec.ts
- packages/docs-ui/src/services/clipboard/clipboard.service.ts
- packages/docs-ui/src/services/clipboard/html-to-udm/converter.ts
- packages/docs-ui/src/services/clipboard/udm-to-html/__test__/convertor.spec.ts
- packages/docs-ui/src/services/clipboard/udm-to-html/convertor.ts
- packages/ui/src/index.ts
- packages/ui/src/services/clipboard/clipboard-interface.service.ts
- pnpm-lock.yaml
> feat(docs): pictures support writing to the clipboard

- packages-experimental/uni-formula-ui/src/uni-formula-ui.plugin.ts
- packages/sheets-formula/src/sheets-formula.plugin.ts
> fix(formula): init trigger calculation controller on rendered

- packages/docs-ui/src/controllers/menu/menu.ts
close https://github.com/dream-num/univer-pro/issues/3431
> fix(docs-ui): menu align when select table cells

- packages/docs-ui/src/controllers/render-controllers/doc.render-controller.ts
close https://github.com/dream-num/univer-pro/issues/3434
close https://github.com/dream-num/univer-pro/issues/2927
> fix: cal page size in modern mode

- packages/core/src/sheets/worksheet.ts
- packages/sheets-data-validation-ui/src/controllers/dv-auto-fill.controller.ts
- packages/sheets-data-validation/src/commands/commands/data-validation.command.ts
- packages/sheets-data-validation/src/utils/formula.ts
- packages/sheets-ui/src/services/clipboard/clipboard.service.ts
- packages/sheets/src/commands/commands/utils/selection-utils.ts
close https://github.com/dream-num/univer-pro/issues/2432
> fix: auto fill should delete dv rules

- packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
- packages/ui/src/components/progress-bar/ProgressBar.tsx
> fix(ui): progress bar animation

- packages/core/src/index.ts
- packages/core/src/shared/r-tree.ts
- packages/core/src/types/interfaces/i-data-validation.ts
- packages/data-validation/src/services/data-validator-registry.service.ts
- packages/data-validation/src/validators/base-data-validator.ts
- packages/sheets-data-validation-ui/src/controllers/dv-auto-fill.controller.ts
- packages/sheets-data-validation/package.json
- packages/sheets-data-validation/src/commands/commands/data-validation.command.ts
- packages/sheets-data-validation/src/controllers/dv-formula-ref-range.controller.ts
- packages/sheets-data-validation/src/controllers/dv-ref-range.controller.ts
- packages/sheets-data-validation/src/facade/f-data-validation-builder.ts
- packages/sheets-data-validation/src/facade/f-data-validation.ts
- packages/sheets-data-validation/src/models/rule-matrix.ts
- packages/sheets-data-validation/src/models/sheet-data-validation-model.ts
- packages/sheets-data-validation/src/services/dv-cache.service.ts
- packages/sheets-data-validation/src/services/dv-custom-formula.service.ts
- packages/sheets-data-validation/src/services/dv-formula.service.ts
- packages/sheets-data-validation/src/utils/formula.ts
- packages/sheets-data-validation/src/validators/any-validator.ts
- packages/sheets-data-validation/src/validators/checkbox-validator.ts
- packages/sheets-data-validation/src/validators/date-validator.ts
- packages/sheets-data-validation/src/validators/decimal-validator.ts
- packages/sheets-data-validation/src/validators/list-multiple-validator.ts
- packages/sheets-data-validation/src/validators/list-validator.ts
- packages/sheets-data-validation/src/validators/text-length-validator.ts
- packages/sheets-data-validation/src/validators/whole-validator.ts
- packages/sheets-hyper-link-ui/src/utils/index.ts
- pnpm-lock.yaml
1. Simplify sheet validator
2. add `offsetFormulaByRanges`
3. support developer to register their custom validator
> refactor(data-validation): data validation validator

- packages/engine-formula/src/functions/logical/iferror/__tests__/index.spec.ts
- packages/engine-formula/src/functions/logical/iferror/index.ts
> fix(formula): fix iferror

- packages/docs-ui/src/services/selection/selection-utils.ts
- packages/docs/src/services/doc-skeleton-manager.service.ts
close https://github.com/dream-num/univer-pro/issues/3520
> fix(docs-ui): double paste issue

- packages/core/src/index.ts
> refactor(core): remove duplicate exports

- packages/sheets-ui/src/index.ts
AddWorksheetMergeAllCommand has multiple implementations
close #xxx
> refactor(sheets-ui)!: remove duplicate command export

- packages/docs-ui/src/services/selection/text-range.ts
- packages/engine-render/src/layer.ts
> fix: cursor blink lags when pointer down at text range

- packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
- packages/sheets-ui/src/plugin.ts
close https://github.com/dream-num/univer-pro/issues/2898
> fix: clipboard deps

- packages/engine-formula/src/basics/common.ts
- packages/engine-formula/src/controller/calculate.controller.ts
- packages/engine-formula/src/engine/analysis/__tests__/create-command-test-bed.ts
- packages/engine-formula/src/functions/__tests__/create-function-test-bed.ts
- packages/engine-formula/src/models/__tests__/formula-data.model.spec.ts
- packages/engine-formula/src/models/formula-data.model.ts
- packages/engine-formula/src/models/utils/formula-data-util.ts
- packages/facade/src/apis/sheets/__tests__/f-range.spec.ts
- packages/sheets-data-validation/src/services/dv-validator-service.ts
- packages/sheets-formula-ui/src/controllers/__tests__/create-command-test-bed.ts
- packages/sheets-formula-ui/src/controllers/formula-clipboard.controller.ts
- packages/sheets-formula-ui/src/controllers/formula-editor-show.controller.ts
- packages/sheets-formula/src/controllers/update-formula.controller.ts
- packages/sheets-formula/src/services/__test__/util.ts
Test any formula-related use cases
For example
> fix(formula): update formula data model

- mockdata/src/docs/default-document.data-simple.ts
- packages/core/src/docs/data-model/empty-snapshot.ts
- packages/core/src/services/instance/instance.service.ts
- packages/docs-ui/src/basics/table.ts
- packages/docs-ui/src/commands/commands/table/doc-table-tab.command.ts
- packages/docs-ui/src/controllers/doc-auto-format.controller.ts
- packages/docs-ui/src/services/doc-auto-format.service.ts
- packages/engine-render/src/basics/i-document-skeleton-cached.ts
- packages/engine-render/src/components/docs/layout/block/paragraph/linebreaking.ts
- packages/engine-render/src/components/docs/layout/block/table.ts
- packages/engine-render/src/components/docs/layout/doc-skeleton.ts
close https://github.com/dream-num/univer-pro/issues/3270
> feat(render-engine): support repeat table header

- packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
- packages/sheets-ui/src/controllers/utils/char-tools.ts
Fix parse cell input
How to test?
1. Enter `=SUM(11, 2 2, 33)` in the Cell
2. Keep `=SUM(11, 2 2, 33)` (Previously it was correctly coverted to `=SUM(11, 45324, 33)`)
> fix(sheet): parseValue handle number

- packages/engine-formula/src/engine/utils/__tests__/reference.spec.ts
- packages/engine-formula/src/engine/utils/reference.ts
- packages/sheets-formula-ui/src/controllers/formula-alert-render.controller.ts
- packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
- packages/sheets-ui/src/controllers/utils/char-tools.ts
close #4076
close #4002
close #3902 (Not reproduced, just test it)
> fix(sheet): sheet name normalize string

- packages/sheets-filter-ui/src/views/components/SheetsFilterByConditionsPanel.tsx
> fix(sheets-filter-ui): fix the react compatibility issue with sheets filter

- packages/sheets-conditional-formatting-ui/src/controllers/cf.editor.controller.ts
- packages/sheets-numfmt-ui/src/controllers/numfmt.editor.controller.ts
…atting does not fall
close https://github.com/dream-num/univer-pro/issues/2495
close #xxx
> fix(conditional-formatting): the style that involves conditional formatting does not fall

- .vscode/settings.json
- packages/engine-render/src/viewport.ts
> chore: add resize$ for viewport

- packages/engine-formula/README.md
- packages/engine-formula/src/functions/date/epochtodate/__tests__/index.spec.ts
- packages/engine-formula/src/functions/date/epochtodate/index.ts
- packages/engine-formula/src/functions/information/isbetween/__tests__/index.spec.ts
- packages/engine-formula/src/functions/information/isbetween/index.ts
- packages/engine-formula/src/functions/math/roundbank/__tests__/index.spec.ts
- packages/engine-formula/src/functions/math/roundbank/index.ts
- packages/engine-formula/src/functions/statistical/average-weighted/__tests__/index.spec.ts
- packages/engine-formula/src/functions/statistical/average-weighted/index.ts
- packages/engine-formula/src/functions/statistical/linest/__tests__/index.spec.ts
- packages/engine-formula/src/functions/statistical/linest/index.ts
- packages/engine-formula/src/functions/statistical/trend/__tests__/index.spec.ts
- packages/engine-formula/src/functions/statistical/trend/index.ts
test in https://univer-preview.vercel.app/sheets/
> fix(formula): some formulas need to be tested in dev

- packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx
close [#3653](https://github.com/dream-num/univer-pro/issues/3653)
> fix(sheet): resizeObserver disconnect when unmount in sheetBarTabs

- packages/core/src/common/url.ts
remove exclusion of private & local ip address
> fix(core): url regexper

- packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
- packages/sheets-ui/src/controllers/clipboard/utils.ts
- packages/sheets-ui/src/services/clipboard/clipboard.service.ts
close https://github.com/dream-num/univer-pro/issues/3715
close https://github.com/dream-num/univer-pro/issues/3716
close https://github.com/dream-num/univer-pro/issues/3718
close https://github.com/dream-num/univer-pro/issues/2577
> fix: paste should clear target cell value

- packages/sheets-ui/src/services/clipboard/clipboard.service.ts
- packages/sheets-ui/src/services/clipboard/copy-content-cache.ts
- packages/sheets-ui/src/views/permission/panel/index.tsx
close https://github.com/dream-num/univer-pro/issues/3428
close https://github.com/dream-num/univer-pro/issues/3429
> fix: fix clipboard when dispose

- packages/engine-render/src/basics/tools.ts
- packages/engine-render/src/canvas.ts
- packages/engine-render/src/components/docs/extensions/background.ts
- packages/engine-render/src/components/docs/extensions/line.ts
- packages/engine-render/src/components/sheets/spreadsheet.ts
- packages/engine-render/src/engine.ts
- packages/engine-render/src/viewport.ts
- packages/sheets-ui/src/services/editor/cell-editor-resize.service.ts
- packages/sheets-ui/src/services/selection/selection-render.service.ts
- packages/sheets-ui/src/views/count-bar/ZoomSlider.tsx
- packages/sheets-ui/src/views/editor-container/EditorContainer.tsx
- packages/sheets-ui/src/views/editor-container/index.module.less
close https://github.com/dream-num/univer-pro/issues/1548
close https://github.com/dream-num/univer-pro/issues/1121
close https://github.com/dream-num/univer-pro/issues/1167
close https://github.com/dream-num/univer-pro/issues/1181
close https://github.com/dream-num/univer-pro/issues/3628
> fix: some rendering issues in doc

- packages/engine-formula/src/functions/__tests__/nested-functions.spec.ts
- packages/engine-formula/src/functions/math/product/__tests__/index.spec.ts
- packages/engine-formula/src/functions/math/product/index.ts
> fix(formula): fix product formula

- packages/engine-formula/src/functions/lookup/xlookup/__tests__/index.spec.ts
- packages/engine-formula/src/functions/lookup/xlookup/index.ts
> fix(formula): fix xlookup formula

- packages/sheets-ui/src/facade/f-sheet-hooks.ts
- packages/sheets/src/facade/f-univer.ts
- packages/ui/src/controllers/ui/ui.controller.ts
- packages/ui/src/facade/f-univer.ts
> feat(ui): add more facade

- common/shared/eslint/index.js
- common/shared/eslint/plugins/no-external-imports-in-facade.js
- common/shared/eslint/plugins/no-self-package-imports.js
- eslint.config.js
- packages/sheets-ui/src/facade/f-workbook.ts
- packages/sheets-ui/src/facade/f-worksheet.ts
- packages/sheets-ui/src/index.ts
- packages/sheets/src/facade/f-workbook.ts
- packages/sheets/src/facade/f-worksheet.ts
> chore: add facade eslint

- examples/src/sheets/main.ts
- packages/sheets-conditional-formatting/package.json
- packages/sheets-conditional-formatting/src/facade/conditional-formatting-builder.ts
- packages/sheets-conditional-formatting/src/facade/f-range.ts
- packages/sheets-conditional-formatting/src/facade/f-workbook.ts
- packages/sheets-conditional-formatting/src/facade/f-worksheet.ts
- packages/sheets-conditional-formatting/src/facade/index.ts
> feat(conditional-formatting): support facade api

- examples/src/sheets/main.ts
- packages/ui/src/controllers/menus/menu.schema.ts
- packages/ui/src/controllers/menus/menus.ts
- packages/ui/src/facade/f-menu-builder.ts
- packages/ui/src/facade/f-univer.ts
- packages/ui/src/facade/index.ts
> feat(ui): support ui menu facade

- packages/sheets-data-validation/src/facade/f-data-validation.ts
- packages/sheets-data-validation/src/facade/f-range.ts
- packages/sheets-data-validation/src/facade/f-univer.ts
- packages/sheets-data-validation/src/facade/f-worksheet.ts
- packages/sheets/src/facade/f-range.ts
> feat(facade): add range to-string api & fix data-validation api

- packages/sheets-ui/src/commands/commands/clipboard.command.ts
- packages/sheets-ui/src/services/clipboard/clipboard.service.ts
- packages/ui/src/facade/f-hooks.ts
- packages/ui/src/index.ts
- packages/ui/src/services/clipboard/clipboard.command.ts
> fix: some bugs on clipboard facade API

- packages/core/src/facade/f-univer.ts
- packages/core/src/facade/f-user.ts
- packages/core/src/facade/f-usermanager.ts
- packages/core/src/services/user-manager/user-manager.service.ts
- packages/sheets-thread-comment/src/facade/f-range.ts
- packages/sheets-thread-comment/src/facade/f-worksheet.ts
- packages/sheets-ui/src/controllers/hover-render.controller.ts
- packages/sheets-ui/src/facade/f-workbook.ts
- packages/sheets-ui/src/facade/f-worksheet.ts
- packages/sheets-ui/src/index.ts
- packages/sheets-ui/src/services/hover-manager.service.ts
- packages/sheets-ui/src/services/selection/selection-render.service.ts
- packages/sheets/src/facade/f-range.ts
- packages/sheets/src/facade/f-worksheet.ts
> feat: user facade api & onCommented  & cellPointerdown & hide selection

- packages/engine-formula/src/functions/__tests__/nested-functions.spec.ts
- packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
- packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
close https://github.com/dream-num/univer-pro/issues/3689
> fix(cell): fix cell format of rich text

- packages/core/src/index.ts
- packages/core/src/sheets/typedef.ts
- packages/core/src/sheets/util.ts
- packages/core/src/sheets/worksheet.ts
- packages/sheets-numfmt-ui/src/controllers/__tests__/cell-content.controller.spec.ts
- packages/sheets-numfmt-ui/src/controllers/__tests__/editor.controller.spec.ts
- packages/sheets-numfmt-ui/src/controllers/__tests__/test.util.ts
- packages/sheets-ui/src/common/utils.ts
- packages/sheets-ui/src/index.ts
- packages/sheets-ui/src/services/clipboard/__tests__/utils.spec.ts
- packages/sheets-ui/src/services/clipboard/clipboard.service.ts
- packages/sheets-ui/src/services/clipboard/type.ts
- packages/sheets/src/commands/commands/add-worksheet-merge.command.ts
> fix: copy cell should generate html & plain

- packages/core/src/common/interceptor.ts
- packages/core/src/sheets/__tests__/worksheet.spec.ts
- packages/core/src/sheets/view-model.ts
- packages/core/src/sheets/worksheet.ts
- packages/sheets/src/services/permission/worksheet-permission/worksheet-permission.service.ts
- packages/sheets/src/services/sheet-interceptor/__tests__/sheet-interceptor.service.spec.ts
- packages/sheets/src/services/sheet-interceptor/sheet-interceptor.service.ts
> feat: fetchThroughInterceptors support filter function

- packages/engine-render/src/components/sheets/extensions/font.ts
> fix: canvas crash when draw broken image

- packages/sheets-formula-ui/src/views/formula-editor/index.tsx
- packages/sheets-formula-ui/src/views/range-selector/index.tsx
close https://github.com/dream-num/univer-pro/issues/3491
close #xxx
> fix(range-selector): remove dataStream

- packages/core/src/facade/f-enum.ts
- packages/core/src/facade/f-event.ts
- packages/core/src/facade/f-univer.ts
- packages/sheets/src/facade/f-event.ts
- packages/sheets/src/facade/f-univer.ts
- packages/ui/src/facade/f-enum.ts
- packages/ui/src/facade/f-univer.ts
- packages/ui/src/facade/index.ts
- packages/ui/src/services/parts/parts.service.ts
- packages/ui/src/views/components/ComponentContainer.tsx
> feat: add api for ui and f-enum

- packages/engine-formula/src/engine/ast-node/function-node.ts
- packages/engine-formula/src/engine/reference-object/base-reference-object.ts
- packages/engine-formula/src/engine/value-object/primitive-object.ts
- packages/engine-formula/src/facade/f-formula.ts
- packages/engine-formula/src/functions/base-function.ts
- packages/engine-formula/src/functions/custom-function.ts
- packages/engine-formula/src/index.ts
- packages/facade/src/apis/__tests__/facade.spec.ts
- packages/sheets-formula/src/facade/f-formula.ts
- packages/sheets-formula/src/facade/f-univer.ts
- packages/sheets-formula/src/index.ts
- packages/sheets-formula/src/services/register-function.service.ts
- packages/sheets-formula/src/services/remote/remote-register-function.service.ts
close #xxx
```js
univerAPI.getFormula().registerFunction('HELLO', (name) => `Hello, ${name}!`, 'A simple greeting function');
// Use the function in a cell
univerAPI.getActiveWorkbook().getActiveSheet().getRange('A1').setValue('World');
univerAPI.getActiveWorkbook().getActiveSheet().getRange('A2').setValue({ f: '=HELLO(A1)' });
// A2 will display: "Hello, World!"
```
// Mock a user score fetching function
```js
univerAPI.getFormula().registerAsyncFunction('FETCH_USER_SCORE',
async (userId) => {
await new Promise(resolve => setTimeout(resolve, 1000));
// Mock fetching user score from database
return userId * 10 + Math.floor(Math.random() * 20);
},
{
description: 'customFunction.description.FETCH_USER_SCORE',
locales: {
'zhCN': {
'customFunction': {
'description': {
'FETCH_USER_SCORE': …
```
> feat(formula): add register async function

- packages/design/src/components/dropdown/DropdownProvider.tsx
close https://github.com/dream-num/univer-pro/issues/3881
> fix(design): fix dropdown on nested situation

- packages/core/src/facade/f-enum.ts
- packages/sheets-filter/src/facade/f-event.ts
> fix(filter): fix event API export

- packages/core/src/types/const/const.ts
- packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
- packages/sheets-ui/src/controllers/clipboard/utils.ts
- packages/sheets/src/basics/cell-style.ts
close https://github.com/dream-num/univer-pro/issues/2579
> fix: paste border should cover origin border

- packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
- packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts
Handing spaces before single quotes in formula strings.
1. Write a cross-sheet formula, such as `= 'dv-test'!C27`
2. Drop down to fill
3. Expected result `= 'dv-test'!C28` (Before fixed `=' 'dv-test''!C28`)
> fix(formula): node maker handle blank

- packages/docs-ui/src/services/clipboard/html-to-udm/converter.ts
- packages/sheets-conditional-formatting-ui/src/controllers/cf.permission.controller.ts
- packages/sheets-data-validation-ui/src/controllers/dv-permission.controller.ts
- packages/sheets-data-validation-ui/src/views/components/list-dropdown/index.tsx
- packages/sheets-filter-ui/src/controllers/sheets-filter-permission.controller.ts
- packages/sheets-hyper-link-ui/src/controllers/hyper-link-permission.controller.ts
- packages/sheets-hyper-link-ui/src/controllers/popup.controller.ts
- packages/sheets-thread-comment-ui/src/controllers/sheets-thread-comment-hover.controller.ts
- packages/sheets-thread-comment-ui/src/controllers/sheets-thread-comment-popup.controller.ts
- packages/sheets-ui/src/controllers/permission/sheet-permission-check-ui.controller.ts
- packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-canvas-render.controller.ts
- packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-clipboard.controller.ts
- packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-formula-render.controller.ts
- packages/sheets-ui/src/index.ts
- packages/sheets-ui/src/mobile-plugin.ts
- packages/sheets-ui/src/plugin.ts
- packages/sheets/src/controllers/permission/sheet-permission-check.controller.ts
- packages/sheets/src/controllers/permission/sheet-permission-init.controller.ts
- packages/sheets/src/controllers/permission/sheet-permission-view-model.controller.ts
- packages/sheets/src/index.ts
- packages/sheets/src/sheets-plugin.ts
> chore: move permission controller to sheets pacakge

- packages/sheets-conditional-formatting-ui/src/controllers/cf.copy-paste.controller.ts
- packages/sheets-data-validation-ui/src/controllers/dv-copy-paste.controller.ts
- packages/sheets-drawing-ui/src/controllers/sheet-drawing-copy-paste.controller.ts
- packages/sheets-formula-ui/src/controllers/formula-clipboard.controller.ts
- packages/sheets-hyper-link-ui/src/controllers/copy-paste.controller.ts
- packages/sheets-ui/src/commands/commands/clipboard.command.ts
- packages/sheets-ui/src/components/hook.ts
- packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
- packages/sheets-ui/src/controllers/clipboard/const.ts
- packages/sheets-ui/src/controllers/config.schema.ts
- packages/sheets-ui/src/index.ts
- packages/sheets-ui/src/services/clipboard/clipboard.service.ts
- packages/sheets-ui/src/services/clipboard/type.ts
- packages/sheets-ui/src/views/clipboard/ClipboardPopupMenu.tsx
- packages/sheets-ui/src/views/clipboard/index.module.less
- packages/ui/src/services/clipboard/clipboard.command.ts
> feat: add paste options

- packages/engine-formula/src/engine/ast-node/function-node.ts
- packages/engine-formula/src/engine/value-object/lambda-value-object.ts
- packages/engine-formula/src/engine/value-object/primitive-object.ts
- packages/engine-formula/src/functions/base-function.ts
- packages/engine-formula/src/index.ts
- packages/facade/src/apis/__tests__/facade.spec.ts
- packages/sheets-formula/src/facade/f-formula.ts
- packages/sheets-formula/src/services/register-function.service.ts
Facade API registered formulas support lambda functions
1. Register function use Uniscript
```js
univerAPI.getFormula().registerFunction('CUSTOMSUM',(...variants) => {
let sum = 0;
const last = variants[variants.length - 1];
if (last.isLambda && last.isLambda()) {
variants.pop();
const variantsList = variants.map((variant) => Array.isArray(variant) ? variant[0][0]: variant);
sum += last.executeCustom(...variantsList).getValue();
}
for (const variant of variants) {
sum += Number(variant) || 0;
}
return sum;
}, 'Adds its arguments');
```
2. test `=CUSTOMSUM(1,2,LAMBDA(s,c,s+c))`, get result 6
3. A1 input 2, A2 input 3, test `=CUSTOMSUM(A1,A2,LAMBDA(s,c,s+c))`, get result 10
> feat(formula): support lambda in function register

- packages/sheets/src/controllers/permission/sheet-permission-init.controller.ts
- packages/sheets/src/facade/f-permission.ts
> chore: add hooks after permission set

- packages/core/src/docs/data-model/rich-text-builder.ts
> fix(facade): insert empty text error

- packages/sheets-ui/src/facade/f-event.ts
- packages/sheets-ui/src/facade/f-workbook.ts
- packages/sheets-ui/src/services/hover-manager.service.ts
- packages/sheets/src/facade/f-workbook.ts
- packages/sheets/src/facade/f-worksheet.ts
> fix: pointer event

- packages/sheets-thread-comment/src/facade/f-range.ts
- packages/sheets/src/commands/commands/remove-worksheet-merge.command.ts
- packages/sheets/src/commands/commands/split-text-to-columns.command.ts
- packages/sheets/src/commands/commands/toggle-gridlines.command.ts
- packages/sheets/src/facade/f-permission.ts
- packages/sheets/src/facade/f-range.ts
- packages/sheets/src/facade/f-worksheet.ts
- packages/ui/src/facade/f-univer.ts
- packages/ui/src/services/clipboard/clipboard.command.ts
> fix(facade): make facade sync

- packages-experimental/sheets-source-binding/src/controllers/binding-manager.ts
- packages-experimental/sheets-source-binding/src/controllers/source-manager.ts
- packages-experimental/sheets-source-binding/src/facade/f-workbook.ts
- packages-experimental/sheets-source-binding/src/index.ts
- packages-experimental/sheets-source-binding/src/model/binding-model.ts
- packages-experimental/sheets-source-binding/src/model/source-model.ts
- packages-experimental/sheets-source-binding/src/services/source-binding-service.ts
- packages-experimental/sheets-source-binding/src/types.ts
- packages/sheets/src/facade/f-workbook.ts
- support delete bind path when delete cell
```
const fWorkbook = univerAPI.getActiveWorkbook();
const fSheet = fWorkbook.getActiveSheet();
const source = fWorkbook.createSource(univerAPI.Enum.DataBindingNodeTypeEnum.Object);
source.setSourceData({
user: {
name: '猿婶'
}
})
fSheet.setBindingNode({
row: 1,
column: 2,
path: 'user.name',
type: univerAPI.Enum.DataBindingNodeTypeEnum.Object,
sourceId: source.getId()
})
const listSource = fWorkbook.createSource(univerAPI.Enum.DataBindingNodeTypeEnum.List, false);
listSource.setSourceData({
fields: ['商品', '种类','日期'],
records: [['苹果', '水果', 1736942545041], ['香蕉', '水果',1736942545041], ['圆珠笔', '文具',1736942545041]]
})
fSheet.setBindingNode({
row: 1,
column: 4,
path: '商品',
type: univerAPI.Enum.DataBindingNodeTypeEnum.List,
sourceId: listSource.getId() …
```
> fix(sheet): support bind delete & date type source

- packages/sheets-numfmt-ui/src/controllers/numfmt.editor.controller.ts
`next()` is not used here, which makes the subsequent interception unable to execute
use 
[snapshot-formula-numfmt.json](https://github.com/user-attachments/files/18423584/snapshot-formula-numfmt.json)
before
after
> fix(numfmt): use next in writeCellInterceptor

- packages/sheets-formula/src/controllers/array-formula-cell-interceptor.controller.ts
- packages/sheets-numfmt/package.json
- packages/sheets-numfmt/src/utils/pattern.ts
- packages/sheets/src/controllers/number-cell.controller.ts
- pnpm-lock.yaml
Importing Excel with formulas, the formula cell contains the v value of a string, the cell type is a number, and the cell number format is `General`, then the number precision is not processed
[snapshot-formula-0114.json](https://github.com/user-attachments/files/18407336/snapshot-formula-0114.json)
> fix(sheet): cell precision error

- packages-experimental/debugger/src/components/float-button.tsx
- packages-experimental/debugger/src/controllers/debugger.controller.ts
- packages/engine-render/src/components/sheets/extensions/column-header-layout.ts
- packages/engine-render/src/components/sheets/extensions/row-header-layout.ts
- packages/engine-render/src/components/sheets/interfaces.ts
- packages/sheets-drawing-ui/src/facade/f-worksheet.ts
- packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts
- packages/sheets/src/facade/f-worksheet.ts
- packages/ui/src/index.ts
> fix: float dom event

- packages/core/src/common/const.ts
- packages/core/src/index.ts
- packages/core/src/services/config/config.service.ts
- packages/engine-render/src/components/sheets/sheet-skeleton.ts
- packages/sheets/src/controllers/config.schema.ts
- packages/sheets/src/sheets-plugin.ts
close https://github.com/dream-num/univer/issues/4445
> fix: customize auto height for merged cell

- packages/engine-formula/src/functions/__tests__/nested-functions.spec.ts
- packages/engine-formula/src/functions/text/t/__test__/index.spec.ts
- packages/engine-formula/src/functions/text/t/index.ts
> fix(formula): t formula bug fix

- packages/sheets-formula-ui/src/commands/operations/__tests__/insert-function.operation.spec.ts
- packages/sheets-formula-ui/src/commands/operations/insert-function.operation.ts
- packages/sheets-formula/src/commands/commands/insert-function.command.ts
> fix(formula): fix insert function of range has number value

- packages/core/src/univer.ts
- packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
- packages/sheets/src/facade/f-permission.ts
- packages/sheets/src/sheets-plugin.ts
- tests/formula-integration/src/__snapshots__/test-formula-correctness---basic-sum-result.json
- tests/formula-integration/src/__snapshots__/test-formula-correctness---basic-sum.json
close https://github.com/dream-num/univer/issues/4457
close https://github.com/dream-num/univer/issues/4442
> fix: fix some permission bugs

- packages/network/src/services/http/__testing__/http-params.spec.ts
- packages/network/src/services/http/params.ts
> feat(network): support array params

- packages/core/src/shared/types.ts
- packages/core/src/types/enum/border-style-types.ts
- packages/core/src/types/enum/text-style.ts
- packages/core/src/types/enum/theme-color-type.ts
- fix coments error, the declaration be used as doc
> fix(docs): fix comments error

- examples/src/sheets/main.ts
- packages/core/src/facade/f-univer.ts
- packages/docs-ui/src/services/editor/editor-manager.service.ts
- packages/sheets-formula-ui/src/views/formula-editor/index.tsx
- packages/sheets-formula-ui/src/views/range-selector/hooks/useFocus.ts
- packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts
- packages/sheets-ui/src/controllers/render-controllers/editor-bridge.render-controller.ts
- packages/sheets-ui/src/facade/f-univer.ts
- packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
- packages/sheets-ui/src/views/formula-bar/index.module.less
> fix(sheets): before edit event can't cancel by formula-bar

- packages/core/src/shared/object-matrix.ts
- packages/sheets-formula/src/controllers/active-dirty.controller.ts
> fix(formula): get dirtyRanges when row column removed

- packages/core/src/index.ts
- packages/core/src/sheets/typedef.ts
- packages/engine-render/src/components/sheets/sheet.render-skeleton.ts
- packages/engine-render/src/viewport.ts
- packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts
- packages/sheets-ui/src/controllers/format-painter/format-painter.controller.ts
- packages/sheets-ui/src/controllers/render-controllers/freeze.render-controller.ts
- packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts
- packages/sheets-ui/src/services/sheet-skeleton-manager.service.ts
close https://github.com/dream-num/univer-pro/issues/3967
clsoe https://github.com/dream-num/univer-pro/issues/3934
> fix: float dom after freeze

- packages/drawing-ui/src/controllers/image-cropper.controller.ts
- packages/engine-render/src/render-manager/render-manager.service.ts
- packages/engine-render/src/render-manager/render-unit.ts
- packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts
- packages/sheets-filter/src/controllers/sheets-filter.controller.ts
- packages/sheets-filter/src/models/filter-model.ts
- packages/sheets-ui/src/controllers/auto-fill.controller.ts
- packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
- packages/sheets-ui/src/controllers/format-painter/format-painter.controller.ts
- packages/sheets-ui/src/controllers/permission/sheet-permission-render.controller.ts
- packages/sheets-ui/src/controllers/render-controllers/format-painter.render-controller.ts
- packages/sheets-ui/src/services/sheet-skeleton-manager.service.ts
- packages/sheets-ui/src/views/clipboard/ClipboardPopupMenu.tsx
- packages/sheets/src/model/range-protection-rule.model.ts
- packages/sheets/src/services/sheet-interceptor/sheet-interceptor.service.ts
> fix: fix multi memory leak problems

- .github/workflows/playwright.yml
- .gitignore
- e2e/memory/memory.spec.ts
- e2e/perf/scroll.spec.ts
- playwright.config.ts
close #xxx
take two heapsnapshot in univer root path when run mem.spec.ts, and upload to artifacts if mem test failed
memory-first.heapsnapshot & memory-second.heapsnapshot
> fix: upload snapshot as artifacts when test failed, record hean snapshot in mem test

- packages/sheets/src/commands/commands/set-worksheet-row-height.command.ts
close https://github.com/dream-num/univer-pro/issues/3996
> fix: adjust height when select all

- packages-experimental/sheets-source-binding/src/model/source-model.ts
- packages-experimental/sheets-source-binding/src/types.ts
- packages/sheets-ui/src/controllers/status-bar.controller.ts
close https://github.com/dream-num/univer-pro/issues/3073
> fix(statusbar): fix status bar can not read date type cell

- packages/ui/src/views/components/ribbon/Ribbon.tsx
> fix(ui): optimize resize observer and update toolbar item structure of Ribbon

- packages/sheets-ui/src/views/clipboard/ClipboardPopupMenu.tsx
close https://github.com/dream-num/univer-workspace/issues/443
> fix: fix paste dropdown in workspace

- packages/sheets/src/commands/commands/set-border-command.ts
- packages/sheets/src/facade/f-range.ts
```js
univerAPI.getActiveWorkbook().getActiveSheet().getRange('A1:B5').setBorder('outside', 8,'#ff0000');
```
> fix(facade): add ranges to setBorder

- packages/engine-formula/src/services/defined-names.service.ts
> chore(formula): defined name cache for getValueByName

- packages/design/src/components/tooltip/Tooltip.tsx
- packages/design/src/components/tree/Tree.tsx
- packages/sheets-conditional-formatting-ui/src/controllers/cf.copy-paste.controller.ts
- packages/sheets-data-validation-ui/src/controllers/dv-copy-paste.controller.ts
- packages/sheets-filter-ui/src/worker/generate-filter-values.service.ts
- packages/sheets-hyper-link-ui/src/controllers/copy-paste.controller.ts
- packages/sheets-ui/src/controllers/utils/range-tools.ts
- packages/sheets-ui/src/index.ts
- packages/sheets-ui/src/services/auto-fill/auto-fill.service.ts
- packages/sheets-ui/src/services/clipboard/clipboard.service.ts
- packages/sheets/src/basics/interfaces/selection-config.ts
- packages/sheets/src/basics/utils.ts
- packages/sheets/src/commands/commands/clear-selection-all.command.ts
- packages/sheets/src/commands/commands/clear-selection-content.command.ts
- packages/sheets/src/commands/commands/clear-selection-format.command.ts
- packages/sheets/src/commands/commands/remove-row-col.command.ts
- packages/sheets/src/index.ts
close https://github.com/dream-num/univer-pro/issues/3978
close https://github.com/dream-num/univer-pro/issues/3980
删除行暂时没处理，因为删除行需要先把这个mutation修改为参数类型为ranges
> fix: the filtered content is not included in the clear

- package.json
After pnpm 10 lifecycle scripts of dependencies are not executed during installation by default!  https://github.com/pnpm/pnpm/releases/tag/v10.0.0
close #xxx
> chore: add `onlyBuiltDependencies` list

- packages/sheets-ui/src/facade/f-range.ts
- packages/sheets-ui/src/services/clipboard/clipboard.service.ts
> fix(ui): fix generate facade should execute before hook

- packages/sheets/src/facade/f-worksheet.ts
```js
// 将前 100 行设定自动行高
univerAPI.getActiveWorkbook().getActiveSheet().setRowAutoHeight(0, 100)
// 或者
// 将整个 Worksheet 的中没有行配置的行，设定自动行高
const rangesWithoutConfig = [];
const workbook = univerAPI.getActiveWorkbook()
const snapshot = workbook.save()
const worksheet = workbook.getActiveSheet()
const currentWorksheetId = worksheet.getSheetId();
const rowCount = worksheet.getLastRow();
const columnCount = worksheet.getLastColumn();
const rowData = snapshot.sheets[currentWorksheetId].rowData;
for (let i = 0; i <= rowCount; i++) {
const row = rowData[i];
if (!row) {
rangesWithoutConfig.push({ startRow: i, endRow: i, startColumn:0, endColumn:columnCount });
}
}
worksheet.setRangesAutoHeight(rangesWithoutConfig)
```
> fix(sheet): set ranges for setAutoHeight

- packages/design/src/components/dialog/Dialog.tsx
- packages/find-replace/src/commands/operations/find-replace.operation.ts
- packages/find-replace/src/controllers/find-replace.controller.ts
- packages/find-replace/src/controllers/find-replace.shortcut.ts
- packages/find-replace/src/locale/en-US.ts
- packages/find-replace/src/locale/fa-IR.ts
- packages/find-replace/src/locale/fr-FR.ts
- packages/find-replace/src/locale/ru-RU.ts
- packages/find-replace/src/locale/vi-VN.ts
- packages/find-replace/src/locale/zh-CN.ts
- packages/find-replace/src/locale/zh-TW.ts
- packages/find-replace/src/services/find-replace.service.ts
- packages/find-replace/src/views/dialog/FindReplaceDialog.tsx
- packages/find-replace/src/views/dialog/SearchInput.tsx
- packages/sheets-drawing/src/controllers/sheet-drawing.controller.ts
- packages/sheets-filter/src/controllers/sheets-filter.controller.ts
- packages/sheets-find-replace/src/controllers/sheet-find-replace.controller.ts
- packages/sheets/src/commands/operations/selection.operation.ts
- packages/sheets/src/controllers/basic-worksheet.controller.ts
- packages/sheets/src/index.ts
- packages/ui/src/services/dialog/dialog.service.ts
> feat(find-replace): use esc to focus on selection

- e2e/perf/scroll.spec.ts
- e2e/visual-comparison/sheets/sheets-formula-related.spec.ts
- package.json
- packages-experimental/debugger/src/controllers/e2e/e2e.controller.ts
- packages/core/src/sheets/sheet-skeleton.ts
- packages/engine-render/src/components/docs/doc-component.ts
- packages/engine-render/src/components/docs/document.ts
- packages/engine-render/src/components/docs/extensions/font-and-base-line.ts
- packages/engine-render/src/components/docs/layout/shaping-engine/font-cache.ts
- packages/engine-render/src/components/extension.ts
- packages/engine-render/src/components/sheets/extensions/font.ts
- packages/engine-render/src/components/sheets/extensions/sheet-extension.ts
- packages/engine-render/src/components/sheets/sheet.render-skeleton.ts
- packages/engine-render/src/components/sheets/spreadsheet.ts
- packages/engine-render/src/context.ts
- packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts
- packages/sheets-ui/src/index.ts
…g glyphs outside the viewBounds (#4775)"
This reverts commit cd3decd487d641738229a8c5a4213d60ff191d57.
close #xxx
> revert: remove unnecessary `ctx.font =` calls, and avoid drawing out of bounds

- packages/sheets/src/model/range-theme-model.ts
> fix: fix range theme fromjson

- packages/sheets-conditional-formatting/src/commands/commands/add-cf.command.ts
Right now if you try to apply conditional formatting on some sheet formatting will be applied to active sheet (not that you're trying to apply).
Other commands (e.g. [clear range](https://github.com/dream-num/univer/blob/dev/packages/sheets-conditional-formatting/src/commands/commands/clear-range-cf.command.ts#L53) and other in this folder) pass `params` parameter.
How to test:
- Open sheet
- Execute code in console
```
const workbook = univerAPI.getActiveWorkbook();
// create a new sheet (and switch to this sheet)
const sheet = workbook.insertSheet('Conditional sheet');
// switch back to initial sheet to make created sheet inactive
workbook.setActiveSheet(workbook.getSheets()[1])
// fill out data
for (let i = 1; i <= 10; i++) {
sheet.getRange(`A${i}`).setValue(i);
}
// setup conditional …
```
> fix(sheets-conditional-formatting): apply conditional formatting for triggered sheet

- packages/core/src/sheets/styles.ts
- packages/core/src/sheets/worksheet.ts
- packages/engine-render/src/components/sheets/sheet.render-skeleton.ts
- packages/sheets-ui/src/controllers/menu/menu.ts
- packages/sheets/src/facade/f-worksheet.ts
> fix(sheets-ui): update sheet font menus

- packages/thread-comment-ui/src/views/thread-comment-tree/index.tsx
> fix(thread-comment-ui): add word break style to thread comment items

- packages/docs-ui/src/controllers/float-menu.controller.ts
- packages/docs-ui/src/services/doc-popup-manager.service.ts
- packages/ui/src/services/popup/canvas-popup.service.ts
- packages/ui/src/views/components/popup/CanvasPopup.tsx
- packages/ui/src/views/components/popup/RectPopup.tsx
> fix(docs-ui): inline format float box postion issue

- packages/engine-render/src/base-object.ts
- packages/engine-render/src/engine.ts
- packages/engine-render/src/scene.input-manager.ts
- packages/engine-render/src/scene.ts
> feat: event click

- packages/sheets-formula-ui/src/commands/operations/__tests__/insert-function.operation.spec.ts
- packages/sheets-formula-ui/src/controllers/__tests__/formula-auto-fill.controller.spec.ts
- packages/sheets-formula-ui/src/controllers/__tests__/update-formula.controller.spec.ts
- packages/sheets/src/commands/commands/__tests__/clear-selection.command.spec.ts
- packages/sheets/src/commands/commands/__tests__/insert-range.command.spec.ts
- packages/sheets/src/commands/commands/__tests__/set-range-values.command.spec.ts
- packages/sheets/src/commands/mutations/set-range-values.mutation.ts
> fix: clear content should not be set empty object

- packages/docs-ui/src/controllers/float-menu.controller.ts
> fix(docs-ui): disable float-menu on whole custom-range

- packages/docs-ui/src/components/float-toolbar/FloatToolbar.tsx
> fix(docs-ui): remove SetInlineFormatFontFamilyCommand from FloatToolbar

- packages/sheets-numfmt/src/utils/pattern.ts
close #5340
- the null or undefined should not change to string
> fix(numfmt): fix the numfmt func change the null to string

- packages/engine-render/src/components/sheets/extensions/font.ts
- Add _drawFallbackImage method to safely render fallback images
- Check if fallback image is fully loaded before drawing
- Replace direct drawImage calls with safe fallback method
- Prevents 'HTMLImageElement provided is in the broken state' error
> fix(engine-render): handle broken image state in font rendering

- packages/sheets-formula-ui/src/views/formula-editor/hooks/use-formula-selection.ts
Check for undefined unitId before comparison to prevent potential errors when selecting formulas across workbooks
> fix(sheets-formula-ui): handle undefined unitId in formula selection

- packages/design/src/components/dialog/DialogPrimitive.tsx
close #5647
increase colorpicker z-index. on the screen at a low height, it was partially blocked.
Decrease the height of the window, open the choice of text or background color, click choose another color
After:-->
> fix: color picker is partially blocked

- mockdata/src/docs/default-document.data-simple.ts
- mockdata/src/sheets/demo/default-workbook-data-demo.ts
- packages/engine-render/src/components/docs/extensions/line.ts
- packages/engine-render/src/components/sheets/extensions/font.ts
- packages/engine-render/src/shape/text.ts
close #5779 
in one of the described issues, I noticed a familiar situation regarding underlining text, but I encountered it when processing import from an excel file. Now that this problem is relevant not only for me, I would like to offer a solution.
Firstly, this solved the problem of displaying underlining on documents for the most part, but I decided to go further and add similar logic to tables. I think this can serve not only as a solution for importing an Excel file depending on the enum textdecoration described in the repository, but also as a feature in the menu for adding the required underlining. in any case it shouldn't have any breaking changes
I hope you don't mind, i added an example of this implementation to the demo of documents and tables. i think it may be convenient …
> feat: add display underline depending on type

- mockdata/src/docs/default-document.data-simple.ts
- mockdata/src/sheets/demo/default-workbook-data-demo.ts
- packages/engine-render/src/components/docs/extensions/line.ts
- packages/engine-render/src/shape/text.ts
in continuation of the underlining, i decided to finish the question with a double line. Also, i made the part i added yesterday in the demo documents a bit cleaner, i think it was too bulky even for a temporary demonstration.
in fact, I have a question about TextDecoration.NONE. Can you clarify what was meant by this concept, if it is simply its absence, then perhaps it may look strange, show: true, type: none? or was it a trigger in the command that would set show false? Also I didn't quite understand how TextDecoration.WORDS can be displayed.  As far as I could see in this repository, these values ​​are not used.
start demo => 
1. open sheet
2. open doc
After: -->
> feat: double line

- packages/core/src/types/const/const.ts
- packages/sheets-ui/src/controllers/menu/menu.ts
- packages/sheets/src/commands/commands/__tests__/set-style.command.spec.ts
close #5646
Partially solved this problem, tried to fix the problem on the background, but for some reason getFontStyleAtCursor does not return the current background, probably there is some problem in this too. Thus, the problem with the active background color, unfortunately, still persists.
I also had to change the default text color to 6 hex characters, because otherwise it wouldn't match when fetching the initial active color. This is only used once in the code (except here) so it shouldn't have any effect =)
I also want to note that if this solution is confirmed, I will add similar code to the docs
start demo - open sheets - choose font color
[Screencast from 2025-09-06 21-48-15.webm](https://github.com/user-attachments/assets/e5ba6214-92fe-4825-a0c5-e88084cc45ea)
> fix(sheets): active current font color

- packages/docs-ui/src/controllers/menu/menu.ts
Similar implementation of the previous PR for setting the active color in the color picker, only in documents
[Screencast from 2025-09-08 21-45-27.webm](https://github.com/user-attachments/assets/03329d1f-8686-41b6-9625-f23ae56f1154)
> fix: active text color in docs

- packages/core/src/sheets/util.ts
- packages/sheets-ui/src/controllers/menu/menu.ts
I found the problem why I was able to immediately set the active color on the background, fixed it, and at the same time, I saw that the getUniverDocInstance method  is deprecated,, I updated it too
start demo => open sheets => set BG Color => check this color in color picker
Before:
After: 
[Screencast from 2025-09-09 22-13-16.webm](https://github.com/user-attachments/assets/92c0e744-8e21-431f-95e3-ff04d652dd12)
> fix(sheets): set bg active color in colorPicker; change deprecated methodgtgt

- packages/docs-ui/src/controllers/render-controllers/doc-editor-bridge.controller.ts
- packages/engine-render/src/components/docs/layout/doc-skeleton.ts
close #5840
as I wrote in the issue it seemed strange to me to see the text when erasing it, at the same time, I really like your solution that appears when scrolling. It seems to me that this solution does not contradict your design, but significantly user experience and expected behavior.
Please note that the size is reset when you lose focus, it does not decrease when you delete characters, but it increases if necessary
It's up to you, but I think this decision is appropriate.
Before: recorded in issue
After: 
[Screencast from 2025-09-12 21-19-28.webm](https://github.com/user-attachments/assets/40c277f7-2c38-40f1-9bf6-febe229c96ab)
> fix: text under active input

- packages/sheets-ui/src/views/status-bar/CopyableStatisticItem.tsx
close #xxx
in the statistics component when selecting a number range the content was cut off, now it is always displayed. In addition, I allowed myself to suggest you change the cursor from the default to the pointer, because this is probably a more expected behavior... but if it is necessary to remove it to the default, please let me know, I will remove it.
languages ​​that had a problem: en, fr, ru, es,  ca
Before:
After:
> fix: statistic not fully displayed

- packages/core/src/sheets/util.ts
- packages/sheets-ui/src/components/border-panel/BorderPanel.tsx
the color in the color picker for cells that have borders has always been default. Now it has the same behavior as other color pickers
Before: always default color #000000
After: 
[Screencast from 2025-09-13 21-25-20.webm](https://github.com/user-attachments/assets/614d2961-2ed0-46bd-b9ac-43af6ca0a036)
> fix: active cell border color

- packages/engine-render/src/components/sheets/extensions/border.ts
- packages/sheets-ui/src/components/border-panel/BorderPanel.tsx
- packages/sheets-ui/src/components/border-panel/border-line/BorderLine.tsx
- packages/sheets-ui/src/components/border-panel/border-line/icons/BorderDouble.tsx
considering that there is a type of double borders, I decided to propose to implement it
run demo => open sheets => choose border double
Before: was not supported
After:
> feat: add double border

- packages/sheets-ui/src/components/border-panel/BorderPanel.tsx
In the process of highlighting the CheckMark Icon of the active border, I missed the implementation directly in the dropdown value. this solves the problem
Before:
always Thin
After: 
[Screencast from 2025-09-17 20-43-42.webm](https://github.com/user-attachments/assets/66c70ce1-4861-41a2-b757-f3a21294bb4c)
> feat: active border type in dropdown value

- packages/design/src/components/kbd/Kbd.tsx
- packages/design/src/components/kbd/__tests__/__snapshots__/index.spec.tsx.snap
- packages/ui/src/locale/ru-RU.ts
- packages/ui/src/views/components/shortcut-panel/ShortcutPanel.tsx
close #xxx
I noticed that the key combination for long texts has a hyphenation, which makes it impossible to read the correct key combination
I fixed this issue by initially leaving the text on a single line, but it became virtually impossible to read the description of this text; it was too hidden. Therefore, I would like to suggest, in addition to fixing the key combination itself, increasing the description text to two lines. I think this will make it more convenient for users.
The problem affected the following languages: ru, fr, es, ca
I also changed the Russian language a little, because this previous translation is not actually used in conversation and is aimed at something slightly different
Before:
After:
> fix: shortcut cropped content in kbd component

- packages/docs-ui/src/components/side-menu/index.tsx
- packages/docs-ui/src/views/side-menu/index.tsx
close #xxx
I was examining the sidebar menu where paragraphs are displayed and noticed that the heading text actually overlaps the border, and if the text exceeds the maximum size, the menu border overlaps the document border. I'd suggest some small indents, and I think it looks nicer. I'd probably increase the right padding even more.
By the way, team, I want to let you know that I'll be on vacation for the next few weeks, so if anything happens, I'm not missing, I'm just on vacation =)
Before:
After:
> feat: side menu stylization

- packages/engine-formula/src/functions/financial/rate/__tests__/index.spec.ts
- packages/engine-formula/src/functions/financial/rate/index.ts
This PR fixes the `RATE` function by improving validation of cash flow inputs to prevent invalid scenarios, aligning behavior more closely with Excel.
Previously, the function did not correctly validate the signs of cash flows and could return a `#NUM!` error even in valid cases such as lump-sum investments where `PMT` is zero. This update ensures the function only returns an error for truly invalid cash flow sign patterns, improving accuracy and user experience.
- Returns an error when all cash flows (`PMT`, `PV`, and `FV`) have the same sign (all non-negative or all non-positive), reflecting invalid economic cash flow scenarios.  
This is because in financial calculations, cash flows must include at least one outflow and one inflow to represent money moving in and out; if all cash flows …
> fix: (RATE func) Validate cash flow signs and support zero PMT scenarios for Excel compatibility

- packages/sheets/src/commands/commands/__tests__/copy-worksheet.command.spec.ts
- packages/sheets/src/commands/commands/copy-worksheet.command.ts
close #xxx
I thought I'd make one more suggestion before I go on vacation =)
When copying a sheet name, there are currently no spaces between the new sheet name and the extension (copy). However, perhaps you could consider my suggestion to add this issue, as I think it would improve the user experience.
For example,
- Excel uses a space between the new name and the copy number:
- LibreOffice uses an underscore:
- Google also uses a space:
Before: has no spaces, written together
After:
> feat: add space on create sheet copy
